[translation]
10137-CVGroup_UITitle_Idle1-1 = "Blue Archive~"
10137-CVGroup_CharacterGet_Idle1-1 = "Ah, hey there. I'm Shima Konoka from the Valkyrie Police School, Public Safety Bureau.\nWant to check today's fortune with me?"
10137-CVGroup_Cafe_Idle1-1 = "There are... so many people here."
10137-CVGroup_Cafe_Idle2-1 = "(Now then, as for the criminals... well, I guess there aren't any here.)"
10137-CVGroup_Cafe_Idle3-1 = "Huh? My badge... where did I put it...?"
10137-CVGroup_Cafe_Idle4-1 = "It's so peaceful. Sigh... I'm bored."
10137-CVGroup_Cafe_Idle5-1 = "Is this even legal?"
10137-CVGroup_WeaponGet_Idle1-1 = "Oh, I wanted this! With this, I can settle things easily!"
10137-CVGroup_UIEventLobby_Enter1-1 = "Tsuchinoko, hey! Where are you!?"
10137-CVGroup_UIEventLobby_Enter1-2 = "If I catch you, you're in for it..."
10137-CVGroup_UIEventLobby_Enter1-3 = "N-no! Come out!"
10137-CVGroup_UIEventLobby_Enter2-1 = "Ugh... so scary..."
10137-CVGroup_UIEventLobby_Enter3-1 = "Why is this like some kind of harassment— Eek!? W-who's there...?"
10137-CVGroup_UIEventLobby_Enter4-1 = "Even if it's a ghost, if I can put handcuffs on it...!"
10137-CVGroup_UIEventLobby_Enter5-1 = "We finished safely! Fate is a piece of cake! Hahaha—"
10137-CVGroup_UIEventLobby_Enter5-2 = "N-no! Forget I said that! It's not a piece of cake! I'm sorry!!"
10137-CVGroup_UIEventLobby_Idle1-1 = "H-hyah!? ...Geez, you scared me!"
10137-CVGroup_UIEventLobby_Idle2-1 = "Phew... the air here is at least nice."
10137-CVGroup_UIEventLobby_Idle3-1 = "Tsuchinoko! If I catch you, I'm never letting you go!"
10137-CVGroup_UIEventLobby_Idle4-1 = "Stay calm... stay calm..."
10137-CVGroup_UIEventBoxGachaShop_Enter1-1 = "Alright! Let's keep going!"
10137-CVGroup_UIEventBoxGachaShop_Enter2-1 = "How was your fortune today? I believe in your luck, Sensei!"
10137-CVGroup_UIEventBoxGachaShop_Enter3-1 = "Cleanup time! Let's give it our all until the end!"
10137-CVGroup_UIEventBoxGachaShop_Idle1-1 = "Are you going to share your luck with me? Yay!"
10137-CVGroup_UIEventBoxGachaShop_Idle2-1 = "I'm with Sensei, so it'll work out somehow!"
10137-CVGroup_UIEventBoxGachaShop_BoxGachaPrize1-1 = "Ooh! This is the one!"
10137-CVGroup_UIEventBoxGachaShop_BoxGachaPrize2-1 = "You're incredibly lucky!? Sensei, you're amazing!"
10137-CVGroup_UIEventBoxGachaShop_BoxGachaPrize3-1 = "I wish every day was like this~"
10137-CVGroup_UIEventBoxGachaShop_BoxGachaFinish1-1 = "I'll investigate until the very end, just in case!"