[translation]
10136-CVGroup_UITitle_Idle1-1 = "Blue Archive."
10136-CVGroup_CharacterGet_Idle1-1 = "Under these circumstances... I suppose I need to change, too.\nWhat do you think, Sensei? Does it suit me?"
10136-CVGroup_Cafe_Idle1-1 = "Ugh... I'm running low on caffeine."
10136-CVGroup_Cafe_Idle2-1 = "I'd love to come here with just you next time, Sensei."
10136-CVGroup_Cafe_Idle3-1 = "Taking a break over there..."
10136-CVGroup_Cafe_Idle4-1 = "This backpack... it feels kind of hot..."
10136-CVGroup_Cafe_Idle5-1 = "It's so peaceful..."
10136-CVGroup_WeaponGet_Idle1-1 = "I've never seen a weapon shaped like this before, but... for the sake of the mission, I'll learn to master it quickly. ...For your sake, too, Sensei."
10136-CVGroup_UICarrierLobby_Enter1-1 = "It's a comfortable and efficient place, but..."
10136-CVGroup_UICarrierLobby_Enter2-1 = "Combat rations are efficient, but..."
10136-CVGroup_UICarrierLobby_Enter3-1 = "For some reason, I have an irresistible urge to go to the kitchen."
10136-CVGroup_UICarrierLobby_Enter4-1 = "Would you like something cold to drink, Sensei?"
10136-CVGroup_UICarrierLobby_Idle1-1 = "Can I turn on the AC? I wonder if the Club President would mind?"
10136-CVGroup_UICarrierLobby_Idle2-1 = "I wonder if it's more efficient to eat meals together with everyone?"
10136-CVGroup_UICarrierLobby_Idle3-1 = "There are things in this world that aren't logical, but are efficient."
10136-CVGroup_UICarrierLobby_Idle4-1 = "I can't get my thoughts together..."
10136-CVGroup_UICarrierLobby_Idle4-2 = "When it's not my body, but my head that feels hot,"
10136-CVGroup_UICarrierLobby_Idle4-3 = "what should I do...?"
10136-CVGroup_UIEventMission_Enter1-1 = "Yahoo, Sensei, can you hear me?"
10136-CVGroup_UIEventMission_Enter2-1 = "It's an emergency, so I'm connecting via comms."
10136-CVGroup_UIEventMission_Enter2-2 = "I'm happy I can see your face, even through the line."
10136-CVGroup_UIEventMission_Idle1-1 = "I've ensured ventilation, but..."
10136-CVGroup_UIEventMission_Idle1-2 = "It's still hot. Should I take off another layer—"
10136-CVGroup_UIEventMission_Idle1-3 = "Huh? Don't? I see..."
10136-CVGroup_UIEventMission_Idle1-4 = "Well, if you say so, Sensei..."
10136-CVGroup_UIEventMission_Idle2-1 = "Right now, I'm more of a marksman than a sniper."
10136-CVGroup_UIEventMission_Idle2-2 = "When moving, I stay with the team."
10136-CVGroup_UIEventMission_Idle2-3 = "...Thanks for moving us to a cooler place."
10136-CVGroup_UIEventMission_Buy1-1 = "Talking to you really is fun, Sensei."
10136-CVGroup_UIEventMission_Buy2-1 = "Here, good work."
10136-CVGroup_UIEventMission_Interaction1-1 = "Mission complete. Looking forward to the next one."