[translation]
10133-CVGroup_UITitle_Idle1-1 = "Blue Archive."
10133-CVGroup_CharacterGet_Idle1-1 = "I will show you the most rational answer\nthat governs the electronic realm."
10133-CVGroup_Cafe_Idle1-1 = "This place is also a type of conceptual space... It requires analysis."
10133-CVGroup_Cafe_Idle2-1 = "I want to become better at cleaning up..."
10133-CVGroup_Cafe_Idle3-1 = "...It seems your sensibilities are similar to mine, Sensei."
10133-CVGroup_Cafe_Idle4-1 = "Perhaps I should build an 'Avant-Garde-kun Type-Maid' and place it here."
10133-CVGroup_Cafe_Idle5-1 = "I will use this as cleanly... as possible."
10133-CVGroup_WeaponGet_Idle1-1 = "I will protect everyone...\nThat strong will is what makes me pull the trigger."
10133-CVGroup_UICarrierHangar_Enter1-1 = "How should I interpret this result..."
10133-CVGroup_UICarrierHangar_Enter2-1 = "This was... supposed to be a hangar."
10133-CVGroup_UICarrierHangar_Enter2-2 = "It has become more like a multi-purpose room, hasn't it?"
10133-CVGroup_UICarrierHangar_Enter3-1 = "The preparations for the upgrade are complete."
10133-CVGroup_UICarrierHangar_Idle1-1 = "I need to find... a breakthrough."
10133-CVGroup_UICarrierHangar_Idle2-1 = "Let's analyze the Prophet's core here."
10133-CVGroup_UICarrierLobby_Enter1-1 = "(I am here right now...)"
10133-CVGroup_UICarrierLobby_Enter1-2 = "(Is this a rational action...?)"
10133-CVGroup_UICarrierLobby_Enter2-1 = "(Precisely because of this situation,)"
10133-CVGroup_UICarrierLobby_Enter2-2 = "(perhaps playing games is rational...)"
10133-CVGroup_UICarrierLobby_Enter3-1 = "I am preparing for all possibilities here..."
10133-CVGroup_UICarrierLobby_Enter4-1 = "(I built a kitchen, but...)"
10133-CVGroup_UICarrierLobby_Enter4-2 = "(Was that irrational after all...?)"
10133-CVGroup_UICarrierLobby_Enter5-1 = "(How should I go about starting a conversation...)"
10133-CVGroup_UICarrierLobby_Idle1-1 = "Just in case, I am continuing the monitoring."
10133-CVGroup_UICarrierLobby_Idle2-1 = "A game console... even though it is just a simple device and program..."
10133-CVGroup_UICarrierLobby_Idle3-1 = "(The Game Development Department... I have always thought,)"
10133-CVGroup_UICarrierLobby_Idle3-2 = "(they are difficult to predict...)"
10133-CVGroup_UICarrierLobby_Idle4-1 = "Actually, I..."
10133-CVGroup_UICarrierLobby_Idle4-2 = "Sometimes I even fail at preparing retort food..."
10133-CVGroup_UICarrierLobby_Idle5-1 = "(How to converse with others...)"
10133-CVGroup_UICarrierLobby_Idle5-2 = "(I should probably consult Sensei...)"