[translation]
10132-CVGroup_UITitle_Idle1-1 = "Blue Archive."
10132-CVGroup_CharacterGet_Idle1-1 = "I am Oono Tsukuyo!\nEven though I am wearing a dress... I am still, truly, a member of the Ninjutsu Research Club...!"
10132-CVGroup_Cafe_Idle1-1 = "Uuu... am I being stared at too much...?"
10132-CVGroup_Cafe_Idle2-1 = "It would be terrible if I got a stain on this dress... so... I must be careful..."
10132-CVGroup_Cafe_Idle3-1 = "Ugh... I wish I could just... blend into that furniture over there..."
10132-CVGroup_Cafe_Idle4-1 = "When wearing a dress, I have to... be mindful of how I walk..."
10132-CVGroup_Cafe_Idle5-1 = "(Everyone... has such unique styles, don't they?)"
10132-CVGroup_WeaponGet_Idle1-1 = "I will... continue to do my very best.\nSo that I can become a fine ninja... alongside everyone else...!"
10132-CVGroup_UIEventLobby_Enter1-1 = "Sensei...!?\nIs this dress... really... strange...?"
10132-CVGroup_UIEventLobby_Enter2-1 = "Welcome back, Sensei..."
10132-CVGroup_UIEventLobby_Enter2-2 = "Um, this outfit is, well..."
10132-CVGroup_UIEventLobby_Enter3-1 = "What on earth... is happening...?"
10132-CVGroup_UIEventLobby_Enter4-1 = "Being on stage is... mysterious."
10132-CVGroup_UIEventLobby_Enter4-2 = "Even though so many people... are watching me..."
10132-CVGroup_UIEventLobby_Enter4-3 = "There are moments... where I feel so lonely..."
10132-CVGroup_UIEventLobby_Enter5-1 = "Everyone...! \nI have... returned...!"
10132-CVGroup_UIEventLobby_Idle1-1 = "Am I... truly worthy of this outfit...?"
10132-CVGroup_UIEventLobby_Idle2-1 = "I'm definitely standing out, aren't I...?"
10132-CVGroup_UIEventLobby_Idle2-2 = "Ugh... and I'm supposed to be a ninja..."
10132-CVGroup_UIEventLobby_Idle3-1 = "A-a-a-are you saying I look pretty...!?"
10132-CVGroup_UIEventLobby_Idle3-2 = "Hyaaaa..."
10132-CVGroup_UIEventLobby_Idle4-1 = "If I think of this outfit as..."
10132-CVGroup_UIEventLobby_Idle4-2 = "Just another form of disguise..."
10132-CVGroup_UIEventMission_Enter1-1 = "I have... compiled a list of things to do..."
10132-CVGroup_UIEventMission_Enter2-1 = "None of them are easy, but..."
10132-CVGroup_UIEventMission_Enter2-2 = "I'm sure that you, Sensei...!"
10132-CVGroup_UIEventMission_Idle1-1 = "Um... was there... a problem with the list I made...?"
10132-CVGroup_UIEventMission_Idle2-1 = "Sensei...? Is something the matter...?"
10132-CVGroup_UIEventMission_Buy1-1 = "As expected...!"
10132-CVGroup_UIEventMission_Buy1-2 = "I knew you could do it, Sensei...!"
10132-CVGroup_UIEventMission_Buy2-1 = "That's amazing...! \nDoes Sensei have a talent for ninjutsu too...!?"
10132-CVGroup_UIEventMission_Interaction1-1 = "Great work...! \nThat was a wonderful finale!"