[translation]
10135-CVGroup_UITitle_Idle1-1 = "I have to say it, right...? \nBlue Archive."
10135-CVGroup_CharacterGet_Idle1-1 = "Hello, I am Kei. \nWhy are you in such a rush...? \nHaa... From now on, I will watch over you, Sensei."
10135-CVGroup_Cafe_Idle1-1 = "(I am a 'student' too, after all... so a cafe is...!)"
10135-CVGroup_Cafe_Idle2-1 = "What does that... taste like?"
10135-CVGroup_Cafe_Idle3-1 = "I see... so this is what it means to relax..."
10135-CVGroup_Cafe_Idle4-1 = "Having a physical body of my own... \nIt can be quite inconvenient, can't it..."
10135-CVGroup_Cafe_Idle5-1 = "Hehe... just standing here like this is somehow fun..."
10135-CVGroup_WeaponGet_Idle1-1 = "It means 'starlight from a distant land.' \nI believe it refers to something from that long ago. \nAccording to the coordinates, they say the past and the future exist simultaneously."
10135-CVGroup_UICarrierLobby_Enter1-1 = "One step toward our first goal, then."
10135-CVGroup_UICarrierLobby_Enter2-1 = "I wonder what kind of drinks everyone likes..."
10135-CVGroup_UICarrierLobby_Enter3-1 = "This body... I feel like it's quite well-made."
10135-CVGroup_UICarrierLobby_Enter4-1 = "Good work, everyone."
10135-CVGroup_UICarrierLobby_Enter5-1 = "Aris has gone to sleep."
10135-CVGroup_UICarrierLobby_Enter6-1 = "I think I'm starting to understand the saying that rest is important..."
10135-CVGroup_UICarrierLobby_Enter7-1 = "Honestly, those three in white...!"
10135-CVGroup_UICarrierLobby_Idle1-1 = "I will never let Aris or any of you get hurt."
10135-CVGroup_UICarrierLobby_Idle2-1 = "Is there any point in putting money into this vending machine...?"
10135-CVGroup_UICarrierLobby_Idle3-1 = "I suppose I can at least acknowledge their engineering skills."
10135-CVGroup_UICarrierLobby_Idle4-1 = "Eimi and Toki went to inspect the transport ship."
10135-CVGroup_UICarrierLobby_Idle5-1 = "Don't forget to take a break, Sensei!"
10135-CVGroup_UICarrierLobby_Idle5-2 = "And brush your teeth too!"
10135-CVGroup_UICarrierLobby_Idle6-1 = "Everything seems to be in order, right?"
10135-CVGroup_UICarrierLobby_Idle7-1 = "...Since I am the older sister, I will endure it."
10135-CVGroup_UIEventShop_Enter1-1 = "This is like... a total war in an emergency."
10135-CVGroup_UIEventShop_Enter1-2 = "I'm managing the shop, if only to provide support."
10135-CVGroup_UIEventShop_Enter2-1 = "Hurry up, Sensei! We're at our limit here too!"
10135-CVGroup_UIEventShop_Idle1-1 = "Markos... and that trio..."
10135-CVGroup_UIEventShop_Idle1-2 = "Honestly! No one listens to a word I say!"
10135-CVGroup_UIEventShop_Idle2-1 = "When this is over... will we be able to go home?"
10135-CVGroup_UIEventShop_Buy1-1 = "It should be right there! Hurry!"
10135-CVGroup_UIEventShop_Buy2-1 = "Pick it quickly and get back to commanding!"
10135-CVGroup_UIEventShop_Buy3-1 = "Huh? You want some kind words...?"
10135-CVGroup_UIEventShop_Buy3-2 = "Choose your time and place for such nonsense!"
10135-CVGroup_UIEventShop_Buy3-3 = "Really... we'd be lost without you, Sensei."
10135-CVGroup_UIEventShop_Buy4-1 = "Is there anything else you need?"
10135-CVGroup_UIEventShop_Buy4-2 = "There isn't much time left to hesitate."
10135-CVGroup_UIEventMission_Enter1-1 = "Consistency is power, you know."
10135-CVGroup_UIEventMission_Enter1-2 = "Are you listening, Sensei?"
10135-CVGroup_UIEventMission_Enter1-3 = "I'm telling you to be sincere, aren't I?"
10135-CVGroup_UIEventMission_Enter2-1 = "Hello, Sensei."
10135-CVGroup_UIEventMission_Enter2-2 = "I've summarized what needs to be done today."
10135-CVGroup_UIEventMission_Idle1-1 = "Is something the matter?"
10135-CVGroup_UIEventMission_Idle1-2 = "Huh? You just called me... for no reason?"
10135-CVGroup_UIEventMission_Idle1-3 = "If you don't have any business, don't call me!"
10135-CVGroup_UIEventMission_Idle1-4 = "...Though, once in a while is fine."
10135-CVGroup_UIEventMission_Idle2-1 = "I-I don't get ticklish or anything!"
10135-CVGroup_UIEventMission_Idle2-2 = "Being ticklish, it's not like I..."
10135-CVGroup_UIEventMission_Idle2-3 = "Uwaaa!! Take this, tickle attack!!"
10135-CVGroup_UIEventMission_Buy1-1 = "...Here, take it."
10135-CVGroup_UIEventMission_Buy1-2 = "W-what is it!? Do you want me to say something!?"
10135-CVGroup_UIEventMission_Buy1-3 = "...Well done, Sensei."
10135-CVGroup_UIEventMission_Buy2-1 = "I thought you'd be coming around now."
10135-CVGroup_UIEventMission_Buy2-2 = "W-why are you petting me all of a sudden!?"
10135-CVGroup_UIEventMission_Buy2-3 = "...I didn't say stop."
10135-CVGroup_UIEventMission_Interaction1-1 = "See, you can do it if you try."
10135-CVGroup_UIEventMission_Interaction1-2 = "Keep up the good work next time too."
10135-CVGroup_UIEventMission_Interaction1-3 = "...Okay?"