[translation]
10134-CVGroup_UITitle_Idle1-1 = "Blue Archive!"
10134-CVGroup_CharacterGet_Idle1-1 = "Aris, moving out!"
10134-CVGroup_Cafe_Idle1-1 = "This... it looks just like Kei!"
10134-CVGroup_Cafe_Idle2-1 = "Aris is starting to feel a little sleepy..."
10134-CVGroup_Cafe_Idle3-1 = "This is a PK-prohibited area!"
10134-CVGroup_Cafe_Idle4-1 = "(Scan complete. Hostile reaction... none.)"
10134-CVGroup_Cafe_Idle5-1 = "Where is the charger?"
10134-CVGroup_WeaponGet_Idle1-1 = "The Sword of Light has always shown Aris the path forward.\nYes... just like you, Sensei!"
10134-CVGroup_UICarrierLobby_Enter1-1 = "Aris... I'm feeling kind of excited!"
10134-CVGroup_UICarrierLobby_Enter2-1 = "I brought my game console!"
10134-CVGroup_UICarrierLobby_Enter2-2 = "Would you like to join me, Sensei?"
10134-CVGroup_UICarrierLobby_Enter3-1 = "Everyone was amazing!"
10134-CVGroup_UICarrierLobby_Enter4-1 = "You were all truly impressive! I respect you!"
10134-CVGroup_UICarrierLobby_Enter5-1 = "Aris can still do more. Sensei!"
10134-CVGroup_UICarrierLobby_Enter6-1 = "Momoi and Midori said they were going to rest in their room..."
10134-CVGroup_UICarrierLobby_Idle1-1 = "...So this is the first step toward saving the world."
10134-CVGroup_UICarrierLobby_Idle1-2 = "Aris will do her best!"
10134-CVGroup_UICarrierLobby_Idle2-1 = "Rest is important, especially at times like this!"
10134-CVGroup_UICarrierLobby_Idle3-1 = "It's a good thing to be free...!"
10134-CVGroup_UICarrierLobby_Idle4-1 = "Courage... that is the true power!"
10134-CVGroup_UICarrierLobby_Idle5-1 = "To cheer up, I suppose..."
10134-CVGroup_UICarrierLobby_Idle5-2 = "It would be better to have something to eat or drink..."
10134-CVGroup_UICarrierLobby_Idle6-1 = "As long as everyone is safe..."
10134-CVGroup_UICarrierLobby_Idle6-2 = "That is enough for Aris."
10134-CVGroup_UIEventMission_Enter1-1 = "Sensei! It's a mission, a mission!"
10134-CVGroup_UIEventMission_Enter2-1 = "What is today's mission?"
10134-CVGroup_UIEventMission_Enter2-2 = "Ah, cleaning up was Aris's job, wasn't it..."
10134-CVGroup_UIEventMission_Enter3-1 = "Pardon the interruption! Sensei! It's Aris!"
10134-CVGroup_UIEventMission_Enter4-1 = "We're in a tough situation, but..."
10134-CVGroup_UIEventMission_Enter4-2 = "Let's overcome it together!"
10134-CVGroup_UIEventMission_Idle1-1 = "Heh, heh, heh..."
10134-CVGroup_UIEventMission_Idle1-2 = "What do you think, Sensei? Aris's new armor!"
10134-CVGroup_UIEventMission_Idle2-1 = "Even without armor..."
10134-CVGroup_UIEventMission_Idle2-2 = "Even if I lose the Sword of Light..."
10134-CVGroup_UIEventMission_Idle2-3 = "Even then, Aris is still Aris."
10134-CVGroup_UIEventMission_Idle2-4 = "As long as everyone is here... and..."
10134-CVGroup_UIEventMission_Idle2-5 = "As long as you are here, Sensei!"
10134-CVGroup_UIEventMission_Idle3-1 = "Malkuth..."
10134-CVGroup_UIEventMission_Idle3-2 = "It really feels like a final boss!"
10134-CVGroup_UIEventMission_Idle3-3 = "If we defeat it... a secret boss won't appear, right...?"
10134-CVGroup_UIEventMission_Idle4-1 = "If we can make it back safely..."
10134-CVGroup_UIEventMission_Idle4-2 = "I want to introduce everyone to Kei!"
10134-CVGroup_UIEventMission_Buy1-1 = "Ta-da!"
10134-CVGroup_UIEventMission_Buy1-2 = "Sensei has earned a reward!"
10134-CVGroup_UIEventMission_Buy2-1 = "That's amazing, Sensei!"
10134-CVGroup_UIEventMission_Buy2-2 = "Let's keep moving forward, one step at a time!"
10134-CVGroup_UIEventMission_Buy3-1 = "Ugh... Aris wants to celebrate by your side too, Sensei!"
10134-CVGroup_UIEventMission_Buy4-1 = "Yes! Aris loves that you are always the same, Sensei!"
10134-CVGroup_UIEventMission_Interaction1-1 = "Wow! Aris is happy too!"
10134-CVGroup_UIEventMission_Interaction2-1 = "Great work again today, Sensei!"