[translation]
16019-CVGroup_UITitle_Idle1-1 = "Blue Archive."
16019-CVGroup_CharacterGet_Idle1-1 = "Perfect maid, perfect recon.\nI am Asuma Toki.\nYou can rest easy and leave everything to me."
16019-CVGroup_Cafe_Idle1-1 = "Rest is important. A four-day work week would be appropriate, I think."
16019-CVGroup_Cafe_Idle2-1 = "Is there anywhere I can rest my body?"
16019-CVGroup_Cafe_Idle3-1 = "Caffeine and sugar are essential."
16019-CVGroup_Cafe_Idle4-1 = "The recipe for this cafe is... acceptable."
16019-CVGroup_Cafe_Idle5-1 = "Let's rest for the next mission."
16019-CVGroup_WeaponGet_Idle1-1 = "Changing weapons requires a bold decision.\nIt's as big a deal as changing your breakfast menu from toast to pancakes.\nHowever, if it's something I received from Sensei... that's a different story."
16019-CVGroup_UICarrierLobby_Enter1-1 = "Please, have some chamomile tea."
16019-CVGroup_UICarrierLobby_Enter1-2 = "They say it has a relaxing effect."
16019-CVGroup_UICarrierLobby_Enter2-1 = "It is enough for me if Sensei watches my performance."
16019-CVGroup_UICarrierLobby_Enter3-1 = "I am bored. Please play with me."
16019-CVGroup_UICarrierLobby_Enter4-1 = "I've recently acquired a hobby (tentative)."
16019-CVGroup_UICarrierLobby_Enter5-1 = "Reconnaissance? Give me your orders."
16019-CVGroup_UICarrierLobby_Idle1-1 = "As a perfect maid and best agent."
16019-CVGroup_UICarrierLobby_Idle1-2 = "If there is anything I can help you with, please let me know."
16019-CVGroup_UICarrierLobby_Idle2-1 = "Thanks to the lightweight suit, more agile movements are now possible."
16019-CVGroup_UICarrierLobby_Idle3-1 = "I should have brought more manga."
16019-CVGroup_UICarrierLobby_Idle4-1 = "There is an archive of the stream."
16019-CVGroup_UICarrierLobby_Idle4-2 = "Would you like to watch it with me?"
16019-CVGroup_UICarrierLobby_Idle5-1 = "I work hard on my missions for everyone's sake."
16019-CVGroup_UICarrierLobby_Idle5-2 = "...And at the same time, to be praised."
16019-CVGroup_UIEventShop_Enter1-1 = "Welcome to Asuma Toki's shop."
16019-CVGroup_UIEventShop_Enter1-2 = "...I lied. It's everyone's shop."
16019-CVGroup_UIEventShop_Enter2-1 = "I couldn't prepare many items, but..."
16019-CVGroup_UIEventShop_Enter2-2 = "I hope I can be of help to Sensei."
16019-CVGroup_UIEventShop_Enter3-1 = "I am Asuma Toki. I am greeting you through the screen."
16019-CVGroup_UIEventShop_Enter3-2 = "I should have visited in person, but due to an emergency, please excuse me for communicating via transmission."
16019-CVGroup_UIEventShop_Enter4-1 = "Even in an emergency, Asuma Toki's shop is open for business."
16019-CVGroup_UIEventShop_Idle1-1 = "Yes, Sensei. I am here."
16019-CVGroup_UIEventShop_Idle1-2 = "I won't run or hide—"
16019-CVGroup_UIEventShop_Idle1-3 = "No... if I were to disappear,\nwould you search for me with bloodshot eyes, Sensei?"
16019-CVGroup_UIEventShop_Idle2-1 = "What do you think?"
16019-CVGroup_UIEventShop_Idle2-2 = "Heat retention, stability, and it also has a relaxing effect on the mind and body—"
16019-CVGroup_UIEventShop_Idle2-3 = "It is an excellent combat suit, just like me."
16019-CVGroup_UIEventShop_Idle2-4 = "Sensei, let's check the suit's functions together."
16019-CVGroup_UIEventShop_Idle2-5 = "You are free to stick to me as much as you like, so please don't hesitate."
16019-CVGroup_UIEventShop_Idle3-1 = "Please wait a moment."
16019-CVGroup_UIEventShop_Idle3-2 = "With a perfect maid's memory, I will recall the location of the stock."
16019-CVGroup_UIEventShop_Idle4-1 = "I am responding online out of necessity, but it does not hinder business."
16019-CVGroup_UIEventShop_Idle4-2 = "A best agent does not choose their field of activity."
16019-CVGroup_UIEventShop_Buy1-1 = "Thank you for your purchase."
16019-CVGroup_UIEventShop_Buy1-2 = "By the way, if you say the word, I can make a purchase too."
16019-CVGroup_UIEventShop_Buy2-1 = "That item, understood."
16019-CVGroup_UIEventShop_Buy2-2 = "While waiting for the restock to be completed, why not play with me?"
16019-CVGroup_UIEventShop_Buy3-1 = "So you like these kinds of things, I see."
16019-CVGroup_UIEventShop_Buy4-1 = "Yes, here you go.\nI look forward to your next visit."
16019-CVGroup_UIEventShop_Buy4-2 = "Please come to see me again, as many times as you like."
16019-CVGroup_UIEventShop_Buy5-1 = "Yes, I think that is good."
16019-CVGroup_UIEventShop_Buy6-1 = "Please take that item from the shelf behind you."
16019-CVGroup_UIEventShop_Buy7-1 = "If you bought the wrong item, returns are possible."
16019-CVGroup_UIEventShop_Buy7-2 = "...I'm sorry. That was not possible."
16019-CVGroup_UIEventShop_Buy8-1 = "If you wish, I will include a call ticket with me as a bonus."
16019-CVGroup_UIEventShop_Buy8-2 = "Of course, you want one, right?"