[translation]
20056-CVGroup_UITitle_Idle1-1 = "Blue! Archive!"
20056-CVGroup_CharacterGet_Idle1-1 = "Ni-ha-ha-ha!\nYou've finally made it this far, Sensei!\nRight to where I, Koyuki Kurozaki, am!"
20056-CVGroup_Cafe_Idle1-1 = "(A place I could hide... is here!)"
20056-CVGroup_Cafe_Idle2-1 = "(I wonder... can I use a Seminar card here?)"
20056-CVGroup_Cafe_Idle3-1 = "You didn't actually follow me all the way here... did you?"
20056-CVGroup_Cafe_Idle4-1 = "Where are you, Sensei~?"
20056-CVGroup_Cafe_Idle5-1 = "Today's coffee is... a random blend!?\nUgh... that's not really my thing."
20056-CVGroup_WeaponGet_Idle1-1 = "I'm sure the greatest stroke of luck was meeting you, Sensei!\nSo, well... I'll give it my all!\nI'm counting on you!"
20056-CVGroup_UIEventLobby_Enter1-1 = "W-who's there!?"
20056-CVGroup_UIEventLobby_Enter1-2 = "...Oh, it was just you, Sensei!!"
20056-CVGroup_UIEventLobby_Enter2-1 = "You came for me, Sensei!"
20056-CVGroup_UIEventLobby_Enter2-2 = "Everything is already set up."
20056-CVGroup_UIEventLobby_Enter2-3 = "Just take a seat for now!"
20056-CVGroup_UIEventLobby_Enter3-1 = "You really came!"
20056-CVGroup_UIEventLobby_Enter3-2 = "You couldn't help yourself, could you? Could you!?"
20056-CVGroup_UIEventLobby_Enter4-1 = "Hehe, leave it to me."
20056-CVGroup_UIEventLobby_Enter4-2 = "Escaping is my specialty, after all!"
20056-CVGroup_UIEventLobby_Enter5-1 = "I feel like a lot of things happened, but..."
20056-CVGroup_UIEventLobby_Enter5-2 = "Well, for tonight at least."
20056-CVGroup_UIEventLobby_Enter5-3 = "Let's play until the sun comes up...!"
20056-CVGroup_UIEventLobby_Enter5-4 = "...That's what I'd like to say, but..."
20056-CVGroup_UIEventLobby_Enter5-5 = "...Ni-ha."
20056-CVGroup_UIEventLobby_Idle1-1 = "What do you think? How does it feel to touch...\nIt's fluffy, right?"
20056-CVGroup_UIEventLobby_Idle2-1 = "You came to rescue me, Sensei!"
20056-CVGroup_UIEventLobby_Idle2-2 = "Wait, did you get captured too, Sensei!?"
20056-CVGroup_UIEventLobby_Idle3-1 = "This board game is rigged!"
20056-CVGroup_UIEventLobby_Idle3-2 = "It explodes every single time it's my turn!!"
20056-CVGroup_UIEventLobby_Idle4-1 = "Ugh... this cramped reflection room..."
20056-CVGroup_UIEventLobby_Idle4-2 = "Well, maybe this isn't so bad after all...?"