[translation]
20057-CVGroup_UITitle_Idle1-1 = "Blue Archive. Hehe."
20057-CVGroup_CharacterGet_Idle1-1 = "Millennium Science School, callsign 03, Murokasa Akane.\nI greet you as a student. Hehe, though I suppose I was a student to begin with, wasn't I?"
20057-CVGroup_Cafe_Idle1-1 = "I should prepare some cake for the time being."
20057-CVGroup_Cafe_Idle2-1 = "It's quite relaxing here."
20057-CVGroup_Cafe_Idle3-1 = "I'd like to have that furniture in our clubroom, too."
20057-CVGroup_Cafe_Idle4-1 = "(It's well-cleaned, but... the attention to detail is lacking.)"
20057-CVGroup_Cafe_Idle5-1 = "(Given this size... the amount of explosives needed would be...)"
20057-CVGroup_WeaponGet_Idle1-1 = "In Kivotos, a gun is a necessity.\nThat doesn't change whether you're a maid or a student.\nAmong the many guns out there...\nI will continue to do my best with this 'cleaning tool' I received from you, Sensei."
20057-CVGroup_UIEventLobby_Enter1-1 = "I've been waiting for you, Sensei."
20057-CVGroup_UIEventLobby_Enter1-2 = "Leave the tour of Millennium to me."
20057-CVGroup_UIEventLobby_Enter2-1 = "If there's anywhere you'd like to go, please don't hesitate to ask."
20057-CVGroup_UIEventLobby_Enter3-1 = "It's usually lively, but..."
20057-CVGroup_UIEventLobby_Enter3-2 = "Millennium is especially so today."
20057-CVGroup_UIEventLobby_Enter3-3 = "It's a good thing to have such energy, though."
20057-CVGroup_UIEventLobby_Enter4-1 = "We're finally reaching the climax."
20057-CVGroup_UIEventLobby_Enter4-2 = "Both the EXPO and the troublesome incidents."
20057-CVGroup_UIEventLobby_Enter5-1 = "Did you enjoy the Millennium EXPO?"
20057-CVGroup_UIEventLobby_Enter5-2 = "I was honored to spend it with you, Sensei."
20057-CVGroup_UIEventLobby_Enter5-3 = "...Yes, very much so."
20057-CVGroup_UIEventLobby_Idle1-1 = "Being able to spend time with you like this..."
20057-CVGroup_UIEventLobby_Idle1-2 = "I am truly happy about it."
20057-CVGroup_UIEventLobby_Idle2-1 = "Please let me know if you get hungry."
20057-CVGroup_UIEventLobby_Idle2-2 = "I know a great school cafeteria."
20057-CVGroup_UIEventLobby_Idle2-3 = "If I were acting as a 'maid,' I would prepare a home-cooked meal for you, but..."
20057-CVGroup_UIEventLobby_Idle2-4 = "Right now, I am a 'student,' after all."
20057-CVGroup_UIEventLobby_Idle3-1 = "Did you call for me, Sensei?"
20057-CVGroup_UIEventLobby_Idle3-2 = "You just called me... for no reason?"
20057-CVGroup_UIEventLobby_Idle3-3 = "Hehe, oh my."
20057-CVGroup_UIEventLobby_Idle4-1 = "Hehe."
20057-CVGroup_UIEventLobby_Idle4-2 = "I'm actually quite resistant to being tickled."
20057-CVGroup_UIEventLobby_Idle4-3 = "Would you mind telling me... how you fare, Sensei?"