[translation]
20054-CVGroup_UITitle_Idle1-1 = "Blue Archive"
20054-CVGroup_CharacterGet_Idle1-1 = "Department head, infiltration, rear support.\nThe super-genius, pure, sickly, all-around beautiful girl hacker who can do it all,\nAkeboshi Himari—arriving right on cue.\nSensei, I've kept you waiting."
20054-CVGroup_Cafe_Idle1-1 = "(Isn't the air conditioning set a bit too low?)"
20054-CVGroup_Cafe_Idle2-1 = "This is the perfect place to take a breather."
20054-CVGroup_Cafe_Idle3-1 = "Moderate caffeine intake has many benefits, you know."
20054-CVGroup_Cafe_Idle4-1 = "A place where one can relax is quite important."
20054-CVGroup_Cafe_Idle5-1 = "I'll pass on the cold drink."
20054-CVGroup_WeaponGet_Idle1-1 = "Thank you.\nTruthfully, it would be best if I didn't have to use weapons at all...\nBut being prepared is important, after all."
20054-CVGroup_UICarrierBridge_Enter1-1 = "Grasping and analyzing the situation is the priority."
20054-CVGroup_UICarrierBridge_Enter1-2 = "Even that is not easy, though."
20054-CVGroup_UICarrierBridge_Enter2-1 = "The Steel Continent... truly a 'singular phenomenon'."
20054-CVGroup_UICarrierBridge_Enter2-2 = "Though it is a bit different from what I had expected."
20054-CVGroup_UICarrierBridge_Enter3-1 = "Sensei. Please deliver the final blow."
20054-CVGroup_UICarrierBridge_Enter4-1 = "I must find what I can do here."
20054-CVGroup_UICarrierBridge_Enter5-1 = "(Sensei telling us to return to the transport ship)"
20054-CVGroup_UICarrierBridge_Enter5-2 = "(must have a reason.)"
20054-CVGroup_UICarrierBridge_Enter6-1 = "It is time to end everything."
20054-CVGroup_UICarrierBridge_Enter6-2 = "We will also give it our all."
20054-CVGroup_UICarrierBridge_Enter7-1 = "The long journey is finally reaching its climax."
20054-CVGroup_UICarrierBridge_Idle1-1 = "We've finally made it this far."
20054-CVGroup_UICarrierBridge_Idle2-1 = "We will... definitely find a way."
20054-CVGroup_UICarrierBridge_Idle3-1 = "(Sensei said... 'in case of emergency'.)"
20054-CVGroup_UICarrierBridge_Idle3-2 = "(That means...)"
20054-CVGroup_UICarrierBridge_Idle4-1 = "Everyone... please stay safe..."
20054-CVGroup_UICarrierBridge_Idle5-1 = "Did you know? There is no end to astrology."
20054-CVGroup_UICarrierBridge_Idle5-2 = "Everything is cyclical."
20054-CVGroup_UICarrierLobby_Enter1-1 = "Calmness is essential when accomplishing great things."
20054-CVGroup_UICarrierLobby_Enter2-1 = "Sweets help reduce stress, you know."
20054-CVGroup_UICarrierLobby_Enter3-1 = "For a break..."
20054-CVGroup_UICarrierLobby_Enter3-2 = "Shall I make you something warm to drink?"
20054-CVGroup_UICarrierLobby_Enter4-1 = "Thank goodness... I'm glad everyone is safe."
20054-CVGroup_UICarrierLobby_Idle1-1 = "Shall I try to predict the future with astrology...?"
20054-CVGroup_UICarrierLobby_Idle2-1 = "A drink in the same color as today's lucky color is..."
20054-CVGroup_UICarrierLobby_Idle3-1 = "Apparently, you can even tell fortunes with coffee."
20054-CVGroup_UICarrierLobby_Idle4-1 = "No need to worry. I am still doing just fine."