[translation]
20053-CVGroup_UITitle_Idle1-1 = "Blu~! Ahem... Archive?"
20053-CVGroup_CharacterGet_Idle1-1 = "Sensei~! How are you doing? This time, it's an infiltration mission!\nI'm counting on you!"
20053-CVGroup_Cafe_Idle1-1 = "Hehe... What should I do if someone notices me...?"
20053-CVGroup_Cafe_Idle2-1 = "This dress... is it too much to wear here...?"
20053-CVGroup_Cafe_Idle3-1 = "(A dress and coffee... Ah! I might be able to use this idea...!)"
20053-CVGroup_Cafe_Idle4-1 = "Someday, for sure...! I'll hold a fan meeting here...!"
20053-CVGroup_Cafe_Idle5-1 = "(Alright! For now... I wonder where a place is that no one will see me?)"
20053-CVGroup_WeaponGet_Idle1-1 = "Are you sure...? For me, something like this...! \nBut, if it's Sensei's decision! Yeah! Thank you!"
20053-CVGroup_UIEventLobby_Enter1-1 = "If I'm taking something on an infiltration mission, should it be a rice ball or a soldier's ration—"
20053-CVGroup_UIEventLobby_Enter1-2 = "Hm?\nSensei! Welcome!"
20053-CVGroup_UIEventLobby_Enter2-1 = "Sensei... that's a nice outfit."
20053-CVGroup_UIEventLobby_Enter2-2 = "This kind of look is refreshing, too."
20053-CVGroup_UIEventLobby_Enter3-1 = "Gaaah!\nWhy are we starting a fight at a fashion show!?"
20053-CVGroup_UIEventLobby_Enter4-1 = "I want to see Tsukuyo..."
20053-CVGroup_UIEventLobby_Enter4-2 = "I wonder if she's doing well... I hope she's eating her ramen properly..."
20053-CVGroup_UIEventLobby_Enter5-1 = "The Ninjutsu Research Club, fully revived!"
20053-CVGroup_UIEventLobby_Enter5-2 = "Sensei too! Over here, over here!"
20053-CVGroup_UIEventLobby_Idle1-1 = "I'm kinda bored..."
20053-CVGroup_UIEventLobby_Idle1-2 = "Hm? You say something always happens when I say that?"
20053-CVGroup_UIEventLobby_Idle2-1 = "Ugh... this is tight and hard to move in..."
20053-CVGroup_UIEventLobby_Idle2-2 = "What do you all like about this!?"
20053-CVGroup_UIEventLobby_Idle3-1 = "Clothing does not define a ninja..."
20053-CVGroup_UIEventLobby_Idle3-2 = "Then, what is it that makes a ninja a ninja...!?"
20053-CVGroup_UIEventLobby_Idle4-1 = "Watch closely...!"
20053-CVGroup_UIEventLobby_Idle4-2 = "A dress is no obstacle at all—to a ninja...!"
20053-CVGroup_UIEventShop_Enter1-1 = "Welcome, Sensei!\nTake your time looking around."
20053-CVGroup_UIEventShop_Enter1-2 = "Ah! But, about this product, in my opinion—"
20053-CVGroup_UIEventShop_Enter2-1 = "We have everything except what we don't have! Heh heh heh!"
20053-CVGroup_UIEventShop_Enter3-1 = "Heh heh~ Let's close up early and go eat a new ninja set meal!"
20053-CVGroup_UIEventShop_Idle1-1 = "Choose carefully, buy boldly...!"
20053-CVGroup_UIEventShop_Idle1-2 = "That is the rule when buying goods...!"
20053-CVGroup_UIEventShop_Idle2-1 = "Someday, I'll have 'Girl Ninja Scroll Michiru-chi' goods here...!"
20053-CVGroup_UIEventShop_Buy1-1 = "Oh~ that one, huh. Good choice, right?"
20053-CVGroup_UIEventShop_Buy2-1 = "Yes! If you're a ninja, you have to choose that!"
20053-CVGroup_UIEventShop_Buy3-1 = "Would you like this warmed u—"
20053-CVGroup_UIEventShop_Buy3-2 = "Ah, my mistake."
20053-CVGroup_UIEventShop_Buy4-1 = "Oh...! That is truly! A top-recommended product!"
20053-CVGroup_UIEventShop_Buy4-2 = "Well, they're all top-recommended, though!"
20053-CVGroup_UIEventFortuneGachashop_Ramen_Enter1-1 = "Ah, Sensei came too!"
20053-CVGroup_UIEventFortuneGachashop_Ramen_Enter1-2 = "...Me? I was just wondering which one to pick."
20053-CVGroup_UIEventFortuneGachashop_Ramen_Enter2-1 = "Mmm~ it smells so good—"
20053-CVGroup_UIEventFortuneGachashop_Ramen_Enter2-2 = "It's not just that! Well, let's give it a try!"
20053-CVGroup_UIEventFortuneGachashop_Ramen_Enter3-1 = "Thank you for the meal... I can't fit anything else in..."
20053-CVGroup_UIEventFortuneGachashop_Ramen_Idle1-1 = "Noodles and soup... that is truly ninja and ninjutsu..."
20053-CVGroup_UIEventFortuneGachashop_Ramen_Idle2-1 = "What kind of ramen does Sensei like?"
20053-CVGroup_UIEventFortuneGachashop_Ramen_Luck4-1 = "Oh...!"
20053-CVGroup_UIEventFortuneGachashop_Ramen_Luck4-2 = "This is a flavor that makes me feel like I could invent a new ninjutsu...!!"
20053-CVGroup_UIEventFortuneGachashop_Ramen_Luck3-1 = "Nyaa...!? Th-this flavor is...!"
20053-CVGroup_UIEventFortuneGachashop_Ramen_Luck2-1 = "Hmm, not bad, huh...?"
20053-CVGroup_UIEventFortuneGachashop_Ramen_Luck1-1 = "It's not bad, but... it's not bad... really, that's all..."
20053-CVGroup_UIEventFortuneGachashop_Ramen_Luck0-1 = "Eh... is this really ramen...?"