[translation]
20055-CVGroup_UITitle_Idle1-1 = "Blue... *sigh*...! Archive!"
20055-CVGroup_CharacterGet_Idle1-1 = "Millennium Science School...\nI'm Hanaoka Yuzu from the Game Development Department...\nI, I know I'm dressed like this, but...\nNice to meet you..."
20055-CVGroup_Cafe_Idle1-1 = "(A peaceful daily life...\nI truly understand\nits importance\nnow.)"
20055-CVGroup_Cafe_Idle2-1 = "The sofa...\nIt won't suddenly\nlaunch me, will it...?"
20055-CVGroup_Cafe_Idle3-1 = "It's warm and\nsmells nice...\nThis is lovely.\nHehehe."
20055-CVGroup_Cafe_Idle4-1 = "I don't want to\nget inside a locker\nfor a while...\nUgh."
20055-CVGroup_Cafe_Idle5-1 = "Is this, um...\na bit too flashy\nafter all...?\nUuu..."
20055-CVGroup_WeaponGet_Idle1-1 = "Practice like it's the real thing. The real thing like it's a game...! I will do my best...!"
20055-CVGroup_UICarrierLobby_Enter1-1 = "Is there... a place to hide...?"
20055-CVGroup_UICarrierLobby_Enter2-1 = "There are game consoles here too..."
20055-CVGroup_UICarrierLobby_Enter3-1 = "I don't want to... get off anymore..."
20055-CVGroup_UICarrierLobby_Enter4-1 = "Sensei... so you've been fighting enemies like this..."
20055-CVGroup_UICarrierLobby_Enter5-1 = "President Rio and Himari-senpai are both... amazing..."
20055-CVGroup_UICarrierLobby_Idle1-1 = "I, I knew it, outside the locker is dangerous..."
20055-CVGroup_UICarrierLobby_Idle2-1 = "(I wonder what kind of games are downloaded here...?)"
20055-CVGroup_UICarrierLobby_Idle3-1 = "Sensei... you'll stay with me, right...?"
20055-CVGroup_UICarrierLobby_Idle4-1 = "Somehow, when I'm with Sensei... I'm not scared... hehehe..."
20055-CVGroup_UICarrierLobby_Idle5-1 = "You've taught me many things, but..."
20055-CVGroup_UICarrierLobby_Idle5-2 = "I feel like I understand, but I also don't..."
20055-CVGroup_UIEventShop_Enter1-1 = "W-welcome,\nSensei..."
20055-CVGroup_UIEventShop_Enter2-1 = "For a place that's like a shop...\nit feels a bit lonely."
20055-CVGroup_UIEventShop_Idle1-1 = "Ugh... I'm kind of scared...\nUuu..."
20055-CVGroup_UIEventShop_Idle1-2 = "Sensei...\nYou won't forget\nabout me, right...?"
20055-CVGroup_UIEventShop_Idle2-1 = "I want to do\nwhat I can, but..."
20055-CVGroup_UIEventShop_Idle2-2 = "Everyone here\nis so amazing..."
20055-CVGroup_UIEventShop_Buy1-1 = "Ah, yes...! \nThat one, right...!"
20055-CVGroup_UIEventShop_Buy2-1 = "Act like a clerk...\nAct like a clerk..."
20055-CVGroup_UIEventShop_Buy2-2 = "Thank you as always!"
20055-CVGroup_UIEventShop_Buy3-1 = "Y-yes... here you go..."
20055-CVGroup_UIEventShop_Buy4-1 = "I, I hope this..."
20055-CVGroup_UIEventShop_Buy4-2 = "will be useful\nto everyone..."
20055-CVGroup_UIEventMission_Enter1-1 = "I'm okay...\nI'm okay, so...!"
20055-CVGroup_UIEventMission_Enter2-1 = "Must not run away,\nmust not run away..."
20055-CVGroup_UIEventMission_Enter2-2 = "Must not... run away...!"
20055-CVGroup_UIEventMission_Idle1-1 = "No matter what... missions are\nimportant, after all..."
20055-CVGroup_UIEventMission_Idle2-1 = "Why did it come to this..."
20055-CVGroup_UIEventMission_Idle3-1 = "If only we could have talked... a little more..."
20055-CVGroup_UIEventMission_Idle4-1 = "If there's anything\nI can do..."
20055-CVGroup_UIEventMission_Idle4-2 = "please tell me\nanytime...!"
20055-CVGroup_UIEventMission_Buy1-1 = "If this were a game system,"
20055-CVGroup_UIEventMission_Buy1-2 = "I think it would say: Mission Clear!"
20055-CVGroup_UIEventMission_Buy1-3 = "Hehehe... \nSaying that,"
20055-CVGroup_UIEventMission_Buy1-4 = "makes me feel a little less nervous."
20055-CVGroup_UIEventMission_Buy2-1 = "Sensei... \naren't you scared?"
20055-CVGroup_UIEventMission_Buy2-2 = "..."
20055-CVGroup_UIEventMission_Buy2-3 = "I, because Sensei is here..."
20055-CVGroup_UIEventMission_Buy2-4 = "I'll try a little harder."
20055-CVGroup_UIEventMission_Interaction1-1 = "Good work...! As expected of Sensei...!"