[translation]
20052-CVGroup_UITitle_Idle1-1 = "Blue, Archive, mufufu."
20052-CVGroup_CharacterGet_Idle1-1 = "Printing, binding, management, distribution—for any consultations regarding books, feel free to reach out to Red Winter Publishing Department Head, Aramaki Yakumo. Mufufu."
20052-CVGroup_Cafe_Idle1-1 = "Now then... where shall the new sales channels be..."
20052-CVGroup_Cafe_Idle2-1 = "It's so warm and relaxing here..."
20052-CVGroup_Cafe_Idle3-1 = "If I were to set up a shop over there... mufufu."
20052-CVGroup_Cafe_Idle4-1 = "Modern literature is quite like a platform business, you see."
20052-CVGroup_Cafe_Idle5-1 = "Now then, what are today's sales...?"
20052-CVGroup_WeaponGet_Idle1-1 = "A fool and his tools... \nFrom now on, it seems I'll be able to make sure contracts are 'properly' honored... mufufu."
20052-CVGroup_UIEventLobby_Enter1-1 = "No risk, no return."
20052-CVGroup_UIEventLobby_Enter1-2 = "Now then, shall we start the business?"
20052-CVGroup_UIEventLobby_Enter2-1 = "Now is the time to show you."
20052-CVGroup_UIEventLobby_Enter2-2 = "The expertise of my publishing department, which survived in the barren land of Red Winter!"
20052-CVGroup_UIEventLobby_Enter2-3 = "…Though perhaps,"
20052-CVGroup_UIEventLobby_Enter2-4 = "survival skills might be a more accurate term."
20052-CVGroup_UIEventLobby_Enter3-1 = "It's coming... the momentum is finally here!"
20052-CVGroup_UIEventLobby_Enter3-2 = "As the publishing department head, I will make sure to capitalize on this no matter what!"
20052-CVGroup_UIEventLobby_Enter4-1 = "How did it come to this..."
20052-CVGroup_UIEventLobby_Enter4-2 = "Well, I do feel like I can identify the cause, though..."
20052-CVGroup_UIEventLobby_Enter4-3 = "I can't give up just yet...!"
20052-CVGroup_UIEventLobby_Enter5-1 = "My, I was worried about how things would turn out for a moment there..."
20052-CVGroup_UIEventLobby_Enter5-2 = "I'm glad it went well... wait, a debriefing session?"
20052-CVGroup_UIEventLobby_Enter5-3 = "Um... could we do that another time... is that not okay...?"
20052-CVGroup_UIEventLobby_Idle1-1 = "Creators are..."
20052-CVGroup_UIEventLobby_Idle1-2 = "They have the power to create something,"
20052-CVGroup_UIEventLobby_Idle1-3 = "but when it comes to spreading it—"
20052-CVGroup_UIEventLobby_Idle1-4 = "they often show no interest, you see."
20052-CVGroup_UIEventLobby_Idle2-1 = "Books... writing is something precious."
20052-CVGroup_UIEventLobby_Idle2-2 = "It draws out the maximum output from the minimum input—"
20052-CVGroup_UIEventLobby_Idle2-3 = "it is a product that holds 'possibility' within it...!"
20052-CVGroup_UIEventLobby_Idle3-1 = "Being able to create something from zero is a wonderful thing."
20052-CVGroup_UIEventLobby_Idle3-2 = "And so is the talent that makes it possible."
20052-CVGroup_UIEventLobby_Idle3-3 = "..."
20052-CVGroup_UIEventLobby_Idle3-4 = "It's nice, isn't it, that kind of talent."
20052-CVGroup_UIEventLobby_Idle3-5 = "I truly... think so."
20052-CVGroup_UIEventLobby_Idle4-1 = "I am truly grateful to all the Trinity students, you know?"
20052-CVGroup_UIEventLobby_Idle4-2 = "…Please don't look at me with those eyes."
20052-CVGroup_UIEventLobby_Idle4-3 = "I really do mean it from the bottom of my heart."
20052-CVGroup_UIEventShop_Enter1-1 = "What do you think is the foundation of business? \nGoods...? Exchange...?"
20052-CVGroup_UIEventShop_Enter1-2 = "Of course, it's money, isn't it!"
20052-CVGroup_UIEventShop_Enter2-1 = "I'm so glad you came!"
20052-CVGroup_UIEventShop_Enter2-2 = "Welcome to the front lines of business, where funds and goods intersect!"
20052-CVGroup_UIEventShop_Enter2-3 = "Mufufu, please, take your time."
20052-CVGroup_UIEventShop_Enter3-1 = "Sometimes treasures are sleeping in the back of the shelves."
20052-CVGroup_UIEventShop_Enter3-2 = "Please take a good look until the very end, Sensei."
20052-CVGroup_UIEventShop_Enter3-3 = "Oh, of course, you're welcome to look at me closely too, if you'd like?"
20052-CVGroup_UIEventShop_Idle1-1 = "Just because you're talking to me doesn't mean it'll get any cheaper, you know?"
20052-CVGroup_UIEventShop_Idle1-2 = "Before a single discount is decided, countless negotiations..."
20052-CVGroup_UIEventShop_Idle1-3 = "…and political dealings are happening behind the scenes, after all."
20052-CVGroup_UIEventShop_Idle2-1 = "I never imagined the day would come where I'd be doing business with you, Sensei."
20052-CVGroup_UIEventShop_Idle2-2 = "My, it pays to live a long life."
20052-CVGroup_UIEventShop_Buy1-1 = "Oh! You have a keen eye, Sensei!"
20052-CVGroup_UIEventShop_Buy1-2 = "In that case, would you be interested in this as well?"
20052-CVGroup_UIEventShop_Buy2-1 = "Just between us..."
20052-CVGroup_UIEventShop_Buy2-2 = "The moment I see the finished product with my own eyes... \nthat's when I'm most excited...!"
20052-CVGroup_UIEventShop_Buy3-1 = "Are you listening, Sensei? Culture is money."
20052-CVGroup_UIEventShop_Buy3-2 = "In other words, the act of purchasing—"
20052-CVGroup_UIEventShop_Buy3-3 = "could be called a cultural activity."
20052-CVGroup_UIEventShop_Buy4-1 = "I guarantee the quality, you know?"