[translation]
10132-CVGroup_Battle_Buffed_1-1 = "Thank you... very much...!"
10132-CVGroup_Battle_Covered_1-1 = "Tsukuyo-style, Art of Hiding...!"
10132-CVGroup_Battle_Defense_1-1 = "I won't... let you...!"
10132-CVGroup_Battle_In_1-1 = "Let's proceed... to the runway of victory...!"
10132-CVGroup_Battle_In_2-1 = "Everyone, it's showtime...!"
10132-CVGroup_Battle_Move_1-1 = "Moving on to the next stage...!"
10132-CVGroup_Battle_Move_2-1 = "Are there... still more left...?"
10132-CVGroup_Battle_Recovery_1-1 = "That was... a big help...!"
10132-CVGroup_Battle_TacticalAction_1-1 = "Am I... going the right way...?"
10132-CVGroup_Battle_Victory_1-1 = "It's the finale. Thank you for your hard work...!"
10132-CVGroup_Battle_Victory_2-1 = "Shall we go get some ramen... for the after-party...?"
10132-CVGroup_CommonSkill-1 = "Ugh... I want to eat... ramen..."
10132-CVGroup_ExSkill_1-1 = "A ninja never gives up... even when backed into a corner...!"
10132-CVGroup_ExSkill_2-1 = "If I were a ninja... in a situation like this...!"
10132-CVGroup_ExSkill_3-1 = "Even if my dress... gets torn...!"
10132-CVGroup_ExSkill_Level_1-1 = "I will... stop them...!"
10132-CVGroup_ExSkill_Level_2-1 = "Please... stand behind me...!"
10132-CVGroup_ExSkill_Level_3-1 = "Tsukuyo-style, New Art of Substitution...!"
10132-CVGroup_Formation_In_1-1 = "Eh! A scout...? For me?"
10132-CVGroup_Formation_In_2-1 = "I will... walk this path... until the very end...!"
10132-CVGroup_Formation_Select-1 = "Hmm... Eek!? Uuuu..."
10132-CVGroup_Growup_1-1 = "I feel like... I'm getting a lot of attention...\nIt's just my imagination, right...?"
10132-CVGroup_Growup_2-1 = "Growth...? \nDo I really... have talent...?"
10132-CVGroup_Growup_3-1 = "This is... too much for me..."
10132-CVGroup_Growup_4-1 = "My stage... is just beginning.\nPlease watch... the new Ninja Tsukuyo...!"
10132-CVGroup_Relationship_Up_1-1 = "Does this dress... suit me...? Really? Ehehe..."
10132-CVGroup_Relationship_Up_2-1 = "As long as Sensei is watching over me... I can walk... any path..."
10132-CVGroup_Relationship_Up_3-1 = "Rather than standing on stage alone... I'd rather be... by Sensei's side..."
10132-CVGroup_Relationship_Up_4-1 = "Between what I'm good at... and what I like...\nIf I had to choose... I'd prefer... what I like."
10132-CVGroup_Tactic_In_1-1 = "Please... watch your step...!"
10132-CVGroup_Tactic_In_2-1 = "Model... no, Ninja Tsukuyo... moving out!"
10132-CVGroup_Tactic_Victory_1-1 = "I'm glad... it ended safely...!"
10132-CVGroup_Tactic_Victory_2-1 = "Is everyone... uninjured...?"