[translation]
10133-CVGroup_Battle_Buffed_1-1 = "Logical."
10133-CVGroup_Battle_Covered_1-1 = "Useless."
10133-CVGroup_Battle_Defense_1-1 = "It won't get through."
10133-CVGroup_Battle_In_1-1 = "Field response is also no problem."
10133-CVGroup_Battle_In_2-1 = "Let's mobilize all resources."
10133-CVGroup_Battle_Move_1-1 = "Continuing battle situation prediction."
10133-CVGroup_Battle_Move_2-1 = "Moving to the next conceptual space."
10133-CVGroup_Battle_Recovery_1-1 = "The load has lightened."
10133-CVGroup_Battle_TacticalAction_1-1 = "Securing tactical superiority."
10133-CVGroup_Battle_Victory_1-1 = "An artistic victory."
10133-CVGroup_Battle_Victory_2-1 = "This is the infinite possibility I found with you."
10133-CVGroup_CommonSkill-1 = "Optimization, complete."
10133-CVGroup_ExSkill_1-1 = "Defeat is—\na decided matter."
10133-CVGroup_ExSkill_2-1 = "Scan start.\nI see right through you."
10133-CVGroup_ExSkill_3-1 = "Turning the hypothetical future—\ninto a rational reality."
10133-CVGroup_ExSkill_Level_1-1 = "Optimal as a target."
10133-CVGroup_ExSkill_Level_2-1 = "I will suppress you."
10133-CVGroup_ExSkill_Level_3-1 = "This is the power of electronics."
10133-CVGroup_Formation_In_1-1 = "You need electronic warfare, right?"
10133-CVGroup_Formation_In_2-1 = "I'll show you the power of this suit."
10133-CVGroup_Formation_Select-1 = "It's a little... tight and uncomfortable..."
10133-CVGroup_Growup_1-1 = "Equipment upgrade successful.\nIt's thanks to you, Sensei."
10133-CVGroup_Growup_2-1 = "We are in a mutually complementary relationship.\nIs it safe to interpret it that way?"
10133-CVGroup_Growup_3-1 = "To invest this many resources into me... \nYes, I understand the meaning behind it."
10133-CVGroup_Growup_4-1 = "Thanks to you, Sensei... I've realized the emotion called 'gratitude'.\n...That is all I have to say."
10133-CVGroup_Relationship_Up_1-1 = "Suddenly, my body feels hot...\nIs it because of the suit's thermal function, I wonder?"
10133-CVGroup_Relationship_Up_2-1 = "So this is... the moment when something uncertain takes shape."
10133-CVGroup_Relationship_Up_3-1 = "The sense of déjà vu I feel from this interaction...\nPerhaps it's because I simulated it in the conceptual space."
10133-CVGroup_Relationship_Up_4-1 = "Do you prefer me in this suit, Sensei?\n...No, there is no... deep meaning to that question."
10133-CVGroup_Tactic_In_1-1 = "Your command and my analysis. A rational combination."
10133-CVGroup_Tactic_In_2-1 = "The analysis of the observation target is finished. All that's left is actual combat."
10133-CVGroup_Tactic_Victory_1-1 = "That was a rational command."
10133-CVGroup_Tactic_Victory_2-1 = "We've proven the rationality of the conceptual space."