[translation]
10131-CVGroup_Battle_Buffed_1-1 = "I appreciate your kindness."
10131-CVGroup_Battle_Covered_1-1 = "Sometimes, it is essential to put down the pen."
10131-CVGroup_Battle_Defense_1-1 = "Is that really all you have?"
10131-CVGroup_Battle_In_1-1 = "Eyes forward, walk with dignity.\nFor one's posture reveals one's character."
10131-CVGroup_Battle_In_2-1 = "A good beginning leads to a good ending.\nJust as it is in a story."
10131-CVGroup_Battle_Move_1-1 = "An ending simply signifies a new beginning."
10131-CVGroup_Battle_Move_2-1 = "Let us proceed to the next paragraph."
10131-CVGroup_Battle_Recovery_1-1 = "I am grateful."
10131-CVGroup_Battle_TacticalAction_1-1 = "Is it... over there?"
10131-CVGroup_Battle_Victory_1-1 = "Phew... 5 stars... at the very least, a 4-star review is guaranteed."
10131-CVGroup_Battle_Victory_2-1 = "To everyone who did their best, praise and glory."
10131-CVGroup_CommonSkill-1 = "Please, use this."
10131-CVGroup_ExSkill_1-1 = "Goodness...! \nPlease be careful!"
10131-CVGroup_ExSkill_2-1 = "Always remember to keep your composure."
10131-CVGroup_ExSkill_3-1 = "Keep elegance in your heart.\nAnd look forward."
10131-CVGroup_ExSkill_Level_1-1 = "Here, take this."
10131-CVGroup_ExSkill_Level_2-1 = "You don't need to return it."
10131-CVGroup_ExSkill_Level_3-1 = "Please be more careful next time."
10131-CVGroup_Formation_In_1-1 = "Criticism is the act of discerning the essence of a text."
10131-CVGroup_Formation_In_2-1 = "If there is anything I can do, please let me know."
10131-CVGroup_Formation_Select-1 = "Eek...!?\nOh, honestly...!\nCould we talk about this later?"
10131-CVGroup_Growup_1-1 = "Humans are beings that continue to move toward a better tomorrow.\nThe reason I never neglect my studies and constantly re-examine myself... is precisely because of that."
10131-CVGroup_Growup_2-1 = "As long as there is potential remaining, one should never stop moving forward.\nCome, take my hand, Sensei. Let us proceed together."
10131-CVGroup_Growup_3-1 = "Surprisingly, not many people truly know themselves.\nEven a critic like me...\nBut by knowing oneself, one can take another new step forward.\nFor growth lies within that very process."
10131-CVGroup_Growup_4-1 = "A fated partner... it is a somewhat trite and overused cliché.\nBut there are times when I feel like clinging to those words.\nFufu, that is surely a signpost for us to keep walking forward."
10131-CVGroup_Relationship_Up_1-1 = "I was just thinking...\nI write critiques quite often, but I have rarely received a critique of my own critiques.\nYes, that is right. I believe... that you, Sensei, would surely write a wonderful critique."
10131-CVGroup_Relationship_Up_2-1 = "When you see so many things, it is hard to find something you truly love from the bottom of your heart.\nBut... there are exceptions to everything, after all. What that is... is a secret.\nYes, for now... it still is."
10131-CVGroup_Relationship_Up_3-1 = "There is nothing that makes my heart dance more than encountering a wonderful story.\nFor me, at least.\nAnd to me, a wonderful person is... much like a story.\nYou don't understand what that means?\nFufu... that is fine for now."
10131-CVGroup_Relationship_Up_4-1 = "Sometimes, I wonder what would have happened if I hadn't met you, Sensei.\nIt would surely have been a gray...\nAnd uneventful story, I suppose.\nYou ask what I mean by that?\nFufu... it doesn't mean anything in particular.\n...Probably, perhaps."
10131-CVGroup_Tactic_In_1-1 = "Now, let us take that step forward."
10131-CVGroup_Tactic_In_2-1 = "Greetings, everyone."
10131-CVGroup_Tactic_Victory_1-1 = "That was a story worth critiquing."
10131-CVGroup_Tactic_Victory_2-1 = "A happy ending... it may be cliché, but what everyone desires is what makes a masterpiece."