[translation]
10130-CVGroup_Battle_Buffed_1-1 = "Thank you. I will continue to improve."
10130-CVGroup_Battle_Covered_1-1 = "Taking cover. Please provide support."
10130-CVGroup_Battle_Defense_1-1 = "Not yet!"
10130-CVGroup_Battle_In_1-1 = "Moving in. Please follow me."
10130-CVGroup_Battle_In_2-1 = "It's alright. Trust me."
10130-CVGroup_Battle_Move_1-1 = "Clear."
10130-CVGroup_Battle_Move_2-1 = "Advancing."
10130-CVGroup_Battle_Recovery_1-1 = "Thank you, that helped."
10130-CVGroup_Battle_TacticalAction_1-1 = "Moving."
10130-CVGroup_Battle_Victory_1-1 = "Were you satisfied? If so, that is all that matters."
10130-CVGroup_Battle_Victory_2-1 = "Suppression complete. I hope this resolves the issue."
10130-CVGroup_CommonSkill-1 = "Out of a perfect score, how did I do? Sensei."
10130-CVGroup_ExSkill_1-1 = "...Everyone is waiting."
10130-CVGroup_ExSkill_2-1 = "...It is my job, after all."
10130-CVGroup_ExSkill_3-1 = "...Shall we finish this quickly?"
10130-CVGroup_ExSkill_Level_1-1 = "Reload complete."
10130-CVGroup_ExSkill_Level_2-1 = "Continuing combat."
10130-CVGroup_ExSkill_Level_3-1 = "Suppressive fire, commencing."
10130-CVGroup_Formation_In_1-1 = "Yes, Sensei."
10130-CVGroup_Formation_In_2-1 = "Understood, I will prepare."
10130-CVGroup_Formation_Select-1 = "Wah!?\nI-I wasn't surprised... I-I'm serious."
10130-CVGroup_Growup_1-1 = "I feel a strange sensation...\nIs this what they call 'growth' in the outside world?"
10130-CVGroup_Growup_2-1 = "Is this what it feels like to grow?\nSo I, too, am able to move forward like this."
10130-CVGroup_Growup_3-1 = "I want to change.\n...Please keep that a secret from the others, okay?"
10130-CVGroup_Growup_4-1 = "'Trust me and follow me'...?\n*Sigh*... Where on earth does that confidence come from?\nWell... I suppose I can trust you just this once."
10130-CVGroup_Relationship_Up_1-1 = "It's a bit embarrassing to put it into words.\nI wasn't sure how best to convey it...\nBut I figured, simple is best.\nThat is... I am truly glad you are here, Sensei."
10130-CVGroup_Relationship_Up_2-1 = "To be honest, I don't trust you 100% yet.\nBut... I do trust you about 95%."
10130-CVGroup_Relationship_Up_3-1 = "You said that every student is precious to you, Sensei.\nAt first, I didn't really understand that...\nBut recently, I've come to understand what that means.\nAt the same time, I find it a little disappointing..."
10130-CVGroup_Relationship_Up_4-1 = "You often tell me to rely on you, but...\nFor me, that feels a bit insufficient, or perhaps... lacking.\nN-no deep meaning there!\nIt's just that... I want to repay you. Returning what I've received is the Arius way."
10130-CVGroup_Tactic_In_1-1 = "Now then, what kind of place is this?"
10130-CVGroup_Tactic_In_2-1 = "I see, so this is how it is."
10130-CVGroup_Tactic_Victory_1-1 = "That was a challenging battle."
10130-CVGroup_Tactic_Victory_2-1 = "This is the Arius way."