[translation]
16019-CVGroup_Battle_Buffed_1-1 = "Thank you for the support."
16019-CVGroup_Battle_Covered_1-1 = "Safety, secured."
16019-CVGroup_Battle_Defense_1-1 = "That won't be enough to affect me."
16019-CVGroup_Battle_In_1-1 = "Leave the vanguard to me."
16019-CVGroup_Battle_In_2-1 = "Dual pistols aren't just for show."
16019-CVGroup_Battle_Move_1-1 = "Section, clear."
16019-CVGroup_Battle_Move_2-1 = "Resuming reconnaissance."
16019-CVGroup_Battle_Recovery_1-1 = "Thank you for the resupply."
16019-CVGroup_Battle_TacticalAction_1-1 = "Position, shifting."
16019-CVGroup_Battle_Victory_1-1 = "Failure is not an option. Yahoo."
16019-CVGroup_Battle_Victory_2-1 = "I have simply carried out my mission. V-sign."
16019-CVGroup_CommonSkill-1 = "Oops. This should be fine now."
16019-CVGroup_ExSkill_1-1 = "Perfect Recon, Asuma Toki. Deploying."
16019-CVGroup_ExSkill_2-1 = "Everything begins from these hands."
16019-CVGroup_ExSkill_3-1 = "Support and suppression are both my specialties."
16019-CVGroup_ExSkill_Level_1-1 = "My gun handling is perfect as well."
16019-CVGroup_ExSkill_Level_2-1 = "Dual pistols are versatile."
16019-CVGroup_ExSkill_Level_3-1 = "It's all about how you use your guns and equipment."
16019-CVGroup_Formation_In_1-1 = "Did you call for me?"
16019-CVGroup_Formation_In_2-1 = "I can deploy at any time."
16019-CVGroup_Formation_Select-1 = "Weapon change. Perfect."
16019-CVGroup_Growup_1-1 = "Asuma Toki, leveling up. My feelings for Sensei have leveled up too. In turn, that means Sensei's feelings for me have leveled up as well."
16019-CVGroup_Growup_2-1 = "I've become even stronger with this. ...Now that I think about it, I feel like I still have a long way to go. So, please stay with me a little longer."
16019-CVGroup_Growup_3-1 = "One cannot grow simply by becoming stronger. That is why we must lean on each other. ...I am ready at any time, Sensei."
16019-CVGroup_Growup_4-1 = "The me who has achieved this growth is Perfect Toki. ...No, I correct myself. Only when Sensei is by my side."
16019-CVGroup_Relationship_Up_1-1 = "I see. So, my presence within you has increased even further, Sensei. ...The opposite? That's impossible."
16019-CVGroup_Relationship_Up_2-1 = "Do not worry. As long as the lucky Maid Agent Recon is with you, nothing will stand in our way."
16019-CVGroup_Relationship_Up_3-1 = "If there is such a thing as 'favorability,' it must go up at times like this. I feel like it just went up by about 10,000 points."
16019-CVGroup_Relationship_Up_4-1 = "Sensei, are you not cold? I am a little... no, I am very cold. So, please come a little closer."
16019-CVGroup_Tactic_In_1-1 = "Starting reconnaissance."
16019-CVGroup_Tactic_In_2-1 = "The mission details are in my head."
16019-CVGroup_Tactic_Victory_1-1 = "Objective achieved. Please praise me promptly."
16019-CVGroup_Tactic_Victory_2-1 = "Area clear."