[translation]
20053-CVGroup_CommonSkill-1 = "I shall impart my secret arts unto you!"
20053-CVGroup_ExSkill_1-1 = "This is the Michiru style... Uwaaah!?"
20053-CVGroup_ExSkill_2-1 = "Behold! This is the latest kame... raaaah!?"
20053-CVGroup_ExSkill_3-1 = "The Maiden Ninja Scroll Michiru-chi, staaarting noooow!?"
20053-CVGroup_ExSkill_Level_1-1 = "Catch... Uwaaah!?"
20053-CVGroup_ExSkill_Level_2-1 = "Phew... m-my eyes...!"
20053-CVGroup_ExSkill_Level_3-1 = "Phew... no off-shots allowed!"
20053-CVGroup_Formation_In_1-1 = "A-ah. This is Undercover Zero-One.\n...Wait, is this how I'm supposed to say it?"
20053-CVGroup_Formation_In_2-1 = "Our operation site is... right here!"
20053-CVGroup_Formation_Select-1 = "This dress is for the mission...\nB-but... um, Sensei-dono, what do you think?"
20053-CVGroup_Growup_1-1 = "This feeling... this is a Cinderella fit...!"
20053-CVGroup_Growup_2-1 = "Just because my outfit changed doesn't mean my mindset has!"
20053-CVGroup_Growup_3-1 = "Giving me something so rare... \nDoes that mean you want to walk the path of the ninja too, Sensei-dono?"
20053-CVGroup_Growup_4-1 = "Hehe, how is it?\nDo I look... cute... no, have I become stronger?"
20053-CVGroup_Relationship_Up_1-1 = "This is a little embarrassing, maybe..."
20053-CVGroup_Relationship_Up_2-1 = "What do you think of this hairstyle?\nI tried pretty hard to set it..."
20053-CVGroup_Relationship_Up_3-1 = "Eh, cute...? \nSensei-dono, you're at it again... heh, hehehe..."
20053-CVGroup_Relationship_Up_4-1 = "In this outfit, as your bodyguard...\nCan I stay by your side...?"