[translation]
20054-CVGroup_CommonSkill-1 = "Fufu, sorry to keep you waiting."
20054-CVGroup_ExSkill_1-1 = "Were you captivated by me?"
20054-CVGroup_ExSkill_2-1 = "I won't lose when it comes to speed."
20054-CVGroup_ExSkill_3-1 = "Shall I make one for you as well?"
20054-CVGroup_ExSkill_Level_1-1 = "This is a wheelchair."
20054-CVGroup_ExSkill_Level_2-1 = "Now, shall we begin?"
20054-CVGroup_ExSkill_Level_3-1 = "You need my help, don't you?"
20054-CVGroup_Formation_In_1-1 = "You need my help?\nYes, I thought as much."
20054-CVGroup_Formation_In_2-1 = "Now then, where shall we begin?"
20054-CVGroup_Formation_Select-1 = "Yes, Sensei. I am here."
20054-CVGroup_Growup_1-1 = "One can grow in any situation...\nI suppose that is what you would say, Sensei."
20054-CVGroup_Growup_2-1 = "Self-study is a very difficult path to growth.\nPerhaps I am who I am today because you were there for me, Sensei."
20054-CVGroup_Growup_3-1 = "I understand, Sensei.\nOne must not let their guard down, but at the same time,\nbeing too tense is not good either."
20054-CVGroup_Growup_4-1 = "Growth is a joyous thing... I do understand that.\nBut at the same time, I find myself thinking about how much of your resources you have dedicated to me.\nPlease, do not push yourself too hard."
20054-CVGroup_Relationship_Up_1-1 = "What do you think of my new suit?\n...It suits me? Yes, I thought so too."
20054-CVGroup_Relationship_Up_2-1 = "It is often said that no one can live alone.\nRecently, I have come to truly understand the meaning of those words.\n...Sensei, you wouldn't leave me all alone, would you?"
20054-CVGroup_Relationship_Up_3-1 = "Everything that has happened since I met you,\neven for me, with my degree in 'Omniscience,' was impossible to predict.\nAnd... I am sure it will continue to be that way."
20054-CVGroup_Relationship_Up_4-1 = "May I show a moment of weakness, just for a little while...?\nPlease stay by my side, just for now is fine.\nThank you, Sensei.\n...I am very happy."