[translation]
10137-101370010 = "It's been a while, Sensei."
10137-101370020 = "I am Shima Konoka."
10137-101370030 = "Konoka!?"
10137-101370040 = "You're more polite than usual..."
10137-101370050 = "What are you talking about?"
10137-101370060 = "I think I always talk like this."
10137-101370070 = "Oh right, today's lucky action said to \"introduce yourself properly\", so..."
10137-101370080 = "I decided that I should introduce myself."
10137-101370090 = "Is that so! I had no idea!"
10137-101370100 = "Sensei... what's wrong?"
10137-101370110 = "Well whatever. Please come to Valkyrie when you have free time."
10137-101370120 = "I have something to discuss about administrative procedures."
10137-101370130 = "This is actually pretty rough."
10137-101370140 = "Are you okay?"
10137-101370150 = "Ah, well, something like this is nothing."
10137-101370160 = "I'm just glad there was milk in the fridge."
10137-101370170 = "Is that girl from today... going to face disciplinary action?"
10137-101370180 = "Of course not."
10137-101370190 = "Someone who can be that suspicious of people is actually well-suited for Valkyrie."
10137-101370200 = "I probably would've done the same thing if I were a rookie, you know?"
10137-101370210 = "That's so cool! Just what I'd expect from the Deputy Director!"
10137-101370220 = "Well, I was also at fault this time..."
10137-101370230 = "Even though the fortune told me to, I didn't introduce myself properly..."
10137-101370240 = "So I brought it upon myself."
10137-101370250 = "Have you been doing well, Sensei?"
10137-101370260 = "Today's lucky action is apparently \"be punctual.\""
10137-101370270 = "Well, I think being on time is just common sense right?"
10137-101370280 = "It can be surprisingly difficult, though."
10137-101370290 = "Well, fortune-telling lucky actions are usually things you should be doing regularly anyway"
10137-101370300 = "If it's written there, it just makes me want to be more conscious of it than usual."
10137-101370310 = "I just wanted to share what today's lucky action was!"
10137-101370320 = "Have a good day! See ya~"
10137-101370330 = "I guess I surprised you, huh."
10137-101370340 = "Man~ it feels great to practice lucky actions right from the morning."
10137-101370350 = "Wasn't strict punctuality... yesterday's lucky action?"
10137-101370360 = "Eh?"
10137-101370370 = "Ah..."
10137-101370380 = "Umm, today's is..."
10137-101370390 = "\"Don't get too caught up in time.\""
10137-101370400 = "..."
10137-101370410 = "Ah-..."
10137-101370420 = "I have some classified information..."
10137-101370430 = "Well, I suppose I could tell you, Sensei."
10137-101370440 = "I'll send you the address, let's meet up there."
10137-101370450 = "Yo, Sensei."
10137-101370460 = "Today's lucky action is \"act together with a partner,\" apparently!"
10137-101370470 = "So with that said, would you be my partner for the day?"
10137-101370480 = "I'm counting on you!"
10137-101370490 = "Ah-"
10137-101370500 = "I'm taking a sick leave today, so..."
10137-101370510 = "just do whatever you think is best."
10137-101370520 = "I'm leaving the rest to you~"
10137-101370530 = "??"
10137-101370540 = "What's with that reaction is that towards your boss? Heh..."
10137-101370550 = "I caught a cold during the investigation the other day."
10137-101370560 = "Anyway, take care of things for me."
10137-101370570 = "Fully! Recovered!"
10137-101370580 = "Sensei, thank you for the other day."
10137-101370590 = "You didn't catch my cold, did you?"
10137-101370600 = "I'm fine!"
10137-101370610 = "I just have a little fever, and my throat and body ache!"
10137-101370620 = "That's definitely a cold!"
10137-101370630 = "Well then..."
10137-101370640 = "To return the favor, I'll come visit you."
10137-101370650 = "I'll treat you to tonkotsu ramen!"