[translation]
20018-200180370 = "Sensei, were you at Shiratori Park yesterday?"
20018-200180380 = "I felt like I saw you running..."
20018-200180390 = "Moe was there too."
20018-200180400 = "You should have said hi."
20018-200180410 = "I thought you were working, so I didn't want to bother you..."
20018-200180420 = "So it would have been okay to talk to you?"
20018-200180430 = "You're always welcome to. I've been jogging lately."
20018-200180440 = "Sitting around all the time is bad for your health, after all."
20018-200180450 = "Ah, I get that."
20018-200180460 = "If you sit for too long, you get hunched over and your shoulders get stiff, right?"
20018-200180470 = "I know that having good posture is important, but..."
20018-200180480 = "Would you like to exercise with me sometime, Moe?"
20018-200180490 = "Sensei, did you forget that I'm a special operative?"
20018-200180500 = "I am a member of SRT, you know. I train every single day."
20018-200180510 = "Well, not as much as Saki or Miyako, though."
20018-200180520 = "But jogging with you... that might be a bit catastrophic, don't you think?"