[translation]
10137-10 = "Blue Archive~"
10137-20 = "Ah, hey there. I'm Konoka Shima from the Valkyrie Police School's Public Safety Bureau. Want to check today's fortune with me?"
10137-30 = "So many people here~"
10137-40 = "(Now then, as for the criminals... well, I guess there aren't any here.)"
10137-50 = "Huh? Where'd I put my badge...?"
10137-60 = "It's so peaceful. *Sigh*... I'm bored."
10137-70 = "Is this even legal?"
10137-80 = "Hey there. How's it going?"
10137-90 = "I hope you haven't become a felon since I last saw you..."
10137-100 = "I'm just kidding, of course!"
10137-110 = "Valkyrie will be just fine even without me."
10137-120 = "Actually, the arrest rate goes up when I'm around, doesn't it..."
10137-130 = "It's like, people keep trying to mess with me."
10137-140 = "So, I feel like it's better if I'm here instead. Just kidding."
10137-150 = "Sensei, you're really good at writing, aren't you? I'm jealous."
10137-160 = "Oh, but I'm great at writing incident reports and letters of apology,"
10137-170 = "so let me know if you ever need one!"
10137-180 = "Tea, tea, time for tea."
10137-190 = "...I wonder if it's time to change this tea bag."
10137-200 = "It's been steeped 30 times, so it's stopped having any flavor..."
10137-210 = "Disciplinary action! Disciplinary action! Disciplinary action!"
10137-220 = "...Doesn't it start to sound kind of funny when you say it over and over?"
10137-230 = "Well, it wouldn't be good to go any further than that, though..."
10137-240 = "Sensei, how was your fortune today?"
10137-250 = "Happy birthday, Sensei!"
10137-260 = "I'm not really sure what you like,"
10137-270 = "so we're going to the shopping mall right now!"
10137-280 = "Happy birthday to me~ Happy birthday to me~"
10137-290 = "Happy birthday, dear Konoka~"
10137-300 = "Happy New Year, Sensei!"
10137-310 = "Time to go crack down on all those rowdy delinquents!"
10137-320 = "It's Christmas, huh... Everyone seems so happy about it, but..."
10137-330 = "Santa is basically a habitual trespasser, isn't he?"
10137-340 = "Someone just told me, 'Trick or treat!'"
10137-350 = "I thought it was a robbery, so I accidentally put handcuffs on them..."
10137-360 = "I wish they'd told me it was Halloween sooner..."
10137-380 = "Ugh, I'm soaked..."
10137-390 = "Ugh... it's freezing."
10137-400 = "It started raining."
10137-410 = "And it's not supposed to stop until tonight... *Sigh*..."
10137-420 = "Well, I guess it's a good way to cool my head off."
10137-430 = "Huh? Oh, yeah."
10137-440 = "It would be a lie to say I'm not frustrated."
10137-450 = "All that effort wasted, and now I'm soaked to the bone..."
10137-460 = "But, it's just like the fortune said."
10137-470 = "Because my buddy was by my side, it turned out to be a good day."
10137-480 = "...It's all thanks to you, Sensei."
10137-490 = "So, if anything—"
10137-500 = "I'm happy."
10137-510 = "...Oh, no, wait!"
10137-520 = "I meant I'm lucky and happy that we were able to find shelter from the rain like this!"
10137-530 = "Th-that's all I meant...!"
10137-2600 = "Oh, I've been wanting this! With this, I can wrap up conversations easily!"