[translation]
10138-10 = "Hmph... Blue Archive!"
10138-20 = "Wildhunt Art Academy, Kinui Rena.\nWatch me. I'm going to prove that\nall this occult stuff is just a sham!"
10138-30 = "What kind of clothes\nwould look good on them?"
10138-40 = "Nothing weird is going to happen\nhere, right...? \nI mean, surely..."
10138-50 = "This layout... Sensei,\nyou actually have\npretty good taste."
10138-60 = "That design... is it\nsupposed to be occult?\nHas Sensei been\ninfluenced by it too?"
10138-70 = "Ah, I thought I heard\na strange noise over there..."
10138-80 = "You're late!!\nI've been waiting forever, you know!?"
10138-90 = "Welcome back, Sensei.\nSo, what should I do?"
10138-100 = "You keep this place nice and clean."
10138-110 = "My dorm is just...\nNo matter how much I clean,\nit never ends."
10138-120 = "Ugh, it's because my seniors\nbring in all that unnecessary junk..."
10138-130 = "I still can't forget the day\nI found out my room assignment..."
10138-140 = "I mean, it's Room 404 in Dorm 4, right?\nEven if you're not into the occult,\nwouldn't you be creeped out?"
10138-150 = "Why does anyone even\nbelieve in the occult?"
10138-160 = "Everything like that can be\nscientifically proven.\n...Sensei, you think so too, right?"
10138-170 = "What do you do when you're free, Sensei?"
10138-180 = "Me? I like to try\nmaking various things."
10138-190 = "Would you like to try it with me sometime?"
10138-200 = "I-it's not like I want you to make something for me or anything!"
10138-210 = "Lately, nothing but weird things\nhave been happening."
10138-220 = "Like my seniors said,\nshould I go get a\nfortune reading...?"
10138-230 = "Ugh... I've decided not to\nbelieve in that stuff!"
10138-240 = "Eh? Sensei, it's your\nbirthday? I didn't know."
10138-250 = "What are you hiding behind your back...?"
10138-260 = "I-it's not a present, okay!?\nI just happened to stop by\nfor some shopping!"
10138-270 = "My seniors said they're going to\nthrow a birthday party for me today."
10138-280 = "You should come too, Sensei.\nThere'll be lots of\ngood food, probably."
10138-290 = "Happy New Year, Sensei.\nSince it's the new year, want to\nmake a wish together?"
10138-300 = "W-wishes aren't occult, you know!"
10138-310 = "I never believed in Santa\nsince I was little."
10138-320 = "Sneaking up to your bedside\nwhile you're sleeping?"
10138-330 = "Isn't that just too scary!?"
10138-340 = "Hmm... this room could use a bit\nmore of a Halloween vibe."
10138-350 = "Ah... \nI'm not talking about the occult!\nI'm talking about the design!"
10138-370 = "You know, I've been\ndexterous since I was little."
10138-380 = "I used to make ribbons\nand give them to my friends."
10138-390 = "It made me so happy\nwhen they were pleased."
10138-400 = "...That's when I realized."
10138-410 = "Even with something this small,"
10138-420 = "you can make someone happy."
10138-430 = "That's why I started aiming\nto be a fashion designer."
10138-440 = "When everyone enjoys the\nclothes and accessories I design,"
10138-450 = "it makes me happy too."
10138-460 = "You can kind of understand\nthat feeling too, right, Sensei?"
10138-470 = "That's also why I think you've been\nso considerate to me like this."
10138-480 = "Eh...? \nYou're asking how today was...?"
10138-490 = "Hiss! D-don't make me say it!\nYou idiot Sensei!"
10138-2600 = "Don't underestimate me just because I'm small, or you'll regret it. Even though I look like this, I'm actually quite good with a gun! I can even draw pictures with the bullet holes... I'm serious, really!"