[translation]
10132-10 = "Blue Archive."
10132-20 = "I am Oono Tsukuyo! Even though I am wearing a dress... I am still a true member of the Ninjutsu Research Club...!"
10132-30 = "Uuu... Am I... being stared at... too much...?"
10132-40 = "It would be terrible... if I got a stain on my dress... so... I must be careful..."
10132-50 = "Uuu... I'd rather just... blend into that furniture over there..."
10132-60 = "When I am wearing a dress... I have to be mindful... of how I walk..."
10132-70 = "(Everyone... has such... unique outfits.)"
10132-80 = "Hello..."
10132-90 = "Today, I am Sensei's model... and only yours..."
10132-100 = "I have been waiting for you, Sensei."
10132-110 = "Um... I am sorry... if my dress... surprised you..."
10132-120 = "Rather than a full-fledged model... I want to aim to be... a full-fledged ninja."
10132-130 = "Would you like to... take a closer look... at this outfit...?"
10132-140 = "If you look closely... the craftsmanship is so detailed... it is quite mysterious!"
10132-150 = "Th-this is... Why is my gravure... here at Schale...!?"
10132-160 = "Are we eating?"
10132-170 = "As for me... as long as it is not salad... I will eat anything..."
10132-180 = "Compared to the sofa... at the fashion show venue..."
10132-190 = "I feel more at ease... in this office chair."
10132-200 = "Happy birthday, Sensei."
10132-210 = "I wanted to show you... so I practiced... my ninja walking...! Would you... watch me...?"
10132-220 = "My birthday... is it?"
10132-230 = "I have been so busy lately... that I had completely... forgotten about it..."
10132-240 = "Thank you very much!"
10132-250 = "Happy New Year!"
10132-260 = "My New Year's wish..."
10132-270 = "Is for the people I love... to be smiling. Ehehe..."
10132-280 = "Sensei...! If you would like... would you... walk through the Christmas streets... with me?"
10132-290 = "I have started to gain confidence... in my walking...!"
10132-300 = "Even for a Halloween costume..."
10132-310 = "It is a bit too flashy, isn't it?"
10132-320 = "Eh... because there are people with even more amazing outfits... it is okay...?"
10132-340 = "Ugh..."
10132-350 = "I managed to... get over the fence, but..."
10132-360 = "My clothes got caught..."
10132-370 = "I cannot move..."
10132-380 = "Uuu... I am sorry..."
10132-390 = "It is because I... tried to take a shortcut..."
10132-400 = "...Huh? Sensei, how did you... get to the other side...?"
10132-410 = "Eh? There is a small gate... next to the fence...!?"
10132-420 = "Uuu... I did not know that... and here I was..."
10132-430 = "...Sensei... could you... please pull on my clothes a little bit?"
10132-2600 = "I will... continue to do my very best. So that I can become... a splendid ninja... with everyone...!"