[translation]
10133-10 = "Blue Archive."
10133-20 = "I will show you the most rational answer\nthat governs the electronic realm."
10133-30 = "This place is also a kind of\nconceptual space... Needs analysis."
10133-40 = "I want to become better\nat tidying up..."
10133-50 = "...It seems that\nSensei's sensibilities\nare close to mine."
10133-60 = "If I make an \"Avant-Garde-kun\nType.Maid\",\nI wonder if I should put it here."
10133-70 = "I will use it as\nneatly as possible."
10133-80 = "I've been waiting, Sensei."
10133-90 = "I will provide efficient operational support.\nIsn't that rational?"
10133-100 = "We're starting work, then.\nJust tell me anything."
10133-110 = "There is a theory that...\ntime does not flow."
10133-120 = "It's the theory that the past, present, and future\nall exist at the same moment."
10133-130 = "If that theory is true..."
10133-140 = "Then it means we are still in the midst\nof that major incident."
10133-150 = "Honestly, I am interested in\nwhat's inside your PC."
10133-160 = "With this suit, I could easily\nhack into a device\nlike Sensei's."
10133-170 = "...Rest assured.\nI don't like\nthat kind of method."
10133-180 = "I wonder what lies beyond\nthe observable world."
10133-190 = "I want to know the answer to that."
10133-200 = "...Together with you."
10133-210 = "I should have prepared a suit\nfor you too, Sensei."
10133-220 = "Then we could have enjoyed\nthe conceptual space together."
10133-230 = "...Should we just go out\nlike this in reality?"
10133-240 = "That won't do in this outfit."
10133-250 = "Gravity exists everywhere."
10133-260 = "...Yes, even between you and me."
10133-270 = "We are unconsciously\nfalling toward each other."
10133-280 = "Happy birthday, Sensei."
10133-290 = "As a gift, I have prepared an\nAvant-Garde-kun specialized\nfor operational support."
10133-300 = "...Eh? You want to receive support\ndirectly from me...?"
10133-310 = "Th-that is... troublesome..."
10133-320 = "Ah, so today is my birthday..."
10133-330 = "I was so immersed in my mission,\nI had forgotten."
10133-340 = "When I focus on something... I can't\npay attention to anything else."
10133-350 = "Thanks to you, Sensei,\nI made a good memory.\nThank you."
10133-360 = "Sensei, Happy New Year."
10133-370 = "There is appropriate attire\nfor the New Year, isn't there?"
10133-380 = "...I wonder if this is alright."
10133-390 = "A warm welcome...?\nIf so... then that's fine."
10133-400 = "It seems today is the day to celebrate\nsomeone's birth."
10133-410 = "I don't really understand\nthose kinds of things, but,"
10133-420 = "I will thank you for\nmaking this time for me."
10133-430 = "Ghosts? I don't believe in them."
10133-440 = "Entities that cannot interact with\ngravity or electromagnetic forces"
10133-450 = "are things that cannot be\ncaught by our eyes."
10133-460 = "...You don't understand? Why?"
10133-480 = "Phew... I've calmed down."
10133-490 = "I hadn't considered\nthe room temperature."
10133-500 = "For me to do such a thing... It seems I was\ndistracted by the results\nright in front of me..."
10133-510 = "...Please, let me rest for a moment."
10133-520 = "Because of the heat, my thinking is not..."
10133-530 = "...Sensei?\nWhy are you making that face..."
10133-540 = "...Ah!!"
10133-550 = "(Wh-what am I...!?)"
10133-560 = "Th-this wasn't intentional...!\nI'm sorry...!"
10133-570 = "I-I am fine now...!"
10133-2600 = "I will protect everyone...\nThat strong will is what\nmakes me pull the trigger."