[translation]
10134-10 = "Blue, Archive!"
10134-20 = "Aris, moving out!"
10134-30 = "This... looks just like Kei!"
10134-40 = "Aris is starting to feel... a little sleepy..."
10134-50 = "This is a no-PK zone!"
10134-60 = "(Scan complete. Hostile reaction... none.)"
10134-70 = "Where is the charger?"
10134-80 = "Hehe, Aris knew you were coming, Sensei."
10134-90 = "Because Aris's auto-intercept system reacted."
10134-100 = "Sensei, I've been waiting for you!"
10134-110 = "I'm fine!"
10134-120 = "Aris can wait as long as it takes!"
10134-130 = "The flight mechanics of this suit feel a bit like a game I played before."
10134-140 = "But unlike games, reality is in first-person view, so it's super confusing...!"
10134-150 = "Aris wants to see it in TPS view too!"
10134-160 = "Sensei? Is something the matter?"
10134-170 = "Ah! You saw that, didn't you?"
10134-180 = "That's right, Aris just entered through the window!"
10134-190 = "In this mode, Aris has both Light and Flight attributes!"
10134-200 = "...Eh? You want me to use the door because it's dangerous?"
10134-210 = "This equipment is unstable, so it requires regular maintenance."
10134-220 = "But don't worry!"
10134-230 = "Himari-senpai, Rio-senpai, and even Utaha-senpai..."
10134-240 = "They all told me I could bring it to them anytime!"
10134-250 = "But... if I ask one of them, the other two get in a bad mood..."
10134-260 = "What should Aris do..."
10134-270 = "Uuuuu...!"
10134-280 = "Uuu... the wings are so big, I keep bumping into things."
10134-290 = "How do people with wings usually manage?"
10134-300 = "The person with the biggest wings that Aris knows is..."
10134-310 = "Ah! I'll ask the Prefect Team leader later!"
10134-320 = "Kei told me, 'If you keep playing games all the time, you'll end up like Momoi'..."
10134-330 = "What does that mean?"
10134-340 = "Aris loves Momoi, so... I want to be like Momoi!"
10134-350 = "...Se-Sensei, why are you reacting like that too? You're just like Kei!"
10134-360 = "Happy birthday, Sensei!"
10134-370 = "A birthday is the day you were born, right?"
10134-380 = "To think there was a time when you didn't exist... it's kind of mysterious."
10134-390 = "Hehe, Sensei, do you remember?"
10134-400 = "Today is the day Aris and Sensei... the day Aris met everyone!"
10134-410 = "Aris doesn't remember when she was born, but..."
10134-420 = "But today, it must be Aris's birthday!"
10134-430 = "Happy New Year, Sensei!"
10134-440 = "I'm sorry, but... Aris cannot join you on your journey after this."
10134-450 = "I promised my friends I'd watch the first sunrise of the year in an online game,"
10134-460 = "So I'll be gaming all night..."
10134-470 = "Eh...? You're going out now?"
10134-480 = "Uuuu! N-no way...!"
10134-490 = "Ta-da!"
10134-500 = "Today, Aris is job-changing into Santa!"
10134-510 = "I'm going to fly through the sky and deliver presents to everyone in place of the busy Santa!"
10134-520 = "Ah, but then I'll be away from Sensei... Hmm."
10134-530 = "...Ah! Sensei, please be Rudolph the reindeer!"
10134-540 = "Waaah! Sensei, help me!"
10134-550 = "So many people are coming up and asking to take my picture!"
10134-560 = "Aris isn't even wearing a costume!"
10134-580 = "Hehe. Were you surprised, Sensei?"
10134-590 = "I wanted to see this night sky with you... so I called you here."
10134-600 = "It's very... beautiful."
10134-610 = "In Aris's world, and in worlds I haven't been to yet..."
10134-620 = "I'm sure there are so many beautiful things like this."
10134-630 = "But... it's strange."
10134-640 = "The world is so beautiful... so why do people fight?"
10134-650 = "Just like that starry sky, this world is overflowing with enough beauty for everyone to share..."
10134-660 = "...I guess Aris still doesn't understand."
10134-2600 = "The Sword of Light has always shown Aris the path forward. Yes... just like you, Sensei!"