[translation]
10135-10 = "I have to say it, right...? \nBlue Archive."
10135-20 = "Hello, I'm Kei. \nWhy are you in such a rush...? \nHaa... From now on, I will be watching over you, Sensei."
10135-30 = "(I am a \"student\" too, after all... \nSo, at least in the cafe...!)"
10135-40 = "What is that... \nI wonder what it tastes like?"
10135-50 = "I see... So this is what it means \nto relax..."
10135-60 = "Having a physical body... \nIt can be quite inconvenient, can't it..."
10135-70 = "Fufu... \nJust standing here like this \nis actually kind of fun..."
10135-80 = "Geez, what were you doing? \nYou're late!"
10135-90 = "I've already finished the preparations... \nYes, please, have a seat."
10135-100 = "Oh, you're here. \nShall we begin?"
10135-110 = "...What are you \ngrining at!"
10135-120 = "Stop calling me cute!"
10135-130 = "A-are you asking if I hate it...? \nW-well, rather than that...!"
10135-140 = "..."
10135-150 = "I mean, say something other than 'cute'..."
10135-160 = "Why am I always \ngetting angry...?"
10135-170 = "...That's rude. I'm not \nactually angry."
10135-180 = "But well... \nOnce you know the truths of the world."
10135-190 = "I find it difficult \nnot to get angry."
10135-200 = "I'll take this opportunity \nto say this."
10135-210 = "Are you eating your meals properly? \nModerate exercise is also necessary."
10135-220 = "Early to bed and early to rise is good, \nand that applies to adults \nas well, you know."
10135-230 = "Work in moderation. \nThough, being lazy in moderation too."
10135-240 = "...Honestly, \nyou're such a handful."
10135-250 = "Oh, geez! \nThat's why you shouldn't treat me \nlike a child!"
10135-260 = "...I'm not \nthat young, you know."
10135-270 = "Did you laugh!? \nYou just laughed, didn't you!? \nI saw it clearly!"
10135-280 = "You'd better remember this!? \nSomeday, I'll make you understand \nexactly what it feels like!!"
10135-290 = "What is it? \nIf you don't have any business, \ndon't call me."
10135-300 = "Huh? \nYour job is to check \nif I'm actually here?"
10135-310 = "This person is really something! \nAlways saying \nsuch random things!"
10135-320 = "But well... \nI don't dislike \nthis kind of interaction."
10135-330 = "Hello, Sensei."
10135-340 = "Huh? \nIs there nothing you want to say?"
10135-350 = "..."
10135-360 = "There isn't."
10135-370 = "I told you there isn't, so there isn't!"
10135-380 = "..."
10135-390 = "Happy birthday, \nSensei."
10135-400 = "Huh!? \nMy birthday? \nI-instead of that, you should be celebrating \nAlice's birthday...!"
10135-410 = "Huh, it's the same day so it's fine...? \nW-well, that may be true, but...!"
10135-420 = "...Thank you."
10135-430 = "Happy \nNew Year. \nIt's the first day \nof the new year, but..."
10135-440 = "No, I should get used to this \nsooner or later."
10135-450 = "Since I am already a proper \n\"student\"."
10135-460 = "I'm not asking for \na present or anything."
10135-470 = "Of course, \nif you give me one, I will \naccept it properly."
10135-480 = "..."
10135-490 = "A-are you really \nnot giving me anything...?"
10135-500 = "...!! \nO-oh, thank you...!"
10135-510 = "A day when spirits return... \nWhat a superstitious festival..."
10135-520 = "..."
10135-530 = "Don't I get any candy?"
10135-550 = "Please don't worry."
10135-560 = "I will not disappear."
10135-570 = "In fact, it's the opposite."
10135-580 = "I intend to survive \nby any means necessary."
10135-590 = "If you, Sensei, \nwill not abandon this world."
10135-600 = "Then I, too, will never \ngive up until the very end."
10135-610 = "So it's okay... \nIt will definitely be okay."
10135-620 = "I will be here forever."
10135-630 = "This is just between us, but... \nI—"
10135-640 = "I don't dislike you, \nSensei."
10135-2600 = "It means 'starlight from a distant land.' \nI think it refers to something from that long ago. \nAccording to the coordinates, they say the past and future \nexist simultaneously, after all."