[translation]
10130-10 = "Blue Archive, it is. Hehe."
10130-20 = "I am Kakehashi Subaru.\nIf you are in trouble, I shall lend you my strength.\nWell... strictly speaking, in the 'Arius style', that is."
10130-30 = "A cafe...\nIt feels like\na rather expensive place."
10130-40 = "(It somehow...\nreminds me of\nWater Time.)"
10130-50 = "What is... that?"
10130-60 = "(I didn't really get to come\nto places like this\nvery often...)"
10130-70 = "I wonder if they're...\nhiring for a cafe job?"
10130-80 = "Welcome back, Sensei. I will be serving as your attendant today, I am Kakehashi Subaru."
10130-90 = "I was waiting for you.\nDo you have any instructions?"
10130-100 = "Huh?\n'First, relax your shoulders'...?"
10130-110 = "I'm allowed to eat\nthe snacks freely...?"
10130-120 = "I, I cannot do that! Even if I am\nthe attendant for the day..."
10130-130 = "..."
10130-140 = "Well, just a little bit then..."
10130-150 = "This is just between us, but—"
10130-160 = "I don't really like being called\nthe Arius 'Branch School'..."
10130-170 = "When they call it a 'branch school,' it sounds like we're inferior to the main school, or... like we're an isolated place, doesn't it?"
10130-180 = "...I'm sorry,\nI was thinking about everyone\nback at Arius."
10130-190 = "I have to do my best\nfor their sake, too."
10130-200 = "...Huh? 'Do your best for yourself, too'?"
10130-210 = "Th... thank you\nvery much..."
10130-220 = "Huh? Studying...? I, I'm doing it properly."
10130-230 = "Sigh... but, why do I have to learn\nthings that don't seem\nuseful at all..."
10130-240 = "'Even if you don't understand it now, there will come a time when it will be useful'\n...is that so?"
10130-250 = "Oh, geez... yes, yes, I understand already!"
10130-260 = "That... whenever I meet you, Sensei, I get this strange feeling."
10130-270 = "Up until now, I've never had an adult\nwho treated me this well..."
10130-280 = "Happy birthday, Sensei."
10130-290 = "Well, there isn't much I can do for you, so it's just words of celebration, but..."
10130-300 = "Huh? You want me to play the harmonica for you sometime...? Th, that is..."
10130-310 = "Sigh... I understand. Only for you, Sensei, okay?"
10130-320 = "Thank you for celebrating my birthday, Sensei."
10130-330 = "At Arius, we cherish birthdays."
10130-340 = "I feel like if we stopped doing that, something truly important would be lost as well."
10130-350 = "Well, though... we'd get scolded, so we couldn't really celebrate them in a grand way."
10130-360 = "The day the year ends\nand a new one begins—"
10130-370 = "It's a strange thing...\nI think it's not so bad\nnow."
10130-380 = "Happy New Year,\nSensei."
10130-390 = "It's Christmas, isn't it?\nI know about it, at least."
10130-400 = "A long time ago—\nback in Trinity and Gehenna..."
10130-410 = "I once joked that I might become a Santa who gifts a rain of bullets."
10130-420 = "I don't know much about Halloween, but..."
10130-430 = "If you don't use the festival as an excuse to beg for candy, it's just a normal day, right?"
10130-440 = "It reminded me of the old Arius.\n...Back when there was nothing left but fear."
10130-460 = "I feel a sense of freshness."
10130-470 = "This is the first time I've played for someone else like this..."
10130-480 = "How was it?"
10130-490 = "Was it... strange...?"
10130-500 = "Can I take that as... your honest feelings?"
10130-510 = "...Thank you."
10130-520 = "Honestly, I wish I could do something else for you..."
10130-530 = "But this is all I have to offer right now..."
10130-540 = "Huh? 'I want you to play for me again after you practice'...?"
10130-550 = "'I bought a lot of sheet music, too'...?"
10130-560 = "Th, that is..."
10130-570 = "Please... let me think about it when the time comes."
10130-2600 = "I still can't quite believe it... I'm so anxious every time I wake up in the morning, wondering if it was just a dream... Thank you so much, Sensei. I will treasure this."