[translation]
20056-10 = "Blue! Archive!"
20056-20 = "Ni-ha-ha-ha! You finally made it this far, Sensei! Right to where Kurosaki Koyuki is!"
20056-30 = "(A place to hide... right here!)"
20056-40 = "(I wonder... if I can use a Seminar card here?)"
20056-50 = "You didn't actually follow me all the way here... did you?"
20056-60 = "Sensei, where are you~?"
20056-70 = "Today's coffee is... a random blend!? Ugh... I'm not really a fan of this."
20056-80 = "Ah! Sensei, perfect timing!"
20056-90 = "I was just about to open a card pack!"
20056-100 = "Hello, Sensei!"
20056-110 = "Can I have some snacks? You don't mind, right?"
20056-120 = "Well, I'm already eating them anyway! Ni-ha-ha!"
20056-130 = "Is it my turn for duty?"
20056-140 = "Wait just a second, I'll go grab the picnic mat!"
20056-150 = "Come on, come on, we're going to the arcade! Sensei!"
20056-160 = "Sensei, hurry up and come over here!"
20056-170 = "...Could you turn off the lights for a second?"
20056-180 = "Schale is such a nice place~!"
20056-190 = "No tracking drones, no security shutters to keep people out..."
20056-200 = "How about we do our 'reflection' here at Schale instead of in the reflection room?"
20056-210 = "It's a good idea, right? Say it's a good idea!"
20056-220 = "Happy Birthday! Sensei!"
20056-230 = "Let's stay up all night and play until we drop!!"
20056-240 = "Something I want...?"
20056-250 = "Hmm~?"
20056-260 = "Are you sure you really want to hear it? You won't regret it?"
20056-270 = "Today is the last day of the year!"
20056-280 = "So no matter what we do today, we can just leave the cleanup for next year! Ni-ha-ha!"
20056-290 = "...Eh? It's not the last day?"
20056-300 = "The year has already started? What do you mean by that!?"
20056-310 = "To make sure Santa can arrive safely,"
20056-320 = "I've disabled all the security! Ni-ha-ha!"
20056-330 = "To think I'm allowed to walk around the streets in an outfit like this...!"
20056-340 = "What a wonderful day!"
20056-360 = "Ahhh!? Why did you use that move just now!!"
20056-370 = "I told you to wait for me to go first!"
20056-380 = "Are you trying to ruin my perfect strategy!?"
20056-390 = "I even woke up early and saved a spot for you, Sensei!!"
20056-400 = "...Eh? That's a separate issue?"
20056-410 = "If you're going to say that, Sensei, you're the one who put in more coins...?"
20056-420 = "Ugh... well... that's true, but..."
20056-430 = "Hmph... let's call a truce! A temporary truce!"
20056-440 = "That's right! I'll definitely do better next time!"
20056-450 = "...Ni-ha-ha!"
20056-460 = "...Ni-ha-ha."
20056-2600 = "I'm sure the greatest stroke of luck was meeting you, Sensei! So, well... I'll give it my all! I'm counting on you!"