[translation]
10015-10 = "What is today's\nmission?"
10015-20 = "Ah, cleaning up\nwas Aris's\nresponsibility..."
10015-30 = "Even without armor..."
10015-40 = "Even if I lose\nthe Sword of Light..."
10015-50 = "Even then,\nAris is still Aris."
10015-60 = "As long as everyone\nis here... and..."
10015-70 = "As long as Sensei is here!"
10015-220 = "Sensei!\nIt's a mission, a mission!"
10015-230 = "Yes! Aris loves\nthat Sensei is always\nthe same!"
10015-240 = "Ta-da!"
10015-250 = "Sensei has acquired a reward!"
10015-260 = "That's amazing, Sensei!"
10015-270 = "Let's keep moving forward\nstep by step like this!"