[translation]
10077-80 = "Welcome! I'm all\nready to go!"
10077-90 = "Alright, time to\nget started!"
10077-100 = "Yes, I'm right here."
10077-110 = "Hmm...? Is something\nthe matter?\nYou've been acting\nstrange for a while."
10077-120 = "Pranks like that\naren't very nice~\nHehe."