[translation]
10135-80 = "Consistency is key, you know."
10135-90 = "Are you listening, Sensei?"
10135-100 = "I am telling you to\nbe sincere, aren't I?"
10135-110 = "Is something the matter?"
10135-120 = "Huh?\nYou just... called me\nfor no reason?"
10135-130 = "If you don't have any business,\nplease don't call me!"
10135-140 = "...I suppose it's fine\nevery once in a while."
10135-150 = "Huh?\nYou want... some kind words?"
10135-160 = "Please pick a time and place\nfor your sleep-talking!"
10135-170 = "Don't forget to take\na break, Sensei!"
10135-180 = "And brush your teeth too!"
10135-190 = "There's nothing wrong\nwith you, is there?"
10135-200 = "Is there anything else\nyou need?"
10135-210 = "There isn't much time left\nto be indecisive."
10135-1810 = "This is like... an emergency\nTotal Assault."
10135-1820 = "I'm managing the shop, if only\nto provide some support."
10135-1830 = "Hurry, Sensei!\nWe're at our limit here too!"
10135-1840 = "Markt...\nAnd that trio..."
10135-1850 = "Geez! Nobody ever\nlistens to me!"
10135-1860 = "When this is over...\nwill we be able to go home?"
10135-1870 = "It should be right there!\nHurry!"
10135-1880 = "Choose quickly and\nget back to commanding!"
10135-1890 = "Huh?\nYou want... some kind words?"
10135-1900 = "Please pick a time and place\nfor your sleep-talking!"
10135-1910 = "Honestly... we'd be lost\nwithout you, Sensei."
10135-1920 = "Is there anything else\nyou need?"
10135-1930 = "There isn't much time left\nto be indecisive."
10135-1940 = "Consistency is key, you know."
10135-1945 = "Consistency is key, you know."
10135-1946 = "Consistency is key, you know."
10135-1947 = "Consistency is key, you know."
10135-1950 = "Are you listening, Sensei?"
10135-1955 = "Are you listening, Sensei?"
10135-1956 = "Are you listening, Sensei?"
10135-1957 = "Are you listening, Sensei?"
10135-1960 = "I am telling you to\nbe sincere, aren't I?"
10135-1965 = "I am telling you to\nbe sincere, aren't I?"
10135-1966 = "I am telling you to\nbe sincere, aren't I?"
10135-1967 = "I am telling you to\nbe sincere, aren't I?"
10135-1970 = "Hello, Sensei."
10135-1975 = "Hello, Sensei."
10135-1976 = "Hello, Sensei."
10135-1977 = "Hello, Sensei."
10135-1980 = "I've summarized\ntoday's tasks."
10135-1985 = "I've summarized\ntoday's tasks."
10135-1986 = "I've summarized\ntoday's tasks."
10135-1987 = "I've summarized\ntoday's tasks."
10135-1990 = "Is something the matter?"
10135-1995 = "Is something the matter?"
10135-1996 = "Is something the matter?"
10135-1997 = "Is something the matter?"
10135-2000 = "Huh?\nYou just... called me for no reason?"
10135-2005 = "Huh?\nYou just... called me for no reason?"
10135-2006 = "Huh?\nYou just... called me for no reason?"
10135-2007 = "Huh?\nYou just... called me for no reason?"
10135-2010 = "If you don't have any business,\nplease don't call me!"
10135-2015 = "If you don't have any business,\nplease don't call me!"
10135-2016 = "If you don't have any business,\nplease don't call me!"
10135-2017 = "If you don't have any business,\nplease don't call me!"
10135-2020 = "...I suppose it's fine\nevery once in a while."
10135-2025 = "...I suppose it's fine\nevery once in a while."
10135-2026 = "...I suppose it's fine\nevery once in a while."
10135-2027 = "...I suppose it's fine\nevery once in a while."
10135-2030 = "I-I'm not ticklish or anything,\nyou know!"
10135-2035 = "I-I'm not ticklish or anything,\nyou know!"
10135-2036 = "I-I'm not ticklish or anything,\nyou know!"
10135-2037 = "I-I'm not ticklish or anything,\nyou know!"
10135-2040 = "Ticklish? Not really..."
10135-2045 = "Ticklish? Not really..."
10135-2046 = "Ticklish? Not really..."
10135-2047 = "Ticklish? Not really..."
10135-2050 = "Aaaah!!\nTake this, tickle attack!!"
10135-2055 = "Aaaah!!\nTake this, tickle attack!!"
10135-2056 = "Aaaah!!\nTake this, tickle attack!!"
10135-2057 = "Aaaah!!\nTake this, tickle attack!!"
10135-2060 = "...Yes, here you go.\nPlease take it."
10135-2065 = "...Yes, here you go.\nPlease take it."
10135-2066 = "...Yes, here you go.\nPlease take it."
10135-2067 = "...Yes, here you go.\nPlease take it."
10135-2070 = "W-what is it!?\nDo you want me to say something!?"
10135-2075 = "W-what is it!? Do you want me to say something!?"
10135-2076 = "W-what is it!? Do you want me to say something!?"
10135-2077 = "W-what is it!? Do you want me to say something!?"
10135-2080 = "...Well done, Sensei."
10135-2085 = "...Well done, Sensei."
10135-2086 = "...Well done, Sensei."
10135-2087 = "...Well done, Sensei."
10135-2090 = "I thought you'd be\ncoming around now."
10135-2095 = "I thought you'd be\ncoming around now."
10135-2096 = "I thought you'd be\ncoming around now."
10135-2097 = "I thought you'd be\ncoming around now."
10135-2100 = "W-why are you suddenly\npetting me!?"
10135-2105 = "W-why are you suddenly\npetting me!?"
10135-2106 = "W-why are you suddenly\npetting me!?"
10135-2107 = "W-why are you suddenly\npetting me!?"
10135-2110 = "...I didn't say\nstop."
10135-2115 = "...I didn't say\nstop."
10135-2116 = "...I didn't say\nstop."
10135-2117 = "...I didn't say\nstop."