[translation]
10132-180 = "Sensei...!?\nIs this dress... really\nthat strange...?"
10132-190 = "Welcome back,\nSensei..."
10132-200 = "Um,\nthis outfit is,\nwell..."
10132-210 = "What on earth...\nis happening...?"
10132-220 = "Being on stage is...\nstrange, isn't it."
10132-230 = "Even though so many people\nare watching me..."
10132-240 = "There are moments where I feel...\nso lonely..."
10132-250 = "Everyone...! I've...\nreturned...!"
10132-260 = "Am I...\nreally worthy of\nthis outfit...?"
10132-270 = "I'm standing out too much,\naren't I...?"
10132-280 = "Ugh...\nAnd I'm supposed to be a ninja..."
10132-290 = "A-a-a-are you saying I look beautiful...!?"
10132-300 = "Hyaaaaaa..."
10132-310 = "If I just think of this outfit as..."
10132-320 = "a transformation jutsu,\nthen..."
10132-590 = "I've compiled a list of things\nthat need to be done..."
10132-600 = "None of them are easy,\nbut..."
10132-610 = "I'm sure you can do it, Sensei...!"
10132-620 = "Um...\nWas there something wrong...\nwith my list...?"
10132-630 = "Sensei...?\nIs something the matter...?"
10132-640 = "As expected...!"
10132-650 = "I knew you could do it,\nSensei...!"
10132-660 = "That's amazing...!\nDo you have a talent for ninjutsu too, Sensei...!?"
10132-670 = "Great work...!\nThat was a wonderful finale!"