[translation]
10136-3070 = "Yahoo, Sensei, can you hear me?"
10136-3080 = "It's an emergency, so\nI'm connecting via comms."
10136-3090 = "Even through the line,\nI'm happy to see your face."
10136-3100 = "I made sure there's ventilation, but..."
10136-3110 = "It's still hot.\nShould I take off one more layer—"
10136-3120 = "Huh? Don't? I see..."
10136-3130 = "Well, if Sensei\nsays so..."
10136-3140 = "Right now, I'm more of a marksman\nthan a sniper."
10136-3150 = "When moving,\nI'm with the team."
10136-3160 = "...Thanks for moving me\nto a cooler place."
10136-3170 = "Talking to Sensei is\nfun, as expected."
10136-3180 = "Yes, good work."