[translation]
10134-1550 = "Sensei!\nIt's a mission, a mission!"
10134-1560 = "What is today's\nassignment?"
10134-1570 = "Ah, cleaning up\nwas Aris's job, wasn't it..."
10134-1580 = "Pardon the interruption via comms!\nSensei! It's Aris!"
10134-1590 = "We've found ourselves in\na difficult situation, but..."
10134-1600 = "Let's overcome it\ntogether!"
10134-1610 = "Heh, heh, heh..."
10134-1620 = "What do you think, Sensei?\nHow is Aris's new armor?"
10134-1630 = "Even without armor..."
10134-1640 = "Even if I were to lose\nthe Sword of Light..."
10134-1650 = "Even then,\nAris is still Aris."
10134-1660 = "As long as everyone is here...\nAnd..."
10134-1670 = "As long as you are here, Sensei!"
10134-1680 = "Malkuth..."
10134-1690 = "It really feels like\na final boss!"
10134-1700 = "If we defeat it...\nA secret boss won't appear,\nwill it...?"
10134-1710 = "If we can make it back\nsafely..."
10134-1720 = "I want to introduce\nKei to everyone!"
10134-1730 = "Ta-da!"
10134-1740 = "Sensei has acquired a reward!"
10134-1750 = "That's amazing, Sensei!"
10134-1760 = "Let's keep moving forward\none step at a time!"
10134-1770 = "Ugh... Aris wants to be by your side\nto celebrate too, Sensei!"
10134-1780 = "Yes! Aris loves that you\nare always the same,\nSensei!"