[translation]
10137-10 = "Hey, Tsuchinoko!\nWhere are you!?"
10137-20 = "If I catch you, I'll...\nI'll..."
10137-30 = "Ugh... so scary..."
10137-40 = "Why is this like some kind of harassment— Eek!?\nW-who's there...?"
10137-50 = "Even if it's a ghost, if I can put handcuffs on it...!"
10137-60 = "We finished safely! Fate is\nnothing to worry about!\nHahaha—"
10137-70 = "N-no! Forget I said that!\nIt's definitely something to worry about!\nI'm sorry!!"
10137-80 = "Y-yikes!? ...Geez, you scared me!"
10137-90 = "Phew... the air here is at least\npretty nice."
10137-100 = "Tsuchinoko! If I catch you,\nI'm never letting you go!"
10137-110 = "Stay calm... stay calm..."
10137-430 = "Alright!\nLet's keep going!!"
10137-440 = "How was your fortune today?\nI believe in your luck,\nSensei!"
10137-450 = "Cleanup time!\nLet's give it our all until the end!"
10137-460 = "You're going to share\nyour luck with me?\nYes!"
10137-470 = "Since I'm with you, Sensei,\nwe'll be fine!"
10137-480 = "Ooh! This is the stuff!"
10137-490 = "You're incredibly lucky, aren't you!?\nSensei, you're seriously amazing!"
10137-500 = "I wish every day could be like this~"
10137-510 = "I'll investigate until the very end,\njust in case!"