[translation]
16019-2150 = "Welcome to\nToki Asuma's shop."
16019-2160 = "...I lied.\nIt's everyone's shop."
16019-2170 = "I wasn't able to prepare\nmany items, but..."
16019-2180 = "I hope this will be\nof use to you, Sensei."
16019-2190 = "Welcome to\nToki Asuma's shop."
16019-2200 = "...I lied.\nIt's everyone's shop."
16019-2210 = "I wasn't able to prepare\nmany items, but..."
16019-2220 = "I hope this will be\nof use to you, Sensei."
16019-2230 = "I am Toki Asuma.\nI greet you through the screen."
16019-2240 = "I should be there in person, but due to\nan emergency, please excuse me\nfor communicating this way."
16019-2250 = "Even in an emergency,\nToki Asuma's shop\nis open for business."
16019-2260 = "Yes, Sensei.\nI am here."
16019-2270 = "I will not run or hide—"
16019-2280 = "No... if I were to disappear,\nwould you search for me\nwith bloodshot eyes, Sensei?"
16019-2290 = "What do you think?"
16019-2300 = "It provides warmth, stability,\nand a relaxing effect for the mind and body—"
16019-2310 = "It is an excellent combat suit,\njust like me."
16019-2320 = "Sensei, let's check the functions\nof this suit together."
16019-2330 = "You may stay close to me as much as you like,\nso please, don't hesitate."
16019-2340 = "Yes, Sensei.\nI am here."
16019-2350 = "I will not run or hide—"
16019-2360 = "No... if I were to disappear,\nwould you search for me\nwith bloodshot eyes, Sensei?"
16019-2370 = "What do you think?"
16019-2380 = "It provides warmth, stability,\nand a relaxing effect for the mind and body—"
16019-2390 = "It is an excellent combat suit,\njust like me."
16019-2400 = "Sensei, let's check the functions\nof this suit together."
16019-2410 = "You may stay close to me as much as you like,\nso please, don't hesitate."
16019-2420 = "Please wait a moment."
16019-2430 = "With my perfect maid memory,\nI will recall the location\nof the stock."
16019-2440 = "I am forced to handle this\nonline, but it will not\nhinder business."
16019-2450 = "A best agent does not\nchoose their field of operation."
16019-2460 = "Thank you\nfor your purchase."
16019-2470 = "By the way, if you say the word,\nI can purchase things too."
16019-2480 = "That item, is it?\nUnderstood."
16019-2490 = "While we wait for the restock,\nwould you like to play with me?"
16019-2500 = "So this is the kind of thing\nyou like, I see."
16019-2510 = "Yes, here you go. I look forward\nto your next visit."
16019-2520 = "Please come to see me\nas many times as you like."
16019-2530 = "Thank you\nfor your purchase."
16019-2540 = "By the way, if you say the word,\nI can purchase things too."
16019-2550 = "That item, is it?\nUnderstood."
16019-2560 = "While we wait for the restock,\nwould you like to play with me?"
16019-2570 = "So this is the kind of thing\nyou like, I see."
16019-2580 = "Yes, here you go. I look forward\nto your next visit."
16019-2590 = "Please come to see me\nas many times as you like."
16019-2600 = "Yes, I think that is good."
16019-2610 = "Please take that item\nfrom the shelf behind you."
16019-2620 = "If you bought the wrong item,\nreturns are possible."
16019-2630 = "...I am sorry.\nI could not do it."
16019-2640 = "If you wish, I will include a\ncall ticket for me as a bonus."
16019-2650 = "Of course,\nyou want that, right?"