[translation]
20057-980 = "I have been waiting for you,\nSensei."
20057-990 = "Please leave the tour of\nMillennium to me."
20057-1000 = "If there is anywhere you would like to go,\nplease do not hesitate\nto let me know."
20057-1010 = "It is usually lively here, but..."
20057-1020 = "Millennium is especially so\ntoday."
20057-1030 = "It is a good thing to have\nso much energy, though."
20057-1040 = "We are finally reaching the climax."
20057-1050 = "Both the EXPO,\nand the troublesome incident."
20057-1060 = "Did you enjoy the\nMillennium EXPO?"
20057-1070 = "I was honored to be\nwith you, Sensei."
20057-1080 = "……Yes, very much so."
20057-1090 = "Being able to spend time\nwith you like this……."
20057-1100 = "I am truly happy\nabout that."
20057-1110 = "Please let me know if\nyou get hungry."
20057-1120 = "I know of a\nrecommended cafeteria."
20057-1130 = "If I were acting as a \"maid,\"\nI would prepare a home-cooked meal for you,\nbut……."
20057-1140 = "Right now, I am\na \"student.\""
20057-1150 = "Did you call for me, Sensei?"
20057-1160 = "You just called me for no reason……?"
20057-1170 = "Ufufu,\nmy, my."
20057-1180 = "Fufu."
20057-1190 = "I am actually quite\nresistant to tickling."
20057-1200 = "Sensei……\nwould you mind telling me\nhow you fare?"