[translation]
20056-790 = "W-Who is it!?"
20056-800 = "...Oh,\nIt’s you, Sensei!!"
20056-810 = "You came for me,\nSensei!"
20056-820 = "Everything is set up,\nso"
20056-830 = "just take a seat\nfor now!"
20056-840 = "You really came!"
20056-850 = "I knew you couldn't\nresist, right?\nRight!?"
20056-860 = "Hehe, just leave it\nto me."
20056-870 = "Escaping is my\nspecialty, after all!"
20056-880 = "I feel like a lot of things\nhappened, but..."
20056-890 = "Well, for tonight,"
20056-900 = "let's play until\nthe sun comes\nup...!"
20056-910 = "...That’s what I’d\nlike to say, but..."
20056-920 = "...*Achoo*"
20056-930 = "What do you think?\nHow does it feel...\nIt's fluffy, right?"
20056-940 = "You came to\nrescue me,\nSensei!"
20056-950 = "Wait, did you get\ncaptured too,\nSensei!?"
20056-960 = "This board game\nis rigged!"
20056-970 = "It explodes every single\ntime it's my turn!!"
20056-980 = "Ugh...\nThis cramped reflection room..."
20056-990 = "Well, maybe this isn't\nso bad after all...?"