[translation]
20055-2660 = "W-welcome, \nSensei..."
20055-2670 = "For a place that looks like a shop... \nit feels a bit lonely."
20055-2680 = "Ugh... I'm a little scared... \nUuuu..."
20055-2690 = "Sensei... \nYou won't forget about me, \nwill you...?"
20055-2700 = "I want to do what I can, \nbut..."
20055-2710 = "Everyone here... \nis so amazing..."
20055-2720 = "Ah, yes...! \nRight over there, right...!"
20055-2730 = "Act like a shop clerk... \nAct like a shop clerk..."
20055-2740 = "Thank you as always!"
20055-2750 = "Y-yes... here you go... \nplease..."
20055-2760 = "I-I hope this..."
20055-2770 = "Will be of use... \nto everyone..."
20055-2780 = "W-welcome, \nSensei..."
20055-2781 = "W-welcome, \nSensei..."
20055-2790 = "For a place that looks like a shop... \nit feels a bit lonely."
20055-2791 = "For a place that looks like a shop... \nit feels a bit lonely."
20055-2800 = "Ugh... I'm a little scared... \nUuuu..."
20055-2801 = "Ugh... I'm a little scared... \nUuuu..."
20055-2810 = "Sensei... \nYou won't forget about me, \nwill you...?"
20055-2811 = "Sensei... \nYou won't forget about me, \nwill you...?"
20055-2820 = "I want to do what I can, \nbut..."
20055-2821 = "I want to do what I can, \nbut..."
20055-2830 = "Everyone here... \nis so amazing..."
20055-2831 = "Everyone here... \nis so amazing..."
20055-2840 = "Ah, yes...! \nRight over there, right...!"
20055-2841 = "Ah, yes...! \nRight over there, right...!"
20055-2850 = "Act like a shop clerk... \nAct like a shop clerk..."
20055-2851 = "Act like a shop clerk... \nAct like a shop clerk..."
20055-2860 = "Thank you as always!"
20055-2861 = "Thank you as always!"
20055-2870 = "Y-yes... here you go... \nplease..."
20055-2871 = "Y-yes... here you go... \nplease..."
20055-2880 = "I-I hope this..."
20055-2881 = "I-I hope this..."
20055-2890 = "Will be of use... \nto everyone..."
20055-2891 = "Will be of use... \nto everyone..."
20055-2900 = "I'm okay... \nI'm okay, so..."
20055-2910 = "Must not run away, \nmust not run away..."
20055-2920 = "Must not... run away...!"
20055-2930 = "No matter what happens... missions are \nimportant, after all..."
20055-2940 = "Why did it end up like this..."
20055-2950 = "If only we could have talked... \na little more..."
20055-2960 = "If there is anything \nI can do..."
20055-2970 = "Please, \nlet me know anytime...!"
20055-2980 = "If this were a game system, \nI think it would say this."
20055-2990 = "Mission Clear!"
20055-3000 = "Hehe... \nSaying that,"
20055-3010 = "I feel like my tension \nhas eased a little."
20055-3020 = "Sensei... \naren't you scared?"
20055-3030 = "..."
20055-3040 = "I am, because Sensei is here..."
20055-3050 = "I'll try a little harder."