[translation]
20052-10 = "No risk, \nno return."
20052-20 = "Now then, shall we \nstart the business?"
20052-30 = "Now is the time \nto show you."
20052-40 = "The skills of my Publishing Department, \nwhich survived the barren lands \nof Red Winter!"
20052-50 = "...Though, rather than skills,"
20052-60 = "perhaps 'survival instincts' \nwould be a more \nfitting term."
20052-70 = "It's coming, isn't it... \nThe momentum, it's coming!"
20052-80 = "As the head of the Publishing Department, \nI will make this a success \nno matter what!"
20052-90 = "How did it \ncome to this..."
20052-100 = "Well, I feel like I can \nidentify the cause, \nbut..."
20052-110 = "I can't give up \njust yet...!"
20052-120 = "My, I was worried about \nwhat would happen for a moment..."
20052-130 = "I'm glad it went well... \nWait, a post-mortem \nmeeting, you say?"
20052-140 = "Um... could we do that \nsome other time... \nwould that be okay?"
20052-150 = "Creators..."
20052-160 = "They have the power \nto create something,"
20052-170 = "but when it comes to \nspreading it—"
20052-180 = "they often show no interest \nat all, you see."
20052-190 = "Books... \nWriting is something precious."
20052-200 = "It is a product that holds \nthe 'potential' to draw out \nmaximum output—"
20052-210 = "with minimal input...!"
20052-220 = "Being able to create something \nfrom nothing is a \nwonderful thing."
20052-230 = "And the talent that makes \nthat possible is, too."
20052-240 = "..."
20052-250 = "It's nice, isn't it, \nthat kind of talent."
20052-260 = "I truly... \nmean that from my heart."
20052-270 = "I am truly grateful to all \nthe students of Trinity, \nyou know?"
20052-280 = "...Please don't look at me \nwith those eyes."
20052-290 = "I really do mean it \nfrom the bottom of my heart."
20052-620 = "What do you think is the \nbasis of business? \nGoods...? Exchange...?"
20052-630 = "Of course, \nit's money, isn't it!"
20052-640 = "I'm so glad you \ncame by!"
20052-650 = "Welcome to the front lines of business, \nwhere funds and goods intersect!"
20052-660 = "Hehehe, well then, \nplease take your time."
20052-670 = "Sometimes there are treasures \nsleeping at the back of the shelves."
20052-680 = "Make sure to look carefully \nuntil the end, Sensei."
20052-690 = "Oh, and of course, you're welcome \nto look at me as much as you like?"
20052-700 = "Just because you talk to me, \nit doesn't mean the prices \nwill ever go down, you know?"
20052-710 = "Before a single discount is decided, \ncountless negotiations and..."
20052-720 = "...political dealings take place \nbehind the scenes, after all."
20052-730 = "I never imagined the day would come \nwhen I'd be doing business \nwith you, Sensei."
20052-740 = "My, you really do see all sorts of things \nif you live long enough."
20052-750 = "Oh! \nYou have a sharp eye, Sensei!"
20052-760 = "In that case, would you \nbe interested in this \nas well?"
20052-770 = "Just between us..."
20052-780 = "The moment I see the finished product \nwith my own eyes... that is when \nI get the most excited...!"
20052-790 = "Are you listening, Sensei? \nCulture is money."
20052-800 = "In other words, \nthe act of purchasing—"
20052-810 = "could be called a \ncultural activity."
20052-820 = "I guarantee the \nquality, you know?"