[translation]
20053-10 = "If I'm going on an infiltration mission,\nshould I bring a rice ball or a ration pill...?"
20053-20 = "Hm? Sensei!\nWelcome!"
20053-30 = "Sensei...\nThat's a nice outfit."
20053-40 = "This kind of look\nis pretty refreshing, too."
20053-50 = "Gahhh! Why are you starting a fight\nat a fashion show!?"
20053-60 = "I want to see Tsukuyo..."
20053-70 = "I wonder how she's doing...\nI hope she's eating her ramen\nproperly..."
20053-80 = "The Ninjutsu Research Club,\nfully revived!"
20053-90 = "Sensei, too!\nCome over here!"
20053-100 = "I'm so bored..."
20053-110 = "Hm? You're saying that if I say that,\nsomething is bound to happen?"
20053-120 = "Ugh... this is\ntight and hard to move in..."
20053-130 = "What does everyone see\nin this thing!?"
20053-140 = "Clothing does not define\na ninja..."
20053-150 = "If so, then what is it that makes\na ninja a ninja...!?"
20053-160 = "Watch closely...! Even a dress,"
20053-170 = "is no obstacle\nfor a ninja...!"
20053-330 = "Welcome, Sensei!\nTake your time looking around."
20053-340 = "Oh! But, about this item,\nin my opinion—"
20053-350 = "We have everything\nexcept what we don't! Hehehe!"
20053-360 = "Hehehe~ Let's close up early\nand go eat some\nnew ninja set meals!"
20053-370 = "Choose carefully,\nbuy boldly...!"
20053-380 = "That is the rule\nwhen buying merch...!"
20053-390 = "Someday, I'll have\n'The Chronicles of Young Ninja Michiru-chi'\nmerch here...!"
20053-400 = "Oh~ so that's the one.\nA good choice, isn't it?"
20053-410 = "Exactly! If you're a ninja,\nyou have to choose that!"
20053-420 = "Would you like me to heat this..."
20053-430 = "Ah, my mistake."
20053-440 = "Oh...! That is truly!\nA top-tier recommendation!"
20053-450 = "Well, they're all\ntop-tier recommendations, though!"
20053-460 = "Oh, Sensei came too!"
20053-470 = "...Me? I was just\ndebating which one to get."
20053-480 = "Mmm~ such a good smell—"
20053-490 = "It's not just that, though! \nWell, let's go!"
20053-500 = "Thank you for the meal...\nI can't fit another thing in..."
20053-510 = "Noodles and soup...\nThey are truly like a ninja and ninjutsu..."
20053-520 = "What kind of ramen do you like, Sensei?"
20053-530 = "Oh...!"
20053-540 = "This flavor is enough to inspire\na new ninjutsu...!!"
20053-550 = "Nyaa...!?\nTh-this flavor is...!"
20053-560 = "Hmm, not bad at all...?"
20053-570 = "It's not bad... it's not bad...\nReally, that's all it is..."
20053-580 = "Eh... is this\nreally ramen...?"