[translation]
10053130-1 = "Afterstory 4: Iron Maiden"
10053130-3 = "...So then.\r\n"
10053130-15 = "What is all this commotion about?\r\n\r\n"
10053130-16 = "Apparently... the troublemaker has come to turn themselves in.\r\n\r\n\r\n\r\n"
10053130-17 = "Turn themselves in? There's no way someone would do something so eccentric—\r\n\r\n"
10053130-18 = "No, well, it seems Deputy Director Konoka sent them over.\r\n\r\n\r\n"
10053130-23 = "We've decided to turn over a new leaf!\r\n\r\n\r\n\r\n"
10053130-24 = "Well, it's more like we just don't want to fight that monster-like person ever again….\r\n\r\n\r\n"
10053130-29 = "...Wasn't she on vacation?\r\n"
10053130-30 = "Well, if Konoka sent them, there must be no mistake.\r\n\r\n"
10053130-31 = "Detain the students who turned themselves in temporarily. Confirm their crimes and process them accordingly.\r\n"
10053130-32 = "Understood.\r\n\r\n\r\n\r\n"
10053130-36 = "...Huh? The Director isn't going to interrogate them? Usually—\r\n"
10053130-37 = "She's currently attending to an important guest.\r\n\r\n\r\n"
10053130-38 = "An important guest? ...Who?\r\n\r\n"
10053130-43 = "...My apologies. It's a bit noisy outside.\r\n\r\n"
10053130-45 = "Oh, not at all. If anything, I'm impressed. Ehehe… I suppose that's the pride of Valkyrie, the Public Safety Bureau, for you….\n\n\n\n\n"
10053130-46 = "The Deputy Director seems quite diligent, even while on vacation….\r\n\r\n\r\n"
10053130-47 = "Please, don't tease me so much.\r\n\r\n\r\n"
10053130-48 = "When it comes to being overworked, no department in Valkyrie is any different.\r\n\r\n\r\n"
10053130-49 = "Especially the two bureaus known as 'If there's a fire, call the Fire Bureau; if there's a person, call the Correctional Bureau.'\r\n\r\n"
10053130-50 = "Excessive modesty makes it difficult for the listener, Director of the Correctional Bureau."
10053130-56 = "Ehehe… I would be happy if the others thought like the Director of Public Safety, too.\r\n"
10053130-57 = "If everyone who was outside… ended up coming to the Correctional Bureau all at once…."
10053130-62 = "Perhaps… things might get a little busy… ehehe….\r\n"