[translation]
10053110-1 = "Afterword Part 2: There's No Such Thing as the Occult!"
10053110-3 = "..."
10053110-8 = "Rena, you seem very focused on your phone. Is it an emergency?"
10053110-9 = "Oh, I'm just sending a MomoTalk to my seniors at the dorm..."
10053110-10 = "Come to think of it, it turned out exactly as I said, didn't it?#nThe Tsuchinoko didn't exist after all.\r\n"
10053110-11 = "No, it existed just fine. The Tsuchinoko lives on in our hearts—\r\n"
10053110-12 = "I'm not looking for that kind of answer!! I'm talking about a real Tsuchinoko!!\r\n"
10053110-13 = "Ah, if that's what you mean, then certainly.\r\n"
10053110-14 = "In the end, the Tsuchinoko sightings were just a hoax by those kids fixing the bridge outside."
10053110-15 = "Exactly! That's why I told my seniors the conclusion of our investigation."
10053110-16 = "...Huh?\r\n"
10053110-17 = "Now they should finally understand that the occult is a sham.\r\n"
10053110-18 = "...No, wouldn't that have the exact opposite effect?\r\n"
10053110-19 = "Oh, I got a reply. Look."
10053110-22 = "Oh my.\r\n\r\n\r\n\r\n\r\n"
10053110-23 = "Hehehe.\r\n\r\n\r\n\r\n\r\n"
10053110-24 = "Ihihi... \r\n\r\n\r\n"
10053110-27 = "W-why are they reacting like that?"
10053110-30 = "I heard Rena-chan was going on a trip with friends, and I wondered what it was about.\r\n\r\n\r\n\r\n\r\n"
10053110-31 = "To think you went all that way just to try and prove the occult existence of a Tsuchinoko.\r\n\r\n\r\n\r\n\r\n"
10053110-32 = "As expected... Rena-chan is a true member of the Occult Research Club...\r\n\r\n\r\n"
10053110-35 = "No, no!! Why does everyone interpret it that way!?\r\n"
10053110-36 = "That's not it!! I'm not interested in the Tsuchinoko at all—\r\n"
10053110-43 = "Hiss! I told you, that's not it!!\r\n\r\n"
10053110-44 = "I told you it would have the opposite effect...\r\n\r\n"
10053110-45 = "...Oh, I almost forgot. Shall we head outside? Everyone is already gathered.\r\n"
10053110-46 = "Wait, outside?\r\n\r\n\r\n\r\n"
10053110-47 = "...It's already evening, though?\r\n\r\n\r\n"
10053110-48 = "We came all the way to these deep mountains."
10053110-53 = "There's only one thing to do at night."
10053110-58 = "Cosmos Cosmos—Aliya Aliya Ali—"
10053110-59 = "Please, answer our call.\r\n"
10053110-60 = "Cosmos Cosmos—\r\n"
10053110-61 = "Aliya Aliya Ali—\r\n"
10053110-63 = "...???\r\n"
10053110-64 = "...What are you doing?"
10053110-66 = "Refrain from idle chatter.#nIf distracting thoughts get mixed in, the dark energy of the universe will be blocked!\r\n\r\n"
10053110-67 = "Beings from beyond the galaxy! Answer our call!\r\n\r\n"
10053110-72 = "...Do something about this. You're her junior, right?\r\n\r\n\r\n"
10053110-73 = "I am, but... it's hard to stop Tsubasa once she gets like this...\r\n\r\n\r\n\r\n\r\n"
10053110-74 = "It's like this.#nHave you ever had to be the one to tell a child that 'Santa isn't real'?\r\n\r\n\r\n\r\n"
10053110-75 = "Ah... yeah.\r\n\r\n\r\n\r\n\r\n"
10053110-76 = "I kind of get what you're saying, but still...\r\n\r\n\r\n"
10053110-78 = "Hey! The chant has stopped! The communication is weakening!\r\n"
10053110-83 = "Aliya Aliya Ali—\r\n"
10053110-84 = "Put more heart into it!!\r\n"
10053110-85 = "Cosmos Cosmos—"
10053110-87 = "Moreeeeeeeeeeeeeeeee!!!!\r\n\r\n"
10053110-89 = "Aliya Aliya Ali—!!\r\n\r\n\r\n"