[translation]
10053120-1 = "Afterword 3;Anonymous who?"
10053120-3 = "...I see."
10053120-4 = "As expected of you, Sensei [USERNAME]."
10053120-5 = "This harvest exceeds my expectations."
10053120-6 = "If I analyze this data... I can take another step forward—"
10053120-13 = "Club President, why are you working in the dark? You'll ruin your eyes.\r\n\r\n"
10053120-14 = "Entering without knocking is a breach of etiquette.\r\n\r\n\r\n\r\n"
10053120-15 = "So, what were you looking at? Something weird again?\r\n\r\n"
10053120-16 = "Please retract that phrasing. #nIt makes it sound like I'm always looking at weird things.\r\n\r\n\r\n"
10053120-17 = "Eh? But you are, right? Like aliens, UFOs, and stuff....\r\n"
10053120-18 = "This time it's... a Tsuchinoko? That's way too outdated.\r\n\r\n"
10053120-19 = "Eimi. Aliens, UFOs, and even Tsuchinoko are not [ruby=weird]things[/ruby]. #nThey are simply [ruby=unproven]not yet proven[/ruby].\n"
10053120-20 = "If we decide that [ruby=because]they don't exist[/ruby] just because they haven't been proven, how are we supposed to make new discoveries?\n"
10053120-21 = "That's a fair point, but... it lacks persuasiveness coming from you, President.\r\n\r\n"
10053120-22 = "You've been quite sharp-tongued lately, haven't you!? #nAs a flower blooming on a precipice, I am a being that should be treated gently and with care, you know?\r\n\r\n\r\n\r\n"
10053120-23 = "No, the President's vitality is more like a dandelion on the side of the road.\r\n"
10053120-24 = "...Well, we are close, so I will let your rudeness slide. #nMore importantly, your timing is perfect. I was just about to call you.\r\n\r\n\r\n"
10053120-25 = "Me? Wasn't the Supernatural Investigation Department's activity finished?\r\n\r\n"
10053120-26 = "...Please look at this.\r\n\r\n\r\n"
10053120-32 = "...?\r\n\r\n"
10053120-33 = "...What is this data?\r\n\r\n"
10053120-34 = "I don't know.\r\n\r\n\r\n\r\n"
10053120-35 = "Straight to the point, huh.\r\n"
10053120-36 = "In fact, there is not a single thing we know about it at this moment.\r\n\r\n"
10053120-37 = "“A bus that appeared in a place it shouldn't be,” “a stone statue that moves on its own,” #n“a public phone that rings in the middle of the night”....\r\n\r\n\r\n\r\n"
10053120-38 = "Supernatural phenomena that cannot be explained by existing common sense or theory.\r\n\r\n\r\n"
10053120-39 = "Truly, a “supernatural phenomenon,” right?\r\n\r\n"
10053120-46 = "...Hehe, what do you think?\r\n"
10053120-47 = "Don't you think we still have—things left to do?\r\n\r\n"