[translation]
10053070-1 = "Episode 7;The Last Ghost Story"
10053070-3 = "Oh, Konoka, Sensei.\r\n"
10053070-4 = "Did something happen? I was just about to go looking for you if you were any later..."
10053070-5 = "Wait, hold on!? Why are you both so drenched in sweat!? What actually happened!?"
10053070-10 = "Ah, well... I really don't want to talk about it... it was too ominous...\r\n"
10053070-11 = "[ns1] \"Nothing happened...\" \n[ns2] \"A lot of things, actually...\""
10053070-16 = "Well, it sounds like something happened, then.\r\n"
10053070-18 = "(You explained to the two of them what happened in the phone booth.)"
10053070-19 = "(In the end, the conversation even touched upon the suspicious bus and the stone statue you saw the day before.)"
10053070-22 = "What!? That bus was a ghost!? Why didn't you tell me!\r\n\r\n"
10053070-23 = "Well, I knew you'd get scared if I told you..."
10053070-24 = "Salt! You should've thrown salt!\r\n"
10053070-25 = "Ah! Sweat is salty too, but... do you think that would have worked!?"
10053070-27 = "[ns3] \"It's a gray area... I guess?\" \n[ns4] \"For now, let's take a shower once we get back...\""
10053070-32 = "If everything you just told me is true, what you two experienced was likely a poltergeist phenomenon."
10053070-33 = "It's generally known as a phenomenon where ghosts move objects, but unnatural and sudden temperature changes are also a classic example.\r\n"
10053070-37 = "However, something is strange. I pride myself on having been in this field for quite a while, but..."
10053070-38 = "I've experienced more paranormal phenomena since coming here than in all my time before. The frequency is abnormally high.\r\n"
10053070-42 = "Tsubasa thought so too."
10053070-43 = "Does that mean someone is pulling the strings behind the scenes?"
10053070-44 = "Eh? No... I was just saying that this area has a high density of paranormal phenomena."
10053070-45 = "Perhaps there are ancient ruins sleeping beneath this ground, or maybe there's a secret alien experimental facility here.\r\n"
10053070-46 = "You're saying that seriously... aren't you? Yeah.\r\n"
10053070-50 = "...Could it be one of the Seven Prisoners?\r\n"
10053070-51 = "Even using common sense, it's weird that these inexplicable things keep happening. Isn't it more realistic to think someone is doing this intentionally?"
10053070-52 = "Is there anyone among those seven who could pull something like this off?"
10053070-57 = "Hmm, I don't care what it is as long as it's not a ghost...\r\n"
10053070-58 = "There is one person who wouldn't be surprised if they were behind all of this."
10053070-59 = "The same person you mentioned before?"
10053070-60 = "...Unfortunately, yes."
10053070-61 = "Ugh... why of all places, is a Tsuchinoko here of all things...\r\n"
10053070-62 = "Or is it the other way around? Is a Tsuchinoko here because it's this kind of place!?"
10053070-68 = "Ah, the taxi's here!"
10053070-72 = "For now, let's head back to the cabin and rethink things—\r\n"
10053070-76 = "...?\r\n"
10053070-79 = "...????"
10053070-81 = "Hey, you bastards! I've had enough!\r\n"
10053070-82 = "Somehow... isn't this a mix of all sorts of things?"
10053070-83 = "At this point, I'm more dumbfounded than scared..."
10053070-84 = "Threatening me by punching tickets when I'm not even riding!!\r\n"
10053070-85 = "And shooting and breaking things whenever you don't like them!!\r\n"
10053070-86 = "Using common sense, who buries things eight meters deep!!\r\n"
10053070-89 = "It seems they are extremely angry...\r\n\r\n"
10053070-90 = "Who are you to talk about common sense?\r\n\r\n\r\n"
10053070-91 = "Even for Konoka, rather than being scared—\r\n\r\n\r\n\r\n"
10053070-93 = "Whoa, what is that!?\r\n\r\n\r\n\r\n"
10053070-94 = "Ah, never mind. It's over.\r\n\r\n\r\n"
10053070-96 = "It's all that gray-haired one...! It's all their fault...!"
10053070-97 = "I'll show you real terror now!!"
10053070-99 = "Konoka! Look out!\r\n"
10053070-101 = "Waaaaah!!\r\n\r\n"
10053070-103 = "No! They're in a complete panic!\r\n\r\n"
10053070-104 = "If it's a ghost story, win with fear like a proper ghost story! Don't use physical violence!!\r\n\r\n\r\n\r\n"
10053070-106 = "The \"Last Ghost Story\" is—to become a ghost story yourself!!"
10053070-107 = "Liar!! That's not a ghost story at all, is it!?\r\n"
10053070-108 = "Hii...!\r\n\r\n"
10053070-110 = "Too scared to even scream? This is the end!!"
10053070-111 = "This is bad! At this rate, Konoka is going to get run over! Eek!\r\n\r\n"
10053070-112 = "Sensei!!\r\n\r\n\r\n"
10053070-113 = "[ns5] \"It's okay, leave this to me!\" \n[ns6] \"Both of you, take Konoka and run...!\""
10053070-119 = "............\r\n"
10053070-124 = "Kyaaaaaaaaaaa!!\r\n\r\n\r\n\r\n\r\n"
10053070-129 = "............"
10053070-132 = "............\r\n"
10053070-136 = "Ouchhhhhhhhhh!!\r\n\r\n\r\n"
10053070-137 = "What is this! This is way too hard!!\r\n"
10053070-141 = "Eh...? What was that just now?\r\n\r\n\r\n\r\n"
10053070-142 = "What happened?\r\n\r\n\r\n"
10053070-143 = "[s7] \"Shattered it with a punch...\" \n[s8] \"That was a truly magnificent straight punch.\""
10053070-146 = "W-wait... Why, until the very end..."
10053070-147 = "This is impossible..."
10053070-148 = "(Static...)"
10053070-149 = "Tsubasa? Hey, Tsubasa?\r\n\r\n\r\n"
10053070-155 = "Sensei, this kid has fainted!!"
10053070-157 = "Ahhh, this is the worst—I want to go home—\r\n\r\n"
10053070-159 = "(...And so, the ghost story incident came to a close without a single thing being solved... or so it seemed.)"
10053070-163 = "(And that night—)"
10053070-166 = "To faint in a situation like that... I'm ashamed as the leader of the investigation team.\r\n"
10053070-167 = "That aside, how did you manage to get through that?"
10053070-173 = "Um... well, you know... somehow...\r\n\r\n\r\n\r\n"
10053070-174 = "Things more mysterious than magic really do happen, don't they... Ah, no, there's no such thing as magic in this world, though...\r\n\r\n"
10053070-176 = "...?\r\n"
10053070-177 = "I don't quite follow, but can I assume it's been resolved?"
10053070-178 = "Resolved... resolved, huh...\r\n\r\n"
10053070-179 = "Honestly, I have no idea what happened or how... what about you, Sensei?"
10053070-180 = "[s9] \"At the very least, it's certain that this isn't a normal situation.\" \n[s10] \"I feel like it's a bit dangerous to stay here any longer.\""
10053070-183 = "Yeah, you're right."
10053070-184 = "No, no, no, what about the Tsuchinoko!?\r\n"
10053070-185 = "Are you still planning on chasing the Tsuchinoko...?\r\n\r\n\r\n"
10053070-186 = "My bad luck is what's attracting the ghosts in the first place! If I don't find the Tsuchinoko and break the curse, it won't be solved!"
10053070-188 = "Opinions are divided, then..."
10053070-189 = "Regardless, it's too late today. It would be difficult to move to another location now."
10053070-190 = "Let's rest for now and decide what to do tomorrow morning."
10053070-191 = "I agree with that plan, but... come to think of it, why is Tsubasa calling the shots?\r\n"
10053070-196 = "—sei."
10053070-201 = "Sensei."
10053070-202 = "[s11] \"Konoka?\" \n[s12] \"Can't you sleep?\""
10053070-208 = "...Shh."
10053070-209 = "There's someone outside the window."
10053070-210 = "[s13] \"Eh?\" \n[s14] \"Since when?\""
10053070-213 = "I don't know. Both the Director and I just noticed it."
10053070-214 = "To be precise, we noticed it because Konoka woke up..."
10053070-215 = "I don't know who it is, but if they've been watching from outside until this hour, there's a high possibility they're the mastermind behind this commotion.\r\n"
10053070-221 = "If my guess is correct, it's one of the Seven Prisoners—\r\n"
10053070-222 = "Kyoko Mitsui.\r\n"
10053070-227 = "Konoka. I've set up the camera you asked for. It's ready to shoot immediately."
10053070-228 = "Alright... then, I'll take them down on the count of three."
10053070-229 = "One—two—\r\n"
10053070-230 = "Here we gooooooo!!\r\n\r\n"
10053070-239 = "Funyaa!? W-what!?\r\n"
10053070-245 = "They were definitely there... where did they disappear to?\r\n"
10053070-246 = "You two saw them too, right?"
10053070-247 = "Yes. They were definitely there until Konoka opened the window. I can state that for certain."
10053070-248 = "And they disappeared...? As if they never existed in the first place..."
10053070-249 = "Ah, right. Director, what about the photo?\r\n"
10053070-250 = "I'm about to check it, but don't get your hopes up."
10053070-251 = "I could have sworn I said on the count of three...\r\n\r\n"
10053070-257 = "Wait! What are you talking about? What is everyone doing?"
10053070-258 = "[s15] \"It seems someone was outside.\" \n[s16] \"I think they're the mastermind behind this incident.\""
10053070-261 = "Outside? Outside the window...?"
10053070-262 = "...?\r\n"
10053070-263 = "What's wrong? Are you still half-asleep?"
10053070-264 = "No, isn't that weird?\r\n"
10053070-269 = "Because we're on the second floor, you know?"