[translation]
10053060-1 = "Episode 6;The Phone Booth Where Voices of Grudge Resonate"
10053060-2 = "(The next day)"
10053060-7 = "I told you, we're never going to find it this way!\r\n\r\n\r\n\r\n"
10053060-12 = "What's with the sudden outburst?\r\n"
10053060-17 = "It's not \"sudden\" at all, okay!? We've been flipping rocks for two hours now, haven't we!?\r\n"
10053060-18 = "However... snakes, by nature, prefer damp, sunless places..."
10053060-19 = "And anyway, what even is a Tsuchinoko?#nDoes it have any features other than being a fat snake?\r\n"
10053060-20 = "Hmm... that's a sharp question. First of all, the term \"fat snake\" isn't quite accurate.\r\n"
10053060-21 = "It's just called that because it's easy to understand,#nin reality, it's said to have a silhouette closer to a rhombus."
10053060-22 = "Is that so? Anything else?"
10053060-23 = "Accounts vary, but it's also said to hiss like a cat when threatened."
10053060-24 = "Isn't that just a cat?"
10053060-25 = "And the most amazing thing is its jumping ability! It's said to be able to leap nearly a meter in place!\r\n"
10053060-26 = "That's just a cat!!"
10053060-27 = "Now that you mention it... wait, was the Tsuchinoko a cat all along!?"
10053060-28 = "Why are you accepting that so easily?\r\n"
10053060-29 = "Don't you have any more useful information to help us find it?"
10053060-30 = "Hmm... not information, but I do have one method."
10053060-31 = "That is—to decide on a team name."
10053060-32 = "...?\r\n"
10053060-33 = "What do you mean?"
10053060-38 = "As you know, a name defines the essence. #nFor example, the moment we call ourselves an \"Investigation Team,\" our purpose becomes investigation, #nand we become subconsciously loyal to that goal.\r\n\r\n"
10053060-39 = "And there are research results suggesting that this clear will readjust the flow of the universe, #ncausing things to converge toward the result we desire—or more accurately, the result we were hoping for.\r\n\r\n"
10053060-40 = "Stop pivoting from plausible grit to occult-like pseudoscience so suddenly!\r\n\r\n"
10053060-45 = "Ah, I'm in favor. It'd get me more hyped if we had a cool name.\r\n"
10053060-46 = "What do you think, Sensei?"
10053060-47 = "[s1] \"I think it's a good idea too.\"\r\n[s2] \"Let's see, for example...\""
10053060-53 = "[ns] \"Since we're researching the occult, how about 'Occult-Investi'—!!\""
10053060-55 = "Stop it! Why would you say that!?\r\n\r\n\r\n"
10053060-60 = "I thought it was a pretty good idea, personally.\r\n"
10053060-61 = "If that doesn't suit your tastes, how about we stay true to our original purpose... \"Tsuchinoko Investigation Team\"?\r\n"
10053060-62 = "Hmm... I don't know, don't you have something that hits a bit harder?\r\n\r\n\r\n\r\n"
10053060-67 = "W-what? Why are you looking at me...?\r\n\r\n\r\n\r\n"
10053060-68 = "Well, if Rena is against \"Occult-Investi,\" she needs to provide an alternative.\r\n\r\n\r\n\r\n"
10053060-69 = "Isn't \"Tsuchinoko Investigation Team\" just fine?\r\n\r\n\r\n\r\n\r\n"
10053060-70 = "[s3] \"For someone who is Kivotos's top fashion designer...\"\r\n[s4] \"This is your chance to show off your artistic sense, Rena!\""
10053060-73 = "N-no, this has nothing to do with fashion—\r\n\r\n\r\n\r\n\r\n"
10053060-74 = "Ugh...\r\n\r\n\r\n\r\n\r\n"
10053060-75 = "It seems you're aware it's not entirely unrelated, then...\r\n\r\n"
10053060-76 = "Whoa, as expected of a student from Wild Hunt!\r\n\r\n\r\n\r\n\r\n"
10053060-77 = "...X.\r\n\r\n\r\n\r\n\r\n\r\n"
10053060-78 = "Hm?\r\n\r\n\r\n\r\n\r\n"
10053060-79 = "\"Investigation Squad X\"... how's that?\r\n\r\n\r\n\r\n\r\n\r\n"
10053060-80 = "...\r\n\r\n"
10053060-81 = "...\r\n\r\n\r\n\r\n"
10053060-82 = "Ah, never mind! Forget I said that!\r\n\r\n\r\n\r\n\r\n"
10053060-83 = "No, that's actually super cool, Investigation Squad X!!\r\n\r\n\r\n\r\n\r\n\r\n"
10053060-84 = "It feels like... agents of a secret organization.\r\n\r\n\r\n"
10053060-85 = "When I ask my guys for names, they only come up with boring stuff like \"Hope\" or \"Light.\" #nArt school really is different, huh?\r\n\r\n\r\n\r\n"
10053060-86 = "R-really? It's not bad...?\r\n\r\n\r\n\r\n\r\n"
10053060-87 = "H-hmpf! Of course it isn't. Who do you think came up with it?\r\n\r\n\r\n\r\n\r\n"
10053060-88 = "Now that we have a name, I feel like our Tsuchinoko hunt is going to pick up speed!\r\n\r\n\r\n"
10053060-90 = "Alright, \"Investigation Squad X\"! Let's put our backs into it and start the search again!\r\n"
10053060-97 = "I told you, we're never going to find it this way!!\r\n\r\n"
10053060-102 = "Hm? Is there a problem?\r\n"
10053060-103 = "There's nothing but problems! Nothing has changed at all!!\r\n"
10053060-104 = "I've flipped so many rocks that I've become an expert on the bugs living under them, you know!?\r\n"
10053060-105 = "Ah, don't worry about that. #nThe flow of the universe's energy is already directed toward us thanks to the \"Law of Attraction.\"\r\n"
10053060-106 = "However, be careful. Do not use negative words. If possible, use the past tense instead of a wish. #nNot \"I want to find a Tsuchinoko,\" but \"I found a Tsuchinoko.\""
10053060-108 = "That's occult!! Pseudoscience!!\r\n\r\n\r\n"
10053060-110 = "Hm? Come to think of it, what time is it?\r\n"
10053060-114 = "...Ah.\r\n"
10053060-115 = "What's wrong? Is it time for the bus?\r\n"
10053060-116 = "No, it's just...\r\n\r\n"
10053060-118 = "...The bus already left, didn't it.\r\n"
10053060-124 = "Well, we can just call a taxi.\r\n"
10053060-133 = "Whoa, seriously? There's no signal here."
10053060-134 = "I didn't know there were still places in Kivotos cut off from civilization.\r\n"
10053060-135 = "Mine's dead too. No signal at all.\r\n"
10053060-136 = "Wouldn't it be better to just walk back now?"
10053060-137 = "...Oh, right."
10053060-138 = "I think I saw a payphone earlier.\r\n"
10053060-139 = "Ah, now that you mention it, I saw one too."
10053060-140 = "Then let's use that to call a taxi! I'll be right back!\r\n\r\n"
10053060-144 = "Wait! The sun is already setting. Walking through the mountains alone is—\r\n"
10053060-145 = "...She's gone, isn't she.\r\n"
10053060-147 = "[ns5] \"I'll go after her.\"\r\n[ns6] \"You two wait here.\""
10053060-154 = "Don't move. Who's there...?\r\n"
10053060-155 = "...Huh? Sensei?\r\n\r\n"
10053060-156 = "Sorry, I knew someone was following me, #nso I thought it was \"that escapee.\"\r\n\r\n"
10053060-157 = "Still, what are you doing here? I'm glad you waited, though.\r\n"
10053060-158 = "...Eh? Worried? #nYou were worried about me?\r\n\r\n"
10053060-164 = "Wow, even at the Public Safety Bureau, I've never been treated this well.\r\n\r\n"
10053060-165 = "If anything, those guys would be the first to push me into a dangerous job, #nhahaha!"
10053060-166 = "So, I'm happy. But I'm fine on my own! #nLike I said, I'm just making a call from a perfectly normal payphone.\r\n"
10053060-167 = "I'll call a taxi real quick, so please wait just a second!"
10053060-172 = "...Ah"
10053060-173 = "Sensei, um... sorry to ask, but do you have any change?\r\n"
10053060-174 = "[s7] \"Right after saying that...\"\r\n[s8] \"It was the right choice to follow you.\""
10053060-179 = "Oh, are you coming in too, Sensei?\r\n"
10053060-182 = "Isn't it cramped? Should I step out? #n...Oh, you're okay with it?"
10053060-183 = "Alright, let's get this over with.\r\n"
10053060-188 = "...Ah, hello? Is this the taxi company?\r\n\r\n"
10053060-189 = "I'm calling to request a pickup. The location is—\r\n"
10053060-190 = "Wait, hold on a second.\r\n"
10053060-191 = "How should I explain where this is... It's Mt. Shirakawa...\r\n\r\n"
10053060-192 = "Ah, it's cutting out! Sensei! The change! Hurry!\r\n\r\n"
10053060-196 = "And, uh, where was this again.\r\n\r\n"
10053060-197 = "...Right, right, please come to the Mt. Shirakawa bus stop. Yes, right in front of the stop.\r\n\r\n"
10053060-198 = "There are four of us. Oh, would a small car be too cramped for you, Sensei?\r\n"
10053060-199 = "No, if you take the passenger seat and we squeeze three in the back—\r\n"
10053060-200 = "Ah, it's cutting out again! This is why I hate payphones!\r\n\r\n"
10053060-204 = "Ah, yes, a small car is fine.\r\n"
10053060-205 = "We'll be waiting, so please come quickly.\r\n"
10053060-206 = "Yes, thank you very much.\r\n"
10053060-210 = "Alright! That's solved! Now we just have to wait at the bus stop—\r\n\r\n\r\n"
10053060-215 = "Huh? It won't open?\r\n"
10053060-220 = "Can't be helped. Sensei, please step back!\r\n\r\n"
10053060-228 = "Sensei? Um...\r\n"
10053060-229 = "Do you happen to have any change left...? I feel like we should call for help...\r\n\r\n"
10053060-230 = "[ns9] \"I'm all out...\"\n[ns10] \"That last one was the end of it.\""
10053060-234 = "Man, when things go wrong, they really pile up, don't they.\r\n\r\n"
10053060-235 = "Sorry for dragging you into this, Sensei...\r\n\r\n"
10053060-236 = "[s11] \"It's not your fault, Konoka, is it?\"\n[s12] \"The door is just old and stuck.\""
10053060-239 = "No, it's because my luck is bad, so I'm attracting disaster.\r\n"
10053060-240 = "That's why when my luck is down, I prefer to be alone. #nOtherwise, it just spreads to everyone around me.\r\n"
10053060-241 = "[s13] \"You really believe in that stuff, huh?\"\n[s14] \"Fortunes and superstitions.\""
10053060-244 = "It's not about believing, isn't it just a fact?\r\n"
10053060-245 = "Look, getting trapped in a phone booth isn't something that happens every day, right?\r\n"
10053060-246 = "The fact that it's happening at this exact moment is proof that my luck is terrible."
10053060-247 = "...Well, the others will probably notice and come to help eventually. #nAnd the taxi will get here sooner or later."
10053060-251 = "...Man, it's cramped in here.\r\n"
10053060-252 = "[s15] \"Yeah...\"\n[s16] \"I feel like it's getting hot in here too...\""
10053060-255 = "Ah, you feel it too, Sensei?\r\n"
10053060-256 = "Is it because there are two of us in here...?\r\n\r\n"
10053060-260 = "Ah... no, sorry, I bumped into you.\r\n\r\n"
10053060-261 = "What is this situation...\r\n\r\n\r\n"
10053060-266 = "Is the payphone ringing...?\r\n"
10053060-267 = "Eh? Can you even receive calls on a payphone?\r\n"
10053060-268 = "[s17] \"Technically, I think it's possible...\"\r\n[s18] \"But usually, they don't ring, right...?\"\r\n"
10053060-271 = "What should we do?\r\n\r\n"
10053060-275 = "Should we answer it?\r\n"
10053060-281 = "...Hello?\r\n"
10053060-286 = "(From the other side of the receiver, the sound of roaring flames and agonizing screams can be heard)"
10053060-287 = "You too... will burn to death here...\r\n\r\n"
10053060-291 = "S-s-s-Sensei!?\r\n\r\n"
10053060-292 = "Did you hear that just now!? This is bad, right!?\r\n\r\n"
10053060-293 = "[s19] \"L-let's calm down for a second.\"\n[s20] \"It might be noise, or a prank call!\""
10053060-296 = "How could it be a prank call!?\r\n\r\n"
10053060-297 = "Who would make a prank call to a payphone in a place like this!\r\n"
10053060-298 = "And they said \"burn to death,\" right? #nI feel like it's getting hotter and hotter in here...\r\n"
10053060-299 = "No, I'm not imagining it!! The floor is seriously hot!!\r\n\r\n"
10053060-300 = "[s21] \"You're right...!\"\n[s22] \"But let's stay calm and wait for rescue...!\""
10053060-304 = "(10 minutes passed, but no help came...)"
10053060-307 = "Haa... haa..."
10053060-308 = "Sensei, are you okay? You've been sweating like crazy...\r\n"
10053060-309 = "[s23] \"You too, Konoka...\"\n[s24] \"I think... I'm at my limit...\""
10053060-312 = "..."
10053060-313 = "Can't be helped.\r\n\r\n"
10053060-314 = "Sensei, please move a little closer."
10053060-318 = "No, this isn't the time to worry about physical contact... #nYes, that's close enough."
10053060-319 = "Alright, here I go—"
10053060-323 = "SMASH IT OPEN!!!!\r\n"
10053060-333 = "Ahhh, that feels refreshing!! We should've done this from the start!\r\n\r\n"
10053060-334 = "Sensei, are you hurt?"
10053060-335 = "[ns25] \"No, thanks to you. Thank you.\"\r\n[ns26] \"I can't believe you threw the phone booth...\""
10053060-338 = "This is nothing!\r\n"
10053060-340 = "(Static...)\r\n"
10053060-341 = "No... that's... cheating...\r\n"
10053060-350 = "Whoa, it talked again!! Is something haunting it!?\r\n"
10053060-351 = "Let's go! Hurry!!\r\n\r\n"
10053060-353 = "(In the end, the identity of the voice on the other side of the phone remained a mystery...)"