[translation]
10053085-3 = "...Huh!?"
10053085-4 = "W-what happened? I remember up until the battle started, but..."
10053085-8 = "You slipped and fell the moment the battle started, and then you passed out."
10053085-9 = "At a time like this... honestly, I'm ashamed.\r\n"
10053085-10 = "Does that mean... Rena-kun defeated them all by herself?"
10053085-11 = "No, why would you think that...? It’s obviously Konoka, right?\r\n"
10053085-12 = "Hmm? That’s pretty harsh for a joke."
10053085-18 = "Now then~\r\n"
10053085-19 = "How should I punish you guys?\r\n"
10053085-24 = "W-wait! We already surrendered, didn't we! #nYou're not actually going to hit someone who's unarmed, are you!?"
10053085-25 = "What kind of nonsense are you spouting? Of course I'm going to hit you.\r\n\r\n\r\n"
10053085-26 = "Are Valkyries even allowed to do that!?\r\n\r\n\r\n\r\n\r\n"
10053085-27 = "If it's you guys, it's no problem. This is why I can't quit being a Valkyrie.\r\n\r\n\r\n"
10053085-28 = "I'll consider us even for all the trouble you've caused me until now.\r\n\r\n"
10053085-29 = "W-wait! What are you talking about? We didn't do anything! It's a false accusation!!\r\n\r\n\r\n\r\n\r\n\r\n"
10053085-30 = "You guys were the ones who cut the phone lines and destroyed the bridge, right?\r\n\r\n"
10053085-31 = "Ah... well, that’s true, but...\r\n\r\n\r\n\r\n\r\n"
10053085-32 = "Honestly, I don't think you can claim 'false accusation' after dragging a tank out here.\r\n\r\n\r\n\r\n\r\n"
10053085-33 = "Whose side are you on, anyway!?\r\n\r\n\r\n\r\n\r\n"
10053085-34 = "Is this a comedy sketch or something?\r\n\r\n"
10053085-35 = "...Rena, magic doesn't exist, right? I'm going to show you one right now.\r\n\r\n"
10053085-41 = "It's called 'a spell that forces you to speak your true feelings.' It’s quite mysterious, actually."
10053085-51 = "N-no... that’s not it! Really! I swear I’m not lying!"
10053085-52 = "I-it’s just, it is true that we spread the Tsuchinoko rumors to lure out the Deputy Director, but――"
10053085-53 = "But really... we truly didn't do anything else..."
10053085-55 = "...Wait a minute, what did you just say?\r\n"
10053085-56 = "You're saying you were the ones who spread the Tsuchinoko rumors?"
10053085-58 = "Huh? What's with the sudden change? Who are you?\r\n\r\n\r\n"
10053085-60 = "Are you saying... the Tsuchinoko doesn't exist?\r\n"
10053085-62 = "Well, obviously. There's no way a Tsuchinoko exists.\r\n\r\n"
10053085-63 = "We just made up some rumors and spread them on the internet, thinking we could bait the occult-loving Deputy Director.\r\n\r\n\r\n"
10053085-64 = "Huh!? There are things you should and shouldn't do, you know!?\r\n\r\n\r\n"
10053085-65 = "B-but hey! Common sense dictates that nobody believes in Tsuchinokos these days――\r\n\r\n\r\n\r\n"
10053085-66 = "But 'it's the victim's fault for being fooled' is a classic perpetrator's line, isn't it?\r\n\r\n\r\n\r\n\r\n"
10053085-67 = "That's why! Whose side have you been on this whole time!?\r\n\r\n\r\n\r\n\r\n\r\n"
10053085-73 = "..."
10053085-74 = "...I see, the Tsuchinoko never existed from the start.\r\n"
10053085-75 = "Tsubasa...?"
10053085-76 = "I thought if I could find a Tsuchinoko... or an alien... that the annoying 'seminar' might... #nreconsider my club once more.\r\n"
10053085-77 = "I thought that if I did that, maybe we could all do club activities together again..."
10053085-78 = "..."
10053085-82 = "...No, it's fine. I had anticipated that this might happen to some extent.\r\n"
10053085-83 = "Even if I can't find a Tsuchinoko, there are other ways to rebuild the club... Yes!"
10053085-84 = "[s1] \"Alright, let's go look for the Tsuchinoko again today.\"\r\n[s2] \"Dawn is almost breaking, anyway.\""
10053085-87 = "Didn't you hear? The Tsuchinoko doesn't exist...\r\n"
10053085-92 = "Yeah, they clearly said they were the ones who spread the rumors themselves."
10053085-93 = "Oh, don't get me wrong? I never believed in Tsuchinokos from the start.\r\n"
10053085-94 = "...So, nothing has changed for me."
10053085-95 = "Rena-kun...\r\n"
10053085-100 = "Sigh... why do they always hit the exact developments I like?\r\n\r\n"
10053085-101 = "Hey, you guys."
10053085-103 = "Y-yes!?"
10053085-104 = "In exchange for pretending today's incident never happened, I'm going to need you to help me with something."
10053085-105 = "But, you said there's no such thing as a Tsuchinoko――"
10053085-106 = "Was the 'spell that makes you understand human speech' a right straight? Or was it a left hook?"
10053085-107 = "Eek, eeeeek!! O-okay!! Everyone, let's go find the Tsuchinoko!! #nSearch every inch around the mountain cabin!"
10053085-108 = "Don't miss even a single scale!"
10053085-114 = "Hmm..."
10053085-115 = "But it still bothers me...\r\n"
10053085-116 = "[s3] \"What's wrong?\"\r\n[s4] \"Is there something bothering you?\""
10053085-119 = "In the end, who was that 'white shadow' in the photo?"
10053085-120 = "Eh? Wasn't that just a reflection of you guys running away after cutting the phone lines?"
10053085-121 = "I thought so at first, too..."
10053085-122 = "But there wasn't anyone wearing white clothes, was there?"
10053085-123 = "...Eh?\r\n"
10053085-127 = "W-what is it!? Who are you people!"
10053085-128 = "Who is this? Were they hiding the whole time we were fighting?"
10053085-129 = "That's way too suspicious."
10053085-131 = "[ns5] \"Wait, this voice...?\"\r\n[ns6] \"Could it be...?\""
10053085-135 = "Club President!?"
10053085-142 = "Ah, ahaha... H-hello. Long time no see."
10053085-143 = "[s7] \"Mirai is... the Club President...?\"\r\n[s8] \"Wait, so the club Tsubasa belonged to was...\""
10053085-150 = "Ah, I hadn't mentioned it yet, had I?"
10053085-151 = "I am a member of the 'Pseudoscience Club.' Or, to be precise, a 'former' member..."
10053085-152 = "I didn't know you were acquainted with President Mirai, Sensei."
10053085-157 = "Well... I feel like I would have been happier not knowing...\r\n\r\n"
10053085-158 = "Pseudoscience Club? President Mirai? I feel like I've heard that somewhere...?"
10053085-159 = "Ah, um, just to be clear and avoid any misunderstandings..."
10053085-160 = "For this time only, I really don't have any malicious intent!"
10053085-161 = "No, it's not like I usually have malicious intent either, but..."
10053085-163 = "Ah, I remember. I've seen you on a wanted poster. You're a con artist, right?"
10053085-165 = "H-how rude! #nI'm just an inventor who commercializes and sells applied sciences in fields that haven't been verified yet!"
10053085-166 = "Like germanium bracelets or magnetic futons?"
10053085-167 = "Those are the best-selling products of our club, yes..."
10053085-168 = "Yeah, you're a con artist."
10053085-169 = "Or rather, did I even hold a grudge against the 'Pseudoscience Club'?\r\n\r\n\r\n\r\n"
10053085-170 = "Yes? What are you talking about?\r\n\r\n"
10053085-171 = "Didn't you come all the way here to take revenge on me?\r\n\r\n\r\n"
10053085-172 = "Revenge? I would never go out of my way to do something so inefficient that doesn't earn a single cent."
10053085-173 = "Are you the type who thinks the world revolves around you? #nThat's an early symptom of delusions of grandeur, you know?\r\n\r\n"
10053085-174 = "...Then why did you come here?\r\n\r\n\r\n"
10053085-175 = "That is, um... top secret, you could say...\r\n\r\n"
10053085-176 = "Rena, the magic is about to start~\r\n\r\n\r\n\r\n"
10053085-180 = "Wait! What are you planning to do! Hey, don't come any closer! #nI'll talk! I'll tell you, okay!? I'll talk!"
10053085-181 = "This is why I dislike the athletic types; they're so barbaric...\r\n\r\n\r\n\r\n"
10053085-182 = "Anyway, strictly speaking, I'm a victim too!"
10053085-183 = "Oh?\r\n\r\n\r\n\r\n"
10053085-184 = "Um... I'd like you to keep this a secret from her, but...\r\n\r\n"
10053085-188 = "I happened to hear through an acquaintance that Tsubasa was going on a trip with people I didn't know..."
10053085-189 = "I don't mean it in a bad way, but Tsubasa is a bit extreme, isn't she? #nBecause she *truly believes* in things, she lacks a bit of social awareness..."
10053085-190 = "So, I got worried and followed her."
10053085-191 = "No, I didn't intend to stay in this rural area for long either!? #nI planned to go home as soon as I confirmed she was doing well!"
10053085-192 = "But the signal doesn't even work properly in this whole area!"
10053085-193 = "And when I tried to go home, the bridge was broken!"
10053085-194 = "On top of that, the people she was with turned out to be Valkyries!!"
10053085-195 = "Do you have any idea how much trouble I've been through!?\r\n\r\n\r\n"
10053085-197 = "A textbook case of getting angry at others for your own mistakes...\r\n"
10053085-199 = "Wouldn't it have been better to just show your face and ask for help...?\r\n\r\n"
10053085-200 = "I couldn't do that! I'm a Club President, you know? #nI'm in a position to be respected!"
10053085-202 = "You don't seem very respected, considering you're saying that out loud...\r\n"
10053085-203 = "So, in the end, who was that white shadow in the photo?"
10053085-204 = "Photo? Ah, that was probably me. Do you have any idea how surprised I was? #nOpening a window and screaming all of a sudden is bad for the heart."
10053085-205 = "I mean... it's a huge letdown, to say the least."
10053085-210 = "Big sis, what should we do with this woman? Should we tie her up?"
10053085-211 = "Eh, w-wait a second!?"
10053085-212 = "You're a con artist, right? And I heard you're wanted by the police.\r\n\r\n\r\n\r\n"
10053085-213 = "Do you people have no hearts!? #nAfter hearing such a heartwarming story, you're still going to say that!\r\n\r\n\r\n\r\n"
10053085-218 = "Hmm... well, just leave her be.\r\n"
10053085-219 = "I'm not that serious, you know. #nBesides, I don't even remember the names of the small-fry on the corners of wanted posters. #nAnd anyway, I'm on vacation right now."
10053085-220 = "A club president who followed her member because she was worried? I don't remember names like that.\r\n"
10053085-221 = "[s] \"Are you really sure about this?\""
10053085-222 = "What are you saying? Of course I'm not sure. By the rules, she should be arrested immediately.\r\n"
10053085-224 = "Ugh...!"
10053085-229 = "But you know."
10053085-230 = "I'm not the type to follow rules in the first place."
10053085-231 = "Oh, please keep this a secret from the older sister, okay?"
10053085-232 = "Are you letting me go?\r\n\r\n\r\n"
10053085-233 = "Letting you go? Of course not. I didn't see anything.\r\n\r\n"
10053085-234 = "But what if you betray us later...\r\n"
10053085-235 = "Hey, are we still talking about this? Try to read the room a little.\r\n\r\n\r\n\r\n"
10053085-236 = "Yes... I'm sorry...\r\n\r\n\r\n"
10053085-239 = "Um, it seems like you've been talking for quite a while...\r\n\r\n\r\n"
10053085-240 = "N-no, no, no! That, um, how should I put it!\r\n\r\n"
10053085-241 = "Ah, the Tsuchinoko! Actually, I came here to look for the Tsuchinoko too! #nSo I was thinking of staying in this mountain cabin for a while...\r\n\r\n"
10053085-242 = "Really!? Then that means we can do activities together like before!?"
10053085-243 = "W-well, that might be a bit difficult... #nAfter all, I'm living as a fugitive, and the Pseudoscience Club is under heavy scrutiny...\r\n\r\n"
10053085-247 = "But――\r\n"
10053085-248 = "I might show my face like this once in a while.\r\n"
10053085-253 = "...!\r\n"
10053085-254 = "...Perhaps.\r\n"
10053085-255 = "Maybe this adventure itself, coming all this way to search for the Tsuchinoko―― #nmight have been the real Tsuchinoko all along."
10053085-260 = "Eh, is that really how you're going to wrap this up...?\r\n\r\n"