[translation]
10053005-1 = "Prologue; Lucky Animal"
10053005-2 = "Oh my god!!!!"
10053005-4 = "And your horoscope for this week is...!"
10053005-5 = "I'm sorry... This is the worst in Chronos broadcast history!"
10053005-6 = "Three days from now—the worst day of your life will arrive!!"
10053005-11 = "Oh..."
10053005-12 = "It's over..."
10053005-19 = "@konoka0819"
10053005-20 = "[log=@konoka0819]＼(^o^)／[/log]"
10053005-23 = "@konoka0819"
10053005-24 = "＼(^o^)／"
10053005-25 = "@konoka0819"
10053005-26 = "[log=@konoka0819]My life is over[/log]"
10053005-29 = "@konoka0819"
10053005-30 = "＼(^o^)／"
10053005-31 = "@konoka0819"
10053005-32 = "My life is over"
10053005-33 = "@konoka0819"
10053005-34 = "[log=@konoka0819]Farewell, my youth[/log]"
10053005-37 = "@konoka0819"
10053005-38 = "＼(^o^)／"
10053005-39 = "@konoka0819"
10053005-40 = "My life is over"
10053005-41 = "@konoka0819"
10053005-42 = "Farewell, my youth"
10053005-43 = "@mo_channel"
10053005-44 = "[log=@mo_channel]Konoka, what's wrong?[/log]"
10053005-47 = "@konoka0819"
10053005-48 = "＼(^o^)／"
10053005-49 = "@konoka0819"
10053005-50 = "My life is over"
10053005-51 = "@konoka0819"
10053005-52 = "Farewell, my youth"
10053005-53 = "@mo_channel"
10053005-54 = "Konoka, what's wrong?"
10053005-55 = "@neko_me_me"
10053005-56 = "[log=@neko_me_me]It's that horoscope again, isn't it?[/log]"
10053005-59 = "@konoka0819"
10053005-60 = "My life is over"
10053005-61 = "@konoka0819"
10053005-62 = "Farewell, my youth"
10053005-63 = "@mo_channel"
10053005-64 = "Konoka, what's wrong?"
10053005-65 = "@neko_me_me"
10053005-66 = "It's that horoscope again, isn't it?"
10053005-67 = "@anemone"
10053005-68 = "[log=@anemone]It was a bit harsh today, wasn't it~[/log]"
10053005-71 = "@konoka0819"
10053005-72 = "Farewell, my youth"
10053005-73 = "@mo_channel"
10053005-74 = "Konoka, what's wrong?"
10053005-75 = "@neko_me_me"
10053005-76 = "It's that horoscope again, isn't it?"
10053005-77 = "@anemone"
10053005-78 = "It was a bit harsh today, wasn't it~"
10053005-79 = "@gurumin_official"
10053005-80 = "[log=@gurumin_official]Is there really a demand for a horoscope segment that's basically just insults? Really?[/log]"
10053005-83 = "@mo_channel"
10053005-84 = "Konoka, what's wrong?"
10053005-85 = "@neko_me_me"
10053005-86 = "It's that horoscope again, isn't it?"
10053005-87 = "@anemone"
10053005-88 = "It was a bit harsh today, wasn't it~"
10053005-89 = "@gurumin_official"
10053005-90 = "Is there really a demand for a horoscope segment that's basically just insults? Really?"
10053005-91 = "@anemone"
10053005-92 = "[log=@anemone]I watch it every day, but that's the first time I've seen a comment like that.[/log]"
10053005-95 = "@neko_me_me"
10053005-96 = "It's that horoscope again, isn't it?"
10053005-97 = "@anemone"
10053005-98 = "It was a bit harsh today, wasn't it~"
10053005-99 = "@gurumin_official"
10053005-100 = "Is there really a demand for a horoscope segment that's basically just insults? Really?"
10053005-101 = "@anemone"
10053005-102 = "I watch it every day, but that's the first time I've seen a comment like that."
10053005-103 = "@anemone"
10053005-104 = "[log=@anemone]Maybe it really is a first in broadcast history?[/log]"
10053005-107 = "@anemone"
10053005-108 = "It was a bit harsh today, wasn't it~"
10053005-109 = "@gurumin_official"
10053005-110 = "Is there really a demand for a horoscope segment that's basically just insults? Really?"
10053005-111 = "@anemone"
10053005-112 = "I watch it every day, but that's the first time I've seen a comment like that."
10053005-113 = "@anemone"
10053005-114 = "Maybe it really is a first in broadcast history?"
10053005-115 = "@mo_channel"
10053005-116 = "[log=@mo_channel]Isn't that a bit problematic...?[/log]"
10053005-119 = "@gurumin_official"
10053005-120 = "Is there really a demand for a horoscope segment that's basically just insults? Really?"
10053005-121 = "@anemone"
10053005-122 = "I watch it every day, but that's the first time I've seen a comment like that."
10053005-123 = "@anemone"
10053005-124 = "Maybe it really is a first in broadcast history?"
10053005-125 = "@mo_channel"
10053005-126 = "Isn't that a bit problematic...?"
10053005-127 = "@mo_channel"
10053005-128 = "[log=@mo_channel]We should probably take some measures.[/log]"
10053005-131 = "@anemone"
10053005-132 = "I watch it every day, but that's the first time I've seen a comment like that."
10053005-133 = "@anemone"
10053005-134 = "Maybe it really is a first in broadcast history?"
10053005-135 = "@mo_channel"
10053005-136 = "Isn't that a bit problematic...?"
10053005-137 = "@mo_channel"
10053005-138 = "We should probably take some measures."
10053005-139 = "@anonymous"
10053005-140 = "[log=@anonymous]Pardon the sudden intrusion. I found this exchange quite interesting...[/log]"
10053005-143 = "@anemone"
10053005-144 = "Maybe it really is a first in broadcast history?"
10053005-145 = "@mo_channel"
10053005-146 = "Isn't that a bit problematic...?"
10053005-147 = "@mo_channel"
10053005-148 = "We should probably take some measures."
10053005-149 = "@anonymous"
10053005-150 = "Pardon the sudden intrusion. I found this exchange quite interesting..."
10053005-151 = "@anonymous"
10053005-152 = "[log=@anonymous]Perhaps the \"text\" I possess could be of some assistance.[/log]"
10053005-155 = "@mo_channel"
10053005-156 = "Isn't that a bit problematic...?"
10053005-157 = "@mo_channel"
10053005-158 = "We should probably take some measures."
10053005-159 = "@anonymous"
10053005-160 = "Pardon the sudden intrusion. I found this exchange quite interesting..."
10053005-161 = "@anonymous"
10053005-162 = "Perhaps the \"text\" I possess could be of some assistance."
10053005-163 = "@anonymous"
10053005-164 = "[log=@anonymous]A [ruby=cryptid]creature[/ruby] long considered a symbol of good fortune.[/log]"
10053005-167 = "@mo_channel"
10053005-168 = "We should probably take some measures."
10053005-169 = "@anonymous"
10053005-170 = "Pardon the sudden intrusion. I found this exchange quite interesting..."
10053005-171 = "@anonymous"
10053005-172 = "Perhaps the \"text\" I possess could be of some assistance."
10053005-173 = "@anonymous"
10053005-174 = "A [ruby=cryptid]creature[/ruby] long considered a symbol of good fortune."
10053005-175 = "@anonymous"
10053005-176 = "[log=@anonymous]Though long thought not to exist...[/log]"
10053005-179 = "@anonymous"
10053005-180 = "Pardon the sudden intrusion. I found this exchange quite interesting..."
10053005-181 = "@anonymous"
10053005-182 = "Perhaps the \"text\" I possess could be of some assistance."
10053005-183 = "@anonymous"
10053005-184 = "A [ruby=cryptid]creature[/ruby] long considered a symbol of good fortune."
10053005-185 = "@anonymous"
10053005-186 = "Though long thought not to exist..."
10053005-187 = "@anonymous"
10053005-188 = "[log=@anonymous]In recent years, there have been successive sightings in a certain region.[/log]"
10053005-192 = "A... symbol... of good fortune?"
10053005-194 = "Rest assured!#nIf you keep a lucky creature by your side, you will be able to avoid your misfortune!!"
10053005-195 = "Your lucky animal is—!"
10053005-198 = "@anonymous"
10053005-199 = "[log=@anonymous]Everyone... are you familiar with the \"Tsuchinoko\"?[/log]"
10053005-202 = "It's a snake!!!!"