[translation]
10053080-1 = "Episode 8: The Alien 'Grey'"
10053080-3 = "Everyone, sorry to keep you waiting. The results of the analysis are in."
10053080-4 = "...Wait, where's Konoka?\r\n"
10053080-5 = "She's locked herself in her room, claiming it's a ghost.\r\n"
10053080-6 = "Could you go bring her here? To put it simply—that was no ghost."
10053080-7 = "Konoka, you heard him, right!? Get down here right now!!\r\n"
10053080-8 = "I'd prefer if you didn't scold her too much. #nKonoka is delicate, so we must protect her."
10053080-9 = "...Are you serious?\r\n"
10053080-14 = "It’s really not a ghost...?\r\n\r\n\r\n\r\n\r\n"
10053080-15 = "I'll explain the details while looking at the photo. First, take a look at this.\r\n\r\n\r\n"
10053080-20 = "......\r\n\r\n\r\n\r\n\r\n"
10053080-21 = "......\r\n\r\n\r\n"
10053080-22 = "...I don't see anything, though?\r\n\r\n\r\n\r\n"
10053080-27 = "Yes, that's what I thought at first, too."
10053080-28 = "But, look at this corner. If you zoom in on the grass—\r\n"
10053080-29 = "A whitish shadow...?"
10053080-33 = "This was taken right after Konoka opened the window. #nThe shape is distorted because it's out of focus, but I am certain."
10053080-34 = "This afterimage must be the mastermind behind the incident, the unknown entity that has been watching us... #nIt must be the true identity of X!\r\n\r\n"
10053080-35 = "And... though it's still just a hypothesis, there is a high probability that its identity is—"
10053080-37 = "A 'Grey'!\r\n\r\n"
10053080-43 = "No, wouldn't it be more like 'White'?\r\n\r\n\r\n\r\n"
10053080-44 = "A 'Grey' is a type of alien. It's not about the color.\r\n\r\n"
10053080-45 = "So, what do you mean by saying that thing is a Grey?\r\n"
10053080-50 = "Your doubt is reasonable. You probably think it's absurd. But please, hear me out until the end.\r\n"
10053080-51 = "First, someone was peeking from outside the window while we were sleeping. #nThis is one of the typical precursor phenomena of an alien abduction."
10053080-52 = "Many victims testify that they felt like they were being watched, but they could never catch a glimpse of the actual figure. #n...Don't you think the current situation matches that perfectly?\r\n"
10053080-53 = "No, isn't that just a persecution complex...?\r\n"
10053080-54 = "But we actually witnessed it. #nIt's impossible for three people, including the teacher, to have a shared delusion at the same time."
10053080-55 = "...Is that so?"
10053080-56 = "[s1] \"I'm not sure if it's really an alien, but...\" \r\n[s2] \"It's certain that someone was there.\""
10053080-59 = "But, there's also the possibility of mass hysteria.\r\n"
10053080-60 = "That is exactly why this photo serves as evidence. This is undeniable physical evidence. #nIt's too clearly defined to be dismissed as light reflection or noise.\r\n"
10053080-61 = "And I have arrived at another hypothesis."
10053080-62 = "Aliens possess the technology to move at supersonic speeds without making a sound. #nIn fact, it's a common feature mentioned in many UFO sightings.\r\n"
10053080-63 = "Does that mean... an alien was watching us, and the moment we opened the window, it escaped at super speed?"
10053080-64 = "And the reason there was no sound was because of that alien technology?"
10053080-65 = "At this moment, there is no other explanation.\r\n\r\n"
10053080-67 = "No, there definitely is! That's quite a leap in logic!\r\n"
10053080-68 = "For starters, you said the Tsuchinoko was an alien reconnaissance drone, right? #nIf they wanted to monitor us, they could just use that. Please, let's get our world-building consistent first!!\r\n\r\n\r\n"
10053080-73 = "So that means it's not a ghost? Phew, what a relief～\r\n"
10053080-77 = "Honestly, as long as it's not a ghost, I don't care what it is...\r\n"
10053080-78 = "But think about it carefully. #nSince we arrived here, the events that have occurred have all been paranormal phenomena that are difficult to explain."
10053080-79 = "Isn't it more rational to think there is one major cause rather than thinking each has a separate reason?"
10053080-80 = "I understand what you're trying to say, but...\r\n"
10053080-84 = "No, I still don't believe it! I won't believe it until I see an alien with my own eyes!\r\n"
10053080-85 = "You're the same, right, Teacher!? You're on my side, aren't you!?"
10053080-86 = "[ns3] \"For now, if there is someone nearby.\" \r\n[ns4] \"We should report this to Valkyrie first.\""
10053080-90 = "That's true, I suppose. Whoever it is, it's definitely dangerous.\r\n"
10053080-91 = "Wait, that's dangerous. If we report it carelessly, the General Student Council might try to destroy the evidence. #nJust like the UFO evidence that was supposedly reported in the past."
10053080-92 = "Don't bring conspiracy theories into this! Forget it, I'll make the call."
10053080-96 = "......"
10053080-101 = "Huh... it's not connecting... Is the plug in properly?"
10053080-102 = "It's fine, though?"
10053080-103 = "Then why...?"
10053080-109 = "Could it be...!?\r\n\r\n"
10053080-116 = "...As I thought. It's exactly the worst-case scenario I anticipated."
10053080-121 = "Director, what's that in your hand?"
10053080-122 = "It's the phone line."
10053080-123 = "No, to be precise—it's a 'cut' phone line."
10053080-124 = "...Huh?\r\n"
10053080-125 = "The fact that the phone line was cut means we've reached the final stage—in other words!"
10053080-135 = "Was it already too late...!\r\n"
10053080-140 = "Hey, wait a minute!? We were able to cross it just a moment ago!\r\n\r\n"
10053080-141 = "Why is the bridge broken!?\r\n\r\n"
10053080-145 = "Everyone, calm down and listen."
10053080-146 = "My deduction is that someone intentionally destroyed this bridge."
10053080-147 = "It must be the same culprit who cut the phone line, the entity that has been watching us, or their accomplice.\r\n"
10053080-148 = "The goal is clear. To isolate us."
10053080-149 = "Why? Who would do this and for what purpose!?\r\n"
10053080-150 = "...Because we are looking for the Tsuchinoko."
10053080-151 = "If the Tsuchinoko is an alien reconnaissance drone, then we, the 'Investigation Team X' who are trying to expose its true identity, are the greatest threat to the aliens!"
10053080-152 = "Perhaps we are closer to the core of the Tsuchinoko mystery than anyone in history...!\r\n"
10053080-153 = "Can we please stop pushing that narrative...\r\n"
10053080-155 = "W-what was that light!?"
10053080-156 = "It's a UFO! A UFO has appeared!"
10053080-157 = "N-no way... is it really an alien...?"
10053080-160 = "...No, that looks familiar.\r\n"
10053080-161 = "Ah, it's a flare.\r\n"
10053080-162 = "Hmm?\r\n"
10053080-165 = "So the rumors that the Vice Director of the Public Safety Bureau loves the occult were true!\r\n\r\n"
10053080-166 = "Let's go! Show them what we're really made of!\r\n"
10053080-171 = "What is this, what's going on?\r\n\r\n"
10053080-172 = "They don't... look like aliens to me.\r\n\r\n"
10053080-173 = "Obviously! What are we going to do!?\r\n"
10053080-178 = "...Hmm, I see. Finally, things are starting to make sense.\r\n"
10053080-182 = "You guys! Arrest every single one of them!!!!"