[translation]
1013002-1 = "Everyone's Senior"
1013002-3 = "You really came, Sensei..."
1013002-4 = "[s] \"Reconstruction has really progressed, hasn't it?\""
1013002-5 = "Yes. Little by little, though."
1013002-6 = "[s] \"I don't know if I should say this, but...\""
1013002-7 = "It's alright. What is it?"
1013002-8 = "[s] \"It feels... nice.\""
1013002-9 = "...I suppose so."
1013002-10 = "I think so too. But, I'm still not quite used to it, I suppose."
1013002-11 = "We are in a time of change right now, aren't we?"
1013002-12 = "...Hm? Are you on patrol?"
1013002-13 = "..."
1013002-14 = "Well, I can only say that a lot has really happened..."
1013002-15 = "I've ended up in a role similar to what other schools call a Prefect Team leader."
1013002-16 = "In terms of protecting Arius's order, it's not much different from what I've been doing until now."
1013002-17 = "Though it's a bit more relaxing now that I don't have to worry about attacks from the outside."
1013002-18 = "...Why, you ask?"
1013002-19 = "Hehe, it's simple."
1013002-20 = "There aren't many people who would go out of their way to come to Arius and cause trouble."
1013002-21 = "In more ways than one."
1013002-27 = "[ns] \"I heard an explosion just now!?\""
1013002-28 = "Let's go check it out."
1013002-32 = "What is all this noise?"
1013002-37 = "Ah, Senior. It's nothing major."
1013002-38 = "That's right, we were just—"
1013002-39 = "Having an Arius-style 'discussion'."
1013002-41 = "Ah... I see."
1013002-45 = "[ns1] \"Arius-style...\"\n[ns2] \"Discussion...?\""
1013002-49 = "You don't know, Sensei?"
1013002-50 = "I suppose you are an outsider, after all."
1013002-51 = "In Arius, when we 'persuade' someone, we value both words and actions!"
1013002-55 = "[ns] \"I understand the words part, but actions too...?\""
1013002-56 = "Yes! That's why we..."
1013002-57 = "When our opinions clash!"
1013002-58 = "We discuss whose 'actions' have more 'persuasive power'!"
1013002-59 = "So, do you admit that the era belongs to 5.56mm rounds?"
1013002-60 = "No way! It's obviously the punchy 7.62mm rounds."
1013002-61 = "Huh? The squad uses 5.56mm, don't they?"
1013002-62 = "They get special supplies, that's why!#nWe should just stick with 7.62mm!"
1013002-63 = "7.62mm is strong, sure, but the recoil makes it impossible to aim!"
1013002-64 = "It's a waste of time to aim slowly. Isn't rapid fire better?"
1013002-65 = "That's just what people like you say!"
1013002-66 = "It's a lie that 7.62mm has huge recoil!#nIf the design and flash hider are done right—"
1013002-67 = "Also, it's just bulky, right? Can you carry 300 rounds of 7.62mm?"
1013002-68 = "Whether you can aim or not depends on the situation anyway, so it's better to just keep firing!"
1013002-69 = "Do you think we have the budget for that kind of ammo!?"
1013002-76 = "Alright, that's enough, both of you."
1013002-78 = "Senior, but!"
1013002-79 = "Senior!!"
1013002-81 = "I understand both of your points. #nBoth arguments are correct. It's a difficult problem."
1013002-82 = "Could I hear the circumstances of how this conversation started?"
1013002-84 = "Th-that is..."
1013002-85 = "We were just wondering which ammo is better for protecting our Arius..."
1013002-87 = "I see. We all share the same desire to protect the academy. #n...That is the important fact."
1013002-88 = "Even though everyone has the same aspirations, just because your ways of thinking differ..."
1013002-89 = "Can we stop having these extreme 'Arius-style discussions' now?"
1013002-90 = "Infighting will only lead to our ruin."
1013002-92 = "...You're right."
1013002-93 = "Yeah... we aren't the old Arius anymore, after all..."
1013002-95 = "I would be happy if you could remember that whenever you're about to start an argument."
1013002-96 = "After all, 'discussions' like that cost a lot in ammo."
1013002-98 = "I'm sorry, Senior..."
1013002-100 = "Hehe. But, I'm happy that both of you care so much about the academy."
1013002-101 = "We will continue to go through trial and error. #nThere might be times when you want to do things the old way."
1013002-102 = "But let's try to face things together using new methods as much as possible. #nI will try my best too."
1013002-103 = "Please call me whenever you're in trouble."
1013002-105 = "...!#nYes, Senior...!"
1013002-106 = "Understood, thank you, Senior!"
1013002-111 = "Phew..."
1013002-112 = "[s] \"You said that well.\""
1013002-113 = "Y-you think so?"
1013002-114 = "Actually, I've only recently become able to have conversations like this..."
1013002-115 = "Back then, I just turned a blind eye to everything."
1013002-116 = "...But, it is indeed an important topic. #nBoth types of ammo aren't compatible, and 5.56mm is the mainstream outside."
1013002-117 = "Still, we can't just scrap the 7.62mm we've been using until now..."
1013002-118 = "My own gun is also customized to 7.62mm for supply reasons."
1013002-119 = "..."
1013002-120 = "But, I feel a little relieved."
1013002-121 = "Honestly, I thought everyone would hate me for taking on this role."
1013002-122 = "Yet, everyone followed me... I'm truly happy."
1013002-123 = "[s3] \"That just shows how reliable of a senior you are, Atsuko.\"\n[s4] \"Because you're the one who's been leading everyone, Atsuko.\""
1013002-126 = "Hehe. You won't get anything even if you praise me that much, you know?"
1013002-127 = "...But, I do feel guilt and remorse sometimes."
1013002-128 = "I can listen to them or be there for them as much as I want, but..."
1013002-129 = "..."
1013002-130 = "I feel like it's not a fundamental solution in the end."
1013002-131 = "I think it's just a temporary comfort."
1013002-132 = "[s5] \"I understand.\"\n[s6] \"Maybe you need someone to talk to as well, Atsuko.\""
1013002-135 = "Eh? What's with the sudden..."
1013002-136 = "Certainly, maybe someone to 'watch the watchers' is necessary."
1013002-137 = "I understand, but... still..."
1013002-138 = "For someone to listen to my problems..."
1013002-139 = "[s7] \"That's what Sensei is here for.\"\n[s8] \"I have other work, but...\""
1013002-142 = "I see. So this is that thing I've heard rumors about."
1013002-143 = "The one where you lure students in with sweet words, making it so they can never go back to how they were—"
1013002-144 = "Um, I think... was it a Chronos Channel special? I think they said that..."
1013002-145 = "[s] \"N-no... that's a total misunderstanding...\""
1013002-146 = "Y-you don't have to be so depressed..."
1013002-147 = "..."
1013002-148 = "Understood. Then, if there's an opportunity next time, please do."
1013002-149 = "When I'm with you, Sensei, I end up talking about all sorts of things."
1013002-150 = "Hehe... is this also one of your 'tactics'?"
1013002-151 = "[s] \"N-no... that's a total misunderstanding...\""
1013002-152 = "...Huh? I feel like I heard that just a moment ago."
1013002-154 = "(Feeling like I somehow lost, I returned to Schale...)"