[translation]
1013708-1 = "A Certain Detective's Recovery"
1013708-2 = "(Worried about Konoka catching a cold, I decided to give her a visit.)"
1013708-6 = "[ns] \"Excuse me~.\""
1013708-7 = "Ugh... who is it... jeez..."
1013708-8 = "I told you I don't have a TV!!"
1013708-9 = "*Cough*, I broke it when the team I was rooting for lost..."
1013708-10 = "I believe I told you I'd arrest you if you came again, *cough*?"
1013708-11 = "[s1] \"C-Calm down, Konoka!\"\n[s2] \"It's me, it's me!\""
1013708-14 = "E-Eh!?"
1013708-15 = "Sensei? Ah, please come in. The door is unlocked!"
1013708-19 = "[ns] \"You left it unlocked!?\""
1013708-20 = "*Cough*, if a burglar comes in, I can catch them red-handed."
1013708-21 = "And I can meet my quota, and it's convenient in a lot of ways."
1013708-22 = "[s] \"A burglar in the Valkyrie dorms...!?\""
1013708-23 = "Either they're fearless, or I just don't understand how criminals think~"
1013708-24 = "Anyway, what can I do for... *cough*..."
1013708-25 = "[s] \"I heard you caught a cold, so I came to visit.\""
1013708-26 = "How did you find out!?"
1013708-27 = "[s3] \"Because you told me on Momotalk, Konoka...\"\n[s4] \"You said you caught a cold and were taking the day off, right?\""
1013708-30 = "*Cough*, h-huh...?"
1013708-32 = "Aah, *cough*... that Momotalk."
1013708-33 = "I thought I sent that to my kouhais... sorry."
1013708-34 = "I can't believe you came out to visit me... I'm really sorry."
1013708-35 = "[s] \"Not at all! I'm happy to come.\""
1013708-36 = "Ugh, thank you.#nBut, I'm feeling a little out of it right now..."
1013708-37 = "This is my first time having someone visit me when I'm sick,#nso I don't know what to do..."
1013708-38 = "[s5] \"Have you eaten yet?\"\n[s6] \"Should I make some porridge?\""
1013708-41 = "Porridge... ah, come to think of it, I haven't eaten anything yet."
1013708-42 = "Umm... *cough*, extra garlic tonkotsu, no vegetables, with extra chili oil please."
1013708-43 = "[s] \"I'm not a ramen shop, you know!?\""
1013708-44 = "Huh?"
1013708-47 = "Phew, thank you for the meal."
1013708-48 = "It was easy to eat, like ramen without the noodles.#nI should've put more garlic in."
1013708-49 = "[s] \"Well, you were able to eat it, so I guess this is fine...?\""
1013708-50 = "*Cough*, *cough*, you're exaggerating."
1013708-51 = "It's just a cold. If I just exercise a bit—"
1013708-56 = "[ns] Touching Konoka's forehead."
1013708-58 = "!!!"
1013708-59 = "Hyah..."
1013708-63 = "...*Cough*."
1013708-64 = "...E-Eh?"
1013708-65 = "[s] \"Your fever is high. You should lie down.\""
1013708-66 = "Ah..."
1013708-67 = "Y-Yeah..."
1013708-71 = "[ns] \"How is it? Still feeling sick?\""
1013708-72 = "Ah, umm...!"
1013708-73 = "Well... it might still be a little tough for me."
1013708-74 = "A-Ah-, it hurts- it hurts. *Cough*, *cough*."
1013708-75 = "[s] \"I'll stay by your side until you fall asleep.\""
1013708-76 = "Y-Yes..."
1013708-77 = "Ah, if that's the case... please... close the door."
1013708-78 = "If a burglar comes right now, I won't be able to protect you, Sensei..."
1013708-79 = "[s] \"Yeah. Oh right, should I read out today's fortune?\""
1013708-80 = "Ah, no. I'm okay."
1013708-81 = "Today has already turned into the best day ever."
1013708-83 = "(After that, I stayed by Konoka's side and continued to take care of her.)"