[translation]
1013706-1 = "バディ"
1013706-2 = "（バスに乗って、コノカと会うべく田舎の方へやってきた）"
1013706-4 = "先生、こっちっす～！"
1013706-5 = "ご足労いただき感謝っす。#nどうしてもバディが必要で……。"
1013706-6 = "なのにヴァルキューレで定期訓練があって、一緒に来てくれる子がいなかったんすよ。"
1013706-7 = "[s] \"何をすればいいの？\""
1013706-8 = "聞き込み捜査っす！"
1013706-9 = "逃走中の容疑者がいるんすけど、ここへ向かうバスに乗ったらしくて。"
1013706-10 = "余所者だから目立つでしょうし、聞き込みすれば一発だと思うっす！"
1013706-11 = "午後には雨降るらしいんで、さっさと終わらせて帰るっすよ！"
1013706-12 = "しゅつど～！"
1013706-25 = "はぁ……。"
1013706-26 = "誰も見てないって……どういうことっすか？"
1013706-27 = "これ以上は聞き込みしても微妙っすよね……。"
1013706-28 = "もしかして、山に逃げてたり……？#n木の根をかき分けてでも探して見せるっす！"
1013706-29 = "[s] \"山の動物が可哀想だからやめて！\""
1013706-30 = "もちろんちゃーんと元通りにはするっすよ。#nというかただの例えっすし……。"
1013706-31 = "時間も遅いし、急いで決着つけないと――"
1013706-36 = "はぇ？"
1013706-37 = "うぎゃーっ！冷たっ！！"
1013706-38 = "あっちで雨宿りできそうっす！#nああ、もーっ！！"
1013706-41 = "（コノカと一緒に急いで雨をしのげる場所へ向かった）"
1013706-42 = "（再三の失敗に肩を落としてたコノカは、唐突に上着を脱ぎ始めた）"
1013706-45 = "[wa:2172]― [log=코노카]Ahh-ah, [wa:1075]I'm soaking wet...[/log]"
1013706-47 = "― [log=코노카]Uuu...[wa:570]it's cold[/log]"
1013706-50 = "[wa:1586]― [log=코노카]it[wa:162] started raining down, huh[/log]"
1013706-52 = "― [log=코노카]They said it wouldn't stop until tonight... [wa:2261]Sigh...[/log]"
1013706-55 = "― [log=코노카]Well, [wa:994]I guess it was just what I needed [wa:1173]to cool my head down.[/log]"
1013706-58 = "[ns] \"Are you okay? Have you calmed down?\""
1013706-59 = "[wa:517]― [log=코노카]Huh? [wa:973]Ah, yeah, [wa:860]I guess.[/log]"
1013706-61 = "― [log=코노카]It would be a lie [wa:487]if I say [wa:995]I'm not frustrated.[/log]"
1013706-64 = "― [log=코노카]All that effort [wa:273]went to waste, [wa:1480]now I ended up soaking wet...[/log]"
1013706-67 = "[wa:556]― [log=코노카]But, [wa:816]it's just like the fortune teller [wa:481]predicted.[/log]"
1013706-69 = "― [log=코노카]Having [wa:217]my partner right by my side [wa:1039]made it [wa:425]a great day.[/log]"
1013706-72 = "― [log=코노카]...Thanks to you, [wa:1002]Sensei.[/log]"
1013706-75 = "[wa:870]― [log=코노카]So, [wa:934]if I had to say...[/log]"
1013706-77 = "― [log=코노카]I'm happy.[/log]"
1013706-80 = "― [log=코노카]...Ah, [wa:376]no, [wa:607]I mean![/log]"
1013706-82 = "― [log=코노카]I mean [wa:337]I'm lucky and happy that [wa:1249]we get to take shelter [wa:490] from the rain [wa:430]like [wa:315]this![/log]"
1013706-85 = "― [log=코노카]T-[wa:456]That's all... [wa:806]I meant...[/log]"
1013706-88 = "……。"
1013706-89 = "あー……ええと、幸せっていうのは。#nその、最悪は免れたから、で……。"
1013706-90 = "特に深い意味は――"
1013706-95 = "おっと、先客がいたな。"
1013706-96 = "アツアツの中わりぃな。急に降ってきたもんだからさぁ。"
1013706-97 = "……？"
1013706-98 = "なんだ、お前も追われてんのか？#nうちらとご同類っぽい感じするけど。"
1013706-99 = "あ、そうだ。この近くでサツ見なかったか？"
1013706-103 = "マジか……。"
1013706-105 = "[ns] \"ヴァルキューレなら、ここに……。\""
1013706-107 = "えっ……。"
1013706-108 = "あ～！急に滝行がしたくなってきたなぁ！#nそれじゃお先に！！"
1013706-112 = "待てぇー！！！"
1013706-116 = "おとり捜査とか卑怯だろ！！"
1013706-117 = "はい、罪状二倍ィ！"
1013706-118 = "なんでー！？"
1013706-119 = "アツアツ妨害罪ってことで！"
1013706-121 = "（雨の中、不良に向かって駆け出したコノカはあっという間に容疑者を逮捕した）"
1013706-122 = "（帰り道、コノカはバスに揺られながら窓の外を眺めていた）"
