[translation]
1013705-1 = "A Detective's Appearance"
1013705-2 = "Yo, Sensei."
1013705-3 = "Ah, you're not following me right?#nIt'd be bad if anyone found out."
1013705-4 = "[s1] \"I think we're fine, but...\"\n[s2] \"What is this all about...?\""
1013705-7 = "We stand out here, let's go inside."
1013705-8 = "Oh, everything you're about to see is top secret, got it?"
1013705-9 = "Please don’t let this get out to anyone."
1013705-10 = "[s] \"Y-Yeah...!\""
1013705-15 = "Hey, who's there? You're looking a lot more neater since the last time I saw you."
1013705-16 = "Don't be so cold. It's me, it's me."
1013705-17 = "I brought a customer.#nThis customer's lips are sealed, so it's fine."
1013705-18 = "This place remains a hidden gem known only to those in the know."
1013705-19 = "There you go, making things up again...!!"
1013705-24 = "I'm running a clothing business here!#nWhat's the point of making it a secret spot!!!"
1013705-25 = "Now, now, I buy a ton from you to make up for it, don't I?"
1013705-26 = "I can't survive on just one person's purchases!!"
1013705-28 = "[ns] \"Is this... an Aloha shirt shop?\""
1013705-29 = "Yep! If you want an Aloha shirt, this is the place to go~"
1013705-30 = "The owner got everything from vintage to brand new and there’s a wide variety of colors…#nIt really feels like a hidden gem!"
1013705-31 = "I'm not hiding it!#nYou're the one keeping it a secret!"
1013705-32 = "Come on now... I'll buy enough for 10 people, so please forgive me~"
1013705-33 = "If more people come, the rare shirts will sell out, won't they?"
1013705-34 = "You're SCHALE's Sensei, right?#nPlease! I beg you, advertise my shop!"
1013705-35 = "I won't let him~!#nI'll absolutely stop the information from leaking!"
1013705-36 = "Heh... how is she a cop..."
1013705-37 = "Sigh, but well... I guess.#nThere aren't many folks who understand the appeal of an Aloha shirt."
1013705-38 = "Like the little lady says, it does help that she only tells enthusiasts who get it, but..."
1013705-39 = "You don't seem to mind it too much.#nNow then, let's see what we've got here~"
1013705-40 = "Which one~~ should I choose~~"
1013705-44 = "Hmm hmm~~ Police dispatch~~ Helmet Gang arrest~~♪"
1013705-48 = "You are~~ finished~~♪"
1013705-49 = "Hmm, I like the color scheme, but...#nthe balance is just a little off."
1013705-50 = "[ns3] \"You really know your stuff when it comes to Aloha shirts, Konoka.\"\n[ns4] \"Have you always liked them?\""
1013705-53 = "Not always, nah."
1013705-54 = "I wasn't really interested in them.#nIf anything, I might've even disliked them."
1013705-55 = "I only started getting interested after coming to Valkyrie."
1013705-56 = "Oh, my~?#nAre you curious about how I came to love Aloha shirts?"
1013705-57 = "[s] \"...Ugh! Was I that obvious?\""
1013705-58 = "Haha! I may not look it, but I am the Deputy Director of the Public Security Bureau."
1013705-59 = "I wonder when it was..."
1013705-60 = "Maybe around the time I enrolled.#nI heard there was an academy where you get praised for beating up delinquents, so I joined."
1013705-61 = "And, well, since fighting was all I knew how to do, they assigned me an instructor.#nMy instructor was someone who didn't talk much, but was really preachy..."
1013705-62 = "We got a report and headed to the scene together...#nbut it was a trap. We were ambushed by a group... and they beat the crap out of me."
1013705-63 = "We managed to win, but my uniform got torn to shreds.#nWell, by the end, they were scared enough that they tried to call the cops themselves."
1013705-64 = "[s] \"They beat up a cop, then tried to call the cops...?\""
1013705-65 = "Yeah, well... my instructor had a scary face and was insanely strong..."
1013705-66 = "So anyway, I couldn't exactly go back looking like that, and while looking for an open store, we found this place."
1013705-67 = "Everywhere you looked, it was Aloha, Aloha, Aloha!#nI laughed so hard!"
1013705-68 = "At first, I thought you were wearing an Aloha shirt with that kind of pattern, your clothes were so muddy and messed up, little lady."
1013705-69 = "Ah, hahaha!#nHaving an eyewitness account makes it feel real!"
1013705-70 = "So, I had no choice but to put on an Aloha shirt and go home with my instructor, and I realized it actually suited me.#nI've been wearing them ever since! It's handy during investigations, too."
1013705-74 = "Ah! This is it!#nI've been wanting one with a duck pattern!"
1013705-75 = "They have another one here, so I'll give it to you, Sensei.#nIt's a present from me!"
1013705-76 = "Boss, I'll take two of these, please!"
1013705-77 = "You got it~#nIt looks good on you, Sensei."
1013705-78 = "[s] \"How much is it?\""
1013705-79 = "Don't worry about the payment.#nThe detective missy here prepaid for about 300 shirts because she said carrying a wallet around is a hassle."
1013705-80 = "Please come again!#nAnd please, do advertise the shop!"
1013705-82 = "Haaah! Shopping is the best! Ehehe!"
1013705-83 = "Sensei, the secret... absolutely keep it safe, okay?#nWe'll go together again sometime!"
1013705-84 = "Man~ thinking about the old days after so long..."
1013705-85 = "I really should've taken a picture of my instructor in her Aloha shirt back then..."
1013705-86 = "[s] \"Could the instructor you were talking about be...?\""
1013705-87 = "Yeah, it's exactly who you're thinking of.#nI mean, who else could it be."
1013705-88 = "A delinquent and a mad dog.#nThe higher-ups who came up with that combo back then were seriously insane."
1013705-89 = "Well then, I'll be taking my leave~#nOh! Make sure to wash the shirt once before wearing it!"
1013705-90 = "See ya~!"
1013705-92 = "(After that, Konoka disappeared down the alleyway with a spring in her step.)"