[translation]
1013408-1 = "The Hero Has Returned?"
1013408-2 = "(Some time had passed since the incident on the Steel Continent.)"
1013408-3 = "(I headed to the address Aris had sent me.)"
1013408-6 = "(There's such a huge crowd.)"
1013408-7 = "(It seems a famous gaming event is being held here.)"
1013408-16 = "(It's going to be hard to find Aris in this crowd.)"
1013408-17 = "(I messaged Aris with my current location.)"
1013408-22 = "Sensei, where are you?"
1013408-23 = "Aris is right here!"
1013408-24 = "[ns1] \"Aris?\"\n[ns2] \"Over here!\""
1013408-27 = "Ah, I found Sensei!"
1013408-28 = "Aris is coming over! Please wait!"
1013408-33 = "Ta-da!"
1013408-34 = "Sensei has joined the party!"
1013408-35 = "[s3] \"That appearance...\"\n[s4] \"Abi-Eshuh!?\""
1013408-38 = "That's right! Hero Aris, fully restored—"
1013408-46 = "Wait, weren't you just flying!?"
1013408-47 = "How does that even work!? That's way beyond just cosplay!?"
1013408-48 = "What game is that from? Which booth is it?"
1013408-50 = "Oh no! I forgot I was in the middle of running away!"
1013408-51 = "Sensei, I'll explain later! Let's run!"
1013408-57 = "So, the Game Development Department decided to participate with a new game."
1013408-58 = "After thinking about how to stand out more than the other booths—"
1013408-59 = "The plan worked. It was a huge success! #nThough, maybe it worked a little too well..."
1013408-60 = "Everyone is ignoring the booth and is only interested in Aris!"
1013408-61 = "This is counterproductive!"
1013408-62 = "[s5] \"Well, you are standing out and flying around...\"\n[s6] \"I might end up staring too.\""
1013408-65 = "Even you, Sensei!?"
1013408-66 = "At this rate, I'll never be able to go back to the clubroom!"
1013408-67 = "Ah, I found her!!"
1013408-68 = "Um, if you don't mind, could you please pose for us?"
1013408-69 = "Oh no! They noticed me!"
1013408-76 = "P-please talk to me one at a time!! Oh no!"
1013408-82 = "(The requests continued non-stop until the very last minute of the event.)"
1013408-90 = "We finally finished..."
1013408-91 = "I feel like... my memories are all a blur..."
1013408-92 = "[s7] \"Good work...\"\n[s8] \"I only remember taking pictures the whole time too...\""
1013408-97 = "[ns9] \"...Oh, come to think of it!\"\n[ns10] \"Didn't Abi-Eshuh get destroyed?\""
1013408-100 = "I was so busy I forgot to explain!"
1013408-101 = "Ta-da! Hero Aris, fully restored!"
1013408-102 = "—or so I'd like to say."
1013408-103 = "This is a replica."
1013408-104 = "I had them faithfully recreate the original."
1013408-105 = "You see... before leaving the Steel Continent, I found the remains of Abi-Eshuh."
1013408-106 = "Though, by remains, I mean a palm-sized fragment..."
1013408-107 = "[s11] \"So you brought it back with you.\"\n[s12] \"Abi-Eshuh is a friend, after all.\""
1013408-112 = "...Yes!"
1013408-113 = "So, I thought maybe... and showed it to everyone at Millennium."
1013408-123 = "That said, they told me it was impossible to restore it from a palm-sized piece."
1013408-124 = "But instead, they agreed to recreate it as close to the original as possible!"
1013408-125 = "Thanks to them, Abi-Eshuh has regained its original form!"
1013408-126 = "...Even if only some of the parts are original."
1013408-127 = "Also, since it's just a replica, its output is significantly lower than before. #nI can't do long-distance flights or high-mobility maneuvers anymore."
1013408-128 = "It's not as durable as it used to be, so they made sure to tell me not to use it for combat."
1013408-129 = "[s13] \"So that's why it's a replica.\"\n[s14] \"It's a shame, since you managed to recreate it.\""
1013408-132 = "?"
1013408-133 = "Aris doesn't think it's a shame at all!"
1013408-134 = "There are many heroes whose powers are sealed away after the Demon King is defeated. #nIt's actually a common ending."
1013408-135 = "Besides..."
1013408-142 = "Today, I stood in front of many people wearing Abi-Eshuh."
1013408-143 = "And everyone looked at Abi-Eshuh and said it was 'cool' and that they 'liked it'."
1013408-144 = "That is much, much more wonderful than flying through the sky or defeating a Demon King."
1013408-145 = "That's why Aris was so happy today!"
1013408-147 = "(Holding hands with Aris, we returned to the Game Development Department clubroom.)"
1013408-148 = "(On the way back, people kept asking to take photos of us.)"