[translation]
1013403-1 = "The Starting Town"
1013403-3 = "Um, Sensei... what is this?"
1013403-4 = "[ns] \"It's special training!!\""
1013403-5 = "Uh, but this is..."
1013403-6 = "Just a normal game... right?"
1013403-7 = "[ns] \"It's special training!!\""
1013403-8 = "Oh, no!"
1013403-9 = "Sensei has broken down!"
1013403-10 = "[s1] \"I was thinking about it.\"\n[s2] \"I don't think Aris is quite used to the Hero's armor yet.\""
1013403-15 = "[ns3] \"So, I thought we should start by getting you comfortable in it.\"\n[ns4] \"Let's get you to the point where you can wear the armor without feeling tense!\""
1013403-18 = "Getting comfortable in it...?"
1013403-19 = "Are you saying I just need to wear the Hero's armor and play a game?"
1013403-23 = "Hmm..."
1013403-24 = "Aris doesn't really understand how that counts as training."
1013403-28 = "Sensei? Why are you turning off the lights?"
1013403-29 = "Huh...? Turning off the lights makes it more immersive and fun...?"
1013403-30 = "Aris thinks so too, but..."
1013403-31 = "Sensei always said that playing games in the dark is bad for your eyes!"
1013403-32 = "[s5] \"Right, usually that's true.\"\n[s6] \"But today is special training.\""
1013403-35 = "...!"
1013403-36 = "Aris feels a little excited now!"
1013403-37 = "It feels just like when I'd stay up late playing games and sneak out to the convenience store!"
1013403-41 = "...Ah! That was supposed to be a secret."
1013403-42 = "A-anyway, the game! What should I play?"
1013403-43 = "Huh, anything I like...?"
1013403-44 = "Aris has many favorite games!"
1013403-50 = "...They're all such masterpieces, I can't choose!"
1013403-54 = "For example, this one!"
1013403-55 = "This is a game where you hunt dragons with a giant weapon!"
1013403-56 = "You hunt dragons to get materials, craft stronger weapons, and then hunt even stronger dragons!"
1013403-57 = "Of course, just having good equipment doesn't make you strong immediately!#nIt's meaningless unless the player themselves gets stronger!"
1013403-61 = "This might be the perfect game for Aris right now!"
1013403-62 = "[s] \"So, shall we go with that one?\""
1013403-63 = "...It's true, Aris does like this game."
1013403-64 = "But I don't think now is the right time. The playtime is just so long..."
1013403-65 = "I think I'll keep looking for a little longer."
1013403-66 = "...Oh, this one!"
1013403-70 = "This game is famous for being incredibly difficult!"
1013403-71 = "There are traps that kill the player instantly all over the field..."
1013403-72 = "Even if you manage to reach the boss, you'll lose in an instant without prior knowledge!#nYou have to challenge it over and over again, and the player has to grow to clear it!"
1013403-73 = "That's exactly why the sense of accomplishment when you clear it is incomparable to anything else!"
1013403-74 = "...This also sounds like Aris right now."
1013403-75 = "[s] \"So, shall we go with that game?\""
1013403-76 = "...No.#nIt is a game I like, but..."
1013403-77 = "If I play this game, I feel like I'll develop trauma regarding the Hero's armor..."
1013403-78 = "Is there anything else... with a reasonable playtime that's also relaxing...?"
1013403-83 = "...Ah."
1013403-87 = "I've decided. Aris wants this one."
1013403-88 = "[s7] \"That is...\"\n[s8] \"'Tales Saga Chronicle'?\""
1013403-91 = "Yes! The original 'Tales Saga Chronicle'!"
1013403-92 = "It's a work created by the Game Development Department before Aris joined."
1013403-93 = "So Aris wasn't involved in making this game.#nBut as you progress through it, you can really feel everyone's passion."
1013403-94 = "And above all, this game is—"
1013403-95 = "A kusoge!"
1013403-96 = "[s9] \"Aris!?\"\n[s10] \"I heard it was a pretty strange game, but...!\""
1013403-99 = "That is a fact!"
1013403-100 = "Aris didn't understand at first, but now that I've played so many games, I can say it with certainty."
1013403-101 = "'Tales Saga Chronicle' is a kusoge!"
1013403-105 = "...But that's okay."
1013403-106 = "This is... the first game Aris ever played."
1013403-107 = "This game was the first to call Aris a 'Hero'."
1013403-108 = "...Aris really does like this game after all."
1013403-109 = "Plus, the playtime is just right!"
1013403-110 = "If you know the strategy, you can see the true ending in three hours!"
1013403-111 = "Sensei! Let's play it together!"
1013403-113 = "(Swept up by her enthusiasm, we ended up playing 'Tales Saga Chronicle')"
1013403-115 = "[56cd7b]In the Cosmos Century 2354, humanity was engulfed in flames of destruction—[-]"
1013403-116 = "It's a standard fantasy RPG, yet this is the opening!"
1013403-117 = "Also, the proper noun 'Cosmos Century' only appears here!"
1013403-118 = "[56cd7b]Starting tutorial.[-]"
1013403-120 = "[56cd7b]First, press the B button to equip the weapon in front of you.[-]"
1013403-121 = "Ah, this is a trap. If you press the B button here, it's game over."
1013403-122 = "You have to press the A button to proceed."
1013403-124 = "[ns11] \"This game is harder than I imagined...\"\n[ns12] \"Can we really clear it in three hours?\""
1013403-127 = "If you don't know the strategy, you might never clear it."
1013403-128 = "But for a veteran player like Aris, it's a breeze!"
1013403-130 = "Ah."
1013403-131 = "I reached the first town without encountering any enemies."
1013403-132 = "Healing options are limited early on, so this is lucky!"
1013403-138 = "...This BGM for the 'Starting Town'."
1013403-139 = "Aris loves it.#nListening to it reminds me of when I first encountered this game."
1013403-140 = "...Hehe."
1013403-141 = "It's very strange. The Aris from back then didn't know anything yet."
1013403-142 = "Since then, I've obtained the Sword of Light, met my friends, and gone on countless adventures—"
1013403-143 = "And now, I've come all the way to the distant Ice Sea."
1013403-144 = "It really is like a Hero's adventure."
1013403-145 = "...This 'Starting Town' is the starting place for Aris, too."
1013403-149 = "...Ah! I encountered a monster!"
1013403-150 = "It's a Puni-Puni using a double shotgun!#nMelee is difficult, so here—"
1013403-152 = "(Proceeded through 'Tales Saga Chronicle' with Aris)"
1013403-153 = "(A while later...)"
1013403-156 = "...I defeated the final boss! It's cleared!"
1013403-157 = "...Sensei? Is something wrong?"
1013403-158 = "You have a face like a sad puppy!"
1013403-159 = "[s] \"Aris... can I ask?\""
1013403-163 = "[ns13] \"Why is the mother the heroine, and yet she's actually the wife from a past life...\"\n[ns14] \"And why is the half-sibling friend time-leaping?\""
1013403-167 = "Aris doesn't know either!"
1013403-168 = "...But."
1013403-169 = "Don't you think it's interesting?"
1013403-170 = "[s15] \"...Yeah.\"\n[s16] \"It was really interesting.\""
1013403-173 = "Aris is happy to be with Sensei! Aris had a lot of fun too!"
1013403-174 = "Now, next is—"
1013403-176 = "(We naturally continued playing games)"
1013403-177 = "(Spent time playing various games with Aris)"