[translation]
1013602-1 = "Efficiency and Inefficiency"
1013602-4 = "Good morning. You're a sleepyhead, Sensei."
1013602-5 = "[s] \"Good morning. You're energetic this early...\""
1013602-6 = "Well, the situation is different from usual right now. We have to do what we can."
1013602-7 = "That being said, reconnaissance is all we can do... Oh, come to think of it—"
1013602-8 = "I picked up a slightly concerning signal earlier. I'm heading there now."
1013602-9 = "[s] \"Can I come with you?\""
1013602-10 = "Hmm, sure, but... Just in case something happens..."
1013602-14 = "...Well, whatever. I'll protect you. No matter what."
1013602-17 = "(I went outside with Eimi.)"
1013602-20 = "We'll scout from here. It should take about 2 hours."
1013602-21 = "I plan to move slowly, at about 4 kilometers per hour."
1013602-22 = "Ah, but it's okay if you're slower than that. Though it'd be a bit of a problem#nif you're too slow."
1013602-23 = "You see, if we get separated, I won't be able to protect you, right?#nTry not to fall too far behind."
1013602-25 = "(And so, I began the reconnaissance with Eimi.)"
1013602-29 = "(Eimi's pace was fast, and it was hard to keep up...)"
1013602-32 = "Amazing. You're actually keeping up, Sensei."
1013602-33 = "[s] \"Even if that's flattery, I'm happy... I mean… can I really say I’m keeping up with this…?\""
1013602-34 = "It's not flattery. Someone would have been exhausted right away."
1013602-35 = "Eh? Yeah, pacing is important. Just like you said, Sensei."
1013602-36 = "I think so, but..."
1013602-37 = "...You get used to it. Still, it’s tough."
1013602-38 = "!?"
1013602-39 = "Sensei, hide!"
1013602-43 = "(Suddenly, Eimi shoved me into a fissure in the cracked ground.)"
1013602-44 = "Sorry for the sudden move."
1013602-45 = "I want you to stay there until I say it's safe."
1013602-46 = "Their numbers are— about one squad? In that case...!"
1013602-53 = "It's safe now, Sensei."
1013602-54 = "...But I doubt that was all of them."
1013602-56 = "(Even after that, Eimi—)"
1013602-60 = "Coordinates confirmed. Distance... 427m. I'll strike first...!"
1013602-63 = "(Facing the enemy forces moving at breakneck speed...)"
1013602-66 = "Maybe it's better to wait a bit—"
1013602-67 = "No, it's probably better to deal with them first and then move on."
1013602-68 = "It would be inefficient if the situation escalated...!"
1013602-73 = "It seems that they haven't discovered our location yet... Judging by their#nequipment, that's probably a transport unit..."
1013602-74 = "In that case—Search and Destroy!"
1013602-77 = "(Eimi proceeded with the force reconnaissance surprisingly skillfully...)"
1013602-80 = "Alright. There are no more danger signals."
1013602-81 = "Good work, Sensei. Let's head back soon."
1013602-82 = "[s] \"Do you always do things like this...? Amazing...\""
1013602-83 = "It's no big deal. It's always like this."
1013602-84 = "Probably because someone out there works people way too hard…"
1013602-85 = "Well, I say it to her face too."
1013602-86 = "[s] \"L-Let's all get along...\""
1013602-87 = "We actually get along pretty well, don't we?"
1013602-88 = "..."
1013602-89 = "...Come to think of it, I've always been alone, so this might be my first time#nworking in a group."
1013602-90 = "I used to think efficiency would drop if there are more people."
1013602-91 = "...And some people were afraid of working with me."
1013602-92 = "...My way of thinking wasn't really understood by others."
1013602-93 = "[s] \"How about now?\""
1013602-94 = "Now..."
1013602-95 = "I wonder why. I'm surprisingly okay with it."
1013602-96 = "Maybe because everyone is a little weird? We get along well, or rather..."
1013602-97 = "It's really comfortable."
1013602-98 = "[s] \"It's best for students to get along if possible. With the other girls, too.\""
1013602-99 = "With the other girls, huh..."
1013602-100 = "..."
1013602-101 = "If it were the old me, I probably would have thought it was inefficient."
1013602-102 = "But, it's kind of strange."
1013602-103 = "Now, I feel like I want to cooperate."
1013602-104 = "[s] \"I'm glad you feel that way.\""
1013602-105 = "Yeah."
1013602-106 = "Maybe your words had a little to do with it. Hehe."
1013602-108 = "(After that, I chatted with Eimi as we returned to where everyone was.)"