[translation]
1013806-1 = "Small Ribbon"
1013806-2 = "(That afternoon)"
1013806-3 = "(I headed to the Occult Research Club room with the requested items and a chocolate banana crepe.)"
1013806-6 = "Oh, welcome, Sensei."
1013806-7 = "The seniors said they'd be a little late."
1013806-8 = "They're probably off doing something like 'searching for hidden occult phenomena' again."
1013806-9 = "[s] \"Rena, you didn't go with them?\""
1013806-10 = "I thought I'd get some of my own work done while they were away."
1013806-11 = "Still, to think the shop would be temporarily closed... *sigh*."
1013806-12 = "Honestly, there isn't a single normal person in this academy... I wonder if I'll really be able to make it through three years here?"
1013806-13 = "[s] \"Here, eat this chocolate banana crepe and cheer up!\""
1013806-14 = "I told you I didn't need anything..."
1013806-15 = "Well... thanks."
1013806-20 = "This is delicious...! Where did you buy it?"
1013806-21 = "[s] \"Actually, I made it myself.\""
1013806-22 = "Huh!? Y-you did!?"
1013806-23 = "[s] \"Well? Is it good?\""
1013806-24 = "W-well..."
1013806-25 = "..."
1013806-26 = "It is... actually... pretty good."
1013806-27 = "Hiss! Ugh, don't make me say it, you idiot!"
1013806-33 = "(Even though she was angry, Rena finished eating it.)"
1013806-35 = "Phew... I've got my sugar fix, so I guess I'll continue."
1013806-36 = "[s1] \"You're making accessories, right?\"\n[s2] \"What are you making?\""
1013806-39 = "A ribbon hairpin."
1013806-40 = "[s3] \"Come to think of it, Rena, you wear a lot of ribbons.\"\n[s4] \"Do you like ribbons?\""
1013806-43 = "Hmm... like, or rather..."
1013806-44 = "I started wearing them for no reason, but before I knew it, they just kept increasing."
1013806-45 = "Now, if I'm not wearing a bunch of them, I feel kind of restless..."
1013806-46 = "[s5] \"So they're like a charm for you?\"\n[s6] \"I guess you really are an Occult Research Club member at heart.\""
1013806-49 = "HISS!! That's not it!"
1013806-50 = "It's nothing like that!! It's just fashion!!"
1013806-51 = "[s] \"You have so many already, are you still making more?\""
1013806-52 = "I lose them often. So I thought I'd make some spares."
1013806-53 = "Anyway, I'm going to start working now. Shouldn't you get back to your work, Sensei?"
1013806-54 = "You came here today for work, didn't you?"
1013806-55 = "[s7] \"I still have time, so it's fine.\"\n[s8] \"Can I watch you make the ribbon?\""
1013806-58 = "...Is that so?"
1013806-59 = "B-but I don't think it's very interesting to watch, you know?"
1013806-60 = "If you're fine with that, then..."
1013806-64 = "I-it's fine, I guess."
1013806-65 = "But don't get in my way, okay?"
1013806-68 = "[wa:1650]— [log=Rena] You know, [wa:1430] I've been dexterous [wa:980] since I was little. [/log]"
1013806-70 = "— [log=Rena] I used to make things like ribbons [wa:1870] and give them to my friends. [/log]"
1013806-73 = "[wa:1150]— [log=Rena] It made me happy [wa:1380] when they were happy. [/log]"
1013806-75 = "— [log=Rena] ...That's when I realized. [/log]"
1013806-78 = "— [log=Rena] That even with something this small, [/log]"
1013806-80 = "— [log=Rena] I can make someone happy, [wa:2230] you know? [/log]"
1013806-83 = "[wa:1140]— [log=Rena] That's why [wa:1120] I started aiming to be a fashion designer. [/log]"
1013806-86 = "— [log=Rena] Because when everyone enjoys [wa:1670] the clothes and accessories I design, [/log]"
1013806-88 = "— [log=Rena] I feel happy, too. [wa:1840] [/log]"
1013806-91 = "[wa:710]— [log=Rena] You kind of understand that, [wa:1160] don't you, Sensei? [/log]"
1013806-93 = "— [log=Rena] That's also why [wa:820] I think you went out of your way [wa:1410] to be kind to me. [/log]"
1013806-96 = "[wa:520]— [log=Rena] Huh...? [/log]"
1013806-98 = "— [log=Rena] How was today, [wa:700] you ask...? [wa:1010] [/log]"
1013806-101 = "[wa:680]— [log=Rena] Hiss! [wa:940] D- [wa:280] don't make me say it! [wa:980] You idiot Sensei! [/log]"
1013806-104 = "(I had a lovely conversation with Rena while she made the ribbon.)"
1013806-110 = "Oh... look at the time."
1013806-111 = "Sensei, shouldn't you get going soon?"
1013806-112 = "[s] \"You're right, I should probably head out.\""
1013806-113 = "Yeah. Good luck with your work."
1013806-114 = "Oh, wait, before that—"
1013806-118 = "Come here for a second."
1013806-123 = "Hehe, it suits you!"
1013806-124 = "Here, you can have it."
1013806-125 = "[s9] \"Are you sure? Thank you!\"\n[s10] \"I'll wear it while I work!\""
1013806-128 = "Huh...? There's really no need to go that far..."
1013806-129 = "[s] \"It's the first ribbon you've ever given me, after all.\""
1013806-130 = "...!"
1013806-131 = "D-do whatever you want!"
1013806-133 = "(Thinking of Rena, who looked so happy...)"
1013806-134 = "(I wore the ribbon and worked hard.)"