[translation]
1013606-1 = "Cocoa with You"
1013606-3 = "Good work today, Sensei."
1013606-4 = "[s1] \"Good work to you too, Eimi!\"\n[s2] \"Huh, where are you right now?\""
1013606-7 = "Me?"
1013606-8 = "I'm on the top."
1013606-9 = "Ah, not for reconnaissance or anything..."
1013606-10 = "How should I put it."
1013606-11 = "Hmm..."
1013606-12 = "Do you want to come up too, Sensei?"
1013606-13 = "It's a bit strange up here."
1013606-16 = "(As Eimi suggested, I climbed up to find—)"
1013606-21 = "[wa:710]― [log=에이미 결전]Welcome, [wa:957]Sensei.[/log]"
1013606-23 = "― [log=에이미 결전]It’s kind of [wa:1440]a strange sky, isn’t it?[/log]"
1013606-26 = "[ns] \"It is really... fascinating.\""
1013606-27 = "[wa:730]― [log=에이미 결전]It looks similar to the night sky we know, [wa:1990]but...[/log]"
1013606-30 = "― [log=에이미 결전]If you look closely, [wa:2100]it's completely different.[/log]"
1013606-32 = "― [log=에이미 결전]Just like the me right now.[/log]"
1013606-35 = "[wa:1070]― [log=에이미 결전]Up until now, [wa:1370]I didn't really[/log]"
1013606-37 = "― [log=에이미 결전]look up like this very often...[/log]"
1013606-40 = "― [log=에이미 결전]But lately, [wa:1760]I’ve been really into it.[/log]"
1013606-43 = "[wa:860]― [log=에이미 결전]I wonder [wa:740]why, though.[/log]"
1013606-45 = "― [log=에이미 결전]Every time I look up, [wa:1180]your face comes to mind, Sensei.[/log]"
1013606-48 = "[ns] \"Why is... that?\""
1013606-49 = "[wa:1720]― [log=에이미 결전]Hehe, [wa:1610]I wonder why.[/log]"
1013606-51 = "― [log=에이미 결전]Sensei.[/log]"
1013606-54 = "― [log=에이미 결전]I'm truly glad [wa:1590]that I met you, [wa:2320]Sensei.[/log]"
1013606-56 = "― [log=에이미 결전]Yeah, [wa:1130]truly. [wa:2225]That's [wa:1288]what I think.[/log]"
1013606-60 = "Eh... Hot Cocoa? Did you bring it for me?"
1013606-61 = "I appreciate the thought, but... I don't do well with hot drinks."
1013606-62 = "[s] \"Your portion is iced cocoa, Eimi.\""
1013606-63 = "Wow, thank you, Sensei!"
1013606-64 = "That's what I like about you."
1013606-67 = "(I sit down next to Eimi.)"
1013606-70 = "Probably..."
1013606-71 = "Before I met you, Sensei—"
1013606-72 = "I seriously thought that I could live my life entirely on my own."
1013606-73 = "I never actually said it out loud, though..."
1013606-74 = "I guess it must have shown on my face without me even realizing it."
1013606-75 = "In my case, it was often more efficient to handle things alone."
1013606-76 = "Even with knowledge, self-study was enough."
1013606-77 = "[s] \"What about now?\""
1013606-78 = "I wonder."
1013606-79 = "At the least, if I were alone—"
1013606-80 = "You handing me iced cocoa like this would never have happened."
1013606-81 = "And sharing our body heat like this wouldn't have happened either."
1013606-87 = "(I can feel Eimi's body heat from where we're touching.)"
1013606-88 = "Is it warm?"
1013606-89 = "[s] \"Yeah, the cocoa is.\""
1013606-90 = "Hmmph..."
1013606-91 = "[s3] \"Sorry, sorry.\"\n[s4] \"Thanks to you, Eimi, I'm not cold.\""
1013606-94 = "That's good."
1013606-95 = "..."
1013606-96 = "This is kind of nice."
1013606-97 = "It really is."
1013606-98 = "From now on, I want to interact with more people—"
1013606-99 = "And a lot of things are going to change... is that how it'll be?"
1013606-100 = "..."
1013606-101 = "......"
1013606-102 = "........."
1013606-103 = "I wonder."
1013606-104 = "[s] \"You're supposed to nod there.\""
1013606-105 = "When there are too many people involved... it gets troublesome."
1013606-106 = "[s] \"So that's the reason...\""
1013606-107 = "That's important, Sensei."
1013606-108 = "One of the reasons people seek efficiency is to escape from bothersome things."
1013606-109 = "[s] \"I won't deny that, but...\""
1013606-110 = "Having you here is enough for now, anyway?"
1013606-111 = "[s] \"Ehh!?\""
1013606-112 = "It's no use pretending you didn't hear that, Sensei."
1013606-113 = "Because I said it so you could hear it."
1013606-118 = "(And so, I chat with Eimi until we finished our cocoa, spending a peaceful time#ntogether.)"