[translation]
1013703-1 = "Sense of Time"
1013703-2 = "(I had some business in the Black Market, but couldn't find what I was looking for. Just as I was about to head back...)"
1013703-3 = "(I heard a noisy commotion coming from the alley.)"
1013703-11 = "Don't run! Get over here!!"
1013703-12 = "Like hell I will, idiot!"
1013703-13 = "You think I'd let a target worth catching get away?#nI'll chase you to the ends of the earth~!"
1013703-14 = "Eeek!!"
1013703-21 = "I mean, today is the day I have to be strictly on time!"
1013703-22 = "So! I need you! To quietly!#nLet yourself be caught, aight!?"
1013703-23 = "Here! Handcuffs! Two holes! Two hands!#nYou know how to use them, right?"
1013703-24 = "Huh!? Who in their right mind handcuffs themselves!?"
1013703-25 = "Are you crazy!? Take this!"
1013703-31 = "Gah...! Ugh...!"
1013703-32 = "Haha! Teflon-coated bullets! That hurts, doesn't it?"
1013703-33 = "There's no way a bag can block them!"
1013703-34 = "Valkyrie's bulletproof vests are nothing compared to—"
1013703-41 = "Huh??????"
1013703-42 = "I emptied a whole magazine and you took zero damage!?"
1013703-43 = "A-Ahhhh, now my school bag is full of holes!"
1013703-44 = "I can't even read my textbooks like this anymore!"
1013703-45 = "How are you gonna take responsibility for this!! Hey!"
1013703-57 = "No, that's because you used your bag as a shield!!"
1013703-62 = "It hurts if I get hit!#nIf I have something I can use, obviously I'm gonna use it!"
1013703-63 = "Why are all your textbooks wrapped up in tape!?"
1013703-68 = "Because they're important! I told you!"
1013703-69 = "Then don't hit me with them! Ouch!"
1013703-71 = "Are you really a cop?#nYou're acting just like a delinquent!"
1013703-72 = "If you've got complaints, you should join Valkyrie~#nI'll at least help you with the paperwork."
1013703-73 = "So, getting beaten up now, or getting beaten up after being arrested...#nwhich do you prefer?"
1013703-74 = "They're exactly the same!!"
1013703-75 = "I'm letting you CHOOSE, so hurry up and pick it!"
1013703-77 = "[ns] \"U-Umm... how about we just talk it out first...\""
1013703-78 = "S-Sensei from SCHALE!?"
1013703-79 = "Please help meee!!!"
1013703-80 = "Hey!#nTelling Sensei is just dirty!"
1013703-81 = "H-Hey there, Sensei!#nWe were just, uh, playing around a bit?"
1013703-83 = "[ns] \"Friends should... get along, right...?\""
1013703-84 = "Is this the part where I'm the one getting in trouble!?"
1013703-85 = "Ah!#nSensei, what time is it right now?"
1013703-86 = "My phone broke...#nyou're paying for it later!"
1013703-87 = "Huh? You used your phone to hit me yourself...#nisn't that a bit harsh!?"
1013703-89 = "[ns] \"It's 5:59, but...\""
1013703-90 = "...!"
1013703-91 = "Huh? 17:59?"
1013703-92 = "Crap... it's already time to clock out."
1013703-93 = "Here, I'm handling you the handcuffs, so make sure to put them on properly.#nCome to Valkyrie at 9 AM tomorrow! I won't go easy on you if you run."
1013703-94 = "It's a promise with me, got it?"
1013703-95 = "Well then Sensei, excuse me for leaving early!#nToday is a strict punctuality day!"
1013703-96 = "Thanks for your hard work!"
1013703-98 = "[ns] \"E-Eh...?\""
1013703-103 = "...Huh?"
1013703-104 = "She went home...?"
1013703-105 = "What is wrong with Valkyrie...?"
1013703-106 = "[s] \"W-What was that all about...\""
1013703-108 = "The Next Day, 8:59 AM"
1013703-109 = "(Continuing from yesterday, I heard noisy voices again.)"
1013703-114 = "Eeek!! This is a completely different city from yesterday! How did you find me!!"
1013703-115 = "I told you I wouldn't show mercy if you ran, didn't I?"
1013703-116 = "I did a stakeout just in case after that...#nwell, looks like it was a bingo."
1013703-117 = "You said you were going home!!"
1013703-118 = "Too bad, stakeouts are a hobby of mine.#nIt wasn't for work."
1013703-119 = "8 seconds until 9 AM!#nBetter prepare yourself!"
1013703-120 = "Uwaaah! Help me!! I promise I won't run away anymore!!!"
1013703-127 = "(Konoka arrested the suspect exactly as the clock struck 9 AM.)"
1013703-128 = "(Checking the time, Konoka noticed me and give me a huge smile.)"