[translation]
1013203-1 = "Another modeling gig...?"
1013203-2 = "Art Prep School - Faculty Office"
1013203-3 = "Oh, Sensei...!"
1013203-4 = "[s] \"Tsukuyo, what happened?\""
1013203-5 = "Well, you see..."
1013203-6 = "I received a modeling offer from an art prep school, but..."
1013203-7 = "I don't have any experience as a painting model..."
1013203-8 = "So I was hoping you could watch over me, Sensei..."
1013203-12 = "...Wait!?#nI'm just inconveniencing you for my own sake...!"
1013203-13 = "I-I'm so sorry...!"
1013203-14 = "[s] \"No, it's perfectly fine.\""
1013203-16 = "[ns] \"But didn't you say you were quitting modeling...?\""
1013203-17 = "A-actually..."
1013203-18 = "Do you remember the president who gave us the 'Ninjas Live Seven Times' pamphlet?"
1013203-23 = "They asked me to lend them my strength just one more time..."
1013203-24 = "Apparently, the model they had for this morning ran off..."
1013203-25 = "And they couldn't find a replacement..."
1013203-26 = "They told me that being a painting model just means sitting still, but..."
1013203-27 = "[s1] \"I see...!\"\n[s2] \"I thought you were aiming to be a painter. That's fine too, though.\""
1013203-30 = "N-no, that's not it!"
1013203-31 = "I am still aiming to be a magnificent ninja...!"
1013203-32 = "...Yes?"
1013203-33 = "Oh, um, the reason I'm wearing a dress is..."
1013203-34 = "The theme for today is 'Woman in a Dress'..."
1013203-39 = "Ah, you must be Tsukuyo-san. Thank you for coming today.#nIf you're ready, could you head to the classroom?"
1013203-43 = "Y-yes...!"
1013203-44 = "I'll be going now...!"
1013203-46 = "Art Prep School - Classroom"
1013203-50 = "Are you Oono Tsukuyo, the substitute model?"
1013203-51 = "Y-yes, I am!"
1013203-52 = "Thanks for stepping in. Let me give you a quick explanation.#n"
1013203-53 = "This is a class for students aiming to enter Wildhunt Art Academy."
1013203-54 = "I'll give you instructions on your pose later..."
1013203-55 = "I'd like you to hold it for as long as possible."
1013203-57 = "U-understood!"
1013203-58 = "This is my first time as a painting model, but I'll do my best...!"
1013203-59 = "Haha, no need to be so nervous."
1013203-64 = "(It must be tough for a beginner...)"
1013203-65 = "(Holding the same pose is surprisingly difficult...)"
1013203-68 = "(...Or so I thought.)"
1013203-69 = "(An hour has passed, and she hasn't moved a muscle!?)"
1013203-75 = "Is that model... actually alive?"
1013203-76 = "Wait, wasn't that a wax figure?"
1013203-77 = "Don't you know? That's the up-and-coming rookie model!"
1013203-78 = "You're right! Now that I look closer, it is her!"
1013203-82 = "(...)"
1013203-83 = "(I was worried, but this is easier than the fashion show...)"
1013203-84 = "(I'm good at staying perfectly still.)"
1013203-85 = "(Hehe, all that practice disguising myself as a tree... it paid off...!)"
1013203-86 = "(S-she's a genius...!)"
1013203-87 = "(In my 10 years of teaching, I've never seen a model this perfect...)"
1013203-88 = "(She's so still, I'd believe it if someone said she was a wax figure!)"
1013203-89 = "(And that serene expression...)"
1013203-90 = "(Where has such a talent been hiding all this time...!?)"
1013203-92 = "(Time passed, and the drawing class ended without incident.)"
1013203-95 = "Great work today!#nThat must have been exhausting, right?"
1013203-96 = "N-no... thank you for your hard work...!"
1013203-97 = "That was a truly magnificent performance!"
1013203-98 = "Was it really your first time as a painting model...?"
1013203-99 = "Y-yes... this was my first time."
1013203-100 = "(A natural-born genius, indeed...!)"
1013203-101 = "Then, I shall take my leave now..."
1013203-102 = "Wait!"
1013203-103 = "If you don't mind, could you model for us a little longer?"
1013203-104 = "Yes...?"
1013203-105 = "We need a model for the sculpture class as well...!"
1013203-107 = "I'll pay you double the hourly rate!"
1013203-108 = "U-um..."
1013203-109 = "I've never met anyone who can hold a pose so perfectly!"
1013203-110 = "If you could model for us, Oono-san..."
1013203-111 = "I'm sure the students' skills will improve by leaps and bounds!"
1013203-112 = "Please, I beg of you!"
1013203-113 = "Um, oh dear..."
1013203-117 = "U-understood. I'll do it..."
1013203-120 = "(And so, Tsukuyo continued...)"
1013203-121 = "(to maintain a perfect pose during the sculpture class.)"
1013203-122 = "(A few hours later...)"
1013203-125 = "You were a huge help!#nThank you, Oono-san!"
1013203-126 = "Y-yes.#nThank you for your hard work...!"
1013203-131 = "I'm sorry, Sensei... I-I kept you waiting."
1013203-132 = "[s] \"It's fine, I enjoyed watching.\""
1013203-133 = "Thanks to you being there, I was able to..."
1013203-134 = "I managed to do my best until the end..."
1013203-135 = "...Yes?#nMy thoughts on the sculpture class...?"
1013203-136 = "Well... the atmosphere wasn't much different from the drawing class..."
1013203-137 = "But since they were carving and shaping stone, there was a lot of dust..."
1013203-138 = "So my throat is a little..."
1013203-139 = "[s3] \"In that case, to soothe your throat--\"\n[s4] \"Let's go get something delicious to eat!\""
1013203-144 = "Ah...!"
1013203-145 = "In that case, I should be the one to--"
1013203-146 = "[s] \"I've already made a reservation!\""
1013203-147 = "O-oh my...!"
1013203-148 = "Um... thank you very much, Sensei...!"
1013203-150 = "(I took Tsukuyo to...)"
1013203-151 = "(a restaurant in Hyakkiyako known for its wide variety of vegetable dishes.)"
1013203-155 = "(...I have a feeling that her modeling career is only just beginning.)"