[translation]
1013702-1 = "Introduce Yourself Properly"
1013702-2 = "(Upon visiting Valkyrie...)"
1013702-3 = "Hello, Sensei!"
1013702-4 = "Is there something you need?"
1013702-5 = "[s1] \"I have something to discuss with Konoka.\"\n[s2] \"Do you know where she is?\""
1013702-8 = "Ah, if you mean the Deputy Director, she's clocked in right now..."
1013702-9 = "She's currently in the middle of other work...#nI believe she's in the basement."
1013702-10 = "[s] \"Basement?\""
1013702-11 = "Yes.#nThere's some work that needs to be done in the basement..."
1013702-13 = "[ns3] \"Is this... the prison cell?\"\n[ns4] \"What kind of work is she doing exactly...\""
1013702-16 = "Zzz... kuuu..."
1013702-17 = "(I can hear someone snoring.)"
1013702-18 = "Guuuu... Zzz..."
1013702-19 = "Zzz... Uwaa... B-Bring it on!#n... Grrrr..."
1013702-20 = "[ns5] \"Konoka...?\"\n[ns6] \"Why are you in a prison cell...?\""
1013702-26 = "A-aughhhhh!!!"
1013702-27 = "Hey!#nThrowing sand like that is so unfair..."
1013702-28 = "Wait, it was a dream... Ugh, I was so close"
1013702-29 = "Huh?"
1013702-34 = "[ns] \"G-Good morning, Konoka...\""
1013702-35 = "What... am I still dreaming...?"
1013702-36 = "Sensei's been showing up in my dreams lately~"
1013702-37 = "[ns] \"This is reality! Wake up!\""
1013702-38 = "*Yawn*... *Mumble mumble*..."
1013702-39 = "Hmm...?#nAh, I must have dozed off."
1013702-40 = "[s7] \"So, when will you be released?\"\n[s8] \"Do they really serve katsudon?\""
1013702-43 = "Ah, no! That's not it!#nI wasn't arrested... well, it's really no big deal, but..."
1013702-44 = "I got into a tiiiiny little fight yesterday..."
1013702-45 = "I got dispatched and it turned into a whole mess...#nso I just got off my shift at dawn."
1013702-46 = "So, I figured I'd take a quick nap, but... the bureau is pretty loud, right?#nThat's why I was sleeping in here."
1013702-47 = "I have to do a welcome party for the rookies, meet and greets, and all that...#nbut I'm just so busy..."
1013702-48 = "Oh, right.#nThe administrative procedures, right? Give me a sec~ I'll go grab the paperwork."
1013702-49 = "Let's see... where did I put the keys~?"
1013702-56 = "P-Put your hands up! Step away from the bars!#nIf you move, I'll shoot!"
1013702-60 = "Huh?"
1013702-61 = "I warned you!#nDon't touch those keys!"
1013702-62 = "Sensei, please step back as well!#nShe's clearly a dangerous criminal!"
1013702-63 = "[s9] \"It's a misunderstanding!\"\n[s10] \"It might look like it, but it's a misunderstanding!\""
1013702-66 = "Hey, aren't you one of the rookies who just joined?#nYou were on the roster."
1013702-67 = "I mean, I'm the Deputy Director of the Public Security Bureau, you know!?"
1013702-68 = "Public Security Bureau!?#nTrying to impersonate the Deputy Director...!"
1013702-69 = "I've never met the Deputy Director, but I'm certain that it definitely isn't you!"
1013702-70 = "I'm reporting you to the Deputy Director on Momotalk!"
1013702-74 = "There, I sent it!"
1013702-79 = "So, who is impersonating the Deputy Director?"
1013702-80 = "Umm..."
1013702-81 = "This is Public Security 1-2-0!!#nIt appears the suspect is in possession of the Deputy Director's phone!!"
1013702-82 = "Wait, why!?"
1013702-83 = "There's no way the Deputy Director would be dressed like that!!"
1013702-84 = "This is your final warning!#nYou prison breaker! Surrender peacefully!"
1013702-85 = "A prison breaker!? Being suspicious is a good thing and all, but...#nwhere in Kivotos are you gonna find a prison breaker who goes to dinner and the baths with Director Kanna!"
1013702-86 = "D-Don't come any closer!#nPepper spray!!"
1013702-93 = "Gyaaaah!! M-My eyes!!!"
1013702-94 = "And here I was trying to play nice...!"
1013702-95 = "W-Why isn't it working!?"
1013702-96 = "Because I'm trained for it, obviously! I could even gargle tear gas!#nI am Shima Konoka—"
1013702-97 = "Shut up!#nEat taser!!!"
1013702-99 = "Deputy Director of the Public Security—#nAbyaah!!!"
1013702-103 = "B-Bureau...#nyou...#nknow..."
1013702-105 = "This is Public Security 1-2-0, suspect has been apprehended in the basement prison cell!!"
1013702-109 = "Ah... come to think of it...#ntoday's fortune... said to introduce myself properly."
1013702-111 = "(Afterwards, a junior officer from the Public Security Bureau rushed over and proved Konoka's identity.)"
1013702-112 = "(The rookie was pale-faced and apologizing profusely. Konoka didn't seem to mind much and laughed it off, forgiving her.)"
1013702-113 = "(Konoka was looking off into the middle distance, perhaps due to the effects of the pepper spray, but she looked somewhat in a good mood.)"