[translation]
1013603-1 = "What We Give"
1013603-4 = "I said this was a night reconnaissance, but I doubt anything will happen."
1013603-5 = "Why do you think that?#nHmm..."
1013603-6 = "A hunch?"
1013603-7 = "[s] \"It's rare for you to go by a hunch, Eimi.\""
1013603-8 = "Is it? Intuition is surprisingly important."
1013603-9 = "It's a conclusion derived from my life experiences—"
1013603-10 = "and the big data I've accumulated as records and lessons."
1013603-11 = "It's what you'd call a heuristic algorithm."
1013603-12 = "Like, if something feels 'off'—whether it's a person or a place—it's better to avoid it."
1013603-13 = "In that sense, I might rely on intuition quite a bit."
1013603-14 = "Of course, when I'm out in the field, I'm always thinking about how to be efficient—"
1013603-15 = "...or rather, how to reduce my workload."
1013603-16 = "[s] \"Do you dislike working?\""
1013603-17 = "Hmm... you see workaholics sometimes, right?#nI'm not one of them."
1013603-18 = "[s] \"I suppose that's true...\""
1013603-23 = "[ns] \"Achoo!!!\""
1013603-24 = "Are you okay?"
1013603-25 = "I just got a little chill... oh, right."
1013603-26 = "Come to think of it, we are in the polar region."
1013603-27 = "In that case—"
1013603-32 = "(Eimi snuggles up to you and links her arm with yours)"
1013603-33 = "[ns] \"E-Eimi!?\""
1013603-36 = "How is it? Are you a little warmer now?"
1013603-37 = "Good, I'm glad."
1013603-38 = "For me... it's lukewarm, which is just right."
1013603-39 = "Huh? Is it efficient?#nWell, I wonder."
1013603-40 = "You could say that, but..."
1013603-41 = "..."
1013603-42 = "Maybe I just want to be like this."
1013603-43 = "[s] \"...Huh?\""
1013603-44 = "What's with that look, Sensei?#nDo you dislike me?"
1013603-45 = "Haha, I'm joking.#nI can understand that reaction now, too."
1013603-46 = "...Yeah."
1013603-47 = "This is something the old me would never have said, either."
1013603-48 = "But when we huddle together like this... and our body temperatures equalize, that's called thermal equilibrium."
1013603-49 = "In that state—"
1013603-50 = "I can feel your body heat as lukewarm—"
1013603-51 = "and you can warm yourself up with my body."
1013603-52 = "I think this is the kind of change we can offer each other."
1013603-53 = "People are meant to influence one another, after all."
1013603-54 = "[s] \"Eimi... have you changed since meeting me?\""
1013603-59 = "...Yeah."
1013603-60 = "Yeah... I think so."
1013603-61 = "If I hadn't met you, I think by now..."
1013603-62 = "I would still be standing alone, unchanged."
1013603-63 = "Without even the thought of sharing my body heat with someone else who is freezing."
1013603-64 = "But now..."
1013603-65 = "..."
1013603-66 = "Haha, that's enough for today."
1013603-67 = "Telling you everything—"
1013603-68 = "might be a bit inefficient, after all."