[translation]
1013605-1 = "Interference"
1013605-2 = "(Following the message sent by Eimi, I head toward the coordinates.)"
1013605-3 = "(Just as I was praying that the worst hadn't happened...)"
1013605-6 = "Yoo-hoo!#nI was waiting for you."
1013605-7 = "[ns] \"……!\""
1013605-9 = "[ns] \"Eimi!!\""
1013605-10 = "!?"
1013605-11 = "W-what's wrong, Sensei?"
1013605-12 = "Are you... angry?"
1013605-13 = "[s] \"I was worried about you.\""
1013605-14 = "……."
1013605-15 = "So that's how it was……."
1013605-16 = "I'm sorry, Sensei……."
1013605-17 = "I……."
1013605-18 = "[s] \"……Let's go home.\""
1013605-19 = "……."
1013605-20 = "Yeah……."
1013605-21 = "[s] \"……I'm glad you're safe.\""
1013605-22 = "Yeah……."
1013605-25 = "I ended up getting into a skirmish on my way back from scouting……."
1013605-26 = "It seems I used too much power then.#nThe battery in my backpack ran out."
1013605-27 = "My equipment is linked to the battery in my backpack, you see."
1013605-28 = "I managed to defeat the enemies, but…… that was the result."
1013605-29 = "[s1] \"……I see.\"\n[s2] \"I was worried that something might have happened to you…….\""
1013605-32 = "That…… I'm sorry."
1013605-33 = "But, I've thought about it a lot—"
1013605-34 = "I think defeating the enemies at that time was an efficient decision."
1013605-35 = "……Even if it was efficient, it's meaningless if I'm not safe, right?"
1013605-36 = "……."
1013605-37 = "……I see."
1013605-38 = "So that's... another way of looking at it."
1013605-39 = "I'm sorry, Sensei.#nIt was my fault."
1013605-40 = "So, please don't be so angry.#nYou look really scary right now."
1013605-41 = "I definitely won't do it again."
1013605-42 = "I promise."
1013605-45 = "……But you know, Sensei."
1013605-46 = "I thought I was going to be fine."
1013605-47 = "I was near the base, after all.#nAnd I was able to send a distress signal."
1013605-48 = "I trusted that you would receive it properly and waited—"
1013605-49 = "……."
1013605-50 = "……Sorry, that's all just an excuse, isn't it."
1013605-51 = "……."
1013605-52 = "How strange."
1013605-53 = "Until now, I thought making excuses was inefficient."
1013605-54 = "I used to think that if you have time to say things like that, it's faster to just resolve the situation……."
1013605-55 = "……."
1013605-56 = "Maybe, right now……."
1013605-57 = "I don't want you to hate me, Sensei."
1013605-58 = "[s3] \"I could never hate you, Eimi.\"\n[s4] \"It's just…… I was worried. So worried.\""
1013605-61 = "……."
1013605-62 = "Thank you, Sensei."
1013605-63 = "……It might be too late for you to hear this, though."
1013605-64 = "I know I can be a bit off-beat sometimes."
1013605-65 = "That's why I have a request for you, Sensei."
1013605-66 = "[s] \"A request?\""
1013605-68 = "(Eimi stops in her tracks and gently closes her eyes.)"
1013605-69 = "(Then, she takes a slow, deep breath.)"
1013605-75 = "Protect me."
1013605-76 = "Keep your eyes on me."
1013605-77 = "And so—I want you to stay by my side and watch over me, so I don't lose my way."
1013605-78 = "I'm aware that I can be selfish."
1013605-79 = "I know people think I'm reckless, too."
1013605-80 = "Even so……."
1013605-81 = "If you're by my side, Sensei, I—"
1013605-82 = "I'll definitely be okay."
1013605-88 = "……I know. I know that a fledgling has to leave the nest someday."
1013605-89 = "But I'm still just a first-year in high school, you know?"
1013605-90 = "So, I think it's fine to stay like this for a while longer."
1013605-91 = "[s] \"……I suppose so.\""
1013605-92 = "Hehe."
1013605-93 = "Besides, even if I were to fly away from here—"
1013605-94 = "……This is just a hypothetical, though."
1013605-95 = "It wouldn't be so bad to look for a partner to spend the rest of my time with, right?"
1013605-96 = "[s] \"What do you mean by that?\""
1013605-99 = "Hehe, it's nothing. I was just saying."
1013605-100 = "There's really no deep meaning behind it."
1013605-101 = "……By the way, Sensei, did you know?"
1013605-107 = "You're back to being your usual self again, Sensei."