[translation]
1013606-1 = "Cocoa with you"
1013606-3 = "Good work today, Sensei."
1013606-4 = "[s1] \"Good work to you too, Eimi!\"\n[s2] \"Wait, where are you right now?\""
1013606-7 = "Me?"
1013606-8 = "I'm up above."
1013606-9 = "Oh, it's not for scouting or anything..."
1013606-10 = "How should I put this?"
1013606-11 = "Hmm..."
1013606-12 = "Do you want to come up, Sensei?"
1013606-13 = "It's a bit strange up here."
1013606-16 = "(As Eimi suggested, I climbed up—)"
1013606-21 = "[wa:710]― [log=에이미 결전]Welcome, [wa:957]Sensei.[/log]"
1013606-23 = "― [log=에이미 결전]The sky looks kind of [wa:1540]strange, doesn't it?[/log]"
1013606-26 = "[ns] \"It really is... amazing.\""
1013606-27 = "[wa:730]― [log=에이미 결전]It looks similar to the night sky we know, [wa:2890]but...[/log]"
1013606-30 = "― [log=에이미 결전]If you look closely, [wa:2100]it's completely different.[/log]"
1013606-32 = "― [log=에이미 결전]It's like me right now.[/log]"
1013606-35 = "[wa:1070]― [log=에이미 결전]I never really [wa:1370]looked up like this[/log]"
1013606-37 = "― [log=에이미 결전]before...[/log]"
1013606-40 = "― [log=에이미 결전]But lately, [wa:1760]I've come to like it.[/log]"
1013606-43 = "[wa:860]― [log=에이미 결전]But [wa:740]I wonder why.[/log]"
1013606-45 = "― [log=에이미 결전]Every time I look up, [wa:1940]your face comes to mind, Sensei.[/log]"
1013606-48 = "[ns] \"Why is that...?\""
1013606-49 = "[wa:1720]― [log=에이미 결전]Hehe, [wa:1610]I wonder why.[/log]"
1013606-51 = "― [log=에이미 결전]Sensei.[/log]"
1013606-54 = "― [log=에이미 결전]I'm [wa:1590]really glad [wa:1820]I met you.[/log]"
1013606-56 = "― [log=에이미 결전]Yeah, [wa:1130]really. [wa:2225]That's [wa:1288]what I think.[/log]"
1013606-60 = "Oh... is that cocoa? Did you bring it for me?"
1013606-61 = "It's a sweet gesture, but I... I don't really like hot things."
1013606-62 = "[s] \"Eimi's is iced cocoa.\""
1013606-63 = "Wow, thank you, Sensei!"
1013606-64 = "I like that about you."
1013606-67 = "(I sit down next to Eimi)"
1013606-70 = "Maybe..."
1013606-71 = "Before I met you, Sensei—"
1013606-72 = "I genuinely thought I could get by just fine on my own."
1013606-73 = "I never said it out loud, though..."
1013606-74 = "I suppose it must have been obvious to others, subconsciously."
1013606-75 = "In my case, it was often more efficient to handle things alone."
1013606-76 = "And for knowledge, self-study was always enough."
1013606-77 = "[s] \"And now?\""
1013606-78 = "I wonder."
1013606-79 = "At the very least, if I were alone—"
1013606-80 = "I wouldn't have had someone bring me iced cocoa like this."
1013606-81 = "And we wouldn't be sharing our body heat like this, either."
1013606-87 = "(I feel Eimi's body heat where we are touching)"
1013606-88 = "Is it warm?"
1013606-89 = "[s] \"Yeah, the cocoa is.\""
1013606-90 = "Hmph..."
1013606-91 = "[s3] \"Sorry, sorry.\"\n[s4] \"Thanks to you, Eimi, I'm not cold.\""
1013606-94 = "That's good."
1013606-95 = "..."
1013606-96 = "This is kind of nice, isn't it?"
1013606-97 = "It really is."
1013606-98 = "From now on, I'll interact with more people—"
1013606-99 = "and change a lot... I wonder if that's how it'll go?"
1013606-100 = "..."
1013606-101 = "..."
1013606-102 = "..."
1013606-103 = "Who knows."
1013606-104 = "[s] \"You should at least nod at that.\""
1013606-105 = "When you interact with more people... it becomes a hassle."
1013606-106 = "[s] \"Is that really your reason...?\""
1013606-107 = "It's an important point, Sensei."
1013606-108 = "One of the reasons people seek efficiency is to avoid things that are a hassle."
1013606-109 = "[s] \"I won't deny that, but...\""
1013606-110 = "For now, having you here is enough, isn't it?"
1013606-111 = "[s] \"Huh!?\""
1013606-112 = "It's no use pretending you didn't hear me, Sensei."
1013606-113 = "I said it so you would hear."
1013606-118 = "(And so, I spent a peaceful time exchanging words with Eimi until we finished our cocoa.)"