[translation]
1013206-1 = "P-please, help me...!"
1013206-3 = "(We were supposed to be going to the fashion show venue together...)"
1013206-5 = "The way to the venue"
1013206-8 = "(...So why am I sprinting at full speed?)"
1013206-13 = "T-time is running out...!"
1013206-14 = "[s1] \"Haa, haa...\"\n[s2] \"Ts-Tsukuyo... wait...!\""
1013206-17 = "Waaah...!#nI-I'm so sorry, Sensei...!"
1013206-18 = "It's all because I overslept...!"
1013206-19 = "Thinking that this would be my last modeling gig, I got so nervous I couldn't sleep...!"
1013206-20 = "[s] \"C-couldn't we just take a taxi...?\""
1013206-21 = "That would be a detour...!"
1013206-22 = "That's it, if we take a shortcut..."
1013206-23 = "Th-this way, Sensei!"
1013206-29 = "[ns] \"I didn't know there was a back alley here...\""
1013206-30 = "Sensei, let's go...!"
1013206-31 = "I learned this route during parkour training, but..."
1013206-32 = "If we go through here, it's a straight line to the venue!"
1013206-33 = "[s] \"Um, Tsukuyo...\""
1013206-35 = "[ns] \"It looks like there's a fence blocking the way...\""
1013206-36 = "I-it's okay...!"
1013206-37 = "[s] \"I see, there's a small gate at the end...\""
1013206-38 = "As a ninja... I'll show you how easily I can clear this!"
1013206-39 = "[s] \"You're going over it!?\""
1013206-40 = "I'll show you an example first...!"
1013206-44 = "Like this, somehow...!"
1013206-45 = "[s] \"Tsukuyo!?\""
1013206-51 = "[ns3] \"...!\"\n[ns4] \"She really jumped over the fence...!\""
1013206-57 = "[ns] \"...She made it?\""
1013206-60 = "[wa:470]― [log=츠쿠요 드레스]Ugh...[/log]"
1013206-62 = "― [log=츠쿠요 드레스]I managed to [wa:1570]clear the fence, [wa:810]but... [wa:1550]well...[/log]"
1013206-65 = "[wa:2990]― [log=츠쿠요 드레스]My dress [wa:1250]got caught...[/log]"
1013206-68 = "― [log=츠쿠요 드레스]I can't [wa:1300]move...[/log]"
1013206-71 = "[wa:1500]― [log=츠쿠요 드레스]Ugh... [wa:2130]I'm sorry...[/log]"
1013206-73 = "― [log=츠쿠요 드레스]It's because I [wa:1920]tried to take [wa:1240]a shortcut... [wa:1450][/log]"
1013206-76 = "[wa:2020]― [log=츠쿠요 드레스]...Huh? [wa:1800]Sensei, [wa:1850]how did you [wa:1000]get to the other side...?[/log]"
1013206-79 = "― [log=츠쿠요 드레스]Eh? [wa:1580]There's a gate [wa:1770]next to the fence...!?[/log]"
1013206-82 = "[wa:770]― [log=츠쿠요 드레스]U[wa:540]ugh...[/log]"
1013206-84 = "― [log=츠쿠요 드레스]Not knowing that, [wa:2060]I...[/log]"
1013206-87 = "― [log=츠쿠요 드레스]...Sensei [wa:2150]...could you please[/log]"
1013206-89 = "― [log=츠쿠요 드레스]pull [wa:1650]my dress a little [wa:2770]for me?[wa:1190][/log]"
1013206-92 = "(...I carefully untangled it so the dress fabric wouldn't tear.)"
1013206-93 = "(We got caught by a police officer on the way, which made me break into a cold sweat, but...)"
1013206-94 = "(We managed to arrive at the venue on time.)"
1013206-96 = "(...My heart skipped a beat when I ran into the officer again after leaving the venue.)"