[translation]
1013706-45 = "[wa:2172]― [log=코노카]Ahh-ah, [wa:1075]I'm soaking wet...[/log]"
1013706-47 = "― [log=코노카]Uuu...[wa:570]it's cold[/log]"
1013706-50 = "[wa:1586]― [log=코노카]it[wa:162] started raining down, huh[/log]"
1013706-52 = "― [log=코노카]They said it wouldn't stop until tonight... [wa:300]Sigh...[wa:1961][/log]"
1013706-55 = "― [log=코노카]Well, I guess it was just what I needed to cool my head down.[wa:2167][/log]"
1013706-58 = "[ns] \"Are you okay? Have you calmed down?\""
1013706-59 = "[wa:517]― [log=코노카]Huh? [wa:973]Ah, yeah, [wa:860]I guess.[/log]"
1013706-61 = "― [log=코노카]It would be a lie [wa:487]if I say I'm not frustrated.[/log]"
1013706-64 = "― [log=코노카]All that effort went to waste, now I ended up soaking wet...[wa:1753][/log]"
1013706-67 = "[wa:556]― [log=코노카]But, it's just like the fortune teller predicted.[/log]"
1013706-69 = "― [log=코노카]Having my partner right by my side made it a great day.[/log]"
1013706-72 = "― [log=코노카]...Thanks to you, Sensei.[/log]"
1013706-75 = "[wa:870]― [log=코노카]So, [wa:934]if I had to say...[/log]"
1013706-77 = "― [log=코노카]I'm happy.[/log]"
1013706-80 = "― [log=코노카]...Ah, [wa:276]no, [wa:607]I mean![/log]"
1013706-82 = "― [log=코노카]I mean I'm lucky and happy that we get to take shelter from the rain like this![/log]"
1013706-85 = "― [log=코노카]T-[wa:456]That's all... [wa:806]I meant...[/log]"