[translation]
1013605-1 = "Interference"
1013605-2 = "(Relying on the message from Eimi, I head to the coordinates.)"
1013605-3 = "(Just as I was praying the worst hadn't happened...)"
1013605-6 = "Yahoo~ I've been waiting."
1013605-7 = "[ns] \"...!\""
1013605-9 = "[ns] \"Eimi!!\""
1013605-10 = "!?"
1013605-11 = "W-What's wrong, Sensei?"
1013605-12 = "Are you... angry?"
1013605-13 = "[s] \"I was worried.\""
1013605-14 = "..."
1013605-15 = "I... see..."
1013605-16 = "I'm sorry, Sensei..."
1013605-17 = "I..."
1013605-18 = "[s] \"...Shall we head back?\""
1013605-19 = "..."
1013605-20 = "Yeah..."
1013605-21 = "[s] \"...I'm glad you're safe.\""
1013605-22 = "Yeah..."
1013605-25 = "I ended up in a little firefight on the way back from scouting..."
1013605-26 = "I guess I used too much power then.#nMy backpack's battery died."
1013605-27 = "My equipment is linked to the battery in my backpack."
1013605-28 = "I managed to defeat the enemy, but... as a result, that happened."
1013605-29 = "[s1] \"...I see.\"\n[s2] \"I was worried something might have happened to you...\""
1013605-32 = "About that... sorry."
1013605-33 = "But, I thought about it a lot, and—"
1013605-34 = "I think defeating the enemy at that moment was the most efficient decision."
1013605-35 = "...Even if it's efficient, it's meaningless if I'm not safe, huh."
1013605-36 = "..."
1013605-37 = "...I see."
1013605-38 = "That way of thinking... also exists, huh."
1013605-39 = "I'm sorry, Sensei.#nI was wrong."
1013605-40 = "So, please don't be too angry.#nYour face right now is really scary."
1013605-41 = "I will absolutely never do it again."
1013605-42 = "I promise."
1013605-45 = "...But you know, Sensei."
1013605-46 = "I thought I was going to be fine."
1013605-47 = "I was near base, for one.#nAnd I was able to send a distress signal."
1013605-48 = "I believed you would receive it, and I was waiting..."
1013605-49 = "..."
1013605-50 = "...Sorry, this is all just turning into excuses."
1013605-51 = "..."
1013605-52 = "How strange."
1013605-53 = "Up until now, I always thought excuses were inefficient."
1013605-54 = "I used to think it was faster to just clean up the mess than to say things like that...#n...so I thought."
1013605-55 = "..."
1013605-56 = "Maybe the me right now..."
1013605-57 = "Might just not want you to hate me."
1013605-58 = "[s3] \"I would never hate you, Eimi.\"\n[s4] \"I was just... worried. Really worried.\""
1013605-61 = "..."
1013605-62 = "Thank you, Sensei."
1013605-63 = "...This is probably too late for you to hear, but."
1013605-64 = "I think I'm a little out of touch with reality sometimes."
1013605-65 = "So, I have a favor to ask you, Sensei."
1013605-66 = "[s] \"A favor?\""
1013605-68 = "(Eimi stops in her tracks and gently closes her eyes.)"
1013605-69 = "(And then, she takes a slow, deep breath.)"
1013605-75 = "Protect me."
1013605-76 = "Keep your eyes on me."
1013605-77 = "And so—I want you to stay by my side and watch over me forever, so I don't lose my way."
1013605-78 = "I am aware that I can be selfish."
1013605-79 = "I know people think I’m a bit reckless."
1013605-80 = "But still..."
1013605-81 = "If you are by my side, Sensei, I—"
1013605-82 = "I'm sure I'll be okay."
1013605-88 = "...I know that a baby bird has to leave the nest eventually."
1013605-89 = "But I'm still a first-year in high school, right?"
1013605-90 = "So, isn't it okay to stay like this for a little longer?"
1013605-91 = "[s] \"...You're right.\""
1013605-92 = "Hehe."
1013605-93 = "Besides, even if I do spread my wings from here—"
1013605-94 = "...This is just talking about possibilities."
1013605-95 = "Wouldn't it be fine to look for someone to spend the rest of my time with?"
1013605-96 = "[s] \"What do you mean by that?\""
1013605-99 = "Hehe, nothing. I just felt like saying it."
1013605-100 = "There's really no deep meaning to it."
1013605-101 = "...By the way, Sensei, did you know?"
1013605-107 = "You're back to your usual self now."