[translation]
1013405-1 = "That there is a difference"
1013405-2 = "(Concerned about Aris's state, you decide to go look for her.)"
1013405-11 = "Warning. An unexpected error has occurred."
1013405-12 = "Tendou Aris, please cease training immediately and return to the transport ship."
1013405-13 = "(An announcement regarding Aris echoes through the ship.)"
1013405-15 = "Oh, Sensei."
1013405-16 = "[s1] \"Are you okay?\"\n[s2] \"Are you hurt?!\""
1013405-19 = "Aris is fine."
1013405-20 = "The trouble isn't with Aris, but with the Hero's armor... Abi-Eshuh."
1013405-21 = "But... I don't really understand what kind of trouble it is."
1013405-22 = "However, I did hear the cause."
1013405-23 = "They said the changes were too much for Abi-Eshuh to handle. #nThey said it needs adjustments to stabilize."
1013405-27 = "I feel sorry for Abi-Eshuh."
1013405-28 = "[s3] \"Sorry for it?\"\n[s4] \"What do you mean by that?\""
1013405-31 = "Well, you see... I understand, too."
1013405-32 = "That Abi-Eshuh is a \"weapon\" created for combat."
1013405-33 = "There is no sadness or joy in that."
1013405-34 = "I heard it from everyone."
1013405-35 = "That Abi-Eshuh used to be incredibly strong."
1013405-36 = "That it was an impossibly huge, cheat-tier armor with no chance of losing."
1013405-37 = "But then, it kept fighting and breaking over and over..."
1013405-38 = "And now, it has shrunk until it fits me perfectly."
1013405-39 = "...They told me this might be the last time."
1013405-40 = "That if it breaks again... it can't be fixed anymore."
1013405-41 = "Even so, they keep modifying Abi-Eshuh for the next battle."
1013405-42 = "To have a fate where it just fights until the very end..."
1013405-43 = "I... I think that's just too much, Sensei..."
1013405-44 = "I want to take Abi-Eshuh to the Game Development Department room. #nI want to show it to everyone in the Engineering Department, too."
1013405-45 = "I want to go to many more places together... and have it meet many more people. #nAnd then—"
1013405-46 = "I hope Abi-Eshuh can be loved by everyone, too. Just like the Sword of Light."
1013405-50 = "...Please tell me, Sensei."
1013405-51 = "What is the difference between Abi-Eshuh and the Sword of Light?"
1013405-52 = "Even though both were created as \"weapons\"..."
1013405-53 = "To just follow a fate decided from the very beginning—"
1013405-54 = "That isn't right. That is... what I was taught."
1013405-55 = "That you are the one who decides your own path."
1013405-56 = "But Abi-Eshuh is..."
1013405-57 = "That's why I... I..."
1013405-62 = "Sensei...?"
1013405-65 = "[ns] You hug Aris."
1013405-68 = "[ns5] \"Don't forget those feelings.\"\n[ns6] \"If you do, I'm sure Abi-Eshuh will be happy too.\""
1013405-71 = "...This is strange."
1013405-72 = "Usually, when you hug me, I feel happy."
1013405-73 = "But for some reason, right now, tears are coming out."
1013405-74 = "I don't really understand why this is happening..."
1013405-75 = "[s7] \"It's okay. Aris still has plenty of time.\"\n[s8] \"The day will come when you understand.\""
1013405-78 = "...You are a mystery, Sensei."
1013405-79 = "I don't understand what you're trying to tell me at all."
1013405-80 = "But when you say it, I feel like it will definitely come true someday."
1013405-81 = "That's why... you really are a mystery, Sensei."
1013405-83 = "(You continue to hold Aris for a while.)"
1013405-84 = "(Once Abi-Eshuh's maintenance was complete, Aris returned to training.)"