[translation]
1600915-1 = "I want you to remember this, Ninja Girl!"
1600915-2 = "Shopping District Entrance"
1600915-3 = "Heh heh heh... You came after all, Sensei."
1600915-4 = "As someone who aspires to be a ninja, you couldn't just ignore this, could you!"
1600915-5 = "[s] \"Wait, I aspire to be a ninja...!?\""
1600915-6 = "What's with that, only realizing it now?"
1600915-7 = "Anyway, the ancient recording medium I've brought is—"
1600915-8 = "This!"
1600915-12 = "[ns] \"...A videotape!?\""
1600915-13 = "I knew you'd know what it was, Sensei~"
1600915-14 = "That's right, a relic that's all but forgotten in this day and age... a vi-deo tape!"
1600915-15 = "[s1] \"Oh, the nostalgia...\"\n[s2] \"What's on the tape?\""
1600915-18 = "Heh heh, curious? You're curious, aren't you?"
1600915-19 = "On this tape is..."
1600915-20 = "Believe it or not...!"
1600915-21 = "[s] \"A recording of the day Michiru took her first steps, or something like that!?\""
1600915-22 = "Meow!?"
1600915-23 = "No! How did you even come up with that!?"
1600915-24 = "[s] \"It's not that...\""
1600915-25 = "Why do you sound so disappointed!?"
1600915-26 = "A-anyway, on this tape is...!"
1600915-27 = "Something everyone who walks the path of the ninja knows..."
1600915-28 = "A black-and-white film shot by the legendary director 'Crow-nyan-nyan' back in his early days!"
1600915-29 = "It's 'The Three Ninjas of the Hidden Classroom'!"
1600915-33 = "[ns] \"...I see?\""
1600915-34 = "That's a weak reaction!?"
1600915-35 = "In times like this, you're supposed to look at each other with a passionate gaze and nod, like 'So you knew about it too!'#nThat's a fundamental rule of being a ninja, isn't it!?"
1600915-36 = "...Wait, is this your first time hearing about it?"
1600915-37 = "W-well, I suppose director Crow-nyan-nyan's work is a bit old...#nMost of them are black-and-white films, and they're hard to come by these days, but..."
1600915-38 = "...But you learned about it in textbooks, right!?"
1600915-39 = "[s] \"Maybe it wasn't in there!? At least not in my textbooks!\""
1600915-40 = "Anywaaay!#nI can't believe you haven't seen 'The Three Ninjas of the Hidden Classroom'..."
1600915-41 = "It just means you still have so much joy left to experience in your life, Sensei."
1600915-42 = "I'm actually jealous that you get to experience it for the first time now...!"
1600915-43 = "[s] \"Is it really that good...!?\""
1600915-44 = "Of course!"
1600915-45 = "Because I... I stepped into the world of ninjas after watching this movie."
1600915-46 = "[s3] \"A movie that means that much to you...\"\n[s4] \"That's amazing!\""
1600915-49 = "Right!?"
1600915-50 = "[s] \"So, are we having a screening today?\""
1600915-51 = "Hmm...#nIf I could, I'd love to screen it right in the middle of the shopping district, but..."
1600915-52 = "I have a different goal today."
1600915-53 = "...I want to make a backup of this videotape."
1600915-54 = "[s] \"A backup?\""
1600915-55 = "Apparently, a photo studio in the shopping district started a new service."
1600915-56 = "They can digitize videotape footage#nso you can back it up on a computer."
1600915-57 = "If it works, I'll be able to watch it whenever I want!"
1600915-58 = "That's why I brought this tape!"
1600915-59 = "It's precious to me, so I want to make sure it's preserved..."
1600915-60 = "You know, like how ninjas turn sweets or ingredients into pills for long-term storage!"
1600915-61 = "Technically, they're called 'Hyourougan' (ration pills)—"
1600915-62 = "[s] \"Alright, let's go!\""
1600915-63 = "Hey, wait a minute!?#nI was just getting to the good part!"
1600915-69 = "...This looks difficult."
1600915-70 = "W-why...!?"
1600915-71 = "Is it not enough money!?"
1600915-72 = "No, it's an issue with the tape itself."
1600915-73 = "It doesn't look like I can extract the footage from this..."
1600915-74 = "[s] \"Is there really no other way?\""
1600915-75 = "Hmm, it's quite old, so..."
1600915-76 = "Look, the film has several scratches on it."
1600915-77 = "It's a bit too much for us to handle."
1600915-81 = "Ugh... I see."
1600915-82 = "It can't be helped...#nLet's go, Sensei."
1600915-87 = "Hmm, I guess I knew it..."
1600915-88 = "[s] \"Did you know from the start?\""
1600915-89 = "Yeah, it had been broken for a long time."
1600915-90 = "[s] \"I see...\""
1600915-91 = "I've watched it hundreds of times, though..."
1600915-92 = "It just stopped spinning properly."
1600915-93 = "I thought maybe a professional could fix it, but I guess it was a no-go."
1600915-94 = "[s] \"...Are you okay?\""
1600915-95 = "...No, I'm actually really sad!"
1600915-96 = "I can't retrieve those memories anymore..."
1600915-97 = "And besides, I can't get this tape anymore."
1600915-98 = "[s] \"Michiru...\""
1600915-99 = "...Sometimes, I think."
1600915-100 = "If only I had shared this joy with more people sooner..."
1600915-101 = "If I hadn't just enjoyed it by myself, but told others and kept it in more people's memories—"
1600915-102 = "...That's what I thought, anyway."
1600915-103 = "[s] Gently pats Michiru on the head."
1600915-104 = "Hehe... Thanks, Sensei."
1600915-105 = "..."
1600915-106 = "Oh, come to think of it, there should be a ninja supply shop two blocks over!"
1600915-107 = "[s] \"You're moving on pretty fast, aren't you!?\""
1600915-108 = "But, but! Rumor has it they just got in not only the 'Cursed Gun Muramato',#nbut also the real 'Cursed Hand Grenade Masamune'!"
1600915-110 = "Though some critics say Masamune is just an homage, or even that it just ripped off Muramato. It's fairly well-known now, though—"
1600915-112 = "(And even as the two of them walked around the shopping district...)"
1600915-114 = "(Michiru held the videotape close, as if it were something precious.)"