[translation]
1600115-1 = "Lucky Charm"
1600115-2 = "(Following Asuna's directions led to a fierce battle.)"
1600115-8 = "Hey! This is supposed to be a stealth mission, right?#nWe've been spotted completely!"
1600115-9 = "Are you seriously telling me you're infiltrating in an outfit that flashy?"
1600115-10 = "Of course we'd get caught! You've gotta be kidding me!"
1600115-11 = "I don't know what to tell you... This is my uniform, after all—"
1600115-15 = "Oh! I should've just taken it off!"
1600115-19 = "[ns1] \"S-Stop!\"\n[ns2] \"Asuna, I'm here!\""
1600115-23 = "Ah! Sensei! Yoo-hoo!"
1600115-24 = "Alright, Plan B! Frontal assault, start♪"
1600115-28 = "Someone stop her!"
1600115-29 = "Don't let her get past!"
1600115-37 = "(After that, a fierce battle ensued—)"
1600115-39 = "Damn it... I thought we could at least stall her for a bit..."
1600115-40 = "So this is... C&C..."
1600115-46 = "[ns] \"Asuna, are you okay?\""
1600115-47 = "Totally! I'm fine!"
1600115-48 = "Oh, but it looks like I dropped my ribbon.#nI'm gonna go look for it!"
1600115-50 = "Is it around here?"
1600115-54 = "Hmm, I can't find it..."
1600115-58 = "Hey! Don't step on that!"
1600115-59 = "Whoa! Sorry, sorry!"
1600115-60 = "Hey, hey, did you see a blue ribbon?"
1600115-61 = "Huh? I don't know...#nBesides, the spot where you shot me still hurts..."
1600115-62 = "Sorry, sorry! Just take a nice long rest!"
1600115-66 = "Ah!#nFound it!"
1600115-68 = "Sensei, thanks for waiting♪"
1600115-69 = "[s] \"Did you find your ribbon?\""
1600115-70 = "Yep! It was right there!"
1600115-71 = "I'm glad I found it so quickly!#nWell then, let's go report that the mission is complete!"
1600115-76 = "[ns] \"Come to think of it, you're always wearing that ribbon.\""
1600115-77 = "As expected of Sensei, you noticed!#nThat's right! I always wear it~"
1600115-82 = "This is Asuna's lucky charm!#nWhen I wear it, all sorts of things go right!"
1600115-83 = "For example...?"
1600115-84 = "Let's see... there are lots of things, but..."
1600115-85 = "Oh, maybe something like this!"
1600115-86 = "I didn't want to study for a test, so I didn't do it at all, but..."
1600115-87 = "My wild guesses were all correct!!"
1600115-88 = "[s] \"All of them!?\""
1600115-89 = "Yep! All of them! Pretty amazing, right?"
1600115-90 = "Also, at my favorite cafe..."
1600115-91 = "The dessert that's limited to 20 servings a day—"
1600115-92 = "Even when I think it might be sold out, I can still get it!#nThere have even been days where I got the very last one!"
1600115-93 = "[s] \"That's amazing!\""
1600115-94 = "And then, during a battle..."
1600115-95 = "When I'm in a pinch because I'm out of ammo and magazines—"
1600115-96 = "I used the ribbon like a sling and managed to take everyone down!"
1600115-97 = "[s] \"I-Is that really... lucky?\""
1600115-98 = "It's lucky! I think of it as a lucky ribbon that protects me!"
1600115-99 = "It's not frayed at all, right?#nI work hard to take care of it."
1600115-100 = "[s5] \"But like today, it came undone...\"\n[s6] \"What would you do if you really lost it?\""
1600115-103 = "If I really lost it...?"
1600115-104 = "Let's see..."
1600115-105 = "Hmm..."
1600115-106 = "Hmmmmmm..."
1600115-107 = "[s] \"Sorry for asking something weird...!\""
1600115-108 = "It might be okay even if I lost it!"
1600115-109 = "[s] \"Huh?\""
1600115-110 = "I'd be super sad, I'm sure."
1600115-111 = "But, right in front of me—"
1600115-112 = "The greatest stroke of luck is already here, so I'll be fine!"
1600115-113 = "I'm talking about you, Sensei!"
1600115-114 = "So, even if I lose the ribbon, it'll be okay!"
1600115-115 = "[s7] \"Asuna...! That's kind of embarrassing.\"\n[s8] \"But let's try to be careful not to lose it!\""
1600115-118 = "Hehe, yeah!"
1600115-119 = "I'll cherish you and the ribbon more than ever!"
1600115-121 = "(After that, I walked home with Asuna while we talked about our own little bits of luck.)"