[translation]
1601903-1 = "Hobbies (Tentative)"
1601903-3 = "Now, I shall report the results of my reconnaissance."
1601903-4 = "To put it briefly, there was nothing of particular note."
1601903-5 = "[s] \"That's good to hear.\""
1601903-6 = "Yes. I destroyed a few things, caused some explosions, and it served as a nice way to relieve stress."
1601903-7 = "[s] \"That sounds like something of note!?\""
1601903-8 = "However, this is truly a mysterious place."
1601903-9 = "Every time I go out for reconnaissance, something changes even at the same coordinates."
1601903-10 = "The only commonality is that everything is made of metal."
1601903-11 = "If I didn't have coordinate data, I would have been lost before long."
1601903-12 = "It feels as if I am entering a labyrinth."
1601903-13 = "[s1] \"That sounds incredibly dangerous, though...\"\n[s2] \"You don't have to force yourself to do reconnaissance...\""
1601903-16 = "That would be a problem."
1601903-17 = "You might not know this, Sensei, since you don't go to the front lines..."
1601903-18 = "Just a moment ago, three metal, animal-like things came charging toward me."
1601903-19 = "[s] \"Wasn't that dangerous!?\""
1601903-20 = "Yes, it was certainly dangerous."
1601903-21 = "They were so cute that I nearly fainted!"
1601903-22 = "[s] \"...Eh?\""
1601903-23 = "When I approached, they rolled over on the ground and showed me their bellies."
1601903-24 = "When I petted them, they were very happy."
1601903-25 = "[s3] \"I-I'm jealous...!\"\n[s4] \"But are those really metal animals...?\""
1601903-28 = "Presumably."
1601903-29 = "At the very least, the texture was metal through and through."
1601903-30 = "I wanted to bring one back, but they left for somewhere else once they were done playing."
1601903-31 = "...That concludes my report."
1601903-32 = "[s] \"If that's the case, let me join in next time!\""
1601903-33 = "Unfortunately, that is a privilege for those on-site. V-sign."
1601903-34 = "Though, it is a shame that everything I saw and heard here is classified."
1601903-35 = "I can't talk about it on my stream."
1601903-36 = "[s] \"Stream?\""
1601903-37 = "Oh, you aren't aware?"
1601903-38 = "I never imagined Sensei would be so behind the times."
1601903-39 = "But it is fine. I will assist you for the rest of your life."
1601903-40 = "[s5] \"I know what streaming is!\"\n[s6] \"It was just refreshing to hear Toki talk about things like that.\""
1601903-43 = "Oh, you aren't aware?"
1601903-44 = "I never imagined Sensei would be so indifferent to their students."
1601903-45 = "Look at me, I've become so dejected."
1601903-46 = "I've lost all the strength in my body from loneliness and sadness."
1601903-47 = "This is all because Sensei was indifferent."
1601903-48 = "Therefore, Sensei must quickly pet me."
1601903-52 = "(I petted Toki's head...)"
1601903-54 = "That is nice."
1601903-55 = "My energy is restored, perfect."
1601903-56 = "[s] \"I'm glad...\""
1601903-57 = "Now, let us return to the topic."
1601903-58 = "You previously advised me to find a hobby, so I tried various things."
1601903-59 = "In the process, I became interested in streaming."
1601903-60 = "Among them, the culture of 'donations' is quite impressive."
1601903-61 = "The streamer's reaction changes depending on the amount donated."
1601903-62 = "I found the dynamic between the streamer and the viewers very interesting."
1601903-63 = "[s] \"Toki... you aren't doing anything strange, are you...?\""
1601903-64 = "I am not."
1601903-65 = "I am only watching."
1601903-66 = "Besides live streams, there are many interesting videos as well. For example—"
1601903-72 = "Everything Game Playthrough Summary"
1601903-73 = "[Sad News] Is Highlander's mascot 'Shuppo' actually unpopular?"
1601903-77 = "Defeated again, a collection of reactions from Corgi Braves fans"
1601903-78 = "On the correlation between Germanium and negative ions"
1601903-83 = "Peroro's true identity is actually a hippo lol"
1601903-84 = "[s] \"...\""
1601903-85 = "..."
1601903-86 = "The world is full of diversity, isn't it?"
1601903-87 = "[s7] \"W-what should I do...\"\n[s8] \"Toki has been tainted by something strange...\""
1601903-90 = "It is fine. I have not been tainted."
1601903-91 = "...Yet."
1601903-92 = "However, there was one channel that even I felt had a high barrier to entry."
1601903-93 = "...The channel name?"
1601903-94 = "If I recall correctly..."
1601903-95 = "It was called something like 'Girl Ninja Scroll Michiru-chi'..."
1601903-96 = "[s] \"...\""
1601903-97 = "It was about... taking on various challenges, and I tried to watch it to the end, but..."
1601903-98 = "It was quite difficult... a formidable opponent."
1601903-99 = "I should become stronger someday, but it seems it was too early for me at least."
1601903-100 = "[s] \"I don't think you need to become strong in that regard...\""
1601903-101 = "Is that so? I don't quite understand what you mean..."
1601903-102 = "Yes? What do you mean, 'are there others'?"
1601903-103 = "Ah, my hobbies. I have them, technically."
1601903-104 = "But Sensei, watching streams and my other hobbies are strictly (tentative)."
1601903-105 = "I am just interested for the time being, and they might change in a heartbeat."
1601903-106 = "After all, my true hobby is—"
1601903-107 = "..."
1601903-108 = "Let us leave it at that."
1601903-109 = "[s] \"You've gotten good at changing the subject!\""
1601903-110 = "That is also thanks to you, Sensei."
1601903-111 = "Because I am Asuma Toki, who grows day by day."
1601903-112 = "[s] \"Y-yeah, that's true...\""
1601903-113 = "People are constantly influenced by those around them."
1601903-114 = "And through that, they grow little by little."
1601903-115 = "Therefore..."
1601903-116 = "..."
1601903-117 = "The games were also interesting."
1601903-118 = "And the manga."
1601903-119 = "[s] \"It sounds like you'd get along with the Game Development Department.\""
1601903-120 = "Yes. Aris is truly a good rival."
1601903-121 = "I am currently down by one match, but I believe I can make a comeback soon."
1601903-122 = "Compared to her, Yuzu is..."
1601903-123 = "[s] \"Isn't she on a different dimension...?\""
1601903-124 = "You know her well, too, Sensei..."
1601903-125 = "I realized that when faced with an opponent who is too strong, one doesn't even feel frustration."
1601903-126 = "Because in the face of natural disasters like earthquakes or typhoons... people are simply powerless."
1601903-127 = "[s] (Is Yuzu on the level of a natural disaster...)"
1601903-129 = "(We finished our work while chatting about trivial things, and I watched various channels with Toki.)"
1601903-130 = "(I felt a weight on my shoulder, and when I looked over, Toki had fallen asleep before I knew it.)"