[translation]
1601906-1 = "Memories of the Sunrise"
1601906-2 = "—Of course, there are no gaps in our defense system. Rio-sama herself built it, after all."
1601906-3 = "However, one must always be prepared for the unexpected."
1601906-4 = "After all, this is a place where common sense does not apply."
1601906-5 = "[s] \"You're as reliable as ever, Toki.\""
1601906-6 = "Thank you."
1601906-7 = "But there is another reason for this dawn reconnaissance."
1601906-8 = "[s] \"And that is?\""
1601906-9 = "You will understand soon."
1601906-17 = "……It’s just about time."
1601906-21 = "Sensei. Please, look over there—"
1601906-25 = "[wa:2060]— [log=토키 결전]It’s a beautiful sunrise, isn't it?[/log]"
1601906-27 = "— [log=토키 결전]Every day here, [wa:1670]I can observe [wa:510]this scenery.[/log]"
1601906-30 = "[wa:730]— [log=토키 결전]Though, [wa:1120]I only have records[/log]"
1601906-32 = "— [log=토키 결전]from the few days [wa:750]since I arrived here…….[/log]"
1601906-35 = "— [log=토키 결전]So it might not be [wa:920]every single day.[/log]"
1601906-38 = "[ns] \"It's incredibly beautiful…….\""
1601906-39 = "#wait;1000"
1601906-40 = "[wa:1070]— [log=토키 결전]Yes. [wa:1460]But, [wa:1030]from here,[/log]"
1601906-42 = "— [log=토키 결전]it feels like [wa:810]a completely different color.[/log]"
1601906-45 = "— [log=토키 결전]The sky……[/log]"
1601906-47 = "— [log=토키 결전]and the earth glowing [wa:1110]in orange…….[/log]"
1601906-50 = "[wa:890]— [log=토키 결전]I love [wa:1080]the time [wa:630]I spend sharing this view [wa:1140]with you, Sensei.[/log]"
1601906-52 = "— [log=토키 결전]This moment, [wa:1780]where I can convey [wa:1490]what moves my heart…….[/log]"
1601906-55 = "[wa:1900]— [log=토키 결전]This instant [wa:1410]only exists [wa:740]in this very moment.[/log]"
1601906-57 = "— [log=토키 결전]And it will [wa:1190]never return.[/log]"
1601906-60 = "[wa:2510]— [log=토키 결전]Sensei.[/log]"
1601906-62 = "— [log=토키 결전]If the \"end\" [wa:1360]were to come [wa:690]right now—[/log]"
1601906-65 = "[wa:730]— [log=토키 결전]I would [wa:1270]be by your side [wa:1610]to share that moment…….[/log]"
1601906-67 = "— [log=토키 결전]Could I be [wa:770]the \"last one\" with you?[/log]"
1601906-70 = "[ns] \"So this is your favorite spot, Toki.\""
1601906-71 = "Yes."
1601906-72 = "Of course, I am aware that these are conflicting emotions."
1601906-73 = "No matter what, this is enemy territory."
1601906-74 = "Even if I find something I like…… in the next moment, it could become the catalyst for a fatal outcome."
1601906-75 = "But…… humans are selfish creatures, aren't they?"
1601906-76 = "Regardless of the situation, if they feel something is good, they will perceive the situation itself as good."
1601906-77 = "[s] \"I think it's a good thing to find beauty in beautiful things.\""
1601906-81 = "[ns1] \"Because that is—\"\n[ns2] \"proof that you haven't lost hope.\""
1601906-84 = "……I see."
1601906-85 = "……Yes? #nDid my talk of \"the end\" or being the \"last one\" scare you a little?"
1601906-86 = "……."
1601906-87 = "Perhaps you are right. #n\"The end\" is a frightening thing."
1601906-88 = "But it is alright. I am here by your side, Sensei."
1601906-89 = "Above all…… I will absolutely prevent that arrival."
1601906-90 = "That is why I am here, armed and ready."
1601906-94 = "……The sunrise has ended. #nGood times always pass by in the blink of an eye."
1601906-95 = "……."
1601906-97 = "I wish time would just stop right here."
1601906-98 = "To gather these precious memories—"
1601906-99 = "And keep them safe forever."
1601906-101 = "[ns3] \"I agree. I think that would be wonderful.\"\n[ns4] \"But…… isn't the \"now\" we're spending together wonderful too?\""
1601906-104 = "……."
1601906-105 = "Yes, that is true……."
1601906-106 = "You and I……."
1601906-107 = "……."
1601906-108 = "Sensei."
1601906-109 = "[s] \"Hmm?\""
1601906-110 = "Please, stay still for a moment."
1601906-114 = "(As Toki said that—)"
1601906-120 = "(She gently embraced me.)"
1601906-121 = "[ns] \"Toki!?\""
1601906-122 = "Shh. Someone might wake up."
1601906-123 = "Just for a little while…… just a tiny bit is fine."
1601906-125 = "……."
1601906-126 = "Since I cannot stop time……."
1601906-127 = "Please, let me engrave this deeply…… into my memory."
1601906-131 = "……Thank you, Sensei."