[translation]
2005303-1 = "Ninja Girl is Embarrassed!"
2005303-2 = "Hyakkiyako Shopping District"
2005303-3 = "Yes, here is the dress you asked for."
2005303-4 = "Ooh...!"
2005303-5 = "...Wow, it's beautiful!"
2005303-6 = "I can't even tell where the torn part was!"
2005303-7 = "So this is the skill of a professional...!"
2005303-8 = "[s] \"I'm glad, Michiru.\""
2005303-9 = "Fufufu... but it's not over yet."
2005303-10 = "Wait just a moment, Sensei-dono!"
2005303-15 = "(5 minutes later...)"
2005303-16 = "Sensei-dono!"
2005303-18 = "Now then, let's head to our next destination!"
2005303-19 = "[ns] \"Why!?\""
2005303-20 = "Fufu, it's not a matter of 'why'..."
2005303-21 = "Clothes are, after all, meant to be \"worn.\""
2005303-22 = "In other words, the only way to know if it's truly been repaired is to try it on!"
2005303-23 = "[s] \"You are actually... making sense!?\""
2005303-24 = "How-ever... just putting it on isn't enough!"
2005303-25 = "Walking, running, lifting heavy stuff!"
2005303-26 = "Only after trying various movements..."
2005303-27 = "We will be able to tell if it's perfectly fixed!"
2005303-28 = "[s] \"You have a point, but...\""
2005303-29 = "Right?"
2005303-30 = "So, I've come up with the perfect course for that!"
2005303-31 = "If we go that way, there are shops selling various goods."
2005303-32 = "And over there is the shop we went to together before."
2005303-33 = "If we walk through the street while shopping...!"
2005303-34 = "Walking, running, lifting heavy objects!#nAll the necessary movements are included!"
2005303-35 = "Besides, I heard they have new goods... I mean, ninja tools in stock!"
2005303-36 = "Haiya, this will surely make even more people realize the charm of ninjas!"
2005303-37 = "[s] \"So that was your real goal after all!?\""
2005303-38 = "I knew you'd come with me, Sensei~!"
2005303-39 = "[s] \"I haven't even said anything yet!?\""
2005303-40 = "It's fine, it's fine! Well then, let's go~!"
2005303-46 = "Hyakkiyako Goods District"
2005303-47 = "(In the end, I was dragged to the shopping street by Michiru.)"
2005303-48 = "Come on, come on, get fired up!"
2005303-49 = "Even for the same goods, the prices can vary from shop to shop..."
2005303-50 = "We have to stay alert and keep a sharp eye out!"
2005303-51 = "Well, ninja go-... I mean, ninja tools are generally around the same price anyway."
2005303-52 = "There aren't many places that sell them in the first place, so there isn't much to compare..."
2005303-53 = "...Hm?"
2005303-54 = "Ah, Matryoshka shuriken!"
2005303-55 = "A special ninja tool with a smaller shuriken inside the shuriken!"
2005303-56 = "An unavoidable weapon where, even if you dodge the first shuriken,#nanother one appears!"
2005303-57 = "Ever since it appeared in a work by director 'Kai Ken Gururu',#nit's been paid homage to all over the place!"
2005303-58 = "Ah, over here is... a ninja fire smoke bomb!"
2005303-59 = "A rare ninja tool that, when exploded, shoots out flames instead of smoke,#nallowing you to attack while blinding enemy's vision!"
2005303-60 = "[s] \"Isn't that just a missile...?\""
2005303-61 = "Well, well, don't worry about the minor details."
2005303-62 = "*Gasp*, this is... an ancient ninja hologram scroll!?"
2005303-63 = "They even have something like this here!?"
2005303-70 = "(And so, I spent some time with Michiru looking at ninja goo... ninja tools.)"
2005303-72 = "Unya~, that was fun."
2005303-73 = "Since I spent money on repairing my clothes, I could only buy a shuriken, but... "
2005303-74 = "It was fun being able to go shopping together."
2005303-75 = "...Um, Sensei-dono."
2005303-76 = "...Thank you for listening to my selfish whims."
2005303-77 = "[s] \"No problem, I had fun too.\""
2005303-78 = "R-Really...?"
2005303-79 = "Fufu... Fufun!"
2005303-80 = "O-Oh, right...!"
2005303-81 = "This is for you, Sensei-dono! "
2005303-82 = "[s] \"...A capsule?\""
2005303-83 = "I just got it from the gashapon a moment ago!"
2005303-84 = "It is none other than a ninja capsule!"
2005303-85 = "Well, I don't know what's inside, but..."
2005303-86 = "Consider the excitement of opening it part of the present!"
2005303-87 = "Now, let's open it!"
2005303-89 = "...Huh?"
2005303-92 = "[wa:1250]― [log=미치루 드레스]Inside... [wa:2300]Is a ring, [wa:1080]right!? [/log]"
2005303-94 = "― [log=미치루 드레스]It has a shuriken decoration, and [wa:2440]it looks [wa:1940]pretty good... right!? [/log]"
2005303-97 = "[ns] \"Since you went to the trouble of getting it for me, maybe I'll try putting it on.\""
2005303-98 = "[wa:440]― [log=미치루 드레스]…… [wa:890]Eh? [wa:1210]Sensei-dono, [wa:1800]you're going to put it on...? [/log]"
2005303-100 = "― [log=미치루 드레스]Ah, [wa:1010]no, [wa:960]it's fine, but... [/log]"
2005303-103 = "[wa:1570]― [log=미치루 드레스]（Wait... [wa:1250]giving a ring [wa:1180]to someone...?）[/log]"
2005303-105 = "― [log=미치루 드레스]（Isn't this... [wa:1420]like a confession, [wa:1540]just like that―?）[/log]"
2005303-108 = "[wa:380]― [log=미치루 드레스]W-Wait, [wa:400]wait a minute [wa:790]Sensei-dono! [/log]"
2005303-110 = "― [log=미치루 드레스]It's not [wa:480]like I was aiming for this...! [wa:1890]But, [wa:500]um...! [/log]"
2005303-113 = "[ns] \"W-What's wrong!?\""
2005303-114 = "[wa:2040]― [log=미치루 드레스]Uu... [wa:840]Uwaaaa~~!! [/log]"
2005303-117 = "...Uuuuu"
2005303-118 = "Ah, um...!"
2005303-119 = "Uuu~~~, eeeiiiih!"
2005303-120 = "Poof!"
2005303-121 = "[ns] \"...\""
2005303-123 = "(When the smoke cleared, Michiru was gone.)"
2005303-124 = "(...Only the capsule remained in the palm of my hand.)"