[translation]
2005705-1 = "Side by Side"
2005705-6 = "(Arrived at the meeting spot with Akane)"
2005705-7 = "(It was an empty classroom where no one else was around)"
2005705-12 = "――Guess who?"
2005705-13 = "[s] \"！？！？！？\""
2005705-15 = "[ns] \"A-Akane！！？？\""
2005705-16 = "Fufu, correct♪"
2005705-19 = "Welcome, Sensei. I've been waiting for you."
2005705-20 = "Oh my... it seems I really startled you. #nMy apologies."
2005705-21 = "[s1] \"It's alright.\"\n[s2] \"By the way, where are we?\""
2005705-24 = "Ah, this classroom is..."
2005705-25 = "...Fufu."
2005705-26 = "I requested to reserve it for the next two hours, so――no one will come."
2005705-27 = "Why are you so bewildered...?"
2005705-28 = "Could it be that you don't trust me?"
2005705-29 = "[s] \"That's not it! It's not that I don't trust you...!\""
2005705-30 = "Then――there shouldn't be a problem, right?"
2005705-36 = "I, too... trust you more than anyone else, Sensei."
2005705-37 = "(I could only nod at Akane's soft, insistent voice...)"
2005705-40 = "The reason I called you here is..."
2005705-41 = "I wanted to show you how I've changed thanks to your guidance last time."
2005705-42 = "But I felt that just telling you with words wouldn't be enough to express it... #nSo I thought I'd convey it to you in a slightly special way."
2005705-43 = "[s3] \"In that case, wouldn't it be better if we weren't alone in a classroom...?\"\n[s4] \"I think it's fine, isn't it?\""
2005705-46 = "So, I thought of this."
2005705-47 = "They say seeing is believing, don't they?"
2005705-48 = "Therefore, I decided to show you directly, Sensei."
2005705-49 = "The method is――"
2005705-50 = "Fufu."
2005705-54 = "Sensei..."
2005705-55 = "From now on, we are――"
2005705-56 = "Classmates."
2005705-60 = "[ns] \"！？！？！！！！！\""
2005705-63 = "(And so, I ended up playing 'classmates' with Akane)"
2005705-64 = "(I was wondering if this was the right way to interact with a student, but then――)"
2005705-69 = "Guess who?"
2005705-70 = "[s] \"Akane...?\""
2005705-71 = "Fufu, that's right."
2005705-76 = "What's wrong?"
2005705-77 = "[USERNAME]?"
2005705-78 = "Ah, the glasses?"
2005705-79 = "I tried a little makeover..."
2005705-80 = "Did you prefer me with glasses, [USERNAME]? #nI worked hard to put in contacts, too. What a shame."
2005705-81 = "[s] \"That's not true at all.\""
2005705-82 = "Fufu. I'm glad."
2005705-83 = "Come to think of it, earlier――"
2005705-86 = "(Akane continued to talk happily)"
2005705-87 = "(While talking, I really felt like I had become Akane's classmate)"
2005705-90 = "...If I can interact with you like this, do you wonder why I haven't done it until now?"
2005705-91 = "..."
2005705-92 = "Even now, I don't have that much confidence."
2005705-93 = "Even the version of me I'm showing you right now, I feel like I'm just playing a role."
2005705-94 = "...I think it's only natural to play the version of yourself you want to show. #nBut――"
2005705-95 = "I think I'm... afraid."
2005705-96 = "[s] \"Afraid of everyone finding out your true self?\""
2005705-97 = "That's close, but... maybe a little different."
2005705-102 = "...Who I actually am. #nI'm afraid of everyone finding out that 'I don't even know myself'."
2005705-103 = "I think I can meet other people's expectations."
2005705-104 = "But no matter how much I try to know what kind of person I am, I just can't see it."
2005705-107 = "I think I'm good at reading the room. #nLike choosing my words so that the other person doesn't feel bad, things like that."
2005705-108 = "...It's also essential as a maid."
2005705-109 = "But that's what the other person wants, it's not showing them what's inside me, right?"
2005705-110 = "...I don't even know what's inside me yet."
2005705-111 = "That's why I think I'm empty. No matter how much I talk, or what appropriate words I say."
2005705-112 = "...I can't go any further than that."
2005705-113 = "I'm the one building the invisible wall... I know that much. #nBut I don't know how to break it down."
2005705-114 = "Like you said, [USERNAME], I've tried to reach out little by little. #nSo I do feel like I'm changing, bit by bit."
2005705-115 = "But I also think that's just a temporary fix."
2005705-119 = "...I'm sorry. Even though you took the time to listen to me."
2005705-120 = "Even though you thought about it with me, this is all I can say."
2005705-122 = "...It all went to waste."
2005705-126 = "Why does it have to be like this..."
2005705-129 = "[ns] \"Thank you for talking to me like this.\""
2005705-130 = "...Yeah."
2005705-131 = "Because..."
2005705-132 = "...You're special, [USERNAME]."
2005705-133 = "One of the few people I can open my heart to――"
2005705-134 = "No, maybe the only one..."
2005705-135 = "Because you're that person..."
2005705-136 = "[s5] \"Yeah. I hope we can increase the number of people like me, little by little.\"\n[s6] \"Of course, it will take time and it will be difficult.\"\n[s7] \"Besides, I'm not exactly confident in answering Akane's worries either.\""
2005705-140 = "...You too, [USERNAME]...?"
2005705-141 = "..."
2005705-142 = "I see..."
2005705-143 = "So even for you, [USERNAME]... there isn't anyone you can talk to on the same level――"
2005705-144 = "[s] \"I'm really happy that Akane opened up to me like this.\""
2005705-145 = "..."
2005705-146 = "Fufu."
2005705-147 = "You know, I think about it sometimes."
2005705-148 = "What if we had met in a different form, at a different time, in a different relationship?"
2005705-149 = "If that happened――how would we have spent our time?"
2005705-150 = "[s] \"Is it different now?\""
2005705-151 = "Fufu."
2005705-152 = "I suppose, yeah. #nCertainly, that's how it is now."
2005705-153 = "..."
2005705-154 = "Um... [USERNAME]."
2005705-155 = "[s] \"What is it?\""
2005705-156 = "Stay right there."
2005705-160 = "(The moment I tried to ask why――)"
2005705-164 = "Gotcha♪"
2005705-165 = "[ns] \"！！？？！！！！！？？？\""
2005705-166 = "(All five senses were filled with Akane――)"
2005705-167 = "Shh."
2005705-168 = "Don't make too much noise. #nSomeone might hear us."
2005705-172 = "...Thank you, [USERNAME]."
2005705-173 = "For saying that――"
2005705-174 = "And for listening to me all this time."
2005705-175 = "I'm truly happy."
2005705-176 = "Yeah... I mean that from the bottom of my heart."
2005705-178 = "..."
2005705-179 = "[s] \"……。\""
2005705-180 = "Hello, Sensei."
2005705-181 = "[s] \"Hey, Akane.\""
2005705-184 = "[wa:350]― [log=아카네 교복]Fufu.[/log]"
2005705-187 = "― [log=아카네 교복]It's more...[/log]"
2005705-189 = "― [log=아카네 교복]embarrassing than I thought.[/log]"
2005705-192 = "[wa:1530]― [log=아카네 교복]Being honest... [wa:2200]with myself.[/log]"
2005705-194 = "― [log=아카네 교복]It's a feeling I just can't [wa:1100]get used to.[/log]"
2005705-197 = "[ns] \"W-well, it is your first time, after all...?\""
2005705-198 = "[wa:520]― [log=아카네 교복]Yes, [wa:1330]as you say.[/log]"
2005705-201 = "― [log=아카네 교복]For me,[/log]"
2005705-203 = "― [log=아카네 교복]I think it was necessary.[/log]"
2005705-206 = "[wa:530]― [log=아카네 교복]I've caused you [wa:1630]a lot of [wa:900]trouble, Sensei.[/log]"
2005705-209 = "― [log=아카네 교복]Even so, [wa:1910]meeting you, Sensei, [wa:3240]I am――[/log]"
2005705-212 = "― [log=아카네 교복]Yes, [wa:1240]I truly think [wa:1550]I was lucky.[/log]"
2005705-215 = "[wa:1850]― [log=아카네 교복]Everything flows,[/log]"
2005705-217 = "― [log=아카네 교복]and will eventually [wa:360]be forgotten.[/log]"
2005705-220 = "― [log=아카네 교복]Even this [wa:810]moment, [wa:2830]someday...[/log]"
2005705-223 = "[wa:1700]― [log=아카네 교복]However, [wa:1550]I will remember.[/log]"
2005705-225 = "― [log=아카네 교복]Even if [wa:530]you, Sensei, [wa:470]forget.[/log]"
2005705-228 = "― [log=아카네 교복]Because things that are truly precious,[/log]"
2005705-230 = "― [log=아카네 교복]are never lost.[/log]"
2005705-233 = "(Just like when I entered the classroom)"
2005705-234 = "(Akane was gone, as if she had never been there from the start)"
2005705-235 = "(I thought it might have all been a dream)"
2005705-236 = "(But what Akane left behind spoke silently that it was anything but...)"