[translation]
2005306-1 = "Ninja Girl is Sensitive to Trends!"
2005306-3 = "[ns] \"Michiru?\""
2005306-8 = "Good day, Sensei-dono."
2005306-12 = "[ns] \"!?\""
2005306-13 = "What's with that reaction!?"
2005306-14 = "It's me, Michiru, Sensei-dono!?"
2005306-15 = "[s1] \"Knocking so politely before entering...\"\n[s2] \"You're not the Michiru I know!?\""
2005306-18 = "Unyaa!?#nWhat do you think I am!?"
2005306-19 = "...N-Never mind, don't say it. I'm afraid to know."
2005306-20 = "Aaaanyway! Today I'm a little different!"
2005306-21 = "Believe it or not, I've even prepared a \"briefing\"!"
2005306-22 = "[s] \"A briefing...!\""
2005306-23 = "Yep!"
2005306-24 = "\"Girl's Ninpocho Michirutchi: Growth Secret and Plan Presentation Briefing\"!"
2005306-25 = "Fufufu, curious, aren't you?"
2005306-26 = "[s] \"Is this what you were talking about on Momotalk?\""
2005306-27 = "Correct!"
2005306-28 = "A secret I came up purely on my own, without relying on any weird methods...!"
2005306-29 = "Well then, I will begin the briefing!"
2005306-30 = "――First, the conclusion!"
2005306-31 = "[s] \"You're starting with the conclusion!?\""
2005306-32 = "It is――"
2005306-33 = "When making videos, reflecting the latest trends is best!"
2005306-34 = "Even if it means the ninja talk gets reduced a liiiitle bit..."
2005306-35 = "[s3] \"Even though it's a ninja channel...?\"\n[s4] \"Is that okay?\""
2005306-38 = "Taking one step back to take ten steps forward... That's what it means!"
2005306-39 = "I mean, look, what do you think is the biggest reason people want to#nwatch a video?"
2005306-40 = "...That is, the number of views!"
2005306-41 = "[s5] \"To get views, you need views...\"\n[s6] \"Like a chicken or the egg situation...?\""
2005306-44 = "But actually, people just aren't interested in videos with low views...!"
2005306-45 = "I don't plan on using any weird tools, but I'll increase my views#nby any other means necessary!"
2005306-46 = "I'm sure the viewers will enjoy it more that way! Probably."
2005306-47 = "So today, I'm going to upload a video reflecting the latest trends!"
2005306-48 = "[s] \"Like what kind of content, for example?\""
2005306-49 = "Fuhuhu, good question, Sensei-dono!"
2005306-50 = "The keyword I chose this time is... \"Fashion\"!"
2005306-51 = "[s] \"Fashion...!\""
2005306-52 = "Yep, the era of \"Fashion\" is here."
2005306-53 = "When I analyzed the \"Trending Videos\"..."
2005306-54 = "The top of the rankings were all fashion-related!"
2005306-55 = "\"7 T-shirts You Won't Get Tired of Wearing Every Day\", \"Finding Your Personal#nColor Hand Grenade\", or \"Outerwear That Perfectly Matches Your Gun\"..."
2005306-56 = "I hopped on that trend and immediately planned something out!"
2005306-57 = "[s] \"Oh, what kind of content?\""
2005306-58 = "That is~...! "
2005306-59 = "...Ta-da!#nA combination of fashion and ninjutsu!"
2005306-60 = "I'm going to invent fashion-related ninjutsu and upload a video every week!"
2005306-61 = "Draw viewers in with this content..."
2005306-62 = "And if I upload authentic ninja content in between..."
2005306-63 = "Everyone, will be captivated by ninjas before they know it!"
2005306-64 = "Just like a boiled frog!"
2005306-65 = "[s] \"I don't know about that analogy!?\""
2005306-66 = "Anyway, this concludes the briefing...!"
2005306-67 = "I'll let the results speak for themselves!"
2005306-68 = "Therefore, Sensei-dono, please look forward to it!"
2005306-69 = "I'll become a super famous influencer and scout you to be my manager,#nSensei-dono!"
2005306-70 = "With that, I'm done talking for today!#nAdios = SAYONARA!"
2005306-76 = "(Even though she used a smoke grenade, it's completely obvious#nwhere she went...)"
2005306-78 = "(A few days later)"
2005306-80 = "(As I was struggling to organize through piles of paperwork today...)"
2005306-81 = "Sensei-dono..."
2005306-85 = "Saaaaave meee..."
2005306-86 = "[s7] \"...Michiru! Did you become a star and come to pick me up!?\"\n[s8] \"Take me away from this paperwork hell...!\""
2005306-89 = "Ehh!?#nNo, I came here hoping you'd save me...!"
2005306-90 = "[s] \"...Eh?\""
2005306-91 = "The other day, I uploaded that video combining fashion and ninjutsu..."
2005306-92 = "The reaction was extremely bad..."
2005306-93 = "It has a crazy amount of dislikes compared to my previous videos...!"
2005306-94 = "[s] \"Have you checked the video and comments?\""
2005306-95 = "..."
2005306-96 = "Um, I was too scared..."
2005306-97 = "So, um, I was wondering if you could watch it with me, Sensei-dono..."
2005306-98 = "[s] \"Alright, let's take a look.\""
2005306-99 = "Thaaanks, Sensei-dono..."
2005306-101 = "(And so, we decided to watch Michiru's video.)"
2005306-106 = "Hyakkiyako, a certain classroom in Old School Building 38"
2005306-107 = "Girl's Ninpocho, Michirutchi~!"
2005306-108 = "Good day.#nI am Michiru."
2005306-109 = "Now then, the ninjutsu I will be showcasing today is~... the \"Quick Change Jutsu\"!"
2005306-110 = "A practical ninjutsu that, if used properly, allows you to change into complex#noutfits in an instant!"
2005306-111 = "Seeing is believing..."
2005306-112 = "Let me demonstrate first!"
2005306-113 = "However, just in case..."
2005306-114 = "Harya!"
2005306-119 = "[ns] (Did she put a cover on the lens...?)"
2005306-121 = "And with that, ta-da!"
2005306-122 = "Changing clothes is done in a flash!"
2005306-123 = "Now, for the secret reveal――"
2005306-124 = "(Because the lens was covered...)"
2005306-125 = "(...nothing was recorded until the very end.)"
2005306-126 = "Schale Office"
2005306-127 = "..."
2005306-128 = "[ns] \"....\""
2005306-129 = "S-S-S-Such a beginner's mistake...!!"
2005306-130 = "Uhayaaaaa!!"
2005306-136 = "(Perhaps the shock was too much, as she disappeared without even using a smoke bomb.)"