[translation]
2005502-1 = "Locker Phobia"
2005502-4 = "Game Development Department - Clubroom"
2005502-5 = "[ns] \"Are you okay!? What happened!?\""
2005502-6 = "Sensei, you don't need to panic so much...!"
2005502-7 = "It's really no big deal..."
2005502-8 = "Uuuu... It's definitely tough for suddenly not being able to do what I was able to do anymore, that is true."
2005502-9 = "That is true, but..."
2005502-10 = "......"
2005502-11 = "A-Actually... well."
2005502-12 = "Even when I get inside the locker, I cannot feel calm anymore..."
2005502-13 = "[s1] \"That is definitely a serious situation.\"\n[s2] \"Your status is not normal.\""
2005502-16 = "I-If you say it like that... maybe, I am."
2005502-17 = "[s] \"Since when did this start?\""
2005502-18 = "Um... probably... I guess..."
2005502-19 = "I think it started around the time we came back from the Steel Continent."
2005502-20 = "[s3] \"Maybe when you go into dark places...\"\n[s4] \"The memories from back then come back?\""
2005502-23 = "N-No. Dark places themselves are fine."
2005502-24 = "But I am sure the memories from that time are the cause..."
2005502-25 = "......"
2005502-26 = "Um... when I enter a tight space, I feel like the floor might give away..."
2005502-27 = "[s] \"The floor?\""
2005502-28 = "Yes... I remember when I entered the transport ship's dropping pod."
2005502-29 = "If I sit in a tight place, I feel like the floor will open and I'll fall...#nand I worry that a battle will start just like that..."
2005502-30 = "That anxiety filled my mind.... and I couldn't stay in the locker any longer."
2005502-31 = "[s] \"That is a problem.\""
2005502-32 = "B-But, Sensei."
2005502-33 = "At the opposite... maybe it is a good thing..."
2005502-34 = "[s] \"Good thing?\""
2005502-35 = "Yes, since I cannot shut myself in the locker anymore..."
2005502-36 = "This is a great opportunity... I could go out more like other people."
2005502-37 = "Maybe I could hang out with lots of people..."
2005502-38 = "Then maybe I could become normal... That's what I thought..."
2005502-39 = "[s] \"Do you really mean that?\""
2005502-40 = "......"
2005502-41 = "......Sensei, what do you think?"
2005502-42 = "[s5] \"I think it's great that you're willing to change.\"\n[s6] \"But I'm a little worried about what triggered that change.\""
2005502-45 = "......You are right."
2005502-46 = "I...I might not be properly prepared to go outside yet."
2005502-47 = "When strangers or Yuuka-senpai suddenly come to the clubroom, I need a place to hide..."
2005502-48 = "[s] \"Then we don't have a choice.\""
2005502-52 = "[ns] \"How about we train getting into the locker?\""
2005502-53 = "Eh? T-Training...? That is..."
2005502-54 = "S-Sensei!?"
2005502-60 = "Wh-Why do I have to wear this outfit!?"
2005502-61 = "[ns] \"This is the one! UZQueen battle mode!\""
2005502-62 = "What do you mean 'this is the one'!?#nI am just entering a locker...!?"
2005502-63 = "...Eh?#nAm I entering the locker just like this...?"
2005502-64 = "W-Wait, this is...!"
2005502-65 = "It is actually pretty scary..."
2005502-66 = "B-but this outfit actually makes that moment come back to me clearly...!"
2005502-67 = "Uuuuu.....#nThe memory of the emergency eject from the cockpit of NEO AVANT GUARD-kun"
2005502-72 = "...Huh?"
2005502-74 = "(I firmly hold Yuzu's anxious hands.)"
2005502-75 = "Se... Sensei? Why are you holding my hands..."
2005502-76 = "Should I just sit inside the locker...?"
2005502-77 = "L-Like this...?"
2005502-83 = "Well, this definitely... might be a little..."
2005502-89 = "[ns] \"How is it?\""
2005502-90 = "I-I don't really know..."
2005502-91 = "I feel a little bit relieved..."
2005502-92 = "I wonder why... the situation hasn't changed much from before."
2005502-93 = "But somehow, I feel calm..."
2005502-94 = "[ns] \"Maybe because I'm holding your hand, Yuzu.\""
2005502-96 = "[ns7] \"Even if the floor collapses or something explodes, it's okay.\"\n[ns8] \"I'll always be holding onto you so you don't fly away.\""
2005502-99 = "Always holding on... me..."
2005502-100 = "......"
2005502-101 = "Ah..."
2005502-102 = "Thank you, Sensei."
2005502-107 = "(I spent a peaceful time in the locker, holding Yuzu's hand.)"