[translation]
2005302-1 = "The Ninja Girl Seeks Treatment!"
2005302-2 = "Hyakkiyako - A Classroom in the Old School Building #38"
2005302-3 = "(Worried, I headed over to Michiru.)"
2005302-6 = "Se-Sensei...!?"
2005302-7 = "You actually came!?"
2005302-8 = "[s] \"Michiru, are you okay!?\""
2005302-9 = "Ah, n-no, well..."
2005302-10 = "I did say I was injured, but..."
2005302-11 = "...Well, it's not actually me."
2005302-12 = "[s] \"...?\""
2005302-13 = "Um... it's more like my clothes got 'injured'."
2005302-14 = "...To be precise, my dress."
2005302-15 = "It's pretty badly damaged, like this..."
2005302-16 = "[s] \"Whoa... what happened?\""
2005302-17 = "Well..."
2005302-18 = "I was practicing the Ninja Art: 'Climb-Climb Kunugi' and fell out of a tree..."
2005302-19 = "[s1] \"In other words...\"\n[s2] \"You ruined your clothes while climbing a tree.\""
2005302-22 = "That's how you summarize it!?"
2005302-23 = "It makes it sound like I was just messing around and tore my clothes!"
2005302-24 = "...Well, I guess that's not entirely wrong."
2005302-25 = "...A-and I wasn't just playing around, okay!?#nIt was strictly training!"
2005302-26 = "Mmph..."
2005302-27 = "...Sensei, you really still have a shallow understanding of ninjas!"
2005302-28 = "So!"
2005302-29 = "I shall give you a lecture on ninjas while we head to the tailor!"
2005302-31 = "(And so, I ended up heading to the tailor with Michiru.)"
2005302-33 = "Hyakkiyako Shopping District"
2005302-35 = "...In other words, ninjas wear clothes other than black!"
2005302-36 = "Black outfits that cover your face are only for nighttime use."
2005302-37 = "During the day, they stand out, so we usually wear normal clothes."
2005302-38 = "The foundation of being a ninja is 'not standing out'..."
2005302-39 = "You must dress appropriately for the situation!"
2005302-40 = "For example, if you're on a mission at a party, you might wear a dress like this..."
2005302-41 = "Of course, if it's at night, black is fine too."
2005302-42 = "Some say that for camouflage, one ninja didn't wear any clothes at all and just painted their body with ink..."
2005302-43 = "And lately, there's even stuff like optical camouflage ninja suits—"
2005302-53 = "[ns] \"Wait, isn't this the place?\""
2005302-54 = "...Oh!"
2005302-55 = "Welcome~"
2005302-56 = "Um, I'd like to get this torn dress repaired..."
2005302-57 = "Yes, I understand.#nMay I take it from you?"
2005302-58 = "Okay..."
2005302-62 = "...Ah."
2005302-64 = "I'm wearing it right now, aren't I!?"
2005302-66 = "Um, do you have a change of clothes?"
2005302-67 = "...I don't."
2005302-68 = "Is there any way to fix it while I'm still wearing it...?"
2005302-69 = "Since I use a sewing machine, that would be quite dangerous..."
2005302-70 = "I figured as much..."
2005302-71 = "Ugh, and we came all this way...!"
2005302-72 = "Ugh, well, there is one way..."
2005302-73 = "If I change into my ninja outfit...!"
2005302-74 = "[s] \"Didn't you just say you didn't have a change of clothes?\""
2005302-75 = "It's fine, it's fine!"
2005302-76 = "Like a certain ninja from the legends, I can just paint myself with ink!"
2005302-77 = "[s] \"...Is that really okay?\""
2005302-78 = "Hehe, for a ninja, that's nothing..."
2005302-79 = "..."
2005302-83 = "N-no way! That's not okay!"
2005302-84 = "Absolutely not!"
2005302-85 = "Se..."
2005302-86 = "Sensei, you pervert!!"
2005302-87 = "[s3] \"Wait, me!?\" \n[s4] \"That's a false accusation...!\""
2005302-91 = "(Afterward, Michiru changed into some gym clothes she bought nearby and left the dress to be repaired.)"
2005302-92 = "(...I paid for the repairs.)"