[translation]
2005505-1 = "Game Tournament"
2005505-2 = "Game Development Department - Clubroom"
2005505-3 = "I had no idea that \"Virtual Boss\" is the prize for game competitions..."
2005505-4 = "Well, considering how popular it is, I think the prize makes sense."
2005505-5 = "D-Don't tell me, the method Sensei mentioned is..."
2005505-6 = "To win \"Virtual Boss\" at a tournament...!?"
2005505-10 = "It's going to be an uphill climb..."
2005505-11 = "[s] \"You don't want to do it?\""
2005505-12 = "No- let me do it, Sensei!#nIf it is a game, I...!"
2005505-13 = "...O-Oh, right.#nWhich game is used for the tournament..."
2005505-14 = "Simulion Quest...!?#nThe VR game I played with Sensei before...!"
2005505-15 = "...Well, if that's the case, we might just win."
2005505-16 = "But, I still don't have the confidence to get top rank on my own..."
2005505-17 = "[s] \"That's why I applied in Co-op round for both of us.\""
2005505-21 = "Eeeh!? You are going to participate with me, Sensei!?"
2005505-22 = "You cannot send a battle buddy to the battlefield alone...?"
2005505-23 = "You are right... In Simulion Quest, it is already difficult for me to even pass the preliminaries..."
2005505-24 = "...Thank you, Sensei. Let's aim for the championship together...!"
2005505-25 = "[s1] \"By the way, Yuzu.\"\n[s2] \"It seems there's one more requirement to participate in the Simulion Quest tournament.\""
2005505-28 = "Participation requirements...?"
2005505-30 = "(A while later, on the day of the Game Tournament.)"
2005505-32 = "Game Tournament Venue Entrance"
2005505-34 = "No way!!!"
2005505-35 = "I trust you sensei... I trust you!"
2005505-36 = "[s] \"Calm down, Yuzu.\""
2005505-40 = "[ns3] \"Everyone is just wearing in-game costumes, you know?\"\n[ns4] \"Just think of it as a normal cosplay venue, you'll be fine.\""
2005505-43 = "E-Even if you say that... there are people in normal clothes too..."
2005505-44 = "S-Sensei, you came in your usual clothes!"
2005505-45 = "[s5] \"This is the outfit of the citizen NPC that appears in the game.\"\n[s6] \"Suits are the armor of adults, after all.\""
2005505-48 = "I-If that's the case, I would have preferred my normal uniform too..."
2005505-49 = "Well, this outfit makes it easiest to play VR games, but..."
2005505-50 = "[s] \"Ah, looks like it's starting. Let's go, Yuzu!\""
2005505-51 = "Fweeeeeeeehn...!!"
2005505-53 = "(After that, Yuzu glued to my back for the entire match.)"
2005505-55 = "Inside Game Tournament Venue"
2005505-56 = "Alright! The excitement is at its peak!"
2005505-57 = "Finally, the championship match! Let's welcome the parties to the stage!"
2005505-58 = "The legendary duo that reached the top in record time—"
2005505-59 = "「UZQueen & Thrones」! Please welcome them with a round of applause!"
2005505-64 = "UZQueen...? They just said UZQueen, right!?"
2005505-65 = "She really is here! Wow... amazing! She has that aura!"
2005505-66 = "But, what the heck is that pose...?"
2005505-72 = "The duo defeating opponents in a piggyback position... was UZQueen!?"
2005505-73 = "A chance to see UZQueen's play live... I have to burn this into my memory!"
2005505-74 = "U-Uuuu... Sensei, piggybacking in front of everyone is just too embarrassing...!"
2005505-75 = "I-It's so embarrassing I can't really concentrate..."
2005505-76 = "on the game..."
2005505-77 = "[s] \"Yuzu.\""
2005505-78 = "Y-Yes!?"
2005505-79 = "[s] \"For now, just think that the world of Simulion Quest is real.\""
2005505-80 = "B-But..."
2005505-81 = "If this is reality...#nWe're risking our lives swinging swords right now... actually it's scarier..."
2005505-82 = "I know immersion is important, but..."
2005505-86 = "Sigh... So to win, we have to defeat UZQueen..."
2005505-87 = "I never guessed that weird piggybacking master was UZQueen... What should we do?"
2005505-88 = "There's no site that has a guide on how to beat an opponent who is piggybacking!"
2005505-89 = "It's okay, I created a winning strategy for times like this."
2005505-90 = "Not on UZQueen, but on Thrones— her partner is a normal player, so if we defeat him first, we have a chance!"
2005505-91 = "Alright...!"
2005505-93 = "S-Sensei! Please be careful!"
2005505-94 = "[ns] \"Huh, am I the one being targeted...?\""
2005505-97 = "(If this game were reality...)"
2005505-98 = "(This outfit, everyone's gazes— I'm not embarrassed at all because...)"
2005505-99 = "(What I really need to worry about right now is...)"
2005505-100 = "...Look out!"
2005505-105 = "W-What happened...?"
2005505-106 = "Did both of our weak points got struck...?"
2005505-110 = "Incredible! The match was over in the blink of an eye!#n「UZQueen & Thrones」 are the winners!"
2005505-111 = "D-Did you see that? The moment Thrones was targeted, UZQueen hit both their weak points with incredible speed...!"
2005505-112 = "It was so fast I couldn't see it at all... Is that a movement possible in reality...?"
2005505-114 = "S-Sensei. Are you okay...?"
2005505-115 = "[s] \"I'm okay.\""
2005505-119 = "[ns] \"How'd you pull off that attack?\""
2005505-120 = "I-I don't know either..."
2005505-121 = "When I thought Sensei was in danger, my hands just moved on their own..."
2005505-122 = "Before I knew it, I was aiming for their weak points..."
2005505-123 = "[s] \"That was an amazing concentration...\""
2005505-124 = "B-But I'm glad.#nNow we can finally get \"Virtual Boss\"—"
2005505-131 = "UZQueen, saっきの技をもう一度見せてくれませんか？"
2005505-132 = "...P-Please, from me too! It's my first time actually getting hit by a move like this!"
2005505-133 = "You can even practice on my body—"
2005505-134 = "Please do me too! I want to experience that move!"
2005505-135 = "M-Me too, pretty please!"
2005505-136 = "UZQueen, me too please!"
2005505-137 = "(I-I feel like we're being flooded with strange requests...)"
2005505-138 = "Please, UZQueen!"
2005505-139 = "I'd pay any amount of money just to get hit by UZQueen...!"
2005505-140 = "T-This is not good......!!!"
2005505-141 = "Sensei... please help me...!"
2005505-142 = "UZQueen! UZQueen!"
2005505-147 = "S-Sensei~!"
2005505-149 = "(After that, I managed to escape the venue while holding Yuzu, who was surrounded and in trouble...)"