[translation]
2005706-1 = "The Best Way to Clean Up"
2005706-3 = "So, the plastic explosives I set up—"
2005706-4 = "[s] \"Wait... when did you set those up...?\""
2005706-5 = "Naturally, when we initiated the operation."
2005706-6 = "[s1] (She was planning to blow everything up from the start.)\n[s2] (I probably shouldn't say that out loud...)"
2005706-9 = "The \"cleaning\" itself went off without a hitch, but..."
2005706-10 = "I keep getting scolded because the post-cleanup costs are too high..."
2005706-11 = "The Director says I shouldn't worry about such things, but I can't keep going on like this forever."
2005706-12 = "I personally don't want my methods to become so predictable, either."
2005706-13 = "Besides, I don't want to be thought of as a \"cleaning maniac\"..."
2005706-14 = "[s] (So she is self-aware, at least...)"
2005706-15 = "Whatever shall I do...?"
2005706-16 = "I do have a desire for a peaceful resolution, but..."
2005706-26 = "Yikes!? W-what the heck is that!?"
2005706-28 = "I knew we were near the Black Market, but—"
2005706-29 = "Ugh... I want to go home. Someone help me!"
2005706-31 = "Shut it! Who's making all that noise!"
2005706-32 = "If you don't pipe down, I'll fire my new rifle round—"
2005706-33 = "The \"Tickle Bullet,\" which makes your sides and the soles of your feet tickle until you die!"
2005706-37 = "Eeeek... anything but that!"
2005706-38 = "Um... Sensei...?"
2005706-39 = "[s] \"How did it come to this...?\""
2005706-40 = "I am so sorry... #nIt is all because of my incompetence..."
2005706-41 = "[s] \"At this rate, many citizens are going to get caught in the crossfire...\""
2005706-45 = "That's enough! You're already surrounded! #nRelease the people you're holding right now!"
2005706-48 = "What should we do, Boss?"
2005706-49 = "We've come this far, you think I'm gonna wave a white flag now? We're seeing this through! #nThere's no other way!"
2005706-50 = "You heard the man, Valkyrie officer! #nIf you don't meet our demands, we can't guarantee the safety of the people here!"
2005706-55 = "Sensei..."
2005706-56 = "[s3] \"Akane—\"\n[s4] \"Now is the time for C&C to step in!\""
2005706-59 = "Yes."
2005706-60 = "..."
2005706-61 = "Now is the time to try a new approach, isn't it?"
2005706-66 = "Excuse me..."
2005706-67 = "Huh? Who are you?"
2005706-68 = "Why don't you try talking to the Valkyrie officers first?"
2005706-69 = "If you exchange words, perhaps you can find some common ground."
2005706-70 = "Huh? What are you talking about?"
2005706-71 = "Don't you know those guys have a policy of \"we don't negotiate with terrorists\"?"
2005706-72 = "Same goes for us! I'm not negotiating with the cops! You never know when they'll betray you!"
2005706-74 = "Outsiders, get lost!"
2005706-75 = "Oh my..."
2005706-76 = "[s] (I guess it's not that simple...)"
2005706-79 = "I happen to have connections with Valkyrie. #nHow about it? Shall I contact them for you?"
2005706-80 = "Perhaps we could reach an amicable resolution."
2005706-81 = "Huh? Why would I ever trust you?"
2005706-82 = "You can tell just by looking. It's written all over your face."
2005706-83 = "...I see."
2005706-84 = "[s] (Akane's face is...!?)"
2005706-88 = "In that case, why not ask for leniency? #nIf you explain the circumstances, perhaps—"
2005706-89 = "There's no turning back now!"
2005706-90 = "You don't know anything, you civilian!"
2005706-94 = "[ns] (If Akane gets serious, I don't think they'll be able to say things like that...)"
2005706-97 = "I believe the Valkyrie officers are also hoping for an amicable resolution. I think that would be best for both sides..."
2005706-98 = "A deal—"
2005706-99 = "Don't mess with me!"
2005706-100 = "Unless they surrender to us, there's no hope for an amicable resolution!"
2005706-101 = "The Black Market is our jurisdiction. There isn't a single person here who welcomes Valkyrie!"
2005706-102 = "Oh, wait? Are you one of them?"
2005706-103 = "Hehe... Uhehe..."
2005706-104 = "[s] (I don't want to know what happens next...)"
2005706-111 = "It's already night, Sensei."
2005706-112 = "[s] \"I suppose so.\""
2005706-113 = "I have to go to school tomorrow, and I haven't finished my review yet..."
2005706-114 = "[s] \"That's true. Studying is your primary duty.\""
2005706-115 = "Sensei, you have preparations for tomorrow as well, don't you..."
2005706-116 = "What should we do...?"
2005706-117 = "[s] \"Akane.\""
2005706-118 = "Yes, Sensei."
2005706-119 = "[s] \"You may go.\""
2005706-120 = "Huh?"
2005706-124 = "..."
2005706-125 = "Are you sure?"
2005706-126 = "[s5] \"If you've tried everything and it doesn't work...\"\n[s6] \"Sometimes it's best to just give up.\""
2005706-129 = "Understood."
2005706-130 = "My Master."
2005706-150 = "Waaaaaahhh!?!?"
2005706-151 = "What is this! What on earth is happening—!!!"
2005706-157 = "R-run! She's gone crazy!!!"
2005706-161 = "Wait! Aaaahhh!!!"
2005706-168 = "Valkyrie! P-please! Help us! We surrender unconditionally!"
2005706-169 = "Just please protect us from her!!!"
2005706-175 = "Phew."
2005706-176 = "As I thought, explosives really are... the best way to \"clean up.\""