[translation]
2005503-1 = "UZQueen's Slump"
2005503-2 = "On the way to the Game Development Department"
2005503-3 = "(I couldn't believe Yuzu would say such words.)"
2005503-4 = "(With this unbelievable situation, I rushed to Millennium.)"
2005503-9 = "Did you play the game released last month?"
2005503-11 = "[ns] (Oh, they're talking about games...)"
2005503-12 = "You mean the new fighting game - \"Simulion Quest\"?"
2005503-13 = "The setting is a cyberpunk-theme near future, and the world-building is amazing.#nIt's incredibly detailed, and the control is super smooth too."
2005503-14 = "But hey, isn't something strange?"
2005503-15 = "Strange? You mean bugs?#nIf it's that, the developers announced something about it the other day..."
2005503-16 = "No, not that... UZQueen isn't on the rankings."
2005503-17 = "—Even though it's been a week since the rankings started."
2005503-19 = "(UZQueen...?)"
2005503-20 = "Ah, you're right! There has never been a fighting game ranking without UZQueen on it...!"
2005503-21 = "Did something happen to UZQueen?"
2005503-23 = "(The moment I heard that conversation, I found myself walking faster.)"
2005503-27 = "Game Development Department - Clubroom"
2005503-28 = "[ns] \"Yuzu! Are you okay!?\""
2005503-29 = "Hiiee!? Sensei!?"
2005503-33 = "Wh-what on earth is going on?!"
2005503-34 = "Why are you in such a rush...?"
2005503-35 = "[s] \"Yuzu, what exactly happened?\""
2005503-36 = "Eh!? Nothing in particular!"
2005503-37 = "L-Look, I can enter the locker properly now."
2005503-42 = "D-Don't tell me...#nYou came all the way here just because of that Momotalk...?"
2005503-43 = "I did grumble about that game was difficult, but..."
2005503-44 = "Was I really that weird...?"
2005503-48 = "That's right... I guess so."
2005503-49 = "I've never thought video games were difficult before..."
2005503-50 = "[s1] \"About that game, is it by any chance...\"\n[s2] \"『Simulion Quest』?\""
2005503-53 = "H-How did you know!?"
2005503-55 = "(I told her what I heard on the way.)"
2005503-56 = "Ah... I-I see..."
2005503-57 = "Um... I haven't really#nplayed 『Simulion Quest』 properly yet..."
2005503-58 = "Umm....."
2005503-59 = "...Would you like to take a look?"
2005503-61 = "(Yuzu booted up 『Simulion Quest』.)"
2005503-62 = "(As soon as the game started, I feel I understood why Yuzu was bad at this game.)"
2005503-64 = "[ns3] \"This game needs you to move your body to fight...\"\n[ns4] \"...it is a VR game!\""
2005503-67 = "Yes, you have to use your whole body to attack and dodge..."
2005503-68 = "But I... I'm fine with moving my hands or something,#nbut running or using my whole body is a bit hard for me..."
2005503-69 = "I wanted to play it properly, but I couldn't even finish the tutorial..."
2005503-70 = "Eh? You want to try it too, Sensei?"
2005503-71 = "W-Well, there is 2 player co-op mode, but..."
2005503-72 = "Do you have some kind of idea...?"
2005503-77 = "W-Why am I in this outfit again...!?"
2005503-78 = "Because you looks like the protagonist in the game, it's easier to play?#nI-I guess I can understand that, but...!"
2005503-79 = "[s5] \"Then, right away—\"\n[s6] \"Let's get on my shoulders, Yuzu.\""
2005503-82 = "Eh!?"
2005503-83 = "H-Hiiee!?"
2005503-88 = "(I lift Yuzu up and give her piggyback rides)"
2005503-91 = "Waaa... I-It's high...!"
2005503-92 = "B-But, I don't think 2-player co-op mode is meant to be like this..."
2005503-93 = "[s7] \"It's properly reflected in the game, see?\"\n[s8] \"Look, Yuzu's character is being piggybacked in the game too.\""
2005503-96 = "W-Well, that is true, but...!"
2005503-97 = "[s9] \"I'll handle moving the body, Pilot-san.\"\n[s10] \"Yuzu, you concentrate on what you're good at!\""
2005503-100 = "....!"
2005503-101 = "Alright then, I'll handle reconnaissance and the planning, so please take care of movement and attack, Sensei."
2005503-102 = "[s] \"Roger, let's roll!\""
2005503-107 = "(And so, after starting co-op session with Yuzu—)"
2005503-108 = "(It didn't even take a day to get into the top rankings.)"
2005503-109 = "(After that...)"
2005503-111 = "(The 『Simulion Quest』 online forums began receiving countless eyewitness accounts of two players challenging the boss while piggybacking each other.)"
2005503-112 = "(...However, it is said that UZQueen was the only one who could pull off that stunt.)"