[translation]
2005305-1 = "Ninja Girl Wants to Know the Secret!"
2005305-2 = "Briefing Venue"
2005305-3 = "(Worried about Michiru...)"
2005305-4 = "(I decided to attend with her.)"
2005305-5 = "Ah, Sensei-dono!#nOver here, over here!"
2005305-6 = "...Hm?"
2005305-7 = "No, no, I won't go in ahead without you."
2005305-8 = "...Ah, this?"
2005305-9 = "Well, I thought maybe I should dress appropriately..."
2005305-10 = "Look, look around you."
2005305-11 = "This is a place where chosen ones are taught the secret...!"
2005305-12 = "So, it's only polite to come dressed suitably for it!"
2005305-13 = "That's why I decided to wear this dress!#nFuhuhu...!"
2005305-14 = "Look, those people are wearing suits and dresses too, right?"
2005305-15 = "[s] \"I suppose so...?\""
2005305-17 = "(I highly doubt they'd teach us the secret that easily, but...)"
2005305-18 = "(For now, I just followed Michiru.)"
2005305-20 = "[ns] \"By the way, how did you find out about this briefing session?\""
2005305-21 = "Umm, a little while ago I was watching a video..."
2005305-22 = "And an ad popped up on the screen."
2005305-23 = "And it was for this briefing session!"
2005305-24 = "[s] \"A-A video ad...\""
2005305-25 = "It's amazing, I was so surprised!"
2005305-26 = "I was worrying about how to grow my channel, so I looked around for ideas."
2005305-27 = "And right after that!"
2005305-28 = "Bam! This ad appeared!"
2005305-29 = "It was as if it was giving me the answer to my worries!"
2005305-30 = "That's when it hit me!#nThis must be destiny!"
2005305-31 = "[s] \"I-I knew it...\""
2005305-32 = "Ah, you don't believe me!?"
2005305-33 = "Anyway, it's starting soon, so let's go inside!"
2005305-38 = "Inside the Venue"
2005305-40 = "Everyone, thank you for coming today."
2005305-41 = "The fact that you've come here means you all share a common concern, correct?"
2005305-42 = "How to increase your views, how to get more subscribers..."
2005305-43 = "...We shall solve those concerns right here today!"
2005305-44 = "I knew it...!"
2005305-45 = "He sees right through everything...!"
2005305-46 = "[s] \"...\""
2005305-47 = "There is no need to worry."
2005305-48 = "The views and subscriber counts you all desire... "
2005305-49 = "Our company will completely guarantee them!"
2005305-50 = "...Hm?"
2005305-51 = "If you simply pay 1,000,000 yen,#nwe will raise the average views of your videos to 1 million!"
2005305-52 = "And what's more, act now and we'll throw in 1 million subscribers as a bonus!"
2005305-53 = "Hnh...!?"
2005305-54 = "Some of you may be feeling uneasy, but please rest assured."
2005305-55 = "We use safe macro programs certified by the#nKivotos Cracker Association!"
2005305-59 = "T-That's just an illegal tool...!"
2005305-60 = "Sensei-dono, I'm sorry... It seems I was mistaken..."
2005305-61 = "I thought I could increase them through legitimate way..."
2005305-62 = "...It was just a scam."
2005305-63 = "Let's go, Sensei-dono."
2005305-69 = "...Hm?"
2005305-70 = "Is there a problem?"
2005305-71 = "The briefing session is still ongoing..."
2005305-72 = "Well, we were thinking of going home..."
2005305-73 = "Hmph... That is a bit of a problem."
2005305-74 = "According to our terms, leaving early is prohibited..."
2005305-76 = "[ns] \"Excuse me, I was just a little curious about something...\""
2005305-77 = "Yes, what is it?"
2005305-81 = "W-wait, are you the one from Schale...?"
2005305-82 = "P-P-P-Please excuse me!#nHave a safe trip home!"
2005305-86 = "[ns] \"Shall we go, Michiru?\""
2005305-87 = "Y-Yeah!"
2005305-89 = "(And so, Michiru and I left the venue.)"
2005305-91 = "Nearby Park"
2005305-92 = "Uuu, how embarrassing..."
2005305-93 = "I almost got tricked by a scam like that..."
2005305-94 = "Wait, Sensei-dono, could it be..."
2005305-95 = "Did you realize it from the very beginning?"
2005305-96 = "[s] \"To some extent, yeah.\""
2005305-97 = "Uuuu... You're so mean, Sensei-dono...!"
2005305-98 = "[s] \"Eh!?\""
2005305-99 = "O-Of course, it's my fault for taking the bait, but...!"
2005305-100 = "You could've at least told me...!"
2005305-101 = "[s] \"Sometimes, mistakes can be an important experience.\""
2005305-102 = "...?"
2005305-103 = "[s1] \"Even if you didn't go to the briefing, it would have been stuck in your mind.\"\n[s2] \"But since you actually went there, you feel better about it, right?\""
2005305-109 = "...T-True."
2005305-110 = "I definitely won't make the same mistake again..."
2005305-111 = "Yeah, I really gotta thank you, Sensei-dono!"
2005305-112 = "Besides, it helped me make up my mind."
2005305-113 = "I won't rely on anything shady—I'll grow my channel on my own strength...!"
2005305-114 = "So please keep watching over me, Sensei-dono!"
2005305-116 = "(After walking Michiru home, I returned to Schale...)"
2005305-117 = "(And reported the briefing session to Valkyrie.)"