[translation]
2005305-1 = "The Ninja Girl Wants to Know the Secret!"
2005305-2 = "Briefing Venue"
2005305-3 = "(I was worried about Michiru...)"
2005305-4 = "(I decided to join her.)"
2005305-5 = "Ah, Sensei!#nOver here, over here!"
2005305-6 = "……Hm?"
2005305-7 = "No, no, I wouldn't just go on ahead without you."
2005305-8 = "……Oh, this?"
2005305-9 = "I just thought it would be better to dress properly, you know……?"
2005305-10 = "Look, look, take a good look around."
2005305-11 = "This is a place where the chosen few are taught the secret……!"
2005305-12 = "So, it’s only polite to dress the part!"
2005305-13 = "That’s why I dragged this dress out!#nHeh heh heh……!"
2005305-14 = "See, those people over there are wearing suits and dresses too, right?"
2005305-15 = "[s] \"I suppose so……?\""
2005305-17 = "(I don't think they'll tell us the secret that easily, though……)"
2005305-18 = "(For now, I followed Michiru.)"
2005305-20 = "[ns] \"By the way, how did you find out about this briefing?\""
2005305-21 = "Well, I was watching some videos a little while ago and……"
2005305-22 = "An ad popped up on the screen."
2005305-23 = "And it was for this briefing!"
2005305-24 = "[s] \"A, a video ad…….\""
2005305-25 = "It was amazing, I was so surprised!"
2005305-26 = "I was worried about how to grow my channel, so I searched for all sorts of things and……"
2005305-27 = "Right after that!"
2005305-28 = "Bam! This ad just appeared!"
2005305-29 = "It was like it was answering my worries!"
2005305-30 = "That’s when it hit me!#nThis must be fate!"
2005305-31 = "[s] \"I, I see…….\""
2005305-32 = "Aww, you don't believe me!?"
2005305-33 = "Anyway, it's starting, let's go inside!"
2005305-38 = "Inside the venue"
2005305-40 = "Everyone, thank you for coming today."
2005305-41 = "The fact that you are here means you all share the same concern, don't you?"
2005305-42 = "How to increase your view counts, how to gain more subscribers……"
2005305-43 = "……Let’s solve those worries right here today!"
2005305-44 = "I knew it……!"
2005305-45 = "They see right through everything……!"
2005305-46 = "[s] \"…….\""
2005305-47 = "There is no need to worry."
2005305-48 = "The view counts and subscriber numbers you desire……"
2005305-49 = "Our company guarantees them completely!"
2005305-50 = "……Hm?"
2005305-51 = "If you pay just 1 million credits,#nwe will boost your average video views to 1 million!"
2005305-52 = "And as a special bonus, you'll get 1 million subscribers too!"
2005305-53 = "Hmm……!?"
2005305-54 = "Some of you may be anxious, but please rest assured."
2005305-55 = "We use safe macro programs certified by the Kivotos Cracker Association!#n"
2005305-59 = "T, that's just an illegal tool……!"
2005305-60 = "Sensei, I'm sorry…… I think I was wrong……"
2005305-61 = "I really thought I could increase them the honest way……"
2005305-62 = "……To think it was just a scam."
2005305-63 = "Let's go, Sensei."
2005305-69 = "……Hm?"
2005305-70 = "Is something the matter?"
2005305-71 = "The briefing is still in progress……"
2005305-72 = "Um, I think we're just going to head home now……"
2005305-73 = "Hmm…… that is a bit of a problem."
2005305-74 = "According to our terms, leaving in the middle is prohibited……"
2005305-76 = "[ns] \"Excuse me, I have a quick question…….\""
2005305-77 = "Yes, what is it?"
2005305-81 = "C, could you possibly be from SCHALE……?"
2005305-82 = "I-I-I-I apologize!#nPlease, have a safe trip home!"
2005305-86 = "[ns] \"Let's go, Michiru.\""
2005305-87 = "O, okay!"
2005305-89 = "(And so, I left the venue with Michiru.)"
2005305-91 = "Nearby park"
2005305-92 = "Ugh, how embarrassing……"
2005305-93 = "I almost got taken in by a scam like that……"
2005305-94 = "Wait, Sensei, could it be……"
2005305-95 = "Did you know from the start?"
2005305-96 = "[s] \"To an extent, yes.\""
2005305-97 = "Ughhhhh…… that’s mean, Sensei……!"
2005305-98 = "[s] \"Eh!?\""
2005305-99 = "I, I know it’s my fault for falling for it, but still……!"
2005305-100 = "You could have told me……!"
2005305-101 = "[s] \"Sometimes, failure is an important experience, too.\""
2005305-102 = "……?"
2005305-103 = "[s1] \"Even if you hadn't gone to the briefing, it would have been stuck in the back of your mind.\"\n[s2] \"But now that you've actually gone, you feel relieved, right?\""
2005305-109 = "……Y, you're right."
2005305-110 = "I won't make the same mistake again……"
2005305-111 = "Yeah, I really should thank you, Sensei!"
2005305-112 = "Besides, I’ve made up my mind."
2005305-113 = "I won't rely on anything shady; I'll grow my channel with my own strength……!"
2005305-114 = "So please keep watching over me, Sensei!"
2005305-116 = "(After dropping Michiru off at home and returning to SCHALE……)"
2005305-117 = "(I reported the briefing incident to Valkyrie.)"