[translation]
2005302-1 = "Ninja Girl Seeking Treatment!"
2005302-2 = "Hyakkiyako, a certain classroom in Old School Building 38"
2005302-3 = "(Worriedly, I headed over to Michiru's location.)"
2005302-6 = "S-Sensei-dono...!#nYou really came!?"
2005302-7 = "You really came!?"
2005302-8 = "[s] \"Michiru, are you okay!?\""
2005302-9 = "Ah, w-well~..."
2005302-10 = "I know I said I was injured, but..."
2005302-11 = "...Um, it's not actually me."
2005302-12 = "[s] \"...?\""
2005302-13 = "Umm... my clothes are what got \"injured,\" I guess you could say."
2005302-14 = "...My dress, to be exact."
2005302-15 = "Like this, pretty spectacularly..."
2005302-16 = "[s] \"Whoa... what happened?\""
2005302-17 = "Umm..."
2005302-18 = "I was practicing the \"Oak Tree Scaling Jutsu\" and fell off of the tree..."
2005302-19 = "[s1] \"So you mean...\"\n[s2] \"You were climbing a tree and ruined your clothes.\""
2005302-22 = "That's how you're summarizing it!?"
2005302-23 = "That makes it sound like I was just messing around and tore my clothes!"
2005302-24 = "...W-Well, you're not wrong, but still."
2005302-25 = "...I-I wasn't playing around, okay!?#nIt was strictly training!"
2005302-26 = "Muuu..."
2005302-27 = "...Sensei-dono, it seems your understanding of ninjas is still a liiittle shallow!"
2005302-28 = "Therefore!"
2005302-29 = "I shall give you a lecture about ninjas while we head to the tailor!"
2005302-31 = "(And so, I ended up heading to the tailor with Michiru.)"
2005302-33 = "Hyakkiyako Shopping District"
2005302-35 = "...In other words, ninjas wear clothes that is not just black!"
2005302-36 = "The black outfits that cover your face are strictly for nighttime use."
2005302-37 = "They actually stand out during the day, so we usually just wear normal clothes."
2005302-38 = "The fundamental rule of a ninja is to \"not stand out\"..."
2005302-39 = "One must dress appropriately for each situation!"
2005302-40 = "For example, if it's a mission at a party venue, you'd wear a dress like this..."
2005302-41 = "Of course, if it were at night, black would be fine too."
2005302-42 = "I've heard there was even a ninja who, for camouflage, wore no clothes and#njust painted their body with ink..."
2005302-43 = "And recently, there are even things like optical camouflage ninja suits—"
2005302-53 = "[ns] \"Ah, isn't this the place?\""
2005302-54 = "...Ah!"
2005302-55 = "Welcome~"
2005302-56 = "Umm, I'd like to ask you to repair a torn dress..."
2005302-57 = "Yes, certainly.#nMay I take it from you?"
2005302-58 = "Suuuure..."
2005302-62 = "...Ah."
2005302-64 = "I'm literally wearing it right now!?"
2005302-66 = "Umm, do you have a change of clothes?"
2005302-67 = "I do not..."
2005302-68 = "Um, is there a way to fix it while I'm wearing it..."
2005302-69 = "We use a sewing machine, so that would simply be dangerous..."
2005302-70 = "Right..."
2005302-71 = "Jeez, after we came all this way too...!"
2005302-72 = "Ugh, well, it's not like there isn't a way..."
2005302-73 = "If I change into my ninja uniform...!"
2005302-74 = "[s] \"Didn't you just say you didn't have a change of clothes?\""
2005302-75 = "It's fine, it's fine!"
2005302-76 = "Like the ninja from the legend, I just need to paint myself with ink!"
2005302-77 = "[s] \"...Is that really okay?\""
2005302-78 = "Hehe, I'm a ninja, so something like that is..."
2005302-79 = "..."
2005302-83 = "T-That's absolutely no good!"
2005302-84 = "Absolutely not!"
2005302-85 = "S-..."
2005302-86 = "Sensei-dono, you pervert!!"
2005302-87 = "[s3] \"Eh, me!?\"\n[s4] \"I'm being framed...!\""
2005302-91 = "(Afterwards, Michiru changed into some gym clothes we bought nearby, and#ndropped off the dress.)"
2005302-92 = "(...and I paid the bill.)"