[translation]
2005602-1 = "Late-Night Errand"
2005602-2 = "(I was curious about Koyuki's message, but I headed to the convenience store to grab a late-night snack anyway.)"
2005602-7 = "……Huh?#n……Sensei?"
2005602-8 = "Am I just imagining things?"
2005602-9 = "[ns1] \"That voice is...\"\n[ns2] \"……Huh?\""
2005602-14 = "It really is Sensei!"
2005602-15 = "What are you doing out at this hour?#nWorking overtime?"
2005602-16 = "Huh? Me?#nNo, no, don't answer a question with a question~"
2005602-17 = "……Ah! So you *are* working overtime.#nHehe, I had a feeling."
2005602-18 = "I was... just about to go to sleep, but I got asked to run an errand."
2005602-19 = "Oh, right. By my seniors."
2005602-20 = "……They're still working on their tasks right now."
2005602-21 = "[s3] \"……Seminar must be tough, too.\"\n[s4] \"They're nice enough to tell you to go to sleep first, though.\""
2005602-24 = "Hey, why are we talking about my seniors all of a sudden!?#nAren't you going to say something like, 'Good job running that errand, Koyuki' or something!?"
2005602-25 = "……Yes?"
2005602-26 = "The MomoTalk you sent earlier...?"
2005602-30 = "……Eh, what are you talking about?"
2005602-31 = "[s5] \"……It didn't really mean anything.\"\n[s6] Send the contents of the MomoTalk."
2005602-34 = "……Ah! That thing!"
2005602-35 = "Hehe... it wasn't really anything special."
2005602-36 = "It came up in conversation... wondering how you'd reply if I sent you an 'XD'."
2005602-40 = "……What's with that look?"
2005602-41 = "It's not like I did anything dangerous or lied, right?"
2005602-42 = "I wasn't gambling or anything! You're not going to lecture me at this hour, are you!?"
2005602-43 = "Look at me! Look at this face!#nI worked super hard all day today, you know!?"
2005602-44 = "……What is it?"
2005602-45 = "You're saying that doesn't sound convincing coming from someone dressed like that...?"
2005602-46 = "The most relaxed outfit in the world?……Hey, that's not true!#nWell, it is a fact that these are pajamas!!"
2005602-47 = "[s7] \"Did you pick those pajamas out yourself?\"\n[s8] \"They look good on you.\""
2005602-50 = "……These?"
2005602-51 = "No, my seniors picked them out for me.#nI used to just sleep in whatever random clothes I had."
2005602-52 = "These pajamas are cute, right!#nThey do stand out quite a bit, though!"
2005602-53 = "[s9] \"They certainly are flashy.\"\n[s10] (Could that have been the intention...)"
2005602-56 = "Are you thinking something weird?"
2005602-57 = "……*Sigh*."
2005602-58 = "I know I shouldn't go out in my pajamas."
2005602-59 = "You're going to tell me to wash clothes immediately after wearing them outside, just like my seniors do, right?"
2005602-60 = "It's fine, isn't it? It's just the convenience store right nearby, you're so fussy."
2005602-61 = "Sensei, you're dressed pretty terribly yourself. Where did the sharp, professional Sensei from earlier go?#nAren't your words and actions a bit contradictory?"
2005602-62 = "[s11] \"No, that's a different story...\"\n[s12] \"……I have no defense for that.\""
2005602-65 = "Well, well, let's just call it even.#nDon't sweat the small stuff!!"
2005602-66 = "Since we ran into each other, tell me if there's anything you want to eat! It's my treat today!"
2005602-67 = "Don't be so shy about it! Come on!!"
2005602-68 = "You know that, right? I would neeeever treat you under normal circumstances!"
2005602-69 = "Come on, let's go to the snack aisle, let's GO~!!"
2005602-71 = "(I bought a few snacks while chatting with Koyuki.)"
2005602-72 = "(I managed to convince Koyuki, who insisted on paying for everything, to let me pay for half.)"
2005602-75 = "Mmm~ The wind isn't cold tonight, it's perfect!"
2005602-76 = "Eating snacks in the park at night... it's quite the refined experience."
2005602-77 = "Here, have some too, Sensei!"
2005602-82 = "……Here! Say 'ah', Sensei!#nAhhh~n!!"
2005602-86 = "……What's wrong?"
2005602-87 = "[s13] \"Didn't you have an errand to run?\"\n[s14] \"Is it okay to be taking a detour?\""
2005602-90 = "……!"
2005602-91 = "Don't worry about it! I've got it all figured out."
2005602-92 = "If I tell them I was with you, my seniors will surely forgive me.#nGet what I mean?"
2005602-93 = "I'm always in your debt, Sensei, right?#nIf I say you treated me as a thank you... see?"
2005602-97 = "……Hehe."
2005602-98 = "[s15] \"I knew you were plotting something bad!!\"\n[s16] I take out my phone to try and contact Seminar."
2005602-101 = "Ahhh!! W-wait, wait, wait, wait! Stop! STOOOOP!!"
2005602-102 = "Jeez! It was a joke, just a joke!"
2005602-103 = "Don't take it so seriously!!"
2005602-104 = "……Eh?"
2005602-105 = "Wait, are you saying I *don't* take jokes seriously?#nUgh, why do you always have to pick apart everything I say!!"
2005602-106 = "Jeez! Can't I have a little fun once in a while!!#nDon't go stealing a student's simple pleasures!"
2005602-107 = "……Come on! Ahhh!!"
2005602-108 = "……AAAAAAHHHHHH!!!"
2005602-110 = "(I decided to let Koyuki enjoy her simple pleasure—)"
2005602-111 = "(I walked Koyuki back to her room after she started dozing off, perhaps because she really was sleepy.)"