[translation]
2005506-1 = "Gamer and the Salvation of the World"
2005506-2 = "Game Development Department - Clubroom"
2005506-3 = "N-No, no, not at all."
2005506-4 = "......"
2005506-5 = "T-Thank you, everyone."
2005506-6 = "[ns] \"Yuzu?\""
2005506-7 = "Ah... this voice is..."
2005506-12 = "S-Sensei? Since when have you been here!"
2005506-13 = "Uuuu...!"
2005506-14 = "[s1] \"You were playing VR games, huh?\"\n[s2] \"What were you talking about just now?\""
2005506-17 = "Eh? Ah, um..."
2005506-18 = "...the people inside the game were thanking me."
2005506-19 = "Saying thank you for saving their world."
2005506-20 = "[s] \"So you saved the world!\""
2005506-21 = "S-Saved it... that's too much...!"
2005506-22 = "B-But, for the first time in a while, I felt a sense of accomplishment... or pride."
2005506-23 = "I don't have any skills outside of games, and I can't really help anyone in reality, but..."
2005506-24 = "Inside a game, I can save the world like this..."
2005506-25 = "Of course, it's just a game..."
2005506-26 = "So it might not mean much..."
2005506-27 = "[s] \"But, is there any reason why a game can't be reality?\""
2005506-28 = "Eh? What... do you mean..."
2005506-29 = "...The time when we are experiencing something itself is a reality?"
2005506-30 = "......"
2005506-31 = "You're right. Even if the world in games are virtual—"
2005506-32 = "The emotions, experiences, and sense of accomplishment felt there are—"
2005506-33 = "It might be the real thing, after all."
2005506-34 = "[s3] \"The games Yuzu and the others will make from now on...\"\n[s4] \"Will hold that kind of meaning for someone.\""
2005506-37 = "That kind of meaning... for someone..."
2005506-38 = "......"
2005506-39 = "U-Um, Sensei."
2005506-40 = "The world I protected... would you like to see it together with me?"
2005506-42 = "(There's no reason to refuse)"
2005506-43 = "(I put on the VR set Yuzu handed me and entered the game world together.)"
2005506-47 = "[wa:3200]― [log=유즈 결전]Please look, [wa:1430]Sensei.[/log]"
2005506-49 = "― [log=유즈 결전]This is the world [wa:1150]I have protected[/log]"
2005506-52 = "[wa:1700]― [log=유즈 결전]...Of course, [wa:950]I understand.[/log]"
2005506-54 = "― [log=유즈 결전]That [wa:820]I'm not the only one [wa:1650]who has seen [wa:1200]this scenery...[/log]"
2005506-57 = "[wa:810]― [log=유즈 결전]During the tournament, [wa:2090]you said this, [wa:1060]didn't you?[/log]"
2005506-59 = "― [log=유즈 결전]That this moment [wa:2560]right now, [wa:1840]this game, [wa:1910]is our reality.[/log]"
2005506-62 = "[wa:780]― [log=유즈 결전]That's why, [wa:2330]even if [wa:1030]this world [wa:830]has a predetermined ending...[/log]"
2005506-64 = "― [log=유즈 결전]Even if everyone [wa:650]in this world [wa:1570]walks the same scenario...[/log]"
2005506-67 = "[wa:890]― [log=유즈 결전]The choices [wa:2840]I made, [wa:370]all these feelings...[/log]"
2005506-69 = "― [log=유즈 결전]They are all [wa:2670]definitely real.[/log]"
2005506-72 = "[ns] \"Come to think of it, Yuzu, you really liked that outfit.\""
2005506-73 = "Eh? Outfit...?"
2005506-74 = "A-Ahhh...!?"
2005506-75 = "N-N-No, it's not like that...#nThis is...!"
2005506-76 = "It's just suitable for this game...!"
2005506-77 = "R-Really, that's all it is!"
2005506-78 = "Because you can't be picky about methods when saving the world...!"
2005506-79 = "[ns] (Smile with satisfaction.)"
2005506-80 = "P-Please don't laugh...!"
2005506-82 = "(After that, I managed to escape the venue while holding Yuzu, who was surrounded and in trouble...)"