[translation]
70011020-1 = "The Melancholy of Kanbara Misuzu (2)"
70011020-2 = "How much is that going to be?"
70011020-6 = "Eh...?"
70011020-7 = "Um... I thought I asked if you had any friends on the outside..."
70011020-8 = "That's why. If I made some, how much would I profit from it?"
70011020-9 = "That's a little hard to understand... making friends isn't about money..."
70011020-10 = "Then it's absolutely useless."
70011020-11 = "Um... there are many things in this world that cannot be bought by money..."
70011020-12 = "Hey."
70011020-13 = "\"Cannot be bought by money\"...? Hah."
70011020-14 = "Could you not waste my time with your self-satisfaction?"
70011020-15 = "Ah, th-that's not... I, I..."
70011020-17 = "Hey—"
70011020-19 = "Hey!"
70011020-20 = "Hafuhi!?"
70011020-21 = "You're the one who called me here right? Don't fall asleep right in front of me."
70011020-22 = "Ah, I'm sorry... I was a little tired."
70011020-23 = "What, did you stay up all night or something?"
70011020-24 = "Well, you could say it was something like that... ehehe."
70011020-25 = "...Anyway. Do you know why you were called here?"
70011020-26 = "Ah, yeah. Well."
70011020-27 = "I don't mean to interrogate you. I just want to know the reason.#nAre you dissatisfied with your daily life here?"
70011020-28 = "Not really."
70011020-29 = "Not really... I see. It's not a bad answer."
70011020-30 = "Even so, it's not a good answer either."
70011020-31 = "I've looked over your daily records, but I couldn't figure it out from paper alone. Why did you try to escape?"
70011020-32 = "...Like I said, there's no reason."
70011020-33 = "I just thought maybe I could do it too."
70011020-34 = "Escape, you mean..."
70011020-35 = "...Could you tell me what gives you that confidence?"
70011020-36 = "Well, apparently 7 people broke out before, right?"
70011020-37 = "The ones they call the \"Seven Prisoners\" on the outside."
70011020-38 = "So I thought I could too."
70011020-39 = "The escape of those 7... That is a fact."
70011020-40 = "However, that also means only 7 people have ever managed to escape."
70011020-41 = "Since the establishment of the Corrections Bureau, we have never allowed#nan escape other than those 7.#nEven back then, we managed to prevent any further escapes."
70011020-42 = "Huh... That's different from what I heard.#nWasn't the Corrections Bureau's security full of holes?"
70011020-43 = "The \"Fox of Calamity\" was coming and going as she pleased, right?"
70011020-44 = "...You mean Wakamo."
70011020-45 = "..."
70011020-46 = "Let's get back on topic. We aren't talking about Wakamo right now."
70011020-47 = "In any case, we don't restrict your outings because we want to make you suffer."
70011020-48 = "As you likely know, there are two cases where one is sent to the Corrections Bureau.#n\"Students whose academy has given up on guiding them,\" or \"Students whose#nacademic registration is unknown to begin with.\""
70011020-49 = "So to speak, problem children that the academies have thrown their hands up at."
70011020-50 = "That's a harsh way to put it."
70011020-51 = "Of course, the standards differ depending on the academy. Like Gehenna recently,#nthere are academies that won't send a single student to the Corrections Bureau,#nwhile there are also academies that will abandon you over one trivial mistake."
70011020-52 = "Therefore, the fact that you \"were in the Corrections Bureau\" won't necessarily be a major obstacle for your future."
70011020-53 = "Is that... supposed to be comforting?"
70011020-54 = "...Well, sort of."
70011020-55 = "Valkyrie Police School is the academy responsible for Kivotos's public order.#nWe cannot afford to let unpredictable problem children roam free."
70011020-56 = "Even so, if you reflect on your actions and turn over a new leaf, you will be#napproved for release at any time."
70011020-57 = "Because the Corrections Bureau is not a \"prison.\""
70011020-58 = "There is no need for you to go out of your way to escape."
70011020-59 = "I get it, I get it. I just have to reflect on it."
70011020-63 = "One more thing. I have an important question."
70011020-64 = "What were you planning to do after escaping?"
70011020-65 = "Huh? I told you, there's no real reason."
70011020-66 = "The reason you decided to escape was \"because you thought you could do it\"#n... right? Then, if your escape succeeded, what were you intending#nto do after that?"
70011020-67 = "Why are you so insist on that? There's no need to ask, is there?"
70011020-68 = "That is not true. Until I hear it from your own mouth, the truth will remain#nunknown."
70011020-69 = "...Fine, I'll tell you! But! ...You absolutely can't laugh, okay?"
70011020-73 = "...Today is my birthday."
70011020-74 = "But, you know, I just got here. I don't have anyone I'm close with..."
70011020-75 = "So I thought I'd just go see my friends for a bit...#nI wasn't planning to run away, and I fully intended to come back!"
70011020-76 = "...Is that so."
70011020-77 = "Hmph, you guys probably won't believe me anyway."
70011020-78 = "I apologize if we made you feel that way. But..."
70011020-84 = "—Excuse me, could you bring that item over?"
70011020-85 = "Yes, the one you entrusted to me earlier, correct?"
70011020-87 = "What is that?"
70011020-88 = "I wanted to give this to you in a slightly more peaceful atmosphere,#nif possible... I'm sorry. Also—"
70011020-89 = "Happy Birthday."
70011020-96 = "Ah... eh...?"
70011020-97 = "It's nothing fancy, but I knitted a beanie.#nSince you have beautiful blonde hair, I thought pastel colors would suit you, so I used light pink yarn.#nI hope you like it."
70011020-98 = "Wait... You knew it was my birthday? And a present too..."
70011020-99 = "It is a precious birthday during your student years that will never come again."
70011020-100 = "Welcoming such a day at the Corrections Bureau must be very tough for you.#nI thought this might be of some comfort..."
70011020-101 = "As expected, this alone isn't enough, is it."
70011020-102 = "If you wouldn't mind... could you give me your friends' contact information?"
70011020-103 = "...Eh?"
70011020-104 = "I will make arrangements so we can invite them here and celebrate together."
70011020-105 = "...Are you allowed to do that?"
70011020-106 = "What do you mean...?"
70011020-107 = "Because I'm a prisoner... and I even tried to break out, you know?"
70011020-108 = "Even so, the Corrections Bureau isn't a \"prison.\""
70011020-109 = "Therefore, you are not a \"criminal.\""
70011020-111 = "Wow, great work out there!"
70011020-112 = "As expected of the Director!#nWhen she left the room, she was bawling her eyes out, you know?"
70011020-113 = "To make her cry on such a joyful day... It breaks my heart..."
70011020-114 = "No, no, it's not like you bullied her or anything."
70011020-115 = "I finally understand the stories about how there's a mountain of students#nwho turned over a new leaf after meeting you, Director."
70011020-116 = "Even so... that is all the fruit of their own efforts.#nI'm just there to keep them company."
70011020-117 = "If the other party isn't interested in talking..."
70011020-118 = "To begin with, someone with deviant thoughts is—"
70011020-119 = "...?"
70011020-120 = "Ah... I'm sorry. Please pretend you didn't hear that."
70011020-121 = "Thank you for your help so early in the morning. Good work."
70011020-122 = "No, this is my duty! Feel free call me again anytime!"
70011020-127 = "...There were people like that.#nPeople who no words could reach, who you wouldn't believe#nlived in the same world—"
70011020-129 = "—Prisoners."
70011020-137 = "We will now have a few words from the newly appointed Director of the#nCorrections Bureau, \"Misuzu Kanbara\".#nEveryone, please give her a big round of applause—"
70011020-141 = "It's an emergency! Prisoners have escaped!!"
70011020-142 = "There are 7 of them!!"
70011020-143 = "It's a mass prison break!!!"
70011020-145 = "(It was on that very day that Misuzu Kanbara assumed the position of Director#nof the Corrections Bureau.)"
70011020-146 = "(And that year— the number of applicants to the Corrections Bureau dropped by 80% compared to the previous year.)"
70011020-147 = "The Melancholy of Kanbara Misuzu"