[translation]
70011010-1 = "The Melancholy of Kanbara Misuzu (1)"
70011010-3 = "Thanks, Suzu-chan!"
70011010-4 = "Thanks to you, I feel like I can do my best! I'll definitely contact you again!"
70011010-5 = "Even so, that's because of your hard work."
70011010-12 = "An award for three months in a row!? That's amazing, Suzu-chan!"
70011010-13 = "That doesn't happen very often even among the Valkyries, right!?"
70011010-14 = "That said, it's all thanks to everyone's cooperation."
70011010-21 = "Well, it has to be Suzu-chan."
70011010-22 = "Suzu-chan? Oh, Misuzu Kanbara?#nI wonder if she'll be okay with that personality..."
70011010-23 = "But look, she has the track record..."
70011010-24 = "(...Hm?)"
70011010-25 = "Ah, over there! Hello! You're Misuzu Kanbara, right?"
70011010-32 = "Please tell us how you feel about being chosen as the next Director of the #nCorrection Bureau!"
70011010-33 = "(How did things end up like this...)"
70011010-34 = "(I didn't want things to...)"
70011010-48 = "...zu-chan."
70011010-50 = "Suzu-chan."
70011010-51 = "Hyaaah!?"
70011010-52 = "Whoa, you startled me... Are you okay?"
70011010-53 = "I'm sorry... I was lost in thought for a bit..."
70011010-54 = "Geez, you're usually spacing out as it is. Get it together, okay?"
70011010-55 = "Ehehe... You're right, I need to be careful. Thank you for your concern."
70011010-56 = "...So, about that thing I asked for."
70011010-57 = "Ah... You mean this, right?"
70011010-62 = "This is it! Mornings are really tough without this."
70011010-63 = "Thanks! I'll be counting on you again!"
70011010-64 = "Ah, um... technically, bringing in outside items multiple times is against the rules..."
70011010-65 = "So it might be a bit difficult... next time..."
70011010-66 = "Huh? This isn't the first time you've brought it for me, right?"
70011010-67 = "Um... you could say that up until now it was a special exception, I guess..."
70011010-68 = "Then make it a special exception next time too~"
70011010-69 = "Yes..."
70011010-70 = "But... how about trying to reduce it little by little?#nIt's not very good for your body, after all."
70011010-71 = "Hmm... Well, I guess so, but..."
70011010-72 = "...Huh? Wait a sec."
70011010-77 = "Gehh, a guard!"
70011010-78 = "How many times do I have to tell you we're not guards... Ah, whatever."
70011010-79 = "So, what did you do this time?"
70011010-80 = "Why are you jumping to conclusions?!"
70011010-81 = "Look back on your everyday behavior.#nSo..."
70011010-84 = "..."
70011010-88 = "Come on. Hand it over yourself before we do a body check."
70011010-89 = "Tch."
70011010-94 = "...What's this?"
70011010-95 = "Isn't it obvious? It's a matcha latte stick. The kind with caffeine."
70011010-96 = "Caffeine? Aren't you provided with instant coffee?"
70011010-97 = "That stuff is bitter and gross."
70011010-98 = "Heh... You're not here to play around, you know..."
70011010-99 = "Actually, isn't this the pretty expensive?#nHow are you getting the money for it?"
70011010-100 = "Huh? It is?"
70011010-101 = "What? You didn't know? Does that mean..."
70011010-102 = "E-Ehehe... I'm the one who picked it for her."
70011010-103 = "They already have to endure feeling so cramped in here...#nso I thought they should at least have something tasty to eat... Ehehe..."
70011010-104 = "Ah, plus... managing the health of the imprisoned students is our job, so..."
70011010-105 = "Director."
70011010-106 = "Ah, well, um... Ehehe..."
70011010-107 = "*Sigh*... We can't have this happening every time.#nYou are increasing our workload, you know?"
70011010-108 = "I'm sorry..."
70011010-109 = "Hey, hey, don't be so hard on Suzu-chan. I'm the one who asked her for the#nunreasonable favor."
70011010-110 = "If you're going to blame anyone, blame me!!"
70011010-114 = "No, that is so..."
70011010-115 = "Why am I the one looking like the bad guy here..."
70011010-116 = "Hey, what's going on?"
70011010-120 = "Ah, Senpai..."
70011010-121 = "Ah... I get the gist of it."
70011010-122 = "You, go back to your room. And don't forget to take that with you."
70011010-123 = "I didn't mean for it to turn out like this..."
70011010-124 = "I guess I will cut down on caffeine... Sorry, Suzu-chan."
70011010-128 = "Ehehe... Take care."
70011010-129 = "Well then, we'll be off as well. We're returning to our posts."
70011010-135 = "Yes... Please keep up the good work..."
70011010-137 = "Is it really okay?"
70011010-138 = "You know the Director's personality... We just have to get used to it."
70011010-139 = "*Sigh*... Misuzu-san is too kind."
70011010-140 = "I mean, I know she's a good person, and I like her too, but..."
70011010-141 = "Well, I know what you mean. Everyone has things they're suited and unsuited for. But—"
70011010-143 = "As behavior for the Director of the Corrections Bureau, it's a bit..."
70011010-150 = "I managed to get through another day..."
70011010-154 = "The Director's Office... It's too big for me."
70011010-155 = "Then again, my desk back when I was a regular staff member was small and#ninconvenient... I wish I could share this space with everyone..."
70011010-160 = "Did the previous directors feel the same way...?#nOr... am I just too common?"
70011010-165 = "Still, there's no use worrying too much about it.#nEnough, enough. Let's leave it at that."
70011010-166 = "I have to think about better things. Especially since work finished early today."
70011010-167 = "Even with this. I pushed myself a little... but I'm glad I'll somehow make it in time."
70011010-171 = "Hehe."
70011010-172 = "Knitting is nice... It calms my mind..."
70011010-173 = "If only time could stop right here—"
70011010-177 = "Director!"
70011010-178 = "Hahih!?"
70011010-183 = "Excuse the intrusion so late at night!#nI felt this needed to be reported immediately...!"
70011010-184 = "Y-Yes, it's fine. If it's an urgent matter, of course."
70011010-185 = "So, what happened?"
70011010-186 = "Well... an inmate attempted a prison break—"
70011010-187 = "Ehh!? A prison break!?"
70011010-188 = "When!? Who!? Was it Wakamo!? By herself!?"
70011010-189 = "Ah... No."
70011010-190 = "Not by herself!?"
70011010-191 = "Then how many Wakamos broke out!?"
70011010-192 = "No, there's only one Wakamo..."
70011010-193 = "Or rather, Wakamo broke out a long time ago."
70011010-194 = "Ah... That's right. I panicked..."
70011010-195 = "Please rest assured. The prison break was prevented."
70011010-196 = "That being said, given the nature of the situation, we need a decision regarding#ndisciplinary action."
70011010-197 = "Here is the identity of the student who attempted the prison break."
70011010-202 = "Ah, in that case."
70011010-209 = "Could you give me a little time? I think I will talk to them in person."
70011010-210 = "In other words, an interrogation, right?"
70011010-211 = "I don't really like that word... but yes, it would be."
70011010-212 = "But there's no need for the director to go out of her way to face a dangerous#nindividual"
70011010-213 = "The Corrections Bureau is short-staffed, after all."
70011010-214 = "Please let me do it."
70011010-215 = "...Understood. I will begin the preparations."
70011010-223 = "...Things like these didn't happen in the past."