[translation]
80000127-1 = "Girl and Snack"
80000127-4 = "Arrived at Schale."
80000127-5 = "[s] \"Huh? Hikari, is it your turn for duty today?\""
80000127-6 = "Nope, nope."
80000127-7 = "Today is the day to give snacks to the person I love most."
80000127-8 = "That's why I came to see you."
80000127-9 = "[s] \"I can't see through my tears...\""
80000127-14 = "Here, take this."
80000127-15 = "The super latest, Framing Composition Type-C Choco Balls."
80000127-16 = "Pretty cool, right?#nI found the one I was curious about, lucky me."
80000127-17 = "With this, Hikari is in invincible mode today."
80000127-18 = "Anyway, try eating it, go ahead."
80000127-22 = "[ns1] \"So cool... Thank you, Hikari!\"\n[ns2] (Received the Choco Balls)"
80000127-31 = "[ns] \"...\""
80000127-33 = "[ns3] \"It would be a waste to eat them alone...\"\n[ns4] \"I wish someone would eat them with me.\""
80000127-37 = "[ns] \"Hikari, will you help me?\""
80000127-38 = "Eh...!?"
80000127-43 = "Yeah!"
80000127-45 = "(Ate the new chocolate product together with Hikari)"
80000127-46 = "(When I winced at the intense sourness, Hikari saw it and laughed very happily.)"