[translation]
80000136-1 = "Mine!"
80000136-2 = "Schale Office"
80000136-3 = "(Returning to Schale, an unfamiliar object caught my eye.)"
80000136-7 = "(...It looked like a giant chocolate.)"
80000136-11 = "(Could that be...)"
80000136-12 = "[ns] \"...Ritsu?\""
80000136-13 = "Spot on!"
80000136-14 = "A surprise chocolate for Sensei!"
80000136-15 = "Happy Valentine's Day, Sensei!"
80000136-16 = "[s] \"Thank you, Ritsu.\""
80000136-17 = "Hehe."
80000136-18 = "But wait, how did you know it was me?"
80000136-19 = "Why did you think it was mine?"
80000136-20 = "[ns] \"Because I'm Sensei, after all.\""
80000136-25 = "[ns] \"...How am I supposed to store that chocolate?\""
80000136-26 = "Don't worry about that!"
80000136-27 = "No need to worry, Sensei!"
80000136-28 = "[s] \"What do you mean?\""
80000136-29 = "You don't even need to put it in the fridge."
80000136-30 = "It'll be fine even if a scorching summer comes!"
80000136-31 = "Because that chocolate—"
80000136-32 = "It will never melt!"
80000136-33 = "[s1] \"What do you mean!?\"\n[s2] \"Is this some kind of mysterious technology...!?\""
80000136-36 = "You'll understand if you touch it! Go ahead, Sensei!"
80000136-37 = "(As urged, I carefully reached out to touch it...)"
80000136-38 = "[ns] \"W-what is this...!\""
80000136-39 = "Hehe... exactly!"
80000136-40 = "[s] \"I see, no wonder it doesn't melt.\""
80000136-44 = "[ns] \"A chocolate... made of stone?\""
80000136-45 = "Yep!#nI made it out of brown marble!"
80000136-46 = "Well? Were you surprised?"
80000136-47 = "[s3] \"I'm doubly surprised...\"\n[s4] \"I couldn't even tell it was stone just by looking...\""
80000136-50 = "Hehe, you're praising me!"
80000136-51 = "...? Oh, you want to know how I made it?"
80000136-52 = "I guess I have no choice, I'll make an exception just for you, Sensei!"
80000136-53 = "I'll explain it from A to Z!"
80000136-55 = "(And so, I ended up learning about sculpture while observing the chocolate(?).)"
80000136-56 = "(Still...)"
80000136-59 = "[ns5] \"How did you even get in here, Ritsu?\"\n[ns6] \"The security system should have triggered...\""
80000136-62 = "Huh?#nThrough the air vent!"
80000136-67 = "(...After Ritsu left, I reviewed the security system.)"