[translation]
80000140-1 = "Chocolate Medovik"
80000140-2 = "There are three principles of negotiation."
80000140-3 = "[s] \"What's the first one?\""
80000140-4 = "You're in a hurry, aren't you?#nI like that about you, though... Mufufu."
80000140-5 = "First, there is 'active listening'."
80000140-6 = "[s] \"That's certainly important, isn't it?\""
80000140-7 = "Yes, because it is important to threaten...#nI mean, guide them so they listen to what you have to say."
80000140-8 = "[s] \"...Hm?\""
80000140-9 = "And the second is 'profit'.#nThis is also always important, isn't it?"
80000140-10 = "It is very important to make the other party think that there is 'mutual benefit'."
80000140-11 = "The third and final one is 'trust'."
80000140-12 = "You need to create an atmosphere where they feel that if they don't comply, something terrible will happen.#nJust so they can't escape if something goes wrong."
80000140-13 = "[s] \"That might not be wrong, but is that really 'trust'!?\""
80000140-14 = "If it's not wrong, then it's practically the correct answer, isn't it?"
80000140-15 = "Regardless, negotiation requires technique."
80000140-16 = "You must always approach it with a give-and-take stance."
80000140-17 = "So, I have brought this for you."
80000140-23 = "[ns] \"A chocolate cake...?\""
80000140-24 = "It's chocolate, but it's called a Medovik."
80000140-25 = "It's made by spreading honey and cream over thin sponge layers, then stacking them..."
80000140-26 = "It's a famous dish in Red Winter, made by repeating that process many times."
80000140-27 = "This one has both the sponge and the cream flavored with chocolate."
80000140-28 = "By the way, it's handmade, you know?#nAs someone with business experience, you probably already guessed..."
80000140-29 = "Handmade chocolate on Valentine's Day."
80000140-30 = "You know what this means, don't you, Sensei...?#nMufufufufu."
80000140-31 = "[s] \"I see...\""
80000140-32 = "As an aside, I love this Medovik."
80000140-33 = "The many layers look just like a stack of books, don't they?"
80000140-34 = "[s] \"That's a romantic reason.\""
80000140-35 = "...Also, they look like stacks of cash, don't they?"
80000140-36 = "[s] \"...That's a very Yakumo-like reason.\""
80000140-37 = "Anyway. To me, Medovik is a cake that enriches my heart just by looking at it."
80000140-38 = "And I'll say it again, it's 'handmade', you know?"
80000140-39 = "On a day like this, to go out of my way to give you my favorite cake...#nAnd to give it to you here at this printing shop, which is also a battlefield for me."
80000140-40 = "Don't tell me you don't know what that means!#nMufufu!"
80000140-41 = "[s] \"I have just one question...\""
80000140-42 = "Yes~♪"
80000140-43 = "[s] \"'Handmade'... whose hands made it?\""
80000140-44 = "W-what are you talking about...!?"
80000140-45 = "...Eh, my past behavior?"
80000140-46 = "My goodness, that's terrible.#nThere's no need to go that far...!"
80000140-47 = "That far..."
80000140-48 = "..."
80000140-49 = "Sensei... can't we forget the past and look toward a bright future?"
80000140-50 = "[s] \"Yakumo? I don't think there's a future in that direction.\""
80000140-51 = "...It can't be helped, I suppose."
80000140-52 = "That said, my feelings were not a lie..."
80000140-53 = "And I haven't told a single lie, either!"
80000140-54 = "Didn't I say that 'trust' is important?"
80000140-55 = "The cake from the cafe is still handmade, after all."
80000140-56 = "Actually, recently...#nA new cafe opened near the office, and they wanted to run an advertisement..."
80000140-57 = "So, I negotiated with them."
80000140-58 = "—I asked if I could have some samples in exchange for a discount on the ad."
80000140-59 = "...I was acting with you in mind, Sensei."
80000140-60 = "[s] \"I see... Thank you, Yakumo.\""
80000140-61 = "Yes, I mean, it's a chocolate Medovik on Valentine's Day, right?#nI thought it would earn me a considerable amount of [ruby=profit]favorability[/ruby]."
80000140-62 = "[s] \"Thank you for being so honest about that...\""
80000140-63 = "Of course, I don't know how much of that is my true heart, though...?"
80000140-64 = "Well then, please enjoy it at your leisure.#nSince my intentions have been exposed, I, the bothersome merchant, will take my leave... Mufufu."
80000140-69 = "S-Sensei?#nWhy won't you let me leave...!?"
80000140-70 = "I-I know you asked me to join you, but this was prepared for you..."
80000140-71 = "...Well, certainly."
80000140-72 = "This place is meaningful to me, but..."
80000140-73 = "Even so, mumu..."
80000140-74 = "...Look, it's that thing."
80000140-75 = "For me, this place isn't for having tea..."
80000140-76 = "[s] \"Does that mean we should go somewhere else?\""
80000140-77 = "...Eh?"
80000140-78 = "Ah, no, that's..."
80000140-79 = "..."
80000140-80 = "Fine, fine, I lose."
80000140-81 = "Since I'm joining you, I'll make sure to treat myself to something good, okay?#nMufufu."
80000140-83 = "(And so, I headed to the new cafe with Yakumo.)"
80000140-88 = "(With the cheerful and energetic Yakumo today...)"
80000140-89 = "(With the cheerful and energetic Yakumo today...)"
80000140-90 = "(I spent a time that was never boring.)"