[translation]
80000138-1 = "Chocolate Meringue Cookies"
80000138-2 = "(I arrived earlier than the meeting time.)"
80000138-3 = "(As I was looking around aimlessly—)"
80000138-4 = "Hello, Sensei."
80000138-5 = "……Did I, by any chance, keep you waiting?"
80000138-6 = "[s] \"Nope, I just got here.\""
80000138-7 = "It's not just about \"now\"... You're quite a bit earlier than our meeting time."
80000138-8 = "[s] \"I just thought I might get to see Subaru sooner!\""
80000138-9 = "You're saying those things again..."
80000138-10 = "I'm starting to understand the truth behind those rumors little by little..."
80000138-11 = "Hehe, making that face won't work. #nI won't be fooled."
80000138-12 = "Anyway, the reason I called you here today is..."
80000138-13 = "Um..."
80000138-14 = "……"
80000138-15 = "Because you've been taking care of me."
80000138-16 = "In other words...!"
80000138-17 = "[ns] \"This is a nice cafe.\""
80000138-18 = "Huh?"
80000138-19 = "Ah, yes. That's right. #nI've been getting used to places like this lately."
80000138-20 = "Maybe it's because I've been working hard at my part-time job..."
80000138-21 = "……I know, even if you don't say it."
80000138-22 = "Studying is important too, right? #nThat's the kind of person you are, Sensei."
80000138-23 = "……Anyway!"
80000138-24 = "……"
80000138-25 = "I heard it while working part-time. #nThat in the \"outside world,\" there is something called a meringue cookie..."
80000138-26 = "……Ah. I did it again."
80000138-27 = "Anyway, you mix sugar into egg whites to create a cream-like foam..."
80000138-28 = "And it seems to be a sweet that is heated at about 100°C."
80000138-29 = "……I cannot forgive this!!!"
80000138-30 = "[s] \"W-why!? Meringue hasn't committed any crimes...!\""
80000138-31 = "Because they say they throw away the leftover egg yolks! #nDon't you think that's a sin against food!?"
80000138-32 = "[s] \"Ah...\""
80000138-33 = "There is a method called blanchir that uses egg yolks, but compared to meringue, its uses are limited."
80000138-34 = "Besides, they spoil faster than egg whites, so... #nin the end, they often can't be used up and end up being thrown away."
80000138-35 = "What crime did the egg yolks commit...! #nSuch selfishness must not be forgiven!"
80000138-36 = "Even if the god of food forgives it, I will not!!"
80000138-37 = "So, that's why... I've been taking the egg yolks that were supposed to be discarded."
80000138-38 = "I soak them in sugar and soy sauce for the Arius children to eat... I've been trying various things."
80000138-39 = "Still, don't you think it's terrible? #nWasting food like that, the world is truly coming to an end...!"
80000138-40 = "[s] \"W-well now...! Food is certainly important, I agree!\""
80000138-41 = "Thank you for understanding... #nWait, what were we talking about?"
80000138-42 = "……Ah, right, meringue cookies."
80000138-43 = "……Sensei."
80000138-47 = "The \"outside world\"... No. I heard that in society, there is something called Valentine's Day."
80000138-48 = "On that day..."
80000138-49 = "Um..."
80000138-50 = "People you are usually indebted to..."
80000138-51 = "Or people you want to convey your feelings to..."
80000138-52 = "They say you give them chocolate as a gift."
80000138-53 = "So, um... I tried preparing some too...!"
80000138-58 = "[ns] \"Wow, you made these meringue cookies...?\""
80000138-59 = "When making meringue, you mix in powder and such."
80000138-60 = "In the end, I'm better at using my body, so to speak... #nIf it's just making meringue, all it takes is a little trick and some arm strength."
80000138-61 = "I thought, maybe I could do it too..."
80000138-62 = "……Of course, I borrowed the oven from my part-time job."
80000138-63 = "When I say it out loud, it's a pathetic story."
80000138-64 = "……"
80000138-65 = "Now that I think about it carefully... I can't possibly serve something like this to you, Sensei...!"
80000138-66 = "P-please pretend you didn't hear that! #nThis is, after all...!"
80000138-73 = "(I hurriedly stopped Subaru as she tried to take the cookies back.)"
80000138-75 = "[ns1] \"It's not 'something like this'!\"\n[ns2] \"I'm really happy!\""
80000138-78 = "……Is that, true?"
80000138-79 = "[s] \"It's how I truly feel.\""
80000138-80 = "Don't complain after you've eaten them, okay?"
80000138-81 = "[s] \"I won't, I promise.\""
80000138-84 = "……I understand."
80000138-85 = "I believe you."
80000138-86 = "……Hehe."
80000138-88 = "(And so, while eating the meringue cookies with Subaru, #nwe spent a gentle time together.)"