[translation]
80000128-1 = "An Unexpected Gift"
80000128-2 = "(I was working, just like always...)"
80000128-3 = "[ns] \"I'm exhausted...\""
80000128-5 = "Sensei, you in there?"
80000128-10 = "Oh, there you are."
80000128-11 = "[s] \"Oh, Nozomi...\""
80000128-12 = "Hehehe, you look like you're dying?"
80000128-13 = "Well, I figured as much."
80000128-14 = "So, anyway..."
80000128-15 = "Here, take this."
80000128-20 = "It's nothing fancy, but I heard it's good for fatigue."
80000128-21 = "You've probably already gotten enough chocolate, and I figured you'd be busy with work anyway..."
80000128-22 = "So gummies are easier to snack on, hehe!"
80000128-23 = "[ns] \"Nozomi...!\""
80000128-25 = "Whoa, what's with that look?"
80000128-26 = "It's written all over your face that you're touched, isn't it?"
80000128-27 = "It's not like I made them myself or anything, you know?"
80000128-28 = "Hehe!#nSensei, you're surprisingly weak to stuff like this."
80000128-29 = "Anyway, make sure you eat them, okay?"
80000128-30 = "I just stopped by on a whim, so I'm heading out now."
80000128-31 = "I thought about slacking off a bit more, but you look busy today too."
80000128-32 = "Huh? You want me to stay?"
80000128-36 = "What?#nAre you saying you want to hang out with me?"
80000128-37 = "[s] \"Work can wait, I can do that anytime!\""
80000128-38 = "Hehehe! That's what I like to hear!"
80000128-43 = "Alright then..."
80000128-44 = "...What should we play?"
80000128-46 = "(I forgot about work and played with all my might with Nozomi.)"
80000128-47 = "(As thanks for helping her relieve some stress, Nozomi helped me with my work until late.)"