[translation]
80000132-1 = "Mana Charge for Sensei"
80000132-2 = "(I received a message from Eri this morning—)"
80000132-5 = "Sensei! You're coming to the academy today, right?"
80000132-6 = "Actually, there's something I want to tell you!"
80000132-7 = "Nyu-fu-fu! Then, let's meet at our secret spot!"
80000132-9 = "(...And so, I arrived at the vacant lot in Wild Hunt Art Academy.)"
80000132-12 = "A deserted vacant lot"
80000132-14 = "Ah, Sensei!#nYou're early!"
80000132-15 = "[s] \"Why did you call me to a place like this?\""
80000132-16 = "...Because here, I can maximize the mana resonance."
80000132-17 = "In places where there are people, well... the magical energy gets interfered with..."
80000132-18 = "[s] \"...? Did you just want to see me alone?\""
80000132-19 = "Y-yes, that's right!"
80000132-20 = "As expected of Sensei, you're sharp."
80000132-21 = "So, since it's just the two of us...!"
80000132-22 = "...It's okay if I take it off, right?"
80000132-23 = "[s] \"...Nn!?\""
80000132-24 = "I want you to see my resolve, Sensei."
80000132-25 = "...Haaah!!!"
80000132-30 = "Kyaaa...!"
80000132-39 = "E-even if it's for you, Sensei, doing this outside... i-it's still embarrassing, after all."
80000132-40 = "[s] \"...Eh?\""
80000132-41 = "S-sorry, that's weird, isn't it! I know that, but...!"
80000132-42 = "To me, this isn't much different from being naked..."
80000132-43 = "I was fine when I practiced in front of everyone at the Occult Research Club, though..."
80000132-44 = "[s] \"I-it's not embarrassing in front of everyone?\""
80000132-45 = "Well, we take baths together and such..."
80000132-46 = "So, taking off my hat doesn't really..."
80000132-47 = "It's the same thing, you could say..."
80000132-48 = "...!?#nAh, no, I don't mean anything by that!"
80000132-49 = "[s] \"D-don't push yourself! You can put it back on now.\""
80000132-50 = "B-but I made up my mind to do this...!"
80000132-51 = "This look is the most efficient for mana sharing..."
80000132-52 = "..."
80000132-53 = "I-it's okay, I can do it properly...!"
80000132-54 = "Phew..."
80000132-55 = "T-then, Sensei!"
80000132-60 = "I've poured plenty of my mana into this."
80000132-61 = "This time, I didn't rely on my hat and made it with my own power..."
80000132-62 = "So, I thought it might not be good to keep my hat on...!"
80000132-63 = "...S-Sensei?"
80000132-64 = "[s] \"Amazing, just looking at this chocolate makes me feel energized...!\""
80000132-65 = "R-really?"
80000132-66 = "T-then, um..."
80000132-67 = "Would it be okay if I fed you...!?"
80000132-68 = "[s] \"...I see, it's a mana charge!\""
80000132-69 = "Y-yes!"
80000132-70 = "This understanding... as expected, Sensei is amazing!"
80000132-71 = "I-it takes resolve to get this close without my hat, though..."
80000132-72 = "Haa... haa...#nI-I'm going for it!"
80000132-73 = "[s] \"Anytime!\""
80000132-74 = "Then...!"
80000132-75 = "First, the star-shaped chocolate...!"
80000132-80 = "H-how... is it?"
80000132-85 = "[ns] \"Amazing, it's popping!\""
80000132-86 = "Ehehe... I tried adding popping candy!"
80000132-87 = "If you eat it when you're sleepy, your eyes should pop wide open!"
80000132-88 = "[s] \"What flavor is the heart-shaped chocolate?\""
80000132-89 = "That is... a surprise for after you eat it."
80000132-90 = "T-then, please...!"
80000132-94 = "[ns] \"T-this is...!?\""
80000132-95 = "(It's sweet... and just a little bit sour?)"
80000132-96 = "(It feels like my mana is actually recovering...!)"
80000132-97 = "H-how is it?"
80000132-98 = "I added various vitamins to it."
80000132-99 = "It's both a chocolate and a nutritional supplement."
80000132-100 = "...Sensei, you're always so busy."
80000132-101 = "I heard you often work late without even having time to eat..."
80000132-102 = "Uuu, just thinking about it makes me feel sad..."
80000132-103 = "So on nights like that...#nplease eat this chocolate while thinking of me!"
80000132-104 = "I'm sure your mana will come surging back!"
80000132-105 = "[s1] \"I can feel Eri's feelings soaking in...\"\n[s2] \"I want to eat it all right now!\""
80000132-108 = "Y-you shouldn't eat too much!?"
80000132-109 = "Mana replenishment isn't good if you overdo it."
80000132-110 = "[ns] \"Indeed, I'll be careful.\""
80000132-112 = "[ns] \"Won't you eat some with me, Eri?\""
80000132-115 = "R-reverse mana supply from Sensei...!?"
80000132-116 = "If we do a mutual charge, the result should be more than double the effect!"
80000132-117 = "Then... please, Sensei!"
80000132-119 = "(After that, I spent a time filled with magical energy together with Eri.)"