[translation]
80000133-1 = "Until You Remember"
80000133-2 = "(While working at Schale...)"
80000133-7 = "Hey, Sensei..."
80000133-8 = "[s] \"Kanoe, what's wrong?\""
80000133-9 = "Hehehe..."
80000133-10 = "The reason I contacted you... you know why, right, Sensei?"
80000133-11 = "Because you and I... are connected by the red string of fate..."
80000133-12 = "[s] \"Could it be... chocolate?\""
80000133-13 = "...Correct."
80000133-14 = "And it's not just ordinary chocolate, it's a super cute chocolate muffin..."
80000133-15 = "I simmered it in a pot... while pouring in special ingredients and all my love."
80000133-16 = "Well, want to try some...?"
80000133-17 = "[s] \"Of course! Kanoe's cooking is always delicious.\""
80000133-18 = "...I knew you'd say that."
80000133-19 = "Heh, hehehehe...!"
80000133-20 = "[s1] \"Ah... but I have some field work to do after this.\"\n[s2] \"Can we meet up when I get back and eat it slowly?\""
80000133-23 = "...I want it now."
80000133-24 = "[s] \"I have about 30 minutes, but if I go to meet you now--\""
80000133-25 = "Don't worry."
80000133-26 = "I thought you'd say that..."
80000133-27 = "Caw! Cawww...!"
80000133-28 = "[ns] \"Th-this sound...!\""
80000133-34 = "...I thought it might come to this."
80000133-35 = "Heh... I am a capable woman, after all."
80000133-36 = "[s] \"Wh-when did you...!\""
80000133-37 = "More importantly, what matters right now is..."
80000133-38 = "...that you and I are here together."
80000133-39 = "Now, close your eyes...?"
80000133-40 = "(Faced with that expression, I couldn't resist what Kanoe said...)"
80000133-41 = "(I quietly closed my eyes)"
80000133-46 = "Heh, wait just a moment..."
80000133-50 = "Caw! Cawww!"
80000133-53 = "Meow! Nyaoo!"
80000133-54 = "[ns] \"...It sounds like there are more of them.\""
80000133-55 = "Did they gather because of the smell...?"
80000133-56 = "This is a special muffin for Sensei, so..."
80000133-57 = "Go away for now... I'll give you yours another time."
80000133-63 = "Here you go, Sensei. Open your eyes?"
80000133-68 = "Sensei..."
80000133-69 = "[ns3] \"Th-the atmosphere is...\"\n[ns4] \"Is this cute Kanoe-chan mode!?\""
80000133-72 = "Yes... this is my feeling for you."
80000133-77 = "Kanoe... I really wanted to give you chocolate, Sensei."
80000133-78 = "If we do this, you'll surely remember your past life's memories."
80000133-79 = "That memory of us sharing chocolate, too..."
80000133-80 = "So, eat it quickly."
80000133-81 = "My special muffin...!"
80000133-82 = "[s] \"...!!\""
80000133-83 = "(As if possessed, I stuffed Kanoe's chocolate muffin into my mouth)"
80000133-88 = "How is it, is it delicious...?"
80000133-89 = "[s] \"I-it's too delicious...!\""
80000133-90 = "Heh...!"
80000133-91 = "As expected of Sensei... I knew you'd be happy."
80000133-96 = "..."
80000133-97 = "...Heh, hehehehe."
80000133-98 = "You've taken mine in... the ritual is now complete."
80000133-99 = "Now you're mine forever, Sensei... Hehehehe!"
80000133-100 = "Now, tell me... who am I?"
80000133-101 = "To you, Sensei... what kind of existence was I in your past life?"
80000133-102 = "[ns5] \"A-a cute kitten...!\"\n[ns6] \"A-a clever crow...!\""
80000133-106 = "...Was it not enough?"
80000133-107 = "In that case, I guess you'll just have to keep eating until you remember..."
80000133-108 = "I thought something like this might happen, so I made plenty."
80000133-110 = "(And so, I spent a fun time eating chocolate muffins with Kanoe, but...)"
80000133-111 = "(...I couldn't remember my past life's memories)"
80000133-117 = "It's okay..."
80000133-118 = "Just a little more, just a little more..."
80000133-119 = "Heh... Hehehehe!"