[translation]
80000130-1 = "Cold Fingertips"
80000130-6 = "Ah, Sensei."
80000130-7 = "You were at SCHALE. I'm glad."
80000130-8 = "[s1] \"Hello, Nagusa.\"\n[s2] \"I don't think you were on duty today, is something the matter?\""
80000130-11 = "Today is Valentine's Day."
80000130-12 = "While I was out on patrol, I naturally heard about it."
80000130-13 = "Here, some chocolate.#nI wanted to give this to you."
80000130-14 = "[s3] \"Nagusa's chocolate...!\"\n[s4] \"Thank you for coming all this way, I'm so happy.\""
80000130-17 = "It's nothing... it's not really anything special."
80000130-18 = "You've helped me so much, Sensei,#nso I've always wanted to thank you."
80000130-19 = "But it feels a bit embarrassing to express my feelings on a random day..."
80000130-20 = "That's why I'm grateful for a day like this."
80000130-21 = "[s] \"I see, that's true.\""
80000130-25 = "[ns] \"Wait, this looks familiar...\""
80000130-28 = "These are special chocolate cookies, exclusive to the Hyakkiyako district.#nMaybe you've seen them at a shop somewhere."
80000130-29 = "They're coated in a sweet, gentle white chocolate made with dairy from Ebisu."
80000130-30 = "They're my favorite snack, but for some reason, the Hyakkiyaran Alliance doesn't really eat them."
80000130-31 = "Even when I buy them, I always end up eating them alone."
80000130-32 = "[s] \"Is that so? Then, let me have a bite...\""
80000130-37 = "[ns5] \"Delicious!\"\n[ns6] \"The chocolate melts the moment it hits my tongue, it's so rich.\""
80000130-40 = "Right? That's what I like about them too."
80000130-41 = "If you'd like, please have some more."
80000130-42 = "[s] \"Um, just a second before that...\""
80000130-46 = "Ah..."
80000130-47 = "Did you... not like it?"
80000130-48 = "I'm sorry...#nI should have realized when everyone else wouldn't eat them."
80000130-49 = "I suppose I really am different from everyone else..."
80000130-50 = "[ns] \"N-no, that's not it! That's not what I meant...!\""
80000130-52 = "[ns] \"I just thought... I didn't want to get the documents dirty.\""
80000130-53 = "Ah... you're right, this 'White Maiden' chocolate melts in an instant..."
80000130-54 = "Wait... but I've always..."
80000130-58 = "...Ah, maybe it's because of my body temperature."
80000130-59 = "[s] \"Body temperature?\""
80000130-60 = "Yes... my normal body temperature is quite low.#nMaybe that's why people often tell me my hands and feet are cold."
80000130-61 = "...So, unlike everyone else, I guess that's why my hands didn't get dirty."
80000130-62 = "[s7] \"I see...\"\n[s8] \"That's actually kind of enviable.\""
80000130-65 = "Hehe..."
80000130-66 = "It's not like it's useful for anything other than times like this..."
80000130-67 = "I'm weak against the heat, too... and I can't really pass any warmth to anyone beside me."
80000130-68 = "...But I didn't know. It has its good points, too."
80000130-69 = "[s9] \"If you don't mind, Nagusa...\"\n[s10] \"Could you feed me one?\""
80000130-72 = "W-with my hands...?"
80000130-73 = "I-if you don't mind, Sensei..."
80000130-78 = "Here, Sensei... say 'ah'."
80000130-83 = "[ns11] \"Delicious...\"\n[ns12] \"My brain is being soothed...\""
80000130-86 = "Hehe, really?"
80000130-87 = "...I've found a new good point."
80000130-89 = "(After that, I spent a wonderful time having Nagusa feed me the rest by hand.)"