[translation]
80000134-1 = "Wait-and-Take Tiramisu"
80000134-2 = "(Per Miyo's invitation, I visited Wildhunt Dormitory.)"
80000134-3 = "(She told me the time the dorm guards' inspection becomes lax, so I could come in easier than usual.)"
80000134-4 = "At the dorm of Free Trade Cartel"
80000134-7 = "Hello, Sensei."
80000134-8 = "[s] \"Yah, how've you been?\""
80000134-9 = "I'm fine... Although the novel I'm writing isn't progressing much......"
80000134-10 = "Unlike smuggling plans, that come to mind easily......"
80000134-11 = "[s] \"……?\""
80000134-12 = "Ah, it's nothing......and sorry."
80000134-13 = "It probably won't take long, but outing rules have become strict again, so... it's hard for me to come and meet Sensei."
80000134-14 = "[s] \"It's okay. I'll come to see you whenever you want, Miyo!\""
80000134-15 = "R- really?#nHehe......"
80000134-16 = "[s] \"I might get kidnapped if I refuse, so......\""
80000134-17 = "Wh-...!#nI- I won't do something that dangerous!"
80000134-18 = "I mean, I can do if I want to, but... if it comes to that, I need to calculate some variables......"
80000134-22 = "...Or not!#nI won't do it, okay?!"
80000134-23 = "Uu..."
80000134-24 = "[s] \"By the way, is that...?\""
80000134-25 = "Ah, this is..."
80000134-26 = "a Tiramisu."
80000134-27 = "[s] \"Let me guess......It's not done yet?\""
80000134-28 = "Ye- yes, it's embarrassing..."
80000134-29 = "It's supposed to be done at this time, but..."
80000134-30 = "This is my first time making it, that's why..."
80000134-31 = "[s] \"Then let's make it together.\""
80000134-32 = "Th- that would be...!"
80000134-33 = "And it's almost finished!"
80000134-34 = "All that's left is to add some cocoa powder...!"
80000134-35 = "And do- ne..."
80000134-38 = "[greeting][greeting][SFX of shaking something]"
80000134-40 = "[…]"
80000134-41 = "...It's like-"
80000134-42 = "[s] \"Hmm?\""
80000134-43 = "Spreading black cocoa powder on pure white Mascarpone cheese..."
80000134-44 = "It's like writing words on a manuscript paper..."
80000134-45 = "[s] \"Now that you mentioned it, that's true.\""
80000134-46 = "......Sometimes, I think-"
80000134-47 = "Writing means you're blotting out on papers-- If that's true, then I'm also..."
80000134-48 = "...I'm sorry, please pay it no mind."
80000134-53 = "Anyway, with this..."
80000134-57 = "It's done, Sensei!"
80000134-60 = "[ns] \"That looks really good!\""
80000134-61 = "Hehe... Thank you."
80000134-62 = "Ah, umm, that..."
80000134-63 = "[s] \"What is it?\""
80000134-69 = "I knew it just now...#nbut it said Tiramisu tastes better if you keep it in refrigerator for about 2 hours."
80000134-70 = "S- so..."
80000134-71 = "If Sensei is okay..."
80000134-72 = "[s] \"Waiting 2 hours is a piece of cake!\""
80000134-73 = "Y- you mean it!?#nThank you very much!"
80000134-74 = "Then I'll prepare some tea."
80000134-75 = "Chamomile Tea sounds good for today."
80000134-77 = "(2 hours flew away while talking with Miyo.)"
80000134-78 = "(The time we spent together made the Tiramisu taste even better.)"