[translation]
80000129-1 = "I hate cheap chocolate"
80000129-7 = "……."
80000129-8 = "Sensei...? You're not here, right...?"
80000129-9 = "If that's the case, then... maybe that's for the best."
80000129-14 = "Ugh... I wonder if something like this is really okay..."
80000129-15 = "But, I'm sure if it's Sensei..."
80000129-20 = "[ns] \"Hello, Aoba.\""
80000129-22 = "Whoa!? S-Sensei!?"
80000129-23 = "H-how long have you been there...!?"
80000129-24 = "Wait, from the beginning...?"
80000129-25 = "Oh, right there on the sofa... I didn't notice you at all..."
80000129-26 = "U-ugh. W-well then, here..."
80000129-27 = "[s1] \"Are you leaving already?\"\n[s2] \"By any chance, is this...\""
80000129-34 = "A-ah...!"
80000129-38 = "Um, well..."
80000129-39 = "S-Sensei, you always take such good care of me, so...!"
80000129-40 = "I just felt like I had to thank you today...!"
80000129-41 = "But I got worried about whether something like this was good enough..."
80000129-42 = "If I could, I would have made something myself... or given you something with a bit more effort put into it..."
80000129-43 = "But I've been working overtime every day... and by the time I get home, the shops are already closed..."
80000129-44 = "I'm sorry, it ended up being just these cheap snacks..."
80000129-45 = "[ns] \"I'm happy, Aoba.\""
80000129-48 = "Huh!?"
80000129-49 = "B-but these are just things you can buy anywhere...!?"
80000129-50 = "[s3] \"Even so, it's something you prepared for me.\"\n[s4] \"I'm happy just for the thought.\""
80000129-53 = "……."
80000129-54 = "I-is that so..."
80000129-55 = "……."
80000129-56 = "...Ah, thank you very much."
80000129-57 = "[ns] \"Hmm... is this a letter?\""
80000129-58 = "Eek!!!"
80000129-59 = "T-that! No! Not now! Absolutely not!!"
80000129-60 = "Please read it later!!!"
80000129-61 = "[s] \"S-sorry...\""
80000129-62 = "Haa, haa..."
80000129-69 = "W-well then, I'll be going now..."
80000129-70 = "U-until next time...!"
80000129-75 = "[ns] \"Aoba.\""
80000129-79 = "D-did you need something!?"
80000129-80 = "[s] \"Since you're here, why don't you stay and rest for a bit?\""
80000129-81 = "Eh... eh!?"
80000129-82 = "...Ah, no. It's not like I'm particularly busy, but..."
80000129-83 = "A-are you really sure...?"
80000129-84 = "\"Resting when you can is part of the job\"...?"
80000129-85 = "[s5] \"You looked like you were tired.\"\n[s6] \"Look at this sofa, it's so fluffy!\""
80000129-88 = "U-ugh..."
80000129-89 = "It's true that I've been working hard lately, but..."
80000129-90 = "Hmm............"
80000129-97 = "...Just for a little bit, excuse me."
80000129-99 = "(And so, Aoba stayed and relaxed for quite a while.)"
80000129-100 = "T-thank you for always looking out for me."
80000129-101 = "Thanks to you..."
80000129-102 = "I think I'll be able to do my best tomorrow, and the day after too."
80000129-106 = "...And for a long time after that, too."