[translation]
80000135-1 = "It's Sweet and Hard"
80000135-2 = "Schale Office"
80000135-4 = "Long time no see, Sensei!"
80000135-5 = "By the way, I brought something good today!"
80000135-6 = "[s] \"Could it be... on your way back from a trade?\""
80000135-7 = "A trade, you say? I was actually out arranging some requested items."
80000135-8 = "But today was an easy one. There was only one type, after all."
80000135-9 = "Go ahead, Sensei, take a look."
80000135-15 = "(Fuyu then showed me the inside of her bag)"
80000135-16 = "(It was packed full of suspicious, individually wrapped spherical objects)"
80000135-17 = "[ns] \"What is this...?\""
80000135-18 = "Hehe, as you can see..."
80000135-19 = "[s] \"A bomb?\""
80000135-20 = "Yes, that's exac—"
80000135-21 = "Wait, no! #nIt's candy, candy!"
80000135-22 = "What do you take the Special Operations Department for!?"
80000135-23 = "...Besides, explosives aren't profitable. #nThere aren't many requests for them, either."
80000135-24 = "[s] \"Is that so...\""
80000135-25 = "Yes. You can make them easily enough with just household ammunition and grenades."
80000135-26 = "[s] \"By the way, what exactly is this candy...?\""
80000135-27 = "This is called a Gobstopper."
80000135-28 = "It's just candy, made of 99% sugar..."
80000135-29 = "However, it's known for being very \"hard.\""
80000135-30 = "It's made by layering melted sugar, so it's incredibly tough."
80000135-31 = "...To the point that trading them is actually banned."
80000135-32 = "[s] \"And why is that...?\""
80000135-33 = "Well, there have been cases where students tried to bite into them and broke their teeth."
80000135-34 = "Because of that, the Dormitory Wardens banned them."
80000135-35 = "[s] \"I see...\""
80000135-36 = "But if you just suck on them, they last a long time. They're perfect for when you need to focus on something, so there's definitely demand."
80000135-37 = "Thanks to that, our pockets are a bit warmer... wait, that's not what I meant..."
80000135-42 = "...Sensei, here you go."
80000135-44 = "(She gave me the largest candy)"
80000135-45 = "(...It's about the size of a baseball)"
80000135-47 = "[ns] \"What is this...?\""
80000135-48 = "I told you, didn't I? #nThat I brought something good."
80000135-49 = "It's a limited edition, extra-large chocolate Gobstopper."
80000135-50 = "You know, since today is... Valentine's Day, and all?"
80000135-51 = "[s] \"Thank you, Fuyu...!\""
80000135-52 = "...Hehe."
80000135-53 = "[s1] \"Still, this size...\"\n[s2] \"I might need a hammer or something...\""
80000135-56 = "No, that won't be necessary."
80000135-60 = "[ns] \"A gun...?\""
80000135-62 = "Bang!"
80000135-66 = "Go ahead, please enjoy!"
80000135-67 = "[s] \"Th-thank you...\""
80000135-69 = "(I put one in my mouth...)"
80000135-70 = "(The taste was better than I imagined)"
80000135-71 = "[ns] \"It's delicious...!\""
80000135-72 = "Isn't it?"
80000135-73 = "It's a limited edition, so they apparently put more effort into it than usual!"
80000135-74 = "[s] \"Won't you have some too, Fuyu?\""
80000135-79 = "Oh...! Y-yes!"
80000135-81 = "...I see. You're right, this is delicious."
80000135-82 = "[s] \"Looks like it'll take a while to finish.\""
80000135-83 = "Yes, the sweet time will last for a long while."
80000135-84 = "...During that time, you'll be thinking of me, right?"
80000135-88 = "Oh, look at the time! Well then, excuse me!"
80000135-95 = "..."
80000135-96 = "Uwaaaaaah...!"
80000135-97 = "I can't believe I said something so embarrassing...!"
80000135-98 = "...Ugh."
80000135-99 = "Well, better to regret doing it than not doing it at all..."
80000135-103 = "...Alright, time to go home! I'm leaving right now! Before we run into each other again!"