[translation]
80000137-1 = "I have to go to the Love Museum!"
80000137-2 = "(While working at Schale, I sensed Love's presence.)"
80000137-3 = "(Let's go check it out.)"
80000137-5 = "Alleyway near Schale"
80000137-10 = "…Nn, good."
80000137-11 = "Ah, but before that, my hair…"
80000137-12 = "[ns1] \"Love!\"\n[ns2] \"It's Love!\""
80000137-18 = "Whoa!?#nYou scared me!!"
80000137-19 = "Cut it out!#nI thought it was a surprise attack!?"
80000137-20 = "Wait, what are you doing here? What about work?"
80000137-21 = "[s] \"I sensed your presence!\""
80000137-22 = "What is that supposed to mean… never mind, I probably shouldn't ask.#nAnd aren't you a little too happy?"
80000137-23 = "Well, it works out perfectly."
80000137-24 = "I had something I wanted to give you, too."
80000137-25 = "[s3] \"A hand-knitted hat?\"\n[s4] \"A shared diary?\"\n[s5] \"A middle school graduation album?\""
80000137-29 = "Why would you want those things!?"
80000137-30 = "Do you not know what day it is today…?#nGeez, just how busy are you?"
80000137-34 = "Don't worry about… no, wait, here!"
80000137-35 = "I bought it at a convenience store, so just deal with it."
80000137-36 = "I didn't have the time or the confidence to make something by hand…"
80000137-37 = "The one I bought for Sensei earlier is… wait, this one is mine… *nom*…"
80000137-41 = "Nmm, nnn… eh, roco ni i ha o ha hi ra…"
80000137-46 = "…Nn, hafeh?"
80000137-47 = "[s6] \"Did you hurt yourself?\"\n[s7] \"A fever?\"\n[s8] \"Are you hungry?\""
80000137-51 = "Afa, afo!!#nNgh, I've got chocolate in my mouth, of course I can't answer!"
80000137-52 = "I was sure I bought two, but I can't find it."
80000137-53 = "Did I drop it when I got hassled earlier…?"
80000137-54 = "[s] \"It's okay, I'm happy just with the thought!\""
80000137-55 = "No, it's Valentine's Day, after all."
80000137-56 = "Nn…"
80000137-60 = "I already bit into it, but are you okay with sharing this one?"
80000137-65 = "Ah, my hands are a bit dirty, could you do it for me?"
80000137-66 = "It should be easy to snap in half."
80000137-70 = "[ns] \"Leave it to me!\""
80000137-71 = "Ah, man… I wanted to give it to you properly."
80000137-72 = "Here, just break it in half—"
80000137-78 = "…"
80000137-79 = "Isn't that a work notification?"
80000137-80 = "[s] \"Ah… you're right.\""
80000137-84 = "Go on, hurry up and go."
80000137-85 = "Someone's in trouble, right?"
80000137-86 = "[s] \"Sorry, Love… I'll definitely come hang out again!\""
80000137-90 = "Yeah, yeah, I get it!#nJust look where you're going and run! It's dangerous, you know!?"
80000137-97 = "…Good grief."
80000137-98 = "…'Next time', huh."
80000137-99 = "Well, maybe when you have time again…"
80000137-100 = "Anyway… I guess I'll go look for a vending machine."
80000137-106 = "Huh?#nWhere's the chocolate…?"
80000137-110 = "I'm sure Sensei had it just a moment ago…"
80000137-111 = "…D-did they take it all!?"