[translation]
80000126-1 = "The Three Sacred Treasures"
80000126-4 = "Hello, Sensei!"
80000126-5 = "[s] \"Oh, Rei. What's wrong?\""
80000126-6 = "Well, you see, um..."
80000126-7 = "............"
80000126-10 = "(Ugh... I was supposed to be prepared! I trained for this so many times...!)"
80000126-11 = "(But in front of Sensei, my courage just...!!)"
80000126-12 = "(I guess mental training isn't enough... I should just say hi and go home for today—)"
80000126-13 = "(No, no! That's just too much!)"
80000126-16 = "[ns] \"Rei?\""
80000126-17 = "Ah...!"
80000126-18 = "Um, well... ah, it's that, that thing. Today is, you know, that day, isn't it?"
80000126-19 = "[s] \"That thing...?\""
80000126-20 = "Ah, Va... Va...!"
80000126-21 = "Valentine's Day!"
80000126-22 = "I-I'm sorry!#nI just blurted it out... ugh."
80000126-23 = "S-so... I, um, tried making this..."
80000126-24 = "I'd be happy if you could accept it!"
80000126-25 = "(Received a glove made of chocolate.)"
80000126-30 = "I-I somehow managed to do it..."
80000126-31 = "[s1] \"Wow, it's shaped like a glove!\"\n[s2] \"Thank you, I'll enjoy eating it.\""
80000126-36 = "!!!"
80000126-37 = "No, thank you instead!"
80000126-38 = "...?#nAh, this chocolate, you mean...?"
80000126-39 = "Well, how should I put it..."
80000126-40 = "I wouldn't say I didn't make it myself...?"
80000126-42 = "(I'm curious, so I decide to ask for details.)"
80000126-45 = "This glove... it's the same model as the one I used to use."
80000126-46 = "I scanned it, processed the data..."
80000126-47 = "And printed it out with a 3D printer."
80000126-48 = "So, in other words, I didn't make the mold myself, but..."
80000126-49 = "At least... I did the finishing touches myself."
80000126-50 = "Ah, but I did melt the chocolate and polish it until it was shiny all by myself...!"
80000126-51 = "Well, that's about all there is to it..."
80000126-52 = "I wonder if you can even call this handmade..."
80000126-53 = "[s3] \"Thank you so much for putting so much effort into this chocolate.\"\n[s4] \"It's definitely 'hand'-made.\""
80000126-56 = "Is that so...?"
80000126-57 = "Hehe..."
80000126-58 = "Oh, actually, I have these too!"
80000126-63 = "[ns] \"A bat, and even a ball...!\""
80000126-64 = "They're the three sacred treasures of baseball!"
80000126-65 = "Even if we can't actually play baseball, this sets the mood perfectly!"
80000126-66 = "Come on, Sensei, be the pitcher...!"
80000126-67 = "Batter Nomasa Rei takes a big swing... It's a hit!#nThe ball goes over the shortstop's head!!"
80000126-68 = "Nomasa is fast! Can she make it to second base!?#nOh! Sensei the pitcher is closing in!"
80000126-70 = "(Afterward, the two of them enjoyed eating the three sacred treasures.)"
80000126-71 = "(Rei, munching on the chocolate, kept her eyes sparkling as she talked about baseball.)"